{literal}
<script type="text/javascript" xmlns="http://www.w3.org/1999/html">
$(document).ready(function() {
	$('#arthistorygrid').dataTable({
		"sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
		"sPaginationType": "bootstrap",
		"aaSorting": [[ 0, "asc" ]],
		"aoColumns": [
			{ "sType": "formatted-num" },
			{ "sType": "string" },
			{ "sType": "string" },
			{ "sType": "string" },
			{ "sType": "string" },
            { "sType": "string" },
            { "sType": "string" }
		]
	});

});

</script>
{/literal}
<form action="/proofread/validatestagearts?submenuId={$submenuId}" method="post" id="valstagearts" name="valstagearts" >
<div class="row-fluid">
  <div class="span12">
    <h3 class="heading">History of <b>{$articledetails[0].title|escape:'htmlall'}</b><button type="button" class="btn btn-inverse pull-right"  id="return">return</button></h3>

        <table id="arthistorygrid" class="table table-bordered table-striped table_vam">
            <thead>
            <tr>
                <th>Sl.no</th>
                <th>Editor</th>
                <th>Stage</th>
                <th>Action</th>
                <th>Action at</th>
                <th>Reasons</th>
                <th>sentence</th>
            </tr>
            </thead>
            <tbody>
            {foreach from=$paginator key=arthistory_key item=arthistory_item name=arthistory_loop}
            <tr>
                <td>{$smarty.foreach.arthistory_loop.index+1}</td>
                <td>{$arthistory_item.first_name}</td>
                <td>{$arthistory_item.stage}</td>
                <td>{if $arthistory_item.action eq ''}-{else}{$arthistory_item.action}{/if}</td>
                <td>{if $arthistory_item.action_at eq ''}-{else}{$arthistory_item.action_at|date_format:"%d/%m/%Y %H:%M"}{/if}</td>
                <td><!--{$arthistory_item.reasons}-->---</td>
                <td><!--{$arthistory_item.action_sentence}-->---</td>
            </tr>
            {/foreach}
            </tbody>
        </table>
  </div>
</div>
    <input type="hidden" id="hide_total" name="hide_total"  />
</form>
<!--///for the article profiles popup///-->
<div class="modal4 hide fade" id="artprofile">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h3>Article Profiles</h3>
    </div>
    <div class="modal-body"></div>
    <div class="modal-footer"></div>
</div>




