{literal}

<script type="text/javascript">
$(document).ready(function() {

    $(".uni_style").uniform();
    gebo_validation.reg();
$(".toggle-button").each(function(obj){
    $('#text-toggle-button'+obj).toggleButtons({
        width:75,
        label: {
            enabled: "Yes",
            disabled: "NO"
        },
        onChange: function (data) {
            var user = $('#blackstatus'+obj).val();
            if($("#blackstatus"+obj).is(":checked")){
                var target_page = "/processao/blackcontributor?status=yes&user_id="+user;
                $.post(target_page, function(data){ //alert(data);
                    smoke.alert("Contributor Blacklisted");
                });
            }
            else{
                var target_page = "/processao/blackcontributor?status=no&user_id="+user;
                $.post(target_page, function(data){
                    smoke.alert("Contributor Unblacklisted");
                });
            }

        }
    });
});
    if (CKEDITOR.instances['clientmail'])
    {
        CKEDITOR.instances['clientmail'].destroy();
    }
    var editor = CKEDITOR.replace( 'clientmail',
        {
            language: 'de', uiColor: '#D9DDDC', enterMode : CKEDITOR.ENTER_BR, removePlugins : 'resize',
            toolbar : [ ['Undo','Redo'], ['Find','Replace'],['Link', 'Unlink', 'Image'], ['FontSize', 'Bold', 'Italic','Underline'],
                ['TextColor', '-', 'Smiley','SpecialChar', '-', 'Maximize'] ]
        }
    );
});
function sendToFo()
{
    smoke.confirm("L\'article sera remis en ligne",function(e){
        if (e)
        {
            smoke.confirm("PREVENIR PAR EMAIL",function(e2){
                if (e2)
                {
                    $("#sendtofo").val('yes');
                    $("#anouncebyemail").val('yes');
                    $("#disapprove1form").submit();
                    return true;
                }
                else
                {
                    $("#sendtofo").val('yes');
                    $("#disapprove1form").submit();
                    return true;
                }
            });
        }
        else
        {
            $("#sendtofo").val('no');
            $("#disapprove1form").submit();
            return true;
        }
    });
}

function checkServices(id)
{
    $("#participateId").val(id);
    var optionscount = $('#hid_options').val();
    var $b = $('#optionsdiv input[type=checkbox]');
    var $c = $('#checksdiv input[type=checkbox]');
    var blen = $b.length;
    var clen = $c.length;
    var countselected = $b.filter(':checked').length;
    var countcheckselected = $c.filter(':checked').length;
    if(blen != countselected || countcheckselected != 3)
    {
       smoke.alert("Merci de cocher les options SEO et la check list");
       return false;
    }
    else if($("#art_doc_"+id).val()== '')
    {
        smoke.alert("please select a file to upload");
        return false;
    }
    else if((blen == countselected || blen==0) && countcheckselected == 3)
    {
       return true;
    }
}
function getRefuseTemp(valtempId)
{
   $("#comment_s1").text('')
      var $b = $('input[type=checkbox]');
      var countselected = $b.filter(':checked').length;
      ////////////////////////////////////
      var selected = new Array();
      $b.filter(':checked').each(function() {
          selected.push($(this).attr('value'));
           $("#hide_total1").val(selected);////for posting the value which are checked
      });
     ////////////////////////////////////
   for(var i=1; i<=countselected; i++)
   {
        var target_page = "/template/getrefusevalidtemp?valtempId="+selected[i-1];
        $.post(target_page, function(data){  //alert(data);
        var obj = $.parseJSON(data);
         $("#comment_s1").append(obj[0].content+'\n\n');
      });
   }
}

function showUploadFile(mode)
{
   if(mode == 'close')
      $(".alert").hide();
   else
   {
      $(".alert").show();
      $("#pop-s1comments").hide();
   }

}
////close the article and re create//////
function showCloseRecreate(artid)
{
    $("#alert").hide();
    smoke.confirm("close article and create new ao",function(e){
        if (e)
        {
            window.location.href = "/proofread/client-rejected-arts-correction?close=yes&closedrecreate=yes&articleId="+artid;
        }
        else
        {
            return false;
        }
    });
}
////close the article and re create//////
function showClosePayment(artid)
{
    $("#alert").hide();
    smoke.confirm("close article and payments",function(e){
        if (e)
        {
            window.location.href = "proofread/clientRejectedArtsCorrection?close=yes&closedpayment=yes&articleId="+artid;
        }
        else
        {
           return false;
        }
    });
}

</script>
{/literal}
<h3 class="heading">client rejected article Correction<a class="label label-inverse pull-right"  id="return">retour</a></h3>

<table id="grptabledetails" class="table btn-gebo tdleftalign" >
  <tr>
      <td><b>Article : </b>{$articledetails[0].title|escape:'htmlall'}</td>
      <td><b>Nom AO : </b>{$articledetails[0].deliveryTitle|escape:'htmlall'}</td>
      <td><b>Type d'article : </b>{$articledetails[0].type|stripslashes}</td>
  </tr>
  <tr>
      <td><b>Mode de comptage : </b>{if $articledetails[0].signtype == 'words'}Mots
          {elseif $articledetails[0].signtype == 'chars'}Caract&eacute;res
          {elseif $articledetails[0].signtype == 'sheets'}Feuillets{/if}</td>
      <td><b>Min {if $articledetails[0].signtype == 'words'}Mots / article
          {elseif $articledetails[0].signtype == 'chars'}Caract&eacute;res / article
          {elseif $articledetails[0].signtype == 'sheets'}Feuillets / article {/if}: </b>{$articledetails[0].num_min}</td>
      <td><b>Max {if $articledetails[0].signtype == 'words'}Mots / article
            {elseif $articledetails[0].signtype == 'chars'}Caract&eacute;res / article
            {elseif $articledetails[0].signtype == 'sheets'}Feuillets / article {/if}: </b>{$articledetails[0].num_max}</td>
  </tr>
  <tr>
    <td><b>Brief &eacute;ditorial : </b>{if $articledetails[0].filepath neq NULL}
        <a href="/proofread/downloadfile?submenuId={$submenuId}&spec={$articledetails[0].id}" class="label label-warning">Download</a>{else}No file{/if}</td>
    <td></td>
     <td></td>
  </tr>
</table>
<div class="span5 ui-sortable"  id="optionsdiv">
    <div class="w-box-header">Options choisies par le client</div>
    <div class="w-box-content cnt_a" >
        <ul class="unstyled">
            {foreach from=$options key=options_key item=options_item name=options_loop}
            {if $options_item.id|in_array:$res_seltdopts}
            <li>
                <label class="uni-checkbox">
                    <span><input type="checkbox" name="option_{$options_item.id}" id="option_{$options_item.id}" {$options_item.id} class="uni_style" /> </span>
                    <span class="pop_over" data-placement="right" data-original-title="Option Details" data-html="true" data-content="{$options_item.description|escape:'htmlall'}">{$options_item.option_name|escape:'htmlall'}</span>
                </label>
            </li>
            {/if}
            {/foreach}

            <input type="hidden" name="hid_options" id="hid_options" value={if $res_seltdopts|@count neq 0}{$res_seltdopts|@count}{else}{0}{/if} />
        </ul>
		{if $articledetails[0].validated_by!=""}
			{$refusecomment}
			<br><a href="/proofread/downloadclientfile?partid={$partId}">Download file</a>
		{/if}
    </div>
</div>

<div class="span5 ui-sortable" id="checksdiv">
    <div class="w-box-header">Check List</div>
    <div class="w-box-content cnt_a" >
        <label class="uni-checkbox">
            <span> <input type="checkbox" name="scheck" id="scheck" class="uni_style" /></span>
            <span class="hint--top hint--error " data-hint="checking for specllings of content">Check Antidote</span>
        </label>
        <label class="uni-checkbox">
            <span><input type="checkbox" name="gcheck" id="gcheck" class="uni_style" /></span>
            <span class="hint--top hint--error" data-hint="checking for grammer of content">Check plagiat</span>
        </label>
        <label class="uni-checkbox">
            <span><input type="checkbox" name="ccheck" id="ccheck" class="uni_style" /></span>
            <span class="hint--top hint--error" data-hint="checking for unfavourable data of content">Relecture du contenu</span>
        </label>
    </div>
</div>

<div class="row-fluid">
  <div class="span12">
<form action="/proofread/client-rejected-arts-correction?submenuId={$submenuId}&articleId={$articledetails[0].id}" method="post" id="clienrejectart" name="clienrejectart" enctype="multipart/form-data">
    <table id="rejectedclientgrid" class="table table-bordered table-striped table_vam">
        <thead>
        <tr>
            <th>Version</th>
            <th>Nom du fichier</th>
            <th>Uploaded by</th>
            <th>Date</th>
            <th>Article</th>
            <th>Comments</th>
        </tr>
        </thead>
        <tbody>
        {foreach from=$versions_details key=versions_key item=versions_item name=versions_loop}
        <tr>
            <td>{$versions_item.version}</td>
            <td>{$versions_item.article_name}</td>
            <td>{if $versions_item.first_name eq ''}{$versions_item.email}{else}{$versions_item.first_name}{/if}</td>
            <td>{$versions_item.article_sent_at|date_format:"%d/%m/%Y %H:%M"}</td>
            <td><a href="/proofread/downloadfile?submenuId={$submenuId}&path={$versions_item.id}">Download</a></td>
            <td>{$versions_item.client_comments|wordwrap:30}</td>
        </tr>
        {/foreach}
        </tbody>
    </table>
    <div class="span10 form-inline">
        <label class="uni-radio alpbold"><input type="radio" id="uploadnew" name="rejectclient" class="uni_style" onclick="return  showUploadFile('open');"/>upload new</label>
        <label class="uni-radio alpbold"><input type="radio" id="closerecreate" name="rejectclient" class="uni_style" onclick="return  showCloseRecreate({$smarty.get.articleId});"/>closed & recreate an ao</label>
        <label class="uni-radio alpbold"><input type="radio" id="closepayment" name="rejectclient" class="uni_style" onclick="return  showClosePayment({$smarty.get.articleId});" />closed & return payment</label>
    </div>
    <!--<div class="alignright" class="span6"><button type="button" name="s1art_approve" class="btn btn-success" onclick="return showUploadFile('open');">Valider</button>
    {if $refused_count.refused_count < 3}
    <button type="button" id="s1art_disapprove" name="s1art_disapprove" class="btn btn-danger"  onclick="return writeS1Comments('{$partId}');">Refuser</button>
    {/if}
    <button type="button" id="s1art_disapprove_permanent" name="s1art_disapprove_permanent" class="btn btn-danger"  onclick="return writeS1CommentsPermanent('{$partId}');">Refuser Definitivement</button>
    <input type="hidden" name="participateId" id="participateId"  />
    </div>
-->
    <input type="hidden" name="participateId" id="participateId" value="{$partId}" />
    <div id="alert" class="alert alert-info fade in hide span10" style="height: auto;">
        <textarea  name="clientmail" id="clientmail"  class="textarea pull-left"></textarea>
            <div class="alpbold">Uplaod your version</div>
            <div id="uniform-uni_file" class="uni-uploader">
                <input id="art_doc_{$partId}" class="uni_style" type="file" name="art_doc_{$partId}" size="19">
                <span class="uni-filename" >No file selected</span>
                <span class="uni-action" >Choose File</span>
            </div>
            <button type="submit" class="btn btn-inverse" name="clientrejectart_approve"  onclick="return checkServices({$partId});" >Confirm</button>
                <a onclick="return showUploadFile('close');" class="btn"><i class="splashy-error_small"></i> ANNULER</a>
    </div>
</form>
  </div>
</div>

<!--///show the density details ///-->
<div class="modal4 hide fade" id="density">
    <div class="modal-header">
        <button class="close" onclick="closePopup('density');">&times;</button>
        <h3>Density Details</h3>
    </div>
    <div class="modal-body" id="density_body">
    </div>
    <div class="modal-footer">

    </div>
</div>

<!--///when republish the popup comes for edit details and mail for republish article///-->
<div class="modal4 hide fade" id="republish">
    <div class="modal-header">
        <button class="close" onclick="closePopup('republish');">&times;</button>
        <h3>Editer les Details de la re-publication</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>
