{literal}
<script type="text/javascript" >
    $(document).ready(function() {
        loadEditors('marks_comments');
        $('#marks_comments').tinymce({
            // Location of TinyMCE script
            script_url 							: '/BO/theme/gebo/lib/tiny_mce/tiny_mce.js?' + new Date().getTime(),
            // General options
            theme 								: "advanced",
            plugins 							: "autoresize,style,table,advhr,advimage,advlink,emotions,inlinepopups,preview,media,contextmenu,paste,fullscreen,noneditable,xhtmlxtras,template,advlist",
            // Theme options
            theme_advanced_buttons1 			: "undo,redo,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
            theme_advanced_buttons2 			: "forecolor,backcolor,|,cut,copy,paste,pastetext,|,bullist,numlist,link,image,media,|,code,preview,fullscreen",
            theme_advanced_buttons3 			: "",
            theme_advanced_toolbar_location 	: "top",
            theme_advanced_toolbar_align 		: "left",
            theme_advanced_statusbar_location 	: "bottom",
            theme_advanced_resizing 			: false,
            height                              : 200,
            content_css                         : "/BO/theme/gebo/css/tinymce_styles.css?" + new Date().getTime(),
            theme_advanced_font_sizes           : "8px,10px,12px,13px,14px,16px,18px,20px",
            font_size_style_values              : "8px,10px,12px,13px,14px,16px,18px,20px",
            init_instance_callback				: function(){

                function resizeWidth() {
                    document.getElementById(tinyMCE.activeEditor.id+'_tbl').style.width='98%';
                }
                resizeWidth();
                $(window).resize(function() {
                    resizeWidth();
                })
            }
        });
        $("#marks").chosen({ allow_single_deselect: false,search_contains: true  });
    });

    ///////////write the comment in popup//////////////////
    function saveMarksComments(artid, partid)
    {
        // var $comment = $("#editor_comment").val();
        var $comment = $("#marks_comments").val();
        var $marks  = $("#marks").val();
        if($marks == 0)
        {
            alert("select marks");
            return false;
        }
        else
        {
            var target_page = "/proofread/markscomments?save_marks_comments=yes&artId="+artid+"&partId="+partid+"&marks="+$marks+"&comments="+escape($comment);
            $.post(target_page, function(data){ //alert(data);
                   window.location.reload();
            });
        }
    }


</script>
{/literal}
<div class="row-fluid">
    {if $recentcommentsblock eq "yes"}
    <table id="stageartsgrid" class="table table-bordered table-striped table_vam">

        <tbody>
        {if $recentcomments != 'NO'}
        <tr>
            <td>{$recentcomments} </td>
        </tr>
        {else}
        <tr>
            <td colspan="2">No data available</td>
        </tr>

        {/if}

        </tbody>

    </table>
    {else}
    <div class="span12" >
        <div class="formSep">
            <div class="row-fluid">
                <div class="span8 form-inline">
                    <label class="span4">Marks <span class="f_req">*</span></label>
                    <select name="marks" id="marks" class="span4">
                        <option value="0">select marks</option>
                        {section name=val start=1 loop=11 step=1}

                        <option value="{$smarty.section.val.index}">{$smarty.section.val.index}</option>
                        {/section}
                    </select>
                </div>
            </div>
        </div>
        <div class="formSep">
            <div class="row-fluid">
                <div class="span10 form-inline">
                    <label class="span3">Comments <span class="f_req">*</span></label>
                    <textarea cols="20" rows="4" id="marks_comments" name="marks_comments" class="span8"></textarea>
                </div>
            </div>
        </div>
        <div class="formSep">
            <div class="row-fluid">
                <div class="span10 form-inline">
                    <button type="button" class="btn btn-success" onclick="saveMarksComments('{$articleId}','{$partId}');" >valider</button>
                </div>
            </div>
        </div>
    </div>
    {/if}
</div>

