{literal}
 <script type="text/javascript" >
	$(document).ready(function() {
	   $('#contact_table').dataTable({
				"sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
				"sPaginationType": "bootstrap",
				"aaSorting": [[ 0, "asc" ]],
				"aoColumns": [
					{ "sType": "formatted-num" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" }
				]
		});
	} );

   function getContactusMessage(msgId)
    {
        var target_page = "/mails/getcontactusmessage?messageId="+msgId;
        $.post(target_page, function(data){
			$("#replymailcontent").html(data);
        });
    }
    
    function valDelete()
    {
       var c = confirm("Do You Really Want to Delete This Message");
        if(c)
        return true;
        else
        return false;
    }
 </script>
{/literal}

<div class="row-fluid">
	<div class="span12">
		<h3 class="heading">Syst&egrave;me de messages :: Messages provenant du  formulaire de contact</h3>
        <table class="table table-bordered table-striped table_vam" id="contact_table">
	  		<thead>
				<tr>
				  <th>ID N&deg;</th>
				  <th>De</th>
				  <th>Objet</th>
				  <th>Email</th>
				  <th>Reçu à</th>
				  <th>ACTIONS</th>
				</tr>
			</thead>
			<tbody>
			{foreach from=$paginator item=message name=MainMenu_loop}
				<tr>
				   <td>{$smarty.foreach.MainMenu_loop.index+1}</td>
				   <td>{$message.name}</td>
				   <td style="text-align:left;"><a href="/mails/viewmail/?submenuId={$submenuId}&mailaction=contactusmailreply&page={$smarty.request.page}&contactusmsgId={$message.identifier}" >
					   {if $message.status == 0}<b>{$message.msg_object|stripslashes|wordwrap:23:"\n":true}</b>{else}
					   {$message.msg_object|stripslashes|wordwrap:23:"\n":true}
					   {/if}</a></div>
				   <td>{$message.email}</td>
				   <td>{$message.created_at}</td>
				   <td>
						<a href="contactus?submenuId={$submenuId}&contactusmsgId={$message.identifier}" onclick="return valDelete();">
							<i class="splashy-remove"></i>
						</a>&nbsp; 
						<a onclick="return getContactusMessage('{$message.identifier}');" style="cursor: pointer" data-target="#replymail" data-toggle="modal">
							<img width="16" height="16" border="0" alt="%reply%" title="%reply%" src="/image/reply.png">
						</a>
				   </td>
				</tr>
				{/foreach}
			</tbody>
		</table>
	</div>
</div>	

	<!--Add/Edit template-->
	<div class="modal hide fade" id="replymail">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">&times;</button>
			<h3>Accepter/ Refuse mail</h3>
		</div>
		<div class="modal-body" id="replymailcontent">
		</div>
		<div class="modal-footer">
		</div>
	</div>