{literal}
<script type="text/javascript" charset="utf-8" src="/BO/theme/gebo/js/datempicker.js"></script>
<script type="text/javascript" charset="utf-8" src="/BO/theme/gebo/js/jquery.MultiFile.js"></script>
<script src="/BO/theme/gebo/lib/tiny_mce/jquery.tinymce.js"></script>
<script type="text/javascript">
	$(document).ready(function(){
		$("#selectgroup").chosen({ allow_single_deselect: false });	
		  
		$('#mail_time').datetimepicker({
            showSecond: true,
            timeFormat: 'hh:mm:ss',
            minDate: new Date(),
            stepHour: 1,
            stepMinute: 1,
            stepSecond: 10,
            timeOnlyTitle: 'Choisir une heure',
            timeText: 'Heure',
            hourText: 'Heures',
            minuteText: 'Minutes',
            secondText: 'Secondes',
            currentText: 'Maintenant',
            closeText: 'Termin&eacute'
        });
    $("#usercontacts").multiselect();
	$("#usercontacts").multiselectfilter();
	$(".uni_style").uniform(); 
	$('#filePJ1').MultiFile();

        $('textarea').tinymce({
            // Location of TinyMCE script
            script_url 							: '/BO/theme/gebo/lib/tiny_mce/tiny_mce.js?' + new Date().getTime(),
            // General options
            theme 								: "advanced",
            plugins 							: "autoresize,style,table,advhr,advimage,advlink,emotions,inlinepopups,preview,media,contextmenu,paste,fullscreen,noneditable,xhtmlxtras,template,advlist",
            // Theme options
            theme_advanced_buttons1 			: "undo,redo,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
            theme_advanced_buttons2 			: "forecolor,backcolor,|,cut,copy,paste,pastetext,|,bullist,numlist,link,image,media,|,code,preview,fullscreen",
            theme_advanced_buttons3 			: "",
            theme_advanced_toolbar_location 	: "top",
            theme_advanced_toolbar_align 		: "left",
            theme_advanced_statusbar_location 	: "bottom",
            theme_advanced_resizing 			: false,
            height                              : 300,
            content_css                         : "/BO/theme/gebo/css/tinymce_styles.css?" + new Date().getTime(),
            theme_advanced_font_sizes           : "8px,10px,12px,13px,14px,16px,18px,20px",
            font_size_style_values              : "8px,10px,12px,13px,14px,16px,18px,20px",
            init_instance_callback				: function(){

                function resizeWidth() {
                    document.getElementById(tinyMCE.activeEditor.id+'_tbl').style.width='100%';
                }
                resizeWidth();
                $(window).resize(function() {
                    resizeWidth();
                })
            }
        });
	

	});
    
	function disablemailtime()
    {
        var chk=$("input[name='mailnow']:checked").val();

        if(chk=="checked")
            $("#mail_time").attr('disabled','true');
         // $("#mail_time_at").val($.now());
        else
		{
            $("#mail_time").removeAttr('disabled');
			$("#mail_time_at").val('');
		}	
    }
   function fnloaduser()
	{
		var utype=$('#selectgroup').val();
		window.location="/mails/newsletter?submenuId=ML4-SL10&selectgroup="+utype;
	}


</script>

<style>
	input,textarea{text-transform:none;}
</style>
{/literal}

<div class="row-fluid">
	<div class="span12">
		<h3 class="heading">Envoi d'une newsletter</h3>
		<form action="/mails/sendnewsletter" method="post" id="user" name="user" enctype="multipart/form-data" >
			<table cellpadding="4" cellspacing="4" align="center" width="80%">
				<tr>
					<td>De</td>
					<td><input type="text" id="newsletter_from" name="newsletter_from" value="{$from_contact}" /></td>
				</tr>
				<tr>
					<td>Groupe</td>
					<td>
						<select id="selectgroup" name="selectgroup" onchange="fnloaduser();" >
							<option value="all" {if $smarty.get.selectgroup eq 'all'} selected{/if}>Tous</option>
							<option value="client" {if $smarty.get.selectgroup eq 'client'} selected{/if}>Clients</option>
							<option value="contributor" {if $smarty.get.selectgroup eq 'contributor'} selected{/if}>Contributors</option>
							<option value="superadmin" {if $smarty.get.selectgroup eq 'superadmin'} selected{/if}>Super Admin</option>
							<option value="ceouser" {if $smarty.get.selectgroup eq 'ceouser'} selected{/if}>Ceo Users</option>
							<option value="salesuser" {if $smarty.get.selectgroup eq 'salesuser'} selected{/if}>Sales</option>
							<option value="chiefeditor" {if $smarty.get.selectgroup eq 'chiefeditor'} selected{/if}>Chief Editors</option>
							<option value="editor" {if $smarty.get.selectgroup eq 'editor'} selected{/if}>Editors</option>
							<option value="seo" {if $smarty.get.selectgroup eq 'seo'} selected{/if}>Seo Users</option>
							<option value="custormercare" {if $smarty.get.selectgroup eq 'custormercare'} selected{/if}>Customer Care</option>
							<option value="partners" {if $smarty.get.selectgroup eq 'partners'} selected{/if}>Partners</option>
							<option value="facturation" {if $smarty.get.selectgroup eq 'facturation'} selected{/if}>Facturation</option>
						</select>
					</td>
				</tr>
				<tr>
					<td valign="top">Utilisateur(s)</td>
					<td>
						<select multiple="multiple" id="usercontacts" name="usercontacts[]" class="span6">    
							{html_options id=usercontacts options=$user_contacts selected=$smarty.get.usercontacts}
						</select>
					</td>
				</tr>
				<tr>
					<td valign="top">Date d'envoi</td>
					<td>
						<input type="text" id="mail_time" name="mail_time" readonly="readonly" value="{$mail_time}" {if $publishnow=="checked"}disabled="disabled"{/if} style="float:left;"/>
						<label class="uni-checkbox" >
							<input type="checkbox" name="mailnow" id="mailnow" onclick="disablemailtime()" class="uni_style" value="checked" {if $mailnow=="checked"}checked{/if}/>Maintenant
						</label>	
					</td>
				</tr>
				<tr>
					<td valign="top">Objet</td>
					<td><input type="text" name="msg_object" id="msg_object" class="span10" /></td>
				</tr>
				<tr>
					<td valign="top">Message</td>
					<td><textarea rows="8" class="span5" name="mail_message" id="mail_message"></textarea></td>
				</tr>
				<tr>
					<td valign="top">Pi&egrave;ce jointe</td>
					<td>
						<input type="file" class="btn btn-file multi" name="attachment[]" id="attachment">
					</td>
				</tr>
				<tr>
					<td></td>
					<td><input type="submit" class="btn btn-info" value="Envoyer" name="usersubmit" /></td>
				</tr>
			</table>	
		</form>
	</div>
</div>
