{literal}
 <script type="text/javascript" >
    function getContactusMessage(msgId)
    {
        var target_page = "/mails/getcontactusmessage?messageId="+msgId;
        $.post(target_page, function(data){
          $("#replymailcontent").html(data);
        });
    }
 </script>
{/literal}

<div class="row-fluid">
	<div class="span12">
		<h3 class="heading">Mail System :: View Mail</h3>
		<div class="formbody">
			{if $replyMessages|@count gt 0}
				{foreach item=message from=$replyMessages}
					<div class="msg-holder-r-read" >
						{if $message.userid==$Identifier}
							<div class="msg-title-r" style="cursor:pointer">
						{else}
							<div class="msg-title-c" style="cursor:pointer">
						{/if}
						{$message.Subject}
						</div>
						<div class="msg-text-r" id="message_{$message.messageId}">
							{if $smarty.now|date_format:"%d/%m/%Y" eq $message.receivedDate|date_format:"%d/%m/%Y"}
								<b>De: {$message.sendername} - Re&ccedil;u le :  {$message.receivedDate|date_format:"%R"} </b><br/>
							{else}		
								<b>De: {$message.sendername} - Re&ccedil;u le :  {$message.receivedDate|date_format:"%d/%m/%Y %R"} </b><br/>
							{/if}
								{$message.content}
							{if $message.attachment_name!=''}
								<div style="text-align:left;margin-top:20px"><strong>Pi&egrave;ce jointe : </strong></div>
									{foreach item=attachment_file from=$message.attachment_files name=files}
										<div style="text-align:left;margin-top:5px">
											{$attachment_file} 		
											<a target="_blank" href="/mails/viewmail?mailaction=viewattachment&display=attachment&index={$smarty.foreach.files.index}&attachment={$message.messageId}" class="btn btn-info">T&eacute;l&eacute;charger</a>
										</div>
									{/foreach}
							{/if}		
						</div>
					</div>
				{/foreach}
			{/if}
			
			{foreach item=message from=$viewMessage}
				<div>
					{if $smarty.get.mailaction!='inboxview'}
					<div style="background-color:rgb(235, 242, 246);line-height: 32px;padding: 0 10px;font-weight:bold">{$message.Subject}</div>
					<div style="text-transform:none;padding: 10px;">
						{if $smarty.get.mailaction=='approveview'}
							<b>From: {$message.sendername}<br> To: {$message.recipientname}  -  Re&ccedil;u le : {$message.receivedDate} </b><br/>
						{else}
							<b>De: {$message.sendername}  -  Re&ccedil;u le : {$message.receivedDate} - Email : {$message.email}</b><br/>
						{/if}

						{$message.text_message|utf8_decode|stripslashes}

						{if $message.attachment_name!=''}

							<div style="text-align:left;margin-top:20px"><strong>Attachment : </strong></div>
							{foreach item=attachment_file from=$attachments name=files}
								<div style="text-align:left;margin-top:5px">
									{$attachment_file}
									<a target="_blank" href="/mails/viewmail/?submenuId={$submenuId}&mailaction=viewattachment&display=attachment&index={$smarty.foreach.files.index}&attachment={$message.id}" class="btn btn-info">T&eacute;l&eacute;charger</a>
								</div>
							{/foreach}

						{/if}

					</div>
					{/if}
					{if $smarty.get.mailaction=='sentview'}
						<div style="text-align:left">
							<a  href="/mails/sentmails?submenuId=ML4-SL3&page={$smarty.get.page}" class="btn btn-info">Retour</a>
						</div>

					{elseif $smarty.get.mailaction=='classview'}
						<div style="text-align:right">
							<a  href="/mails/classifybox?submenuId=ML4-SL4&mailaction=classifybox&ticket={$smarty.get.ticket}&page={$smarty.get.page}" class="btn btn-info">Retour</a>
						</div>

					{elseif $smarty.get.mailaction=='inboxview'}
						{if ($message.locked_user eq NULL && $message.bo_user_type eq NULL ) OR ($message.locked_user && $message.bo_user_type)}
						<div style="float:right">
							<a href="/mails/replymail?submenuId=ML4-SL3&mailaction=reply&reply_message={$message.id}&ticket={$message.ticket_id}"><img src="/BO/images/reply.png"/></a>
						</div>
						<div style="float:right;margin-right:8px">
							<a href="/mails/classifymail?submenuId=ML4-SL3&ticket={$message.ticket_id}" onclick="return confirm('Do you want to move this message to classes?');"><img src="/BO/images/classify.png"/></a>
						</div>
						{/if}
						{if $message.locked_user eq NULL && $message.bo_user_type}
							<div style="float:right;margin-right:8px">
							<a href="/mails/message-lock?submenuId=ML4-SL2&status=lock&messageId={$message.id}">
							 <img width="28" height="27" border="0" alt="Lock" title="Lock" src="/image/picto/unlock_blue.png" style="vertical-align:top"></a>
							 </div>
						{elseif $message.locked_user && $message.bo_user_type}
							<div style="float:right;margin-right:8px">
							<a href="/mails/message-lock?submenuId=ML4-SL2&status=unlock&messageId={$message.id}">
							 <img width="28" height="27" border="0" alt="Unlock" title="Unlock" src="/image/picto/lock_org.png" style="vertical-align:top"></a>
							 </div>
						{/if}
						<div style="text-align:left">
							<a  href="/mails/inbox?submenuId=ML4-SL2&page={$smarty.get.page}" class="btn btn-info">Retour</a>
						</div>
					{elseif $smarty.get.mailaction=='contactusmailreply'}
						<div style="text-align:left">
							<a  href="/mails/contactus?submenuId=ML4-SL9" class="btn btn-info">Retour</a>
						</div>
						<div style="text-align:right">
							<a  onclick="return getContactusMessage({$message.contactusmailId});" class="btn btn-info" data-target="#replymail" data-toggle="modal">Reply</a>
						</div>
					{else}
						<div style="text-align:left">
							<a  href="/mails/approvemails?submenuId=ML4-SL5&page={$smarty.get.page}" class="btn btn-info">Retour</a>
						</div>
						<div style="text-align:right">
							<a  href="/mails/mailapprove?messageId={$message.id}&page={$smarty.get.page}" class="btn btn-info">Approve</a>
						</div>
					{/if}
				</div>
			{/foreach}
	</div>
</div>

	<!--Add/Edit template-->
	<div class="modal hide fade" id="replymail">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">&times;</button>
			<h3>Accepter/ Refuse mail</h3>
		</div>
		<div class="modal-body" id="replymailcontent">
		</div>
		<div class="modal-footer">
		</div>
	</div>