
<form class="form_validation_reg" method="POST" action="/seotool/backlinks" name="importcsv" id="seo" ENCTYPE="multipart/form-data">
        <div class="span10">
            <h3 class="heading">Back links</h3>
            <div class="control-group formSep" id="seotool-notify" style="display: none;">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                            <div id="seo-message">{$msg}</div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">Type </label>
                        <label class="uni-radio"><input type="radio" name="file_type" class="uni_style"  value="1" {if $file_type neq '2'} checked {/if} id="csvxls">CSV / XLS</label>
                            <label class="uni-radio"><input type="radio" name="file_type" class="uni_style"  value="2" {if $file_type eq '2'} checked {/if} id="opt_text">Text</label>
                    </div>
                </div>
            </div>
            <div class="control-group formSep" id="csv" {if $file_type eq '2'} style="display:none" {/if}>
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3 control-label">URL(s)<span class="f_req">*</span></label>
                        <div data-provides="fileupload" class="fileupload fileupload-new"><input type="hidden" />
                            <div data-provides="fileupload" class="fileupload fileupload-new"><input type="hidden" />
                                <div class="input-append">
                                    <div class="uneditable-input span2"><i class="icon-file fileupload-exists"></i> <span class="fileupload-preview"></span></div><span class="btn btn-file"><span class="fileupload-new">Select file</span><span class="fileupload-exists">Change</span><input name="url_file" id="url_file" type="file" /></span><a data-dismiss="fileupload" class="btn fileupload-exists" href="#">Remove</a>
                               </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep" id="text_words" {if $file_type neq '2'} style="display:none"{/if} >
                <div class="row-fluid">
                    <div class="control-group">
                        <label class="span3 control-label">URL(s)<span class="f_req">*</span></label>
                        <div class="span8 controls">
                            <textarea name="url" id="txtarea_sp" cols="1" rows="4" class="span10">{$url}</textarea>
                            <span class="help-block">Enter Multiple urls in separate line</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">Run for</label>
                        <label class="uni-radio"><input type="radio" name="run_for" class="uni_style"  id="run_for1" value="1" checked>Given page</label>
                            <label class="uni-radio"><input type="radio" name="run_for" class="uni_style"  id="run_for2" value="2" >All pages of website</label>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <button class="btn btn-gebo" name="submit" type="submit" value="1">Process</button>
                    </div>
                </div>
            </div>
        </div>
</form>

<div id="data">
    
</div>

{literal}
    <script type="text/javascript">
	$.validator.addMethod("csvextension", function(value, element, param) {
		param = typeof param === "string" ? param.replace(/,/g, '|') : "xls|csv";
		return this.optional(element) || value.match(new RegExp(".(" + param + ")$", "i"));
	}, $.format("Please use only csv/xls file."));

        $(document).ready(function() {
            $(".uni_style").uniform();
            gebo_validation.reg();
        });
        $("input[name='file_type']").change(function() {
            var type=$('input[name=file_type]:checked').val();
            if(type==1)
            {
                $("#text_words").hide();
                $("#csv").show();
            }
            else
            {
                $("#text_words").show();
                $("#csv").hide();
            }
        });

        gebo_validation = {
            reg: function() {
                reg_validator = $('.form_validation_reg').validate({
                    onkeyup: false,
                    errorClass: 'error',
                    validClass: 'valid',
                    highlight: function(element) {
                        $(element).closest('div').addClass("f_error");
                        $(element).closest('div').css("color", "black");
                    },
                    unhighlight: function(element) {
                        $(element).closest('div').removeClass("f_error");
                    },
                    submitHandler: function(element) {
                        $('#seotool-notify').show();
                    },
                    errorPlacement: function(error, element) {
                        $('#seotool-notify').hide();
                        $(element).closest('div').append(error);
                        $('.error').css("font-size", "10px");
                        $('.error').css("padding-top", "5px");
                    },
                    rules: {
                             url: {required: function(element) {
                                  return $('input:radio[name=file_type]:checked').val()==2;
                                 }
                              },
                             url_file: {required: function(element) {
                                  return $('input:radio[name=file_type]:checked').val()==1;
                                 },
				 csvextension: "xls|csv"
                              }
                    },
                    messages: {
                        url: "Please enter url(s).",
                        url_file: {required: "Please selects csv/xls file.", accept: "Accept only xls or csv."}
                    },
                    invalidHandler: function(form, validator) {
                        $.sticky("There are some errors. Please corect them and submit again.", {autoclose : 5000, position: "top-center", type: "st-error" });
                    }
                })
            }
        };
    </script>
{/literal}
