
<form class="form_validation_reg" method="POST" action="/seotool/boulanger-product-url" name="importcsv" id="seo" ENCTYPE="multipart/form-data">
        <div class="span10">
            <h3 class="heading">Boulanger - Product URL</h3>
            <div class="control-group formSep" id="seotool-notify" style="display: none;">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                            <div id="seo-message">{$msg}</div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="control-group">
                        <label class="span3 control-label">Reference(s)<span class="f_req">*</span></label>
                        <div class="span8 controls">
                            <textarea name="reference" id="txtarea_sp" cols="1" rows="4" class="span10">{$reference}</textarea>
                            <span class="help-block">Enter references in separate line</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <button class="btn btn-gebo" name="submit" type="submit" value="1">Process</button>
                    </div>
                </div>
            </div>
        </div>
</form>

<div id="data">
    
</div>

{literal}
    <script type="text/javascript">

        $(document).ready(function() {
            $(".uni_style").uniform();
            gebo_validation.reg();
        });

        gebo_validation = {
            reg: function() {
                reg_validator = $('.form_validation_reg').validate({
                    onkeyup: false,
                    errorClass: 'error',
                    validClass: 'valid',
                    highlight: function(element) {
                        $(element).closest('div').addClass("f_error");
                        $(element).closest('div').css("color", "black");
                    },
                    unhighlight: function(element) {
                        $(element).closest('div').removeClass("f_error");
                    },
                    submitHandler: function(element) {
                        $('#seotool-notify').show();
                    },
                    errorPlacement: function(error, element) {
                        $('#seotool-notify').hide();
                        $(element).closest('div').append(error);
                        $('.error').css("font-size", "10px");
                        $('.error').css("padding-top", "5px");
                    },
                    rules: {
                             reference: { required: true }
                    },
                    messages: {
                        reference: "Please enter reference(s)."
                    },
                    invalidHandler: function(form, validator) {
                        $.sticky("There are some errors. Please corect them and submit again.", {autoclose : 5000, position: "top-center", type: "st-error" });
                    }
                })
            }
        };
    </script>
{/literal}
