
<form class="form_validation_reg" method="POST" action="/seotool/validatelinks" name="importcsv" id="seo" ENCTYPE="multipart/form-data">
        <div class="span10">

            <h3 class="heading">links</h3>
                        
            <div class="control-group formSep" id="seotool-notify" style="display: none;">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                            <div id="seo-message">{$msg}</div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">URL<span class="f_req">*</span></label>
                        <div class="span8 form-inline no-margin-first">
                            <input type="text" name="url_text" class="span5"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="control-group">
                        <label class="span3 control-label">Link(s)<span class="f_req">*</span></label>
                        <div class="span8 controls no-margin-first">
                            <textarea name="comp_url_text" id="txtarea_sp" cols="1" rows="4" class="span10"></textarea>
                            <span class="help-block">Enter Multiple links in separate line</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <button class="btn btn-gebo" name="submit" type="submit">Validate</button>
                    </div>
                </div>
            </div>
        </div>
</form>

<div id="data">
    
</div>

{literal}
    <script type="text/javascript">
    $.validator.addMethod("csvextension", function(value, element, param) {
        param = typeof param === "string" ? param.replace(/,/g, '|') : "xls|csv";
        return this.optional(element) || value.match(new RegExp(".(" + param + ")$", "i"));
    }, $.format("Please use only csv/xls file."));

        $(document).ready(function() {
            gebo_validation.reg();
        });

        gebo_validation = {
            reg: function() {
                reg_validator = $('.form_validation_reg').validate({
                    onkeyup: false,
                    errorClass: 'error',
                    validClass: 'valid',
                    highlight: function(element) {
                        $(element).closest('div').addClass("f_error");
                        $(element).closest('div').css("color", "black");
                    },
                    unhighlight: function(element) {
                        $(element).closest('div').removeClass("f_error");
                    },
                    submitHandler: function(element) {
                        $('#seotool-notify').show();
                    },
                    errorPlacement: function(error, element) {
                        $('#seotool-notify').hide();
                        $(element).closest('div').append(error);
                        $('.error').css("font-size", "10px");
                        $('.error').css("padding-top", "5px");
                    },
                    rules: {
                             url_text: { required: true },
                             comp_url_text: { required: true }
                    },
                    messages: {
                              url_text: "Please enter url.",
                              comp_url_text: "Please enter link(s)."
                    },
                    invalidHandler: function(form, validator) {
                        $.sticky("There are some errors. Please corect them and submit again.", {autoclose : 5000, position: "top-center", type: "st-error" });
                    }
                })
            }
        };
        function modalwindow(url)
        {
            $.get( "http://admin-ep-test.edit-place.com/seotool/"+url, function( data ) {
              $( ".modal-body" ).html( data );
            });
            $("#seoresults").modal('show');
        }
    </script>
{/literal}
