        <div class="span10">
        <form class="form_validation_reg" method="POST" action="/fblikeshare/torprocess" id="seo" ENCTYPE="multipart/form-data">
            <h3 class="heading">Facebook like/share count</h3>
                        
            <div class="control-group formSep" id="seotool-notify" style="display: none;">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                            <div id="seo-message">{$msg}</div>
                    </div>
                </div>
            </div>  
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3 control-label">Enter URL(s)<span class="f_req">*</span></label>
                        <div class="span8 controls">
                            <textarea name="url" id="txtarea_sp" cols="1" rows="4" class="span10">{$url}</textarea>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12">
                        <label class="span3">&nbsp;</label>
                        <div class="span8 no-margin-first">
                            <label class="uni-radio"><input type="radio" name="crawl_type" class="uni_style" id="crawl_type1" value="1" {$checked1}>Check all pages linked to given URL</label>
                            <label class="uni-radio"><input type="radio" name="crawl_type" class="uni_style" id="crawl_type2" value="2" {$checked2}>Check all pages of given site</label>
                            <label class="uni-radio"><input type="radio" name="crawl_type" class="uni_style" id="crawl_type3" value="3" {$checked3}>Only in given URL</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <label class="span3">&nbsp;</label>
                    <div class="span8 no-margin-first">
                        <label class="uni-checkbox">
                            <input type="checkbox" name="titlescraper" id="titlescraper" class="uni_style" value="1">
                            Title scraper
                        </label>
                        <label class="sub_chkbox_sep"></label>
                        <label class="uni-checkbox" id="title">
                            <input type="checkbox" name="kwdensity" id="kwdensity" class="uni_style" value="1">
                            kw density
                        </label>
                    </div>
                    <div class="span12" id="fr">
                        <label class="span3">&nbsp;</label>
                        <span class="help-block syntax">Limit</span>
                         <select name="limit" id="chosen_c" class="chzn_c">
                            <option value="10">10</option>
                            <option value="20">20</option>
                            <option value="30">30</option>
                         </select>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <label class="span3">&nbsp;</label>
                    <div class="span8 no-margin-first">
                        <label class="uni-checkbox">
                            <input type="checkbox" name="fbtwittercount" id="fbtwittercount" class="uni_style" value="1">
                            facebook/twitter count
                        </label>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12">
                        <label class="span3">&nbsp;</label>
                        <div class="span8 no-margin-first">
                            <label class="uni-radio"><input type="radio" name="result_type" class="uni_style" id="result_type" value="1" checked="checked">Immediate results</label>
                            <label class="uni-radio"><input type="radio" name="result_type" class="uni_style" id="result_type" value="2">Later</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep" id="emailRow" style="display:none;">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3 control-label">Email<span class="f_req">*</span></label>
                        <div class="span8 controls">
                            <input type="text" class="span5" name="email" id="email">
                        </div>
                    </div>
                </div>
            </div>
        </form>
            <div class="control-group">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <button class="btn btn-gebo" name="submit" id="fbtwsubmit" type="submit">Submit</button>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="row-fluid" id="data">
                </div>
            </div>
        </div>

{literal}
    <script type="text/javascript">
        var cnt;
        $(document).ready(function() {
            $(".uni_style").uniform();
            gebo_validation.reg();
            //gebo_validation.validated();
    	    gebo_chosen.init();
        });
	    gebo_chosen = {
            init: function(){
                $(".chzn_c").chosen({
                    allow_single_deselect: true,
                    disable_search: true
                });
            }
        };
        gebo_validation = {
            reg: function() {
                reg_validator = $('.form_validation_reg').validate({
                    onkeyup: false,
                    errorClass: 'error',
                    validClass: 'valid',
                    highlight: function(element) {
                        $(element).closest('div').addClass("f_error");
                        $(element).closest('div').css("color", "black");
                    },
                    unhighlight: function(element) {
                        $(element).closest('div').removeClass("f_error");
                    },
                    errorPlacement: function(error, element) {
                        $('#seotool-notify').hide();
                        $(element).closest('div').append(error);
                        $('.error').css("font-size", "10px");
                        $('.error').css("padding-top", "5px");
                    },
                    rules: {
                             url: { required: true },
                             email: { required: function(element) {return $('input:radio[name=result_type]:checked').val()==2;}, email :true }
                    },
                    messages: {
                              url: "Please enter url(s).",
                             email: { required: "Please enter email id.", email :"Invalid email id." }
                    },
                    invalidHandler: function(form, validator) {
                        $.sticky("There are some errors. Please corect them and submit again.", {autoclose : 5000, position: "top-center", type: "st-error" });
                    },
                    submitHandler: function(form) {
                        $('#seotool-notify').show();
                        var lenn = ($('#txtarea_sp').val()).split('\n');
                        cnt = (lenn.length)*4;
                        var result_type = $("input[type='radio'][name='result_type']:checked").val();
                        if(result_type != 2)
                        {
                            var worker = new Worker('http://admin-ep-test.edit-place.com/BO/theme/gebo/js/processingInterval.js');
                            worker.postMessage(cnt);
                            worker.onmessage = function (event) {
                                //if(event.data!='undefined')
                                document.getElementById('seo-message').innerHTML ="<b>" + event.data + "</b> seconds remaining approximately.";
                            };
                        }
                    }
                })
            }
        };

        $("input[name='kwdensity']").change(function() {
            var type=$('input[name=kwdensity]:checked').val();
            if(type==1) {$("#fr").show();} else {$("#fr").hide();}
        });

        $("input[name='titlescraper']").change(function() {
            var titlescraper=$('input[name=titlescraper]:checked').val();
            if(titlescraper==1) {$("#title").show();} else {$("#title").hide();}
        });
        
        $("input[name='result_type']").change(function() {
            var result_type=$('input[name=result_type]:checked').val();
            if(result_type==1)
            {
              $("#emailRow").hide();
            }
            else
            {
              $("#emailRow").show();
            }
        });
        
        $(document).ready(function() {
            $("#fbtwsubmit").click(function(event) {
                
                var lenn1 = ($('#txtarea_sp').val()).split('\n');
                cnt1 = (lenn1.length)*4;
                var result_type = $("input[type='radio'][name='result_type']:checked").val();
                if(((lenn1.length)>0) && ((result_type==1) || (result_type==2 && ($('#email').val()!='') )))
                {//alert('if valid');
                    if(result_type != 2)
                    {//alert('if valid rt=1');
                        if(cnt1>180) //180
                        {//alert('if valid rt=1 3m if');
                            if(confirm("Processig will take more than 3 minutes. Do you want to proceed?"))
                            {
                                $('#seo').submit();
                            }
                            else
                            {
                                event.preventDefault();
                            }
                        }
                        else
                        {//alert('if valid rt=1 3m else');
                            $('#seo').submit();
                        }
                    }
                    else
                    {//alert('if valid rt=2');
                        $('#seo').submit();
                    }
                }
                else
                {
                    //alert('else valid');
                    $('#seo').submit();
                }
            });
        });
    </script>
{/literal}
