<form class="form_validation_reg" method="POST" action="/seotool/frequencyssh2upload" name="importcsv" id="seo" ENCTYPE="multipart/form-data">
    <div class="span10">

        <h3 class="heading">Frequency Search Tool</h3>

        <div class="control-group formSep" id="seotool-notify" style="display: none;">
            <div class="row-fluid">
                <div class="span12 form-inline">
                    <div id="seo-message">
                        {$msg}
                    </div>
                </div>
            </div>
        </div>

        <div class="control-group formSep">
            <div class="row-fluid">
                <div class="span12 form-inline">
                    <label class="span3"><span class="error_placement">Client</span><span class="f_req">*</span></label>
                    <select name="client" id="clientlst" class="chzn_a">
                        <option value="">S&eacute;lectionner</option>
                        {$clients}
                    </select>
                </div>
            </div>
        </div>

        <div class="control-group formSep">
            <div class="row-fluid">
                <div class="span12 form-inline">
                    <label class="span3"><span class="error_placement">Contract</span><span class="f_req">*</span></label>
                    <select name="contract" id="contract" class="chzn_b">
                        <option value="">S&eacute;lectionner</option>
                        {$contracts}
                    </select>
                </div>
            </div>
        </div>
        <!--<div class="control-group formSep" id="from">
            <div class="row-fluid">
                <div class="span12 form-inline">
                    <label class="span3">From<span class="f_req">*</span></label>
                    <div id="from_date1" class="input-append date" >
                        <input data-format="dd/mm/YYYY" id="from_date" name="from_date" type="text" value="" class="input-append date" readonly="readonly" />
                        <span class="add-on"> <i data-time-icon="icon-time" data-date-icon="icon-calendar"> </i> </span>
                    </div>
                </div>
            </div>
        </div>
        <div class="control-group formSep" id="to">
            <div class="row-fluid">
                <div class="span12 form-inline">
                    <label class="span3">To<span class="f_req">*</span></label>
                    <div id="to_date1" class="input-append date" >
                        <input data-format="dd/mm/YYYY" id="to_date" name="to_date" type="text" value="" class="input-append date" readonly="readonly" />
                        <span class="add-on"> <i data-time-icon="icon-time" data-date-icon="icon-calendar"> </i> </span>
                    </div>
                </div>
            </div>
        </div>-->
        <div class="control-group formSep" id="to">
            <div class="row-fluid">
                <div class="span12 form-inline">
                    <label class="span3">Date<span class="f_req">*</span></label>
                    <div class="span2 no-margin-first">
                        <span class="help-block">From</span>
                        <div class="input-append date" id="dp_start">
                            <input class="span6" name="from_date" type="text" readonly="readonly" style="width:90px;" /><span class="add-on"><i class="splashy-calendar_day_up"></i></span>
                        </div>
                    </div>
                    <div class="span3">
                        <span class="help-block">To</span>
                        <div class="input-append date" id="dp_end">
                            <input class="span6" name="to_date" type="text" readonly="readonly" style="width:90px;" /><span class="add-on"><i class="splashy-calendar_day_down"></i></span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="control-group formSep">
            <div class="row-fluid">
                <div class="span12 form-inline">
                    <label class="span3">Frequency<span class="f_req">*</span></label>
                    <label class="uni-checkbox"> <span id="select_all" style="display: block;"><a class="label label-info select-all" href="javascript:void(0);">Select all</a></span> </label>
                </div>
            </div>
        </div>
        <div class="control-group formSep">
            <div class="row-fluid" id="frequencyDaysRow">
                <div class="span12" id="days">
                    <label class="span3">&nbsp;</label>
                    <div class="span2 no-margin-first">
                        <label class="uni-checkbox">
                            <input type="checkbox" name="day[]" id="day1" class="uni_style" value="sunday">
                            sunday </label>
                        <label class="uni-checkbox">
                            <input type="checkbox" name="day[]" id="day2" class="uni_style" value="thursday">
                            Thursday </label>
                    </div>
                    <div class="span2">
                        <label class="uni-checkbox">
                            <input type="checkbox" name="day[]" id="day3" class="uni_style" value="monday">
                            Monday </label>
                        <label class="uni-checkbox">
                            <input type="checkbox" name="day[]" id="day4" class="uni_style" value="friday">
                            Friday </label>
                    </div>
                    <div class="span2">
                        <label class="uni-checkbox">
                            <input type="checkbox" name="day[]" id="day5" class="uni_style" value="tuesday">
                            Tuesday </label>
                        <label class="uni-checkbox">
                            <input type="checkbox" name="day[]" id="day6" class="uni_style" value="saturday">
                            Saturday </label>
                    </div>
                    <div class="span2">
                        <label class="uni-checkbox">
                            <input type="checkbox" name="day[]" id="day7" class="uni_style" value="wednesday">
                            Wednesday </label>
                    </div>
                </div>
            </div>
        </div>
        <div class="control-group">
            <div class="row-fluid">
                <div class="span12 form-inline">
                    <button class="btn btn-gebo" name="submit" type="submit">
                        Search
                    </button>
                </div>
            </div>
        </div>
    </div>
</form>

<div id="data">

</div>

{literal}
<script type="text/javascript">
	$(document).ready(function() {
		$(".uni_style").uniform();
		gebo_validation.reg();
		gebo_chosen.init();
		gebo_datepicker.init();
		$('#from_date1').datepicker({
			language : 'pt-BR',
			format : 'dd/mm/yyyy',
			pickSeconds : false,
			pick12HourFormat : false
		});
		$('#to_date1').datepicker({
			language : 'pt-BR',
			format : 'dd/mm/yyyy',
			pickSeconds : false,
			pick12HourFormat : false
		});
	});

	$('a.select-all').bind('click', function() {
		for (var i = 1; i <= 7; i++) {
			$('#day' + i).click();
		}
		if (this.innerHTML.indexOf('Deselect') != -1) {
			$(this).text('Select all');
		} else {
			$(this).text('Deselect all');
		}
	});

	gebo_chosen = {
		init : function() {
			$(".chzn_a").chosen({
				allow_single_deselect : true
			});
			$(".chzn_b").chosen({
				allow_single_deselect : true,
				disable_search : true
			});
		}
	};

	gebo_validation = {
		reg : function() {
			reg_validator = $('.form_validation_reg').validate({
				onkeyup : false,
				errorClass : 'error',
				validClass : 'valid',
				highlight : function(element) {
					$(element).closest('div').addClass("f_error");
					$(element).closest('div').css("color", "black");
				},
				unhighlight : function(element) {
					$(element).closest('div').removeClass("f_error");
				},
				submitHandler : function(element) {
					$('#seotool-notify').show();
				},
				errorPlacement : function(error, element) {
					$('#seotool-notify').hide();
					$(element).closest('div').append(error);
					$('.error').css("font-size", "10px");
					$('.error').css("padding-top", "5px");
				},
				rules : {
					client : {
						required : true
					},
					contract : {
						required : true
					},
					from_date : {
						required : true
					},
					to_date : {
						required : true
					},
					'day[]' : {
						required : true
					},
				},
				messages : {
					client : "Please Select client.",
					contract : "Please Select contract.",
					from_date : "Please select from date.",
					to_date : "Please select end date.",
					'day[]' : "Please select any one of the frequency day."
				},
				invalidHandler : function(form, validator) {
					$.sticky("There are some errors. Please corect them and submit again.", {
						autoclose : 5000,
						position : "top-center",
						type : "st-error"
					});
				}
			})
		}
	};

    gebo_datepicker = {
        init: function() {
            $('#dp1').datepicker();
            $('#dp2').datepicker();
            
            $('#dp_start').datepicker({format: "mm/dd/yyyy"}).on('changeDate', function(ev){
                var dateText = $(this).data('date');
                
                var endDateTextBox = $('#dp_end input');
                if (endDateTextBox.val() != '') {
                    var testStartDate = new Date(dateText);
                    var testEndDate = new Date(endDateTextBox.val());
                    if (testStartDate > testEndDate) {
                        endDateTextBox.val(dateText);
                    }
                }
                else {
                    endDateTextBox.val(dateText);
                };
                $('#dp_end').datepicker('setStartDate', dateText);
                $('#dp_start').datepicker('hide');
            });
            $('#dp_end').datepicker({format: "mm/dd/yyyy"}).on('changeDate', function(ev){
                var dateText = $(this).data('date');
                var startDateTextBox = $('#dp_start input');
                if (startDateTextBox.val() != '') {
                    var testStartDate = new Date(startDateTextBox.val());
                    var testEndDate = new Date(dateText);
                    if (testStartDate > testEndDate) {
                        startDateTextBox.val(dateText);
                    }
                }
                else {
                    startDateTextBox.val(dateText);
                };
                $('#dp_start').datepicker('setEndDate', dateText);
                $('#dp_end').datepicker('hide');
            });
            $('#dp_modal').datepicker();
        }
    };
    
	function modalwindow(url) {
		$.get("http://admin-test.edit-place.com/seotool/" + url, function(data) {
			$(".modal-body").html(data);
		});
		$("#seoresults").modal('show');
	}
</script>
{/literal}
