
<form class="form_validation_reg" method="POST" action="/seotool/googlesuggesttor" name="importcsv" id="seo" ENCTYPE="multipart/form-data">
        <div class="span10">

            <h3 class="heading">Google Suggest</h3>
                        
            <div class="control-group formSep" id="seotool-notify" style="display: none;">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                            <div id="seo-message">{$msg}</div>
                    </div>
                </div>
            </div>  
            
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">Type </label>
                        <label class="uni-radio"><input type="radio" name="word_type" class="uni_style"  value="1" {if $word_type neq '2'} checked {/if} id="csvxls">CSV / XLS</label>
                            <label class="uni-radio"><input type="radio" name="word_type" class="uni_style"  value="2" {if $word_type eq '2'} checked {/if} id="opt_text">Text</label>
                    </div>
                </div>
            </div>
            <div class="control-group formSep" id="csv" {if $word_type eq '2'} style="display:none" {/if}>
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">Keywords<span class="f_req">*</span></label>
                        
                        <div data-provides="fileupload" class="fileupload fileupload-new"><input type="hidden" />
                            <div data-provides="fileupload" class="fileupload fileupload-new"><input type="hidden" />
                                <div class="input-append">
                                    <div class="uneditable-input span2"><i class="icon-file fileupload-exists"></i> <span class="fileupload-preview"></span></div><span class="btn btn-file"><span class="fileupload-new">Select file</span><span class="fileupload-exists">Change</span><input name="keyword_file" id="keyword_file" type="file" /></span><a data-dismiss="fileupload" class="btn fileupload-exists" href="#">Remove</a>
                               </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep" id="text_words" {if $word_type neq '2'} style="display:none"{/if} >
                <div class="row-fluid">
                    <div class="control-group">
                        <label class="span3 control-label">Keywords<span class="f_req">*</span></label>
                        <div class="span8 controls">
                            <textarea name="kw" id="txtarea_sp" cols="1" rows="4" class="span10">{$kw}</textarea>
                            <span class="help-block">Enter Multiple keywords in separate line</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3"><span class="error_placement">Site<span class="f_req">*</span></span></label>
                        <label class="uni-checkbox">
                            <input type="checkbox" name="site[]" id="google" class="uni_style" value="google">
                            Google
                        </label>
                        <span id="ae_ch">
                            <label class="uni-checkbox">
                                <input type="checkbox" name="site[]" id="yahoo" class="uni_style" value="yahoo">
                                Yahoo
                            </label>
                            <label class="uni-checkbox">
                                <input type="checkbox" name="site[]" id="amazon" class="uni_style" value="amazon">
                                Amazon
                            </label>
                            <label class="uni-checkbox">
                                <input type="checkbox" name="site[]" id="bing" class="uni_style" value="bing">
                                Bing
                            </label>
                            <label class="uni-checkbox">
                                <input type="checkbox" name="site[]" id="wiki" class="uni_style" value="wiki">
                                Wikipedia
                            </label>
                        </span>
                        <label class="uni-checkbox" id="aol_">
                            <input type="checkbox" name="site[]" id="aol" class="uni_style" value="aol">
                            AOL
                        </label>
                        <label class="uni-checkbox" id="ask_">
                            <input type="checkbox" name="site[]" id="ask" class="uni_style" value="ask">
                            ASK
                        </label>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12">
                        <label class="span3">Language</label>
                        <div class="span2 no-margin-first">
                            <label class="uni-radio"><input type="radio" id="site_ext1" name="site_ext" class="uni_style"  value="1" checked>fr</label>
                            <label class="uni-radio"><input type="radio" id="site_ext2" name="site_ext" class="uni_style"  value="2">com</label>
                            <label class="uni-radio"><input type="radio" id="site_ext3" name="site_ext" class="uni_style"  value="3">pt</label>
                            <label class="uni-radio"><input type="radio" id="site_ext4" name="site_ext" class="uni_style"  value="4">in</label>
                        </div>
                        <div class="span2">
                            <label class="uni-radio"><input type="radio" id="site_ext5" name="site_ext" class="uni_style"  value="5">uk</label>
                            <label class="uni-radio"><input type="radio" id="site_ext6" name="site_ext" class="uni_style"  value="6">it</label>
                            <label class="uni-radio"><input type="radio" id="site_ext7" name="site_ext" class="uni_style"  value="7">es</label>
                            <label class="uni-radio"><input type="radio" id="site_ext8" name="site_ext" class="uni_style"  value="8">de</label>
                        </div>
                        <div class="span2">
                            <label class="uni-radio"><input type="radio" id="site_ext9" name="site_ext" class="uni_style"  value="9">br</label>
                            <label class="uni-radio"><input type="radio" id="site_ext10" name="site_ext" class="uni_style"  value="10">Arabic</label>
                            <label class="uni-radio"><input type="radio" id="site_ext11" name="site_ext" class="uni_style"  value="11">Chinese</label>
                            <label class="uni-radio"><input type="radio" id="site_ext12" name="site_ext" class="uni_style"  value="12">pl</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">Combinations</label>
                        <label class="uni-radio"><input type="radio" name="combination" class="uni_style"  id="combination1" value="1" checked>Only Source Keyword</label>
                            <label class="uni-radio"><input type="radio" name="combination" class="uni_style"  id="combination2" value="2" >Source and +a...+z</label>
                        <label class="uni-radio"><input type="radio" name="combination" class="uni_style"  id="combination3" value="3" >for Source and +a...+z and +0..+9</label>


                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <button class="btn btn-gebo" name="submit" type="submit">Suggest</button>
                    </div>
                </div>
            </div>
        </div>
</form>

<div id="data">
    
</div>

{literal}
    <script type="text/javascript">
	$.validator.addMethod("csvextension", function(value, element, param) {
		param = typeof param === "string" ? param.replace(/,/g, '|') : "xls|csv";
		return this.optional(element) || value.match(new RegExp(".(" + param + ")$", "i"));
	}, $.format("Please use only csv/xls file."));

        $(document).ready(function() {
            $(".uni_style").uniform();
            gebo_validation.reg();
        });
        $("input[name='word_type']").change(function() {
            var type=$('input[name=word_type]:checked').val();
            if(type==1)
            {
                $("#text_words").hide();
                $("#csv").show();
            }
            else
            {
                $("#text_words").show();
                $("#csv").hide();
            }
        });
        $("input[name='site_ext']").change(function() {
            var lang=$('input[name=site_ext]:checked').val();
            if(lang==10 || lang==11)
            {
                $('#ae_ch').hide();
                if($('#yahoo').attr('checked', true)){$('#yahoo').click();}
                if($('#amazon').attr('checked', true)){$('#amazon').click();}
                if($('#bing').attr('checked', true)){$('#bing').click();}
                if($('#wiki').attr('checked', true)){$('#wiki').click();}
            }
            else
            {
                $('#ae_ch').show();
            }
            if(lang>5 && lang!=12)
            {
                $('#aol_').hide();  if($('#aol').attr('checked', true)){$('#aol').click();}
            } else {$('#aol_').show();}
            if(lang>2 && lang!=5 && lang!=12)
            {
                $('#ask_').hide();  if($('#ask').attr('checked', true)){$('#ask').click();}
            } else {$('#ask_').show();}
        });

        gebo_validation = {
            reg: function() {
                reg_validator = $('.form_validation_reg').validate({
                    onkeyup: false,
                    errorClass: 'error',
                    validClass: 'valid',
                    highlight: function(element) {
                        $(element).closest('div').addClass("f_error");
                        $(element).closest('div').css("color", "black");
                    },
                    unhighlight: function(element) {
                        $(element).closest('div').removeClass("f_error");
                    },
                    submitHandler: function(element) {
                        $('#seotool-notify').show();
                    },
                    errorPlacement: function(error, element) {
                        $('#seotool-notify').hide();
                        $(element).closest('div').append(error);
                        $('.error').css("font-size", "10px");
                        $('.error').css("padding-top", "5px");
                    },
                    rules: {
                             'site[]': { required: true },
                               kw: {required: function(element) {
                                  return $('input:radio[name=word_type]:checked').val()==2;
                                 }
                              },
                     keyword_file: {required: function(element) {
                                  return $('input:radio[name=word_type]:checked').val()==1;
                                 },
				 csvextension: "xls|csv"
                              }
                    },
                    messages: {
                        'site[]': "Please select site(s).",
                              kw: "Please enter keyword(s).",
                    keyword_file: {required: "Please selects csv/xls file.", accept: "Accept only xls or csv."}
                    },
                    invalidHandler: function(form, validator) {
                        $.sticky("There are some errors. Please corect them and submit again.", {autoclose : 5000, position: "top-center", type: "st-error" });
                    }
                })
            }
        };
        function modalwindow(url)
        {
            $.get( "http://admin-test.edit-place.com/seotool/"+url, function( data ) {
              $( ".modal-body" ).html( data );
            });
            $("#seoresults").modal('show');
        }
    </script>
{/literal}
