<div class="mod">
    
    
    <div class="row-fluid">
        <div class=" well">
            <form action="#" method="POST" id="template_save_form" enctype="multipart/form-data">
                <h4>Choose Template name</h4>
                <fieldset>
                    <div class="controls span8">
                        <!-- <input type="file" class="span9" name="ftv_doc" id="ftv_doc">-->
                        <div class="mail_uploader">
                            <input type="text" name="template_name" id="template_name" class="multi">

                        </div>
                        <input type="submit" id="savesubmit" name="attachname" value="save" class="btn "/>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>
