{literal}
<script type="text/javascript">
    $.validator.addMethod("csvextension", function(value, element, param) {
        param = typeof param === "string" ? param.replace(/,/g, '|') : "xls|csv";
        return this.optional(element) || value.match(new RegExp(".(" + param + ")$", "i"));
    }, $.format("Please use only csv/xls file."));


$(document).ready(function() {
    $(".uni_style").uniform();
    gebo_validation.reg();

    $('#frequencyEndDate').datepicker({
        language: 'pt-BR',
        format: 'yyyy/mm/dd',
        pickSeconds: false,
        pick12HourFormat: false
    });

    $("input[name='word_type']").change(function() {
        var type=$('input[name=word_type]:checked').val();
        if(type==1)
        {
            $("#text_words").hide();
            $("#csv").show();
        }
        else
        {
            $("#text_words").show();
            $("#csv").hide();
        }
    });

    $('input[name=frequency]').change(function(){
        if($('input[name=frequency]').is(':checked'))
        {
            $('#fr').show();
            $('#fr_end_date').show();
            $('#title').show();
            $('#select_all').show();
            $('#cron_email').show();
        } 
        else 
        {
             $('#fr').hide();
             $('#fr_end_date').hide();
             $('#title').hide();
             $('#cron_email').hide();
             $('#select_all').hide();
             var $b = $('input[name=day\\[\\]]');
             $b.attr('checked', false); 
             $('a.select-all').text('S.elect all');
             
        }
    });

    $('a.select-all').bind('click', function() {
        for (var i = 1; i <= 7; i++) {
            $('#day'+i).click();
        }
        if(this.innerHTML.indexOf('Deselect') != -1) {
            //var $b = $('input[name=day\\[\\]]');
                //$b.attr('checked', false); 
            $(this).text('Select all');
        } else {
            $(this).text('Deselect all');
            //var $b = $('input[name=day\\[\\]]');
            //$b.attr('checked', true);                
            //$(this).closest("span").addClass("uni-checked");
        }
    });
}) ;

        gebo_validation = {
            reg: function() {
                reg_validator = $('.form_validation_reg').validate({
                    onkeyup: false,
                    errorClass: 'error',
                    validClass: 'valid',
                    highlight: function(element) {
                        $(element).closest('div').addClass("f_error");
                        $(element).closest('div').css("color", "black");
                    },
                    unhighlight: function(element) {
                        $(element).closest('div').removeClass("f_error");
                    },
                    submitHandler: function(element) {
                        $('#seotool-notify').show();
                    },
                    errorPlacement: function(error, element) {
                        $('#seotool-notify').hide();
                        $(element).closest('div').append(error);
                        $('.error').css("font-size", "10px");
                        $('.error').css("padding-top", "5px");
                    },
                    rules: {
                               urls: {required: function(element) {
                                  return $('input:radio[name=word_type]:checked').val()==2;
                                 }
                              },
                     url_file: {required: function(element) {
                                  return $('input:radio[name=word_type]:checked').val()==1;
                                 },
                 csvextension: "xls|csv"
                              },
                          title: {required: function(element) {
                                  return ($('#frequency').is(':checked'));
                                 }
                              },
                  enddate: {required: function(element) {
                                  return ($('#frequency').is(':checked'));
                                 }
                              },
                  "day[]": {required: function(element) {
                                  return ($('#frequency').is(':checked'));
                                 }
                              },
                  email: {required: function(element) {
                                  return ($('#frequency').is(':checked'));
                                 }
                              }
                    },
                    messages: {
                              urls: "Please enter url(s).",
                    url_file: {required: "Please selects csv/xls file.", accept: "Accept only xls or csv."},
                    title: "Please enter title.",
                    enddate: "Please select the end date.",
                    "day[]": "Please select frequency.",
                    email: "Please enter email."
                    },
                    invalidHandler: function(form, validator) {
                        $.sticky("There are some errors. Please corect them and submit again.", {autoclose : 5000, position: "top-center", type: "st-error" });
                    }
                })
            }
        };
</script>

{/literal}
<form class="form_validation_reg" method="POST" action="/seotool/page-rank-analysis-process" name="importcsv" id="seo" ENCTYPE="multipart/form-data">
        <div class="span10">

            <h3 class="heading">Page rank analysis</h3>
                        
            <div class="control-group formSep" id="seotool-notify" style="display: none;">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                            <div id="seo-message">{$msg}</div>
                    </div>
                </div>
            </div>   
            <div class="control-group formSep" id="title">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">Title<span class="f_req">*</span></label>
                        <div class="span8 form-inline no-margin-first">
                            <input type="text" name="title" class="span5"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">Type </label>
                        <label class="uni-radio"><input type="radio" name="word_type" class="uni_style"  value="1" {if $word_type neq '2'} checked {/if} id="csvxls">CSV / XLS</label>
                            <label class="uni-radio"><input type="radio" name="word_type" class="uni_style"  value="2" {if $word_type eq '2'} checked {/if} id="opt_text">Text</label>
                    </div>
                </div>
            </div>
            <div class="control-group formSep" id="csv" {if $word_type eq '2'} style="display:none" {/if}>
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">URL(s)<span class="f_req">*</span></label>                        
                        <div data-provides="fileupload" class="fileupload fileupload-new"><input type="hidden" />
                            <div data-provides="fileupload" class="fileupload fileupload-new"><input type="hidden" />
                                <div class="input-append">
                                    <div class="uneditable-input span2"><i class="icon-file fileupload-exists"></i> <span class="fileupload-preview"></span></div><span class="btn btn-file"><span class="fileupload-new">Select file</span><span class="fileupload-exists">Change</span><input name="url_file" id="url_file" type="file" /></span><a data-dismiss="fileupload" class="btn fileupload-exists" href="#">Remove</a>
                               </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep" id="text_words" {if $word_type neq '2'} style="display:none"{/if} >
                <div class="row-fluid">
                    <div class="control-group">
                        <label class="span3 control-label">URL(s)<span class="f_req">*</span></label>
                        <div class="span8 controls">
                            <textarea name="urls" id="txtarea_sp" cols="1" rows="4" class="span10"></textarea>
                            <span class="help-block syntax">Enter multiple urls in seperate line</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">Frequency</label>
                        <label class="uni-checkbox">
                            <input type="checkbox" name="frequency" id="frequency" class="uni_style" value="1">
                            <span id="select_all"><a class="select-all" href="javascript:void(0);">Select all</a></span>
                        </label>
                    </div>
                </div>
            </div>
            <div class="control-group formSep" id="fr">
                <div id="frequencyDaysRow" class="row-fluid">
                    <div class="span12" id="days">
                        <label class="span3">&nbsp;</label>
                        <div class="span2 no-margin-first">
                            <label class="uni-checkbox">
                                <input type="checkbox" name="day[]" id="day1" class="uni_style" value="sunday">
                                sunday
                            </label>
                            <label class="uni-checkbox">
                                <input type="checkbox" name="day[]" id="day2" class="uni_style" value="thursday">
                                Thursday
                            </label>
                        </div>
                        <div class="span2">
                            <label class="uni-checkbox">
                                <input type="checkbox" name="day[]" id="day3" class="uni_style" value="monday">
                                Monday
                            </label>
                            <label class="uni-checkbox">
                                <input type="checkbox" name="day[]" id="day4" class="uni_style" value="friday">
                                Friday
                            </label>
                        </div>
                        <div class="span2">
                            <label class="uni-checkbox">
                                <input type="checkbox" name="day[]" id="day5" class="uni_style" value="tuesday">
                                Tuesday
                            </label>
                            <label class="uni-checkbox">
                                <input type="checkbox" name="day[]" id="day6" class="uni_style" value="saturday">
                                Saturday
                            </label>
                        </div>
                        <div class="span2">
                            <label class="uni-checkbox">
                                <input type="checkbox" name="day[]" id="day7" class="uni_style" value="wednesday">
                                Wednesday
                            </label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep" id="fr_end_date">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">Frequency end Date<span class="f_req">*</span></label>
                        <div  id="frequencyEndDate" class="input-append date" >
                              <input data-format="dd/mm/YYYY" id="enddate" name="enddate" type="text" value=""   class="input-append date" readonly="readonly" />
                                <span class="add-on">
                                  <i class="icon-calendar" data-time-icon="icon-time" data-date-icon="icon-calendar">
                                  </i>
                                </span>
                          </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep" id="cron_email">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">Email<span class="f_req">*</span></label>
                        <div class="span8 form-inline no-margin-first">
                            <input type="text" name="email" class="span5"/>
                        </div>
                    </div>
                </div>
            </div>
            <div class="control-group formSep">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <label class="span3">Output</label>
                        <label class="uni-radio"><input type="radio" name="op_type" class="uni_style"  value="1" checked>csv</label>
                        <label class="uni-radio"><input type="radio" name="op_type" class="uni_style"  value="2">xls</label>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="row-fluid">
                    <div class="span12 form-inline">
                        <button class="btn btn-gebo" name="submit" type="submit">Upload</button>
                    </div>
                </div>
            </div>
        </div>
</form>

<div id="data">
    
</div>
