{literal}
<script type="text/javascript">
$(document).ready(function() {
    /*$('#subject_proposals').dataTable({
        "sPaginationType": "bootstrap",
        "sDom": "<'row'<'span4'l><'span4'T><'span4'f>r>t<'row'<'span6'i><'span6'p>>",
        "oTableTools": {
            "aButtons": [
                "copy",
                "print",
                {
                    "sExtends":    "collection",
                    "sButtonText": 'Sauvegarder <span class="caret" />',
                    "aButtons":    [ "csv", "xls", "pdf" ]
                }
            ],
            "sSwfPath": "/BO/theme/gebo/lib/datatables/extras/TableTools/media/swf/copy_csv_xls_pdf.swf"
        }
    });*/
    $.post("https://admin-ep-test.edit-place.com/BO/proposals.php", function(data)
    {
        
        alert(data);
    });
});
</script>
<style>
    .table, #seoviewresultspage .heading, #seoviewresultspage .row {
        margin: auto!important;
        width: 100%!important;
    }
</style>
{/literal}

<div class="row-fluid">
  <div class="span12" style="">
    <h3 class="heading">Subject tool results</h3>
        <table id="subject_proposals" class="table table-bordered table-striped table_vam">
            <thead>
            <tr>
                <th>SL.NO</th>
                <th>Site</th>
                <th>Limit</th>
                <th>Email</th>
                <th>Version</th>
                <th>Creation date</th>
                <th>Status</th>
            </tr>
            </thead>
            <tbody id="pResults">
                
            </tbody>
        </table>
   </div>
</div>

<div id="data">
    
</div>