<div style="padding-left:6px;padding-top:52px;padding-bottom:30px;">

	<b>
	<!--AO a &eacute;t&eacute; cr&eacute;&eacute;e avec succ&egrave;s en ligne et disponible d&egrave;s maintenant. -->
	La mission a &eacute;t&eacute; cr&eacute;&eacute;e avec succ&egrave;s. Elle est en ligne sur www.edit-place.com et accessible d&egrave;s maintenant.
	</b>

</div>

<br>



{if $duplicate=="yes"} 

	<button type="submit" value="Dupliquer cette mission" class="btn btn-info" onClick="window.location='/ao/ao-create1?submenuId=ML2-SL3'" >Dupliquer cette mission</button>&nbsp;&nbsp;

	<button type="submit" value="New AO" class="btn btn-info" onClick="window.location='/ao/ao-create1?submenuId=ML2-SL3&delsession=1'" >New AO</button>

{/if}