{literal}
<script type="text/javascript" charset="utf-8" src="/BO/theme/gebo/js/datempicker.js"></script>
<script language="JavaScript" type="text/javascript" src="/BO/theme/gebo/lib/ckeditor/ckeditor.js"></script>
<script type="text/javascript"> 
(function($) {
		$.fn.extend( {
			limiter: function(limit, elem) {
				$(this).on("keyup focus", function() {
					setCount(this, elem);
				});
				function setCount(src, elem) {
					var chars = src.value.length;
					if (chars > limit) {
						src.value = src.value.substr(0, limit);
						chars = limit;
					}
					elem.html( chars+'/'+(limit - chars) );
				}
				setCount($(this)[0], elem);
			}
		});
	})(jQuery);
	
$(document).ready(function() {
		
		// Timepicker
		 var today = new Date();
		
            $('#publishtime').datetimepicker({
				showSecond:false,
				//defaultValue: new Date(),
				numberOfMonths: 1,
				minDate: 1,
				maxDate: new Date(today.getTime() + (24 * 60 * 60 * 1000)), 
				timeFormat: 'hh:mm',
				ampm: false,
				stepHour: 1,
				hourMin:10,
				hourMax:today.getHours(),
				hour:today.getHours(),
				minute:today.getMinutes(),
				timeOnlyTitle: 'Choisir une heure',
				timeText: 'Heure',
				hourText: 'Heures',
				currentText: 'Maintenant',
				closeText: 'Termin&eacute;',
            });
	
	
	
	$(".uni_style").uniform();  
	$('#mail_sendcheck').toggleButtons({
	 	label:{enabled: "Oui",disabled: "Non"}
    });
	$("#paytype").chosen({ disable_search: true });
	setpublishnow();
	
	var aotype=$("#aotype").val();
	
	if(aotype!="private")
	{
		var elem = $("#missioncomment_count");
		$("#missioncomment").limiter(160, elem);
	}
	
	var elem = $("#fbcomment_count");
	$("#fbcomment").limiter(125, elem);
	
	/*mailcontriblist(1);
	$("#mailcontrib_lang").multiselect();
    $("#mailcontrib_lang").multiselectfilter();
	
	$("#mailcontribcheck").multiselect();  
    $("#mailcontribcheck").multiselectfilter();
	
	$(".ui-multiselect-all").click(function() 
	{
		mailcontriblist(1);
	});*/
});
</script>
<style>
	input,textarea {text-transform:none !important;}
</style>
{/literal}

<form action="/ao/ao-create4?submenuId=ML2-SL3" name="creation_step3" id="creation_step3" method="POST" enctype="multipart/form-data" >
	<div class="row-fluid">
  		<div class="span12">
    		<h3 class="heading">
				<span align="right"> 
					<img src="/BO/theme/gebo/img/path-3.png" width="120" height="35" border="0" usemap="#Map" style="float:right;" />
					<map name="Map" id="Map">
					{if $nav_1==1}
						<area shape="circle" coords="18,18,17" href="/ao/ao-create1?submenuId=ML2-SL3"/>
					{/if}
					{if $nav_2==1}
						{if $missiontest=='on'}
							<area shape="circle" coords="60,18,17" href="/ao/ao-create2test?submenuId=ML2-SL3"/>
						{else}
							{if $articletype=="lot"}
								<area shape="circle" coords="60,18,17" href="/ao/ao-create2lot?submenuId=ML2-SL3"/>
							{else}
								<area shape="circle" coords="60,18,17" href="/ao/ao-create2?submenuId=ML2-SL3"/>
							{/if}
						{/if}
					{/if}
					</map>
				</span>
			</h3>
			<table align="center" cellpadding="2" cellspacing="2" width="80%" >
				<tr {if $ao_type=="private"}style="display:none;"{/if}>
					<td>Date et heure de publication</td>
					<td> 
						<input type="text" name="publishtime" id="publishtime" value="{$tommorow}" readonly class="span5" onChange="setpublishnow('1');"/>
						{if $ao_type=="private" || $usertype=='superadmin' || (in_array('senior',$contribtype) && $contribtype|@count eq 1)}
							<span style="vertical-align:top;"><input type="checkbox" name="publishnow" id="publishnow" value="yes" onClick="setpublishnow('0');" checked /> Maintenant</span>
						{/if}
					</td>
				</tr>	
				<tr><td>&nbsp;</td></tr> 
				<tr style="font-family:Arial;font-size:16px;font-weight:bold;font-style:normal;text-decoration:none;color:#CC6600;text-align:center;padding-bottom:20px;"><td colspan="2"  {if $ao_type=="private" || (in_array('senior',$contribtype) && $contribtype|@count eq 1)}style="display:none;"{/if} id="mailhighlight">L'AO sera mise en avant dans la Newsletter de demain, 10h.</td></tr>
				<tr id="nltitle_block" {if $ao_type=="private" || (in_array('senior',$contribtype) && $contribtype|@count eq 1)}style="display:none;"{/if}>
					<td>Nom pour la newsletter</td>
					<td>
						<input type="text" name="nltitle" id="nltitle" value="{$nltitle}" size="50"/>
					</td>
				</tr>
				
				<!------------------------------ Contributor mail --------------------------------------------->
				<tr><td colspan="2" style="font-weight:bold;padding-bottom:15px;padding-bottom:15px;" id="mailtext">{if $ao_type=="private" || (in_array('senior',$contribtype) && $contribtype|@count eq 1)}Cet email sera envoy&eacute; &agrave; tous les r&eacute;dacteurs s&eacute;lectionn&eacute;s en &eacute;tape 1{else}Cet email sera envoy&eacute; &agrave; tous les r&eacute;dacteurs qui ont souscrit &agrave; l'alerte {/if}</td></tr>	
				
				<!--send from edit-place.com -->
				<tr>	
					<td valign="top">From</td> 
					<td>
						<select name="sendfrom" id="sendfrom">
							<option value="editorial">Editorial</option>
							<option value="me">Me</option>
						</select>
					</td>
				</tr>
				
				<tr>	
					<td valign="top">Objet de l'email</td> 
					<td>
						<div id="mailcontent" {if $mail_send_contrib=="no"}style="display:none;"{/if}>
							<input type="text" size="70" name="mailsubject" id="mailsubject" style="width:440px"/> 
							<div style="height:10px;"></div>
							<textarea rows="4" cols="50" name="mailcontrib" id="mailcontrib" ></textarea>  
						</div>
					</td>
				</tr>
				<tr><td>&nbsp;</td></tr>
				
				<!-----------------------------------------------Corrector mail ----------------------------->
				{if $correction=="on"}
					<tr><td colspan="2" style="font-weight:bold;padding-bottom:15px;padding-bottom:15px;">Cet email sera envoy&eacute; &agrave; tous les correcteurs s&eacute;lectionn&eacute;s en &eacute;tape 1</td></tr>	
					
					<!--send from edit-place.com -->
					<tr>	
						<td valign="top">From</td> 
						<td>
							<select name="correctorsendfrom" id="correctorsendfrom">
								<option value="editorial">Editorial</option>
								<option value="me">Me</option>
							</select>
						</td>
					</tr>
					
					<tr>	
						<td valign="top">Objet de l'email</td> 
						<td>
							<div id="correctormail">
								<input type="text" size="70" name="correctormailsubject" id="correctormailsubject" style="width:440px"/> 
								<div style="height:10px;"></div>
								<textarea rows="4" cols="50" name="correctormailcontent" id="correctormailcontent" ></textarea>  
							</div>
						</td>
					</tr>
					<tr><td>&nbsp;</td></tr>
				{/if}
				<!-- Contributor mail -->
				<!-- 
				{if $ao_type!="private"}
				<tr id="mailcontribblock" align="center">
					<td colspan="2">
						<div class="well" style="width:600px">  
							<table align="center" cellpadding="4" cellspacing="4" width="90%">  
								<tr><td colspan="2"><b>S&eacute;lectionner les contributeurs &agrave; qui  envoyer l'email</b></td></tr>
								<tr>
									<td>Tri par langue</td>
									<td> 
										<select name="mailcontrib_lang[]" id="mailcontrib_lang" onChange="mailcontriblist(0);" multiple="multiple" style="width:250px;">
											{foreach from=$Contrib_langs item=langitem key=langkey}
												{if in_array($langkey,$contrib_langarray)}
													<option value="{$langkey}" selected>{$langitem}</option>
												{else}
													<option value="{$langkey}">{$langitem}</option>
												{/if}
											{/foreach}
										</select>
									</td>
								</tr>
							
								<tr>
									<td valign="top">Contributeurs</td>
									<td valign="top" id="contribsmail">
										<select name="mailcontribcheck[]" id="mailcontribcheck" multiple="multiple">   
										{foreach from=$mailcontriblist item=contrib}
											<option value="{$contrib.identifier}" selected>{$contrib.name}</option>
										{/foreach}
										</select>
										<div id="mailcontrib_err" style="color:red;"></div>
									</td>
								</tr>
							</table>
						</div>		
					</td>
				</tr>
				{/if}
				-->
				<tr>	
					<td>Envoyer un email au client</td>
					<td>
						<div id="mail_sendcheck">
							<input type="checkbox" name="mail_send" id="mail_send" />
						</div>
					</td>
				</tr>
				
				<tr>	
					<td>Montant &agrave; payer sur le site</td>
					<td>
						<select name="paytype" id="paytype" onChange="fncontribpay();" style="width:80px">
							<option value="1" {if $paytype=="1"}selected{/if}>%</option>
							<option value="2" {if $paytype=="2"}selected{/if}>Valeur</option>
						</select>
						<input type="text" name="paypercent" id="paypercent" value="{$paypercent}" class="span2" style="width:80px;margin-top:-12px"/>
						<input type="text" name="payvalue" id="payvalue" value="{$payvalue}" style="display: none;width:80px;margin-top:-12px" class="span2"/>
						<span style="vertical-align:top;">(0 ou 100% de la valeur)</span>
						<div id="payerror" style="color:red;"></div>  
					</td>				
				</tr>	
				<tr>
					<td valign="top">Commentaire qui sera affich&eacute; sur {if $ao_type!="private"}la Newsletter et{/if} la plateforme {if $ao_type!="private"}(Obligatoire - 100 car. minimum - 160 car. maximum){/if}</td>
					<td valign="top">
						<textarea name="missioncomment" id="missioncomment" style="width:390px;" {if $ao_type!="private"}maxlength="160"{/if} cols="100">{$missioncomment|stripslashes}</textarea>
						<span id="missioncomment_count" style="vertical-align:top"></span>
						<div id="missioncomment_error" style="color:red;"></div> 						 
					</td>
				</tr>
				<tr>
					<td valign="top">Commentaire qui sera affich&eacute; sur Facebook et Twitter(Obligatoire - 100 car. minimum - 125 car. maximum)</td>
					<td valign="top">
						<textarea name="fbcomment" id="fbcomment" style="width:390px;" maxlength="125" cols="100" {if $ao_type=="private" || $premium_option=="liberte"}disabled{/if}>{$fbcomment|stripslashes}</textarea>
						<span id="fbcomment_count" style="vertical-align:top"></span>
						<div id="fbcomment_error" style="color:red;"></div>						 
					</td>
				</tr>
				<tr>
					<td>Dupliquer cette mission</td>
					<td>
						<input type="checkbox" name="duplicateao" id="duplicateao" value="yes" />
					</td>
				</tr>
				<tr {if $missiontest=='on'}style="display:none;"{/if}>
					<td valign="top">Sauvegarder en tant que template</td>
					<td valign="top">
						<input type="checkbox" name="saveao" id="saveao" value="yes" onClick="fnsaveao();" style="vertical-align:top" />
						<span id="selectsave" style="display:none;"><input type="text" name="templatename" id="templatename"/></span>
						<span id="save_err"></span>
					</td>
				</tr>
			</table>
		</div>
		<div style="float:right;padding:30px">
			<button type="submit" value="Aller en Etape 4" class="btn btn-info" id="aoSubmit" onClick="return validate_aocreation_step3();">Aller en Etape</button>
		</div>
		<input type="hidden" id="premium" name="premium" value="{$premium_option}" />
		<input type="hidden" name="totcost" id="totcost" value="{$total_price}"/>
		<input type="hidden" id="aotype" name="aotype" value="{$ao_type}" />
		<input type="hidden" id="sconly" name="sconly" value="{$sconly}" />
		<input type="hidden" id="correction" name="correction" value="{$correction}" />
	</div>
</form>