{literal}
    <script type="text/javascript" >
		$(document).ready(function() {
			$(".uni_style").uniform(); 
			$('#scjctable').dataTable({
				"sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
				"sPaginationType": "bootstrap",
				"aaSorting": [[ 1, "asc" ]],
				"aoColumns": [
					{ "sType": "string" },
					{ "sType": "formatted-num" },
					{ "sType": "string" },
					{ "sType": "date-euro" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" }
				]
			});
		});
			
		function updowngrade(user,act)
		{
			var confirmtext='';
			
			if(act=="up")
			{
				confirmtext="Do you really want to upgrade this Contributor?";
				typetext='Senior';
			}
			else
			{
				confirmtext="Do you really want to downgrade this Contributor?";
				typetext='Junior';
			}
			if(confirm(confirmtext))
			{
				$.ajax({
				  type: 'GET',
				  url: '/ao/updateprofiletype',
				  data: 'contrib=' + user + '&action='+act,
				  
				  success: function(data)
				  {   
						smoke.alert("Profile updated successfully");
						$("#action_"+user).html('-');
						$("#ptype_"+user).html(typetext);
						$("#check_"+user).html('');
				  }
				});
			}
		}
			
		function validatemultipleupdate()
		{
			var checked = $("input[type=checkbox]:checked");
			var nbChecked = checked.size(); 
			 
			if(nbChecked==0)
			{
				smoke.alert("Please select profiles to update");
				return false;
			}
			else
			{
				if(confirm("Do you really want to update these contributors?"))
				{
					document.form1.action ="/ao/automatizescjc?submenuId=ML2-SL19";
					document.form1.submit();
					return true;
				}
				else
					return false;
			}				
		}
	</script>
{/literal}

<div class="row-fluid">
	<div class="span12">
		<h3 class="heading">Automatize JC and SC</h3>
		<form method="post" name="form1" id="form1">
			<table class="table table-bordered table-striped table_vam" id="scjctable">
				<thead>
					<tr>
					  <th></th>
					  <th>S.I</th>
					  <th>Contributor</th>
					  <th>Joining Date</th>
					  <th>Categories</th>
					  <th>Profile Type</th>
					  <th>Action</th>
					</tr>
				</thead>
				<tbody>
				{foreach from=$contriblist item=contrib name=contrib_loop}
					<tr>
					   <td id="check_{$contrib.identifier}">
							{if $contrib.updown!="NO"}
								<label class="uni-checkbox">
									<input type="checkbox" name="contribtype[]" value="{$contrib.identifier}_{$contrib.updown}" class="uni_style"/>
								</label>	
							{/if}
					   </td>
					   <td>{$smarty.foreach.contrib_loop.index+1}</td>
					   <td>
							{if $contrib.first_name!=""}
								{$contrib.first_name}&nbsp;{$contrib.last_name}
							{else}
								{$contrib.email}
							{/if}
						</td>
					   <td>{$contrib.created_at|date_format:"%d/%m/%Y %H:%M:%S"}</td>
					   <td>{$contrib.category}</td>
					   <td id="ptype_{$contrib.identifier}">{$contrib.profile_type}</td>
					   <td id="action_{$contrib.identifier}"><b>
							{if $contrib.updown=="up"}
								<a href="javascript:void(0);" onClick="updowngrade('{$contrib.identifier}','{$contrib.updown}');" class="hint--left hint--info" data-hint="Upgrade to SC"><i class="splashy-arrow_large_up"></i></a>
							{elseif $contrib.updown=="down"}
								<a href="javascript:void(0);" onClick="updowngrade('{$contrib.identifier}','{$contrib.updown}');" class="hint--left hint--info" data-hint="Downgrade to JC"><i class="splashy-arrow_large_down"></i></a>
							{else}
								-
							{/if}</b>
					   </td>
					 </tr>
				{/foreach}
				</tbody>
			</table>
			<input type="submit" name="update_all" value="Update" class="btn btn-success" onClick="return validatemultipleupdate();"/>
		</form>
	</div>
</div>


