{literal}
<script type="text/javascript" charset="utf-8" src="/BO/theme/gebo/js/custom/validations_poll.js"></script>
<script type="text/javascript" charset="utf-8" src="/BO/theme/gebo/js/datempicker.js"></script>

<script type="text/javascript">
	var today = new Date(); 
	$(document).ready(function() { 
		$("#client_list").chosen({ allow_single_deselect: true });	
		$('#poll_date').datetimepicker({
			showSecond: true,
			timeFormat: 'hh:mm:ss',
			minDate: new Date(),
			stepHour: 1,
			stepMinute: 1,
			stepSecond: 10,
			timeOnlyTitle: 'Choisir une heure',
			timeText: 'Heure',
			hourText: 'Heures',
			minuteText: 'Minutes',
			secondText: 'Secondes',
			currentText: 'Maintenant',
			closeText: 'Termin&eacute;',
		});
		
		 $('#publish_time').datetimepicker({
			showSecond: true,
			timeFormat: 'hh:mm:ss',
			numberOfMonths: 1,
			minDate: 1,
			maxDate: new Date(today.getTime() + (24 * 60 * 60 * 1000)),   
			ampm: false,
			stepHour: 1,
			hourMin:10,
			hourMax:today.getHours(),
			hour:today.getHours(),
			minute:today.getMinutes(),
			second:today.getSeconds(),
			timeOnlyTitle: 'Choisir une heure',
			timeText: 'Heure',
			hourText: 'Heures',
			minuteText: 'Minutes',
			secondText: 'Secondes',
			currentText: 'Maintenant',
			closeText: 'Termin&eacute;',
		});
		
		$('#poll_anonymouscheck').toggleButtons({
			label:{enabled: "Oui",disabled: "Non"}
		});
		$("#type").chosen({ disable_search: true });
		$("#language").chosen({	disable_search: true });
		$("#category").chosen({ disable_search: true });
		$("#signtype").chosen({ disable_search: true });
		$(".uni_style").uniform(); 
		$('#min_sign').blur(function() {
		if($('#min_sign').val() =='')
				this.value = "Min.";
		});
		$('#max_sign').blur(function() {
			if($('#max_sign').val() =='')
				this.value = "Max.";
		});
		$('#min_sign').focus(function() {
			if($('#min_sign').val() ==String("Min.")) 
			  this.value = "";
		});
		$('#max_sign').focus(function() {
			if($('#max_sign').val() ==String("Max."))
				  this.value = "";
		}); 
	});
	
	$(function(){
		var btnUpload=$('#uploadspec');
		var status=$('#fname');

		new AjaxUpload(btnUpload, {
			action: 'uploadpollspecdoc',
			name: 'uploadfile',

			onSubmit: function(file, ext){
			 if (! (ext && /^(doc|docx|rtf|zip|xls|xlsx|pdf)$/.test(ext))){
					status.html('Uniquement doc, docx, zip, xls, xlsx, pdf et rtf').css('color','#FF0000');
					return false;
				}
				status.html('<img src="/FO/images/loading.gif" />');
			},

			onComplete: function(file, response){ //alert(response);
				if(response!="error"){
					status.html('').css('color','#000000');
					var fname=response.split("#"); 
					$('#poll_spec_name').val(fname[1]);
					$('#fname').html(fname[1]);
				} 
			}
		 });
	});
</script>

<style>
.error {  color:red;}
input {text-transform:none !important;}
.usererror {  color:red}
/* css for timepicker */
.ui-timepicker-div .ui-widget-header { margin-bottom: 8px; }
.ui-timepicker-div dl { text-align: left; }
.ui-timepicker-div dl dt { height: 25px; margin-bottom: -25px; }
.ui-timepicker-div dl dd { margin: 0 10px 10px 65px; }
.ui-timepicker-div td { font-size: 90%; } 
.ui-tpicker-grid-label { background: none; border: none; margin: 0; padding: 0; }
</style>

{/literal}

<form action="/ao/createpoll1?submenuId=ML2-SL15" name="poll_step1" method="post" enctype="multipart/form-data" >
<div class="row-fluid">
  	<div class="span12">
		<h3 class="heading">Cr&eacute;ation d'un Devis
			<span align="right">
				<img src="/BO/theme/gebo/img/path-1.png" width="120" height="35" border="0" usemap="#Map" style="float:right;" />
				<map name="Map" id="Map">
				{if $nav_2==1}	
					<area shape="circle" coords="60,18,17" href="/ao/createpoll1?submenuId=ML2-SL15" />
				{/if}
				{if $nav_3==1}	
					<area shape="circle" coords="102,17,18" href="/ao/createpoll2?submenuId=ML2-SL15"/>
				{/if}
				</map>
			</span> 
		</h3>	
		
		<table align="center" cellpadding="4" cellspacing="4" width="78%">
			<tr>
				<td valign="top" width="50%">Client</td>
				<td>
					<select name="client_list" id="client_list" class="chzn_a span12">
					{foreach from=$client_array item=client key=clientkey}
						{if $clientkey==$def_user}
							<option value="{$clientkey}" selected>{$client}</option>
						{else}
							<option value="{$clientkey}">{$client}</option>
						{/if}
					{/foreach}
					</select>
					<br>
					<a href="javascript:void(0);" data-toggle="modal" data-target="#newuser">
						Ajouter un nouveau client
					</a>
					<br>
					<span id="client_div" class="error"></span>
				</td>
			</tr>
			<tr>
				<td valign="top">Nom de ce Devis</td>
				<td><input type="text" name="title" id="title" value="{$title}" /></td>
			</tr>
			<tr>
				<td valign="top">Date de fin du Devis</td>
				<td><input type="text" id="poll_date" name="poll_date" readonly="readonly" value="{$poll_date}"/>
					<span id="date_err" class="error"></span>
				</td>
			</tr>
			<tr>
				<td valign="top">D&eacute;lai de priorit&eacute; donn&eacute; aux participants</td>
				<td><input type="text" id="priority_hours" name="priority_hours" class="span2" value="{$priority_hours}"/> heure(s)</td>
			</tr>
			<tr>
				<td valign="top">Appel d'offres Anonyme</td>
				<td>
					<div id="poll_anonymouscheck">
						<input type="checkbox" name="poll_anonymous" id="poll_anonymous" {if $poll_anonymous=="on"}checked="checked"{/if}/>
					</div>
				</td>
			</tr>
			<tr>
				<td valign="top">Brief</td>
				<td>
				  <div id="uploadspec">
						<span class="btn btn-file">
							<span class="fileupload-new">Select poll brief</span>
							<input type="file" name="file" id="file" />
						</span>	
						<span id="file_err" class="error"></span>
						<div id="fname">{$poll_file}</div>
				   </div>
				</td>
			</tr>
			<tr><td>&nbsp;</td></tr>
		</table>
		
		<div class="w-box">
			<div class="w-box-header">Cr&eacute;ez votre mod&egrave;le d'article</div>
			<div class='w-box-content'>
				<table align="center" cellpadding="4" cellspacing="4" width="78%">
				   <tr>
						<td width="50%" valign="top">Type</td>
						<td>{html_options name=type id=type options=$type_array|stripslashes selected=$type class="span8"}</td>
					</tr>
					<tr>
						<td valign="top">Langue</td>
						<td>{html_options name=language id=language options=$language_array selected=$language class="span8"} </td>
					</tr>
					<tr>
						<td valign="top">Cat&eacute;gorie</td>
						<td>{html_options name=category id=category options=$category_array selected=$category class="span8"} </td>
					</tr>
					<tr>
						<td valign="top">Nombre de</td>
						<td>{html_options name=signtype id=signtype selected=$signtype options=$signtype_array class="span8"}
							<span><input type="text" id="min_sign" name="min_sign" value="{$min_sign}" class="span2" style="margin-top:-12px"/></span>
							<span><input type="text" id="max_sign" name="max_sign" value="{$max_sign}" class="span2" style="margin-top:-12px"/></span>
						</td>
					</tr>
					<tr>
						<td valign="top">Part pour le contributeur</td>
						<td><input type="text" id="contrib_percentage" name="contrib_percentage"  value="{$contrib_percentage}" class="span2" />&nbsp;%</td>
					</tr>
					<tr>
						<td valign="top">Nb devis max &agrave; recevoir</td>
						<td><input type="text" id="poll_max" name="poll_max" value="{$poll_max}" class="span2"/></td>
					</tr>
					<tr>
						<td valign="top">Date/Heure de publication</td>
						<td>
							<label class="uni-checkbox">
								<span style="float:left;padding-right:10px;">
									<input type="text" id="publish_time" name="publish_time" readonly="readonly" value="{$publish_time}" {if $publishnow=="checked"}disabled="disabled"{/if} />
								</span>
								<input type="checkbox" name="publishnow" id="publishnow" class="uni_style" onclick="disablepublishtime()" value="checked" {if $publishnow=="checked"}checked{/if}/>&nbsp;Maintenant
								<span id="publishtime_err" class="error"></span>
							</label>
						</td>
					</tr>
				</table>
				<input type="hidden" id="poll_spec_name" name="poll_spec_name" value="{$poll_file}" />
				<input type="hidden" id="modify" name="modify" value="{$get_modify}" />
			</div>
		</div>
		<div style="float:right;padding:30px">
			 <input type="submit" value="ALLER EN ETAPE 2" class="btn btn-info" onClick="return validate_poll_step1();"/>
		</div>
	</div>
</div>	
</form>

<!--   Add new user   -->
<div class="modal hide fade" id="newuser">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>AJOUT D'UN NOUVEAU CLIENT</h3>
    </div>
    <div class="modal-body">
		<form action="/ao/adduser?type=poll" id="newuserform" id="newuserform" method="post" >
			<table cellpadding="2" cellspacing="2" align="center">
				<tr>
					<td valign="top">Email</td>
					<td><span><input type="text" id="newemail" name="newemail"/></span></td>
				</tr>
				<tr>
					<td valign="top">Mot de passe</td>
					<td><span><input type="password" id="newpwd" name="newpwd"/></span></td>
				</tr>
				<tr>
					<td valign="top">Confirmer mot de passe</td>
					<td><span><input type="password" id="newcpwd" name="newcpwd" value=""/></span></td>
				</tr>
				<tr>
					<td valign="top">Nom du client</td>
					<td><span><input type="text" id="company_name" name="company_name" value=""/></span></td>
				</tr>
				<tr>
					<td>&nbsp;</td>
					<td>
						<button type="submit" id="submit_pop_edit" name="submit_pop_edit" value="ADD" class="btn btn-success" onClick="validate_newuser();">Ajouter client</button>&nbsp;&nbsp;
					</td>
				</tr>
			</table>	
		</form>
    </div>
    <div class="modal-footer">
    </div>
</div>

