{literal}
 <script type="text/javascript" >
    $(document).ready(function(){
		$("#belongs_to").chosen({ disable_search: true });	
		$("#parentoptions_list").chosen({ disable_search: true });	
		$("#status").chosen({ disable_search: true });	
		$(".uni_style").uniform(); 
	});	
		
	function parentOrChild()
    {
        var parentoption=$("#parentoptions_list").val();
        if(parentoption != 0)
			$("#typeOption").hide();
        else
			$("#typeOption").show();
    }
 </script>
 <style>
	input {text-transform:none !important;}
	textarea {text-transform:none !important;}
</style>
{/literal}
<div class="row-fluid">
	<div class="span12">
		<h3 class="heading">Premiun Options :: Edit Option </h3>
		<form action="/ao/editpremoption?submenuId=ML2-SL8&optionId={$optiondetails[0].id}" method="post" enctype="multipart/form-data">
			<table cellpadding="4" cellspacing="4" width="80%" align="center">
				<tr>
					<td>Option Name</td>
					<td><input type="text" name="option_name" id="option_name" value="{$optiondetails[0].option_name|escape:'htmlall'}"/></td>
				</tr>
				<tr>	
					<td>Option Price</td>
					<td><input type="text" name="option_price" id="option_price" value="{$optiondetails[0].option_price|escape:'htmlall'}"/></td>
				</tr>
				<tr>
					<td>BO Option Price</td>
					<td><input type="text" name="option_price_bo" id="option_price_bo" value="{$optiondetails[0].option_price_bo|escape:'htmlall'}"/></td>
				</tr>
				<tr>	
					<td>Option Belongs to</td>
					<td> 
						<select name="belongs_to" id="belongs_to">
							<option value="fo" {if $optiondetails[0].belongs == "fo"} selected="selected" {/if}>FO</option>
							<option value="bo" {if $optiondetails[0].belongs == "bo"} selected="selected" {/if}>BO</option>
							<option value="both" {if $optiondetails[0].belongs == "both"} selected="selected" {/if}>BOTH</option>
						</select>
					</td>
				</tr>
				<tr {if $optiondetails[0].parent eq "0"}style="display:none;"{/if}>
					<td>Parent</td>
					<td>{html_options name=parentoptions_list id=parentoptions_list options=$parentoptions_list selected=$parentOption}</td>
				</tr>
				<tr {if $optiondetails[0].parent neq "0"}style="display:none;"{/if}>
					<td valign="top">Type</td>
					<td> 
						<label class="uni-radio"><input type="radio" name="parentoptiontype" id="unique" disabled="disabled" class="uni_style" value="unique" {if $optiondetails[0].type == "unique"} checked="checked"{/if} />Unique</label>
						<label class="uni-radio"><input type="radio" name="parentoptiontype" id="addition" disabled="disabled" class="uni_style" value="additional" {if $optiondetails[0].type == "additional"} checked="checked"{/if} />Additional</label>
					</td>	
				</tr>
				<tr>
					<td>Status </td>
					<td>
						<select name="status" id="status">
							<option value="active" {if $optiondetails[0].status == "active"} selected="selected" {/if}>Active</option>
							<option value="inactive" {if $optiondetails[0].status == "inactive"} selected="selected" {/if}>Inactive</option>
						</select>
					</td>
				</tr>	
				<tr>
					<td valign="top">Option Description </td>
					<td><textarea rows="6" class="span9" name="option_desc">{$optiondetails[0].description|escape:'htmlall'}</textarea></td>
				</tr>
				<tr>
					<td></td>
					<td>
						<input type="submit" value="SUBMIT" name="optionsubmit" class="btn btn-info">
						<input type="button" value="CANCEL" onClick="window.location='/ao/premiumoptions?submenuId=ML2-SL8'" class="btn btn-info"/>
					</td>
				</tr>
			</table>	
		</form>
	</div>
</div>	

