{literal}

    <script type="text/javascript" >
		$(document).ready(function() {
			 $('#marktable').dataTable({
				"sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
				"sPaginationType": "bootstrap",
				"aaSorting": [[ 1, "asc" ]],
				"aoColumns": [
					{ "sType": "formatted-num" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" }
				]
			});
		} );
		
		

		function updowngrade(user,act,ptype)
		{
			var confirmtext='Do you really want to upgrade/downgrade this Contributor?';
			
			if(confirm(confirmtext))
			{
				$.ajax({
				  type: 'GET',
				  url: '/ao/updateprofiletypemarks',
				  data: 'contrib=' + user + '&action='+act+'&ptype='+ptype,
				  
				  success: function(data)
				  {   
						smoke.alert("Profile updated successfully");
						window.location.reload();
				  }
				});
			}
		}
		
		function markdetail(id)
		{
			var target_page = "/ao/marksdetail?participate="+id;

			$.post(target_page, function(data){  // alert(data);
				$("#markdetailcontent").html(data);
			});
		}
		
	</script>

	{/literal}

<div class="row-fluid">
  <div class="span12">
	 <h3 class="heading">Statistiques de missions test</h3>
	
	<form action="/ao/poll?submenuId=ML2-SL17" method="post" name="formmark">
	<table class="table table-bordered table-striped table_vam" id="marktable">
		<thead>
			<tr>
				<th>ID N°</th>
				<th>Name</th>
				<th>Mission name</th>
				<th>Writer</th>
				<th>Type</th>
				<th>Note/10</th>
				<th>Avg Mark</th>
				<th>Action</th>
				<th>Status</th>
			</tr>
		</thead>
		<tbody>
	 	{foreach from=$testmissions item=mission_item name="mark_loop"}
	        <tr>
				<td>{$smarty.foreach.mark_loop.index+1}</td>
			    <td>{$mission_item.atitle}</td>
				<td>{$mission_item.title}</td> 
				<td>{$mission_item.first_name}&nbsp;{$mission_item.last_name}</td>
				<td>{$mission_item.profile_type}</td>
				<td>{$mission_item.min_mark}</td>
				<td>{$mission_item.marks|zero_cut:2}</td>
				<td nowrap>
					<span style="float:left">
						<a href="javascript:void(0);" data-toggle="modal" data-target="#markdetail" OnClick="return markdetail('{$mission_item.participate_id}')" class="hint--left hint--info" data-hint="View Detail"><i class="icon-eye-open"></i></a>
					</span>
					{if $mission_item.marks>=$mission_item.min_mark} 
						{if $mission_item.profile_type!='senior'}
							{if $mission_item.profile_type=='sub-junior'}
								<a href="javascript:void(0);" onClick="updowngrade('{$mission_item.user_id}','junior','{$mission_item.profile_type}');" class="hint--left hint--info" data-hint="Upgrade to Junior"><img src="/BO/theme/gebo/img/up_blue.png"/></a>
								&nbsp;
							{/if}
							<a href="javascript:void(0);" onClick="updowngrade('{$mission_item.user_id}','senior','{$mission_item.profile_type}');" class="hint--left hint--info" data-hint="Upgrade to Senior"><img src="/BO/theme/gebo/img/up_green.png"/></a>
						{/if}
					{else}
						{if $mission_item.profile_type!='sub-junior'}
							{if $mission_item.profile_type=='senior'}
								<a href="javascript:void(0);" onClick="updowngrade('{$mission_item.user_id}','junior','{$mission_item.profile_type}');" class="hint--left hint--info" data-hint="Downgrade to Junior"><img src="/BO/theme/gebo/img/down_orange.png"/></a>
								&nbsp;
							{/if}
							<a href="javascript:void(0);" onClick="updowngrade('{$mission_item.user_id}','sub-junior','{$mission_item.profile_type}');" class="hint--left hint--info" data-hint="Downgrade to Sub-junior"><img src="/BO/theme/gebo/img/down_red.png"/></a>
						{/if}
					{/if}
				</td>
				<td>
					{if $mission_item.status=='published'}
						Validated
					{else}
						-
					{/if}	
				</td>
			</tr>
        {/foreach}
    	</tbody>
	</table>

	</form>
  </div>
</div>

	
	<!--Marks detail-->
	<div class="modal hide fade" id="markdetail">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">&times;</button>
			<h3>Mission test Detail</h3>
		</div>
		<div class="modal-body" id="markdetailcontent">
		</div>
		<div class="modal-footer">
		</div>
	</div>

	 
