{literal}
<script type="text/javascript" charset="ISO-8859-1" src="/BO/theme/gebo/js/custom/validations_poll.js"></script>
<script type="text/javascript" charset="utf-8" src="/BO/theme/gebo/js/datempicker.js"></script> 
<script>  
	$(document).ready(function() {
		$(".uni_style").uniform(); 
		$('#contribtable').dataTable({
				"sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
				"sPaginationType": "bootstrap",
				"aaSorting": [[ 1, "asc" ]],
				"aoColumns": [
					{ "sType": "string" },
					{ "sType": "formatted-num" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" }
				]
		});
	});
			
	$(function()
		{
			var hideDelay = 50;
			var hideTimer = null;
			
			//User mouseover
		   var container1 = $('#contribPopupContainer');
		  $('body').append(container1);

		  $('.contribPopupTrigger').live('click', function()
		  {
			  // format of 'rel' tag: userid
			  var userid = $(this).attr('rel');
			  var tooltype = 'user';

			  if (hideTimer)
				  clearTimeout(hideTimer);

			  var pos = $(this).offset();
			  var width = $(this).width();
			  container1.css({
				  left: (pos.left + width) + 'px',
				  top: pos.top - 80 + 'px'
			  });

			  $('#contribPopupContent').html('');
			  $('#contribPopupContent').html('<img src="http://www.h2obazaar.com/h2obazaarlogin/images/loading.gif" />');

			  $.ajax({
				  type: 'GET',
				   url: '/ao/pollpopup',
				  data: 'user=' + userid + '&tooltype=' + tooltype,
				  
				  success: function(data)
				  {  
						  var text = $(data).find('.contribPopupResult').html();
						  $('#contribPopupContent').html(data);

				  }
			  });

			  container1.css('display', 'block');
		  });

		  $('.contribPopupTrigger').live('mouseout', function()
		  {
			  if (hideTimer)
				  clearTimeout(hideTimer);
			  hideTimer = setTimeout(function()
			  {
				  container1.css('display', 'none');
			  }, hideDelay);
		  });

		  // Allow mouse over of details without hiding details
		  $('#contribPopupContainer').mouseover(function()
		  {
			  if (hideTimer)
				  clearTimeout(hideTimer);
		  });

		  // Hide after mouseout
		  $('#contribPopupContainer').mouseout(function()
		  {
			  if (hideTimer)
				  clearTimeout(hideTimer);
			  hideTimer = setTimeout(function()
			  {
				  container1.css('display', 'none');
			  }, hideDelay);
		  });
		  
		});		
	
</script>

<style>
	#contribPopupContainer{ position:absolute; left:0; top:0; display:none; z-index: 2000;text-align:left; }
	#contribPopupContent { background-color: #FFF; min-width: 250px; min-height: 150px; z-index: 1000; }
	.contribPopupPopup .personPopupImage { margin: 0px; margin-right: 5px; }
	.contribPopupPopup .corner { width: 19px; height: 15px; }
	.contribPopupPopup .topLeft { background: url(/BO/theme/gebo/img/balloon_topLeft.png) no-repeat; }
	.contribPopupPopup .bottomLeft { background: url(/BO/theme/gebo/img/balloon_bottomLeft.png) no-repeat; }
	.contribPopupPopup .left { background: url(/BO/theme/gebo/img/balloon_left.png) repeat-y; }
	.contribPopupPopup .right { background: url(/BO/theme/gebo/img/balloon_right.png) repeat-y; }
	.contribPopupPopup .topRight { background: url(/BO/theme/gebo/img/balloon_topRight.png) no-repeat; }
	.contribPopupPopup .bottomRight { background: url(/BO/theme/gebo/img/balloon_bottomRight.png) no-repeat; }
	.contribPopupPopup .toptool { background: url(/BO/theme/gebo/img/balloon_top.png) repeat-x; }
	.contribPopupPopup .bottomtool { background: url(/BO/theme/gebo/img/balloon_bottom.png) repeat-x; text-align: center; }
</style>
{/literal}

<div class="row-fluid">
	<div class="span12">
		<h3 class="heading">Participation(s) &agrave; votre devis - {$PollParticipationDetails[0].title}</h3>
	<div align="right" style="padding-right:120px">
		<input type="button" class="btn btn-info" onClick="window.location='/ao/poll?submenuId=ML2-SL17';" value="RETOUR" />
	</div>
	<div>
		Statistiques de r&eacute;ponses au questionnaire
	</div>	
	{if $pollstats|@count >0}
		<div>
			<br>
			<label class="uni-checkbox">
				<input type="checkbox" name="checksmic" id="checksmic" {if $smarty.get.smic == 1}checked{/if} onClick="smicresponse();" class="uni_style" />&nbsp; 
				Je souhaite exclure les participants dont le SMIC calcul&eacute; est inf&eacute;rieur au SMIC en vigueur dans le pays de chaque participant
			</label>
			<br><br>
		</div>
	{/if}
	<div id="responsestats" style="clear:both;"> 
		<table width="55%" align="center" cellpadding="2" style="" class="w-box-content">
			{if $pollstats|@count >0}
				{foreach from=$pollstats item=stat}
					<tr class="w-box-header"><th colspan="4">{$stat.title|stripslashes}</th></tr>
					{if $stat.type!='radio' &&  $stat.type!='checkbox' && $stat.type!='calendar' && $stat.type!='timing'}
						<tr>
							<td width="30%">Nombre de r&eacute;ponses : </td>
							<td align="left">{$stat.partcount}</td>
							<td align="right">Minimum : </td>
							<td>{$stat.min|zero_cut:2} &euro;</td>
							
						</tr>
						<tr>
							<td colspan="2"></td>
							<td align="right">Maximum : </td>
							<td>{$stat.max|zero_cut:2} &euro;</td>
						</tr>
						<tr>
							<td colspan="2"></td>
							<td style="font-weight:bold;" align="right">Moyenne : </td>
							<td style="font-weight:bold;">{$stat.avg|zero_cut:2} &euro;</td>
						</tr>
					{elseif $stat.type=='timing'}	
						<tr>
							<td width="30%">Nombre de r&eacute;ponses : </td>
							<td align="left">{$stat.partcount}</td>
							<td align="right">Minimum : </td>
							<td>{$stat.min|zero_cut:2} {$stat.optionname}</td>
							
						</tr>
						<tr>
							<td colspan="2"></td>
							<td align="right">Maximum : </td>
							<td>{$stat.max|zero_cut:2} {$stat.optionname}</td>
						</tr>
						<tr>
							<td colspan="2"></td>
							<td style="font-weight:bold;" align="right">Moyenne : </td>
							<td style="font-weight:bold;">{$stat.avg|zero_cut:2} {$stat.optionname}</td>
						</tr>
					{elseif $stat.type=='calendar'}
						<tr>
							<td>Nombre de r&eacute;ponses : </td>
							<td valign="top">{$stat.partcount}</td>
						</tr>
					{else}
						<tr>
							<td width="30%">Nombre de r&eacute;ponses : </td>
							<td>{$stat.partcount}</td>
							<td align="right" valign="top">Options :</td> 
							<td nowrap>
							{foreach from=$stat.optionlist item=optionval key=optionkey}
								{$optionkey} - {$optionval} <br>
							{/foreach}	
							</td>
						</tr>
					{/if}
					<tr><td>&nbsp;</td></tr>
				{/foreach}
			{else} 
				{foreach from=$pollquestions item=ques}
					<tr class="w-box-header"><th colspan="4">{$ques.title|stripslashes}</th></tr>
					
					<tr><td>&nbsp;</td></tr>
				{/foreach}
			{/if}
		</table>
	</div>
	
	<div style="padding-top:20px">
		<form method="POST" name="pollform">
			<table class="table table-bordered table-striped table_vam" id="contribtable">
				<thead>
					<tr>
					  <th></th>
					  <th>ID</th>
					  <th>Contributeur</th>
					  <th>Tarif (&euro;)</th>
					  <th>Date d'envoi du devis</th>
					  <th>Filtrer</th>
					  <th>T&eacute;l&eacute;charger</th>
					</tr>
				</thead>
				<tbody>
				{foreach from=$PollParticipationDetails item=condetail_item name=contrib_loop}
					<tr>
					   <td>
							<label class="uni-checkbox">
								<input type="checkbox" name="contribtype[]" value="{$condetail_item.id}" class="uni_style"/>
							</label>
					   </td>
					   <td>{$smarty.foreach.contrib_loop.index+1}</td>
					   <td><a class="contribPopupTrigger" style="cursor: pointer;text-decoration: underline" rel="{$condetail_item.user_id}">
							{if $condetail_item.first_name==""}
								{$condetail_item.email}
							{else}	
								{$condetail_item.first_name}
							{/if}
							</a>
						</td>
					   <td><div style="display:none;">{$condetail_item.price_user}</div>{$condetail_item.price_user|zero_cut:2}</td>
					   <td><div style="display:none;">{$condetail_item.created_at}</div>{$condetail_item.created_at|date_format:"%d/%m/%Y %H:%M:%S" }</td>
					   <td id="partstatus_{$condetail_item.id}"><b>
							{if $condetail_item.status=="active"}
								<a href="javascript:void(0);" onClick="pollparticipationactive({$condetail_item.id},'{$condetail_item.status}');" style="cursor:pointer;">Exclure</a>
							{elseif $condetail_item.status=="inactive"}
								<a href="javascript:void(0);" onClick="pollparticipationactive({$condetail_item.id},'{$condetail_item.status}');" style="cursor:pointer;">Inclure</a>
							{else}
								-
							{/if}</b>
					   </td>
					   <td>
							<!--a href="/ao/questiondetail?poll={$smarty.get.poll}&contrib={$condetail_item.user_id}"><img src="/BO/theme/gebo/img/excel.png" /></a>-->
							<a href="/BO/download_questioncontrib.php?poll={$smarty.get.poll}&contrib={$condetail_item.user_id}"><img src="/BO/theme/gebo/img/excel.png" /></a>
						</td>
					 </tr>
				{/foreach}
				</tbody>
			</table>
			
		 <input type="submit" name="activate_all" id="activate_all" value="Inclure tous" class="btn btn-info" onClick="return updateParticipationall('active');"  />	
		 <input type="submit" name="inactivate_all" id="inactivate_all" value="Exclure tous" class="btn btn-info" onClick="return updateParticipationall('inactive');" />	
		{if $usertype=='superadmin' || $usertype=='ceouser'}
			<input type="button" name="brief" id="brief" value="Compl&eacute;ter brief pour la production" class="btn btn-info" data-toggle="modal" data-target="#pollbrief2" onClick="return brief2form();" />	
		{/if} 
		{if $brief=='yes'} 
			<!--<input type="button" name="briefdownload" id="briefdownload" value="Download Brief2" class="btn btn-info" onClick="window.location='/ao/downloadbrief2?poll={$smarty.get.poll}'" />-->
			<input type="button" name="briefdownload" id="briefdownload" value="T&eacute;l&eacute;charger brief" class="btn btn-info" onClick="window.location='/BO/download_brief2.php?poll={$smarty.get.poll}'" />
		{/if} 
		 <input type="hidden" id="pagelimit" name="pagelimit" value="{$paginationlimit}" />
		 <input type="hidden" id="poll" name="poll" value="{$smarty.get.poll}" />
		</form>	
	</div>
	</div>
</div>	
	
	<!--Brief2-->
	<div class="modal2 hide fade" id="pollbrief2">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">&times;</button>
			<h3>Compl&eacute;ter brief pour la production </h3>
		</div>
		<div class="modal-body" id="pollbrief2content">
		</div>
		<div class="modal-footer">
		</div>
	</div>
	
	<!-- Participation tool tip -->
	<div id="contribPopupContainer">
		<table width="" border="0" cellspacing="0" cellpadding="0" align="center" class="contribPopupPopup" width="auto">
			<tr>
				<td class="corner topLeft"></td>
				<td class="toptool"></td>
				<td class="corner topRight"></td>

			</tr>
			<tr>
				<td class="left">&nbsp;</td>
				<td><div id="contribPopupContent"></div></td>
				<td class="right">&nbsp;</td>
			</tr>
			<tr>
				<td class="corner bottomLeft">&nbsp;</td>
				<td class="bottomtool">&nbsp;</td>
				<td class="corner bottomRight"></td>
			</tr>
		</table>
     </div>  

