{literal}
<script type="text/javascript" charset="utf-8" src="/BO/script/datempicker.js"></script>
<script type="text/javascript">
	$(document).ready(function() {
		optiontext();
	});
	var counter = $("#editcounter").val();
	
	if(counter=="")
		counter = 1;
		
	function optiontext()
	{
		var opt = $("#type").val();
		
		if(opt=='price')
			$("#typeinfo").html("La r&eacute;ponse attendue sera un montant (en euros).");
		else if(opt=='bulk_price')
			$("#typeinfo").html('La r&eacute;ponse attendue sera un montant (en euros) apr&egrave;s r&eacute;duction pour donner un prix de gros s\'il y a plusieurs articles. Ce type de question devra &ecirc;tre li&eacute; &agrave; une question de type "Prix" lors de la cr&eacute;ation du devis.');
		else if(opt=='range_price')
			$("#typeinfo").html('La r&eacute;ponse attendue sera un montant (en euros) situ&eacute; entre deux montants d&eacute;finis lors de la cr&eacute;ation du devis.');
		else if(opt=='timing')
			$("#typeinfo").html('La r&eacute;ponse attendue sera une dur&eacute;e en jours, heures ou minutes, param&egrave;tre d&eacute;fini lors la cr&eacute;ation du devis. Ce type de question devra &ecirc;tre li&eacute; &agrave; une question de type "Prix" ou "Prix de gros" lors de la cr&eacute;ation du devis.');
		else if(opt=='radio')
			$("#typeinfo").html('La r&eacute;ponse attendue sera &agrave; s&eacute;lectionner parmi la liste de r&eacute;ponses que vous devez d&eacute;finir ci-dessous (un seul choix sera possible pour le contributeur).');
		else if(opt=='checkbox')
			$("#typeinfo").html('La/les r&eacute;ponses attendue(s) seront &agrave; cocher parmi une liste de r&eacute;ponses que vous devez d&eacute;finir ci-dessous (plusieurs choix seront possibles pour le contributeur).');
	}
	
	function showoptions()
	{ 
		var opt = $("#type").val();
		
		optiontext();
			
		if(opt == 'radio' || opt == 'checkbox')
		{
			$("#TextBoxesGroup").show();
			
			var fldtext = '<div id="TextBoxDiv2"><input type="text" name="option[]"/></div>';
			$("#option_block").show();
			$("#TextBoxesGroup").html(fldtext);
		}
		else
		{
			$("#TextBoxesGroup").hide();
		}
	}
	
	function loadoptions()
	{
		//var cnt = $("#noofoptions").val();
		
		var fldtext = '';
		
		/*for(var i=1; i<=cnt; i++)
		{*/
			fldtext+='<div id="TextBoxDiv2"><input type="text" name="option[]"/></div>';
		//}
		$("#option_block").show();
		$("#TextBoxesGroup").html(fldtext);
	}
	
	function addfield()
	{
		if (counter > 10) {
                alert("Only 10 textboxes allowed");
                return false;
            }
            $('<div/>',{'id':'TextBoxDiv' + counter})
            .append( $('<input type="text" name="option[]">') )
            .appendTo( '#TextBoxesGroup' )       
            counter++;
	}
	
	function removefield()
	{
			if (counter == 1) {
                alert("No more textbox to remove");
                return false;
            }
            
            $("#TextBoxDiv" + counter).remove();
			counter--;
	}
</script>

{/literal}	

	<form action="/ao/pollconfiguration?submenuId=ML2-SL23" name="pollconfig_form_step{$smarty.foreach.quesloop.index+1}" method="post"  >
		<table align="center" width="100%" cellpadding="4" cellspacing="4" style="padding:10px">
		<tr>
			<td valign="top" width="15%" colspan="2">Titre de la question</td>
		</tr>
		<tr>	
			<td colspan="2">
				<textarea name="title" rows="3" class="span5" placeholder="Entrer votre question...">{$quesdetail[0].title|stripslashes|utf8_encode}</textarea>
			</td>
		</tr>
		<tr>
			<td colspan="2">Type de r&eacute;ponse attendue</td>
		</tr>
		<tr>		
			<td colspan="2">
				<select name="type" id="type" onChange="showoptions();" >
					<option value="price" {if $quesdetail[0].type=="price"}selected{/if}>Prix</option>
					<option value="bulk_price" {if $quesdetail[0].type=="bulk_price"}selected{/if}>Prix de gros</option>
					<option value="range_price" {if $quesdetail[0].type=="range_price"}selected{/if}>Fourchette de prix</option>
					<option value="timing" {if $quesdetail[0].type=="timing"}selected{/if}>Dur&eacute;e</option>
					<option value="radio" {if $quesdetail[0].type=="radio"}selected{/if}>Boutons radio</option>
					<option value="checkbox" {if $quesdetail[0].type=="checkbox"}selected{/if}>Cases &agrave; cocher</option>
					<!--<option value="calendar" {if $quesdetail[0].type=="calendar"}selected{/if}>Calendar</option>-->
				</select>
			</td>
		</tr>
		<tr>
			<td id="typeinfo" colspan="2">
				La r&eacute;ponse attendue sera un montant (en euros).
			</td>
		</tr>
		<tr id="option_block" {if $quesdetail[0].type!="radio" && $quesdetail[0].type!="checkbox"}style="display:none;"{/if}>	
			<td valign="top">Options</td>
			<td>
				<div id="TextBoxesGroup">
					{if $quesdetail[0].optionlist|@count>0}
						{foreach from=$quesdetail[0].optionlist item=opt name=optloop}
						{math assign="loopindex" equation='x+1' x=$smarty.foreach.optloop.index} 
							<div id="TextBoxDiv{$loopindex}">
								<input type="text" name="option[]" value="{$opt|utf8_encode}" />
							</div>
						{/foreach}
						<input type="hidden" name="editcounter" id="editcounter" value="{$quesdetail[0].optionlist|@count}" />
					{/if}
				</div>
				<a href="javascript:void(0);" class="hint--bottom hint--info" data-hint="Add Option" onClick="addfield();"><i class="splashy-add"></i></a>&nbsp;
				<a href="javascript:void(0);" class="hint--bottom hint--info" data-hint="Remove Option" onClick="removefield();"><i class="splashy-remove"></i></a>
			</td>
		</tr>
		<tr>
			<td>&nbsp;</td>
			<td style="float:right">&nbsp; <samp id="222"><input type="submit" name="submit_config" id="submit_config" value="Ajouter"  class="btn btn-info" /></samp> </td>
		</tr>
		</table>
		<input type="hidden" name="quesid" id="quesid" value="{$quesdetail[0].id}"/>
	</form>
