{literal}
<script type="text/javascript" >
    $(document).ready(function(){
        $("input:text").focus(function () {
        $(this).blur();
        });
        $('.service_tooltip').qtip({
            position: {
                corner: {
                    target: 'top',
                    tooltip: 'bottomLeft'
                }
            },
            style: {
                name: 'cream',
                padding: '-70px -13px',
                width: {
                    max: 200,
                    min: 0
                },
                tip: true
            }
        });
        var to = $("#actionmode").val();
        if(to == "accept")
        {
            $("#Moderator_comment").hide();
            $("#refusearea").hide();
        }

        else
        {
            $("#Moderator_crtwindow").hide();
            $("#Moderator_contribwindow").hide();
            $("#acceptarea").hide();
        }

        var editor = CKEDITOR.instances['Moderator_comment'];
        if (editor) { editor.destroy(true); }
        var editor = CKEDITOR.replace( 'Moderator_comment',
                {
                    language: 'de', uiColor: '#D9DDDC', enterMode : CKEDITOR.ENTER_BR, removePlugins : 'resize',
                    toolbar : [ ['Undo','Redo'], ['Find','Replace'],['Link', 'Unlink', 'Image'], ['FontSize', 'Bold', 'Italic','Underline'],
                        ['TextColor', '-', 'Smiley','SpecialChar', '-', 'Maximize'] ]
                }
        );
        var editor = CKEDITOR.instances['Moderator_crtwindow'];
        if (editor) { editor.destroy(true); }
        var editor = CKEDITOR.replace( 'Moderator_crtwindow',
                {
                    language: 'de', uiColor: '#D9DDDC', enterMode : CKEDITOR.ENTER_BR, removePlugins : 'resize',
                    toolbar : [ ['Undo','Redo'], ['Find','Replace'],['Link', 'Unlink', 'Image'], ['FontSize', 'Bold', 'Italic','Underline'],
                        ['TextColor', '-', 'Smiley','SpecialChar', '-', 'Maximize'] ]
                }
        );
        var editor = CKEDITOR.instances['Moderator_contribwindow'];
        if (editor) { editor.destroy(true); }
        var editor = CKEDITOR.replace( 'Moderator_contribwindow',
                {
                    language: 'de', uiColor: '#D9DDDC', enterMode : CKEDITOR.ENTER_BR, removePlugins : 'resize',
                    toolbar : [ ['Undo','Redo'], ['Find','Replace'],['Link', 'Unlink', 'Image'], ['FontSize', 'Bold', 'Italic','Underline'],
                        ['TextColor', '-', 'Smiley','SpecialChar', '-', 'Maximize'] ]
                }
        );
    });
    function confirmAction()
    {
        var r=confirm("Confirmez-votre choix!");
        if (r==true)
        {
           return true;
        }
        else
        {
            return false;
        }
    }
    function sendToFo()
    {
        var r=confirm("L'article sera remis en ligne");
        if (r==true)
        {
            var r1=confirm("Announcement by email");
            if (r1==true)
            {
                $("#sendtofo").val('yes');
                $("#anouncebyemail").val('yes');
                return true;
            }

            $("#sendtofo").val('yes');
            return true;
        }
        else
        {
            $("#sendtofo").val('no');
            return true;
        }
    }
 </script>
{/literal}


		<div class="pophead" style="width:100%;">Moderation for Disapprovals</div>




    <table id="moderateversion" class="table table-bordered table-striped table_vam">
        <thead>
        <tr>
            <th>Version</th>
            <th>Nom du fichier</th>
            <th>Contributeur</th>
            <th>Date</th>
            <th>Article</th>


            <th>Comments</th>
        </tr>
        </thead>
        <tbody>
        {foreach from=$versions_details key=versions_key item=versions_item name=versions_loop}
        <tr>
            <td>{$versions_item.version}</td>
            <td>{$versions_item.article_name}</td>
            <td>{if $versions_item.first_name eq ''}{$versions_item.email}{else}{$versions_item.first_name}{/if}</td>
            <td>{$versions_item.article_sent_at|date_format:"%d/%m/%Y %H:%M"}</td>
            <td><a href="/proofread/downloadfile?submenuId={$submenuId}&path={$versions_item.id}">Download</a></td>
            <td>{$versions_item.article_name|utf8_encode|stripslashes}</td>
        </tr>
        {/foreach}
        </tbody>
    </table>

  <form action="/correction/moderation?submenuId={$submenuId}&articleid={$artId}" method="post" id="moderation" name="moderation" >
    <div>
       <div id="acceptarea">
          <table width="100%">
              <tr><td></td></tr>
              <tr><td><b>Comment of the corrector to the writer:</b></td></tr>
              <tr><td></td></tr>
              <tr >
                <td width="100%"><textarea id="Moderator_contribwindow" name="Moderator_contribwindow" cols="100" rows="5">{$Contribmailcontent}  </textarea>
                    <input type="hidden" id="Contribmailobject" name="Contribmailobject" value="{$Contribmailobject}"></td>
              </tr>
              <tr><td></td></tr>
               <tr >
                   <td width="100%"><textarea id="Moderator_crtwindow" name="Moderator_crtwindow" cols="100" rows="5">{$Correctormailcontent}</textarea>
                       <input type="hidden" id="Correctormailobject" name="Correctormailobject" value="{$Correctormailobject}"></td>
               </tr>
          </table>
          {if $refusetype == 'disapproved_temp'}
             <samp id="343"><input type="submit" class="buttonbg" value="{$nodes[343]}" name="moderate_approve" onclick="return confirmAction();"></samp>
          {else}
             <samp id="343"><input type="submit" class="buttonbg" value="{$nodes[343]}" name="moderate_approve" onclick="return sendToFo();"></samp>
          {/if}
             <div> En appuyant sur « VALIDER », vous confirmez le choix du correcteur. </div>
             <input type="hidden" id="sendtofo" name="sendtofo" value="">
             <input type="hidden" id="anouncebyemail" name="anouncebyemail" value="">
       </div>
       <div id="refusearea">
          <div style="width: 100%;height: 7px; background: #93B7DA;"></div>
          <table width="100%" id="magic">
            <tr><td></td></tr>
            <tr><td><b>Commentaire laiss&eacute; au correcteur par Edit-place :</b></td></tr>
            <tr><td></td></tr>
            <tr >
                <td width="100%"><textarea id="Moderator_comment" name="Moderator_comment" cols="100" rows="5">{$onlycorrectorcontent}</textarea>
                    <input type="hidden" id="onlycorrectorobject" name="onlycorrectorobject" value="{$onlycorrectorobject}">
                </td>
            </tr>
          </table>
          <samp id="344"><input type="submit" class="buttonbg" value="{$nodes[344]}" id="moderate_disapprove" name="moderate_disapprove" onclick="return confirmAction();">
           <div> En appuyant sur « REFUSER », vous ne confirmez pas le choix du correcteur et lui demandez de corriger l’article tel que le rédacteur lui a envoyé. </div>
       </div>
       <div class="buttontwo" >
            <input type="hidden" id="latestmarks" name="latestmarks" value="{php} echo $latestmarks; {/php}">
            <input type="hidden" id="correctorId" name="correctorId" value="{php} echo $correctorId; {/php}">
            <input type="hidden" id="contributorId" name="contributorId" value="{php} echo $contributorId; {/php}">
			<input type="hidden" id="artsentdate" name="artsentdate" value="{php} echo $artsentdate; {/php}">
            <input type="hidden" id="actionmode" name="actionmode" value="{php} echo $_GET['actionmode']; {/php}" />
            <input type="hidden" id="status" name="status" value="{php} echo $_GET['status']; {/php}" />
       </div>
    </div>
  </form>



