{literal}
<link rel="stylesheet" href="/BO/theme/gebo/js/validation-engine/validationEngine.jquery.css" type="text/css"/>
<link rel="stylesheet" href="/BO/theme/gebo/lib/x-editable/bootstrap-editable/css/bootstrap-editable.css">
<link rel="stylesheet" href="/BO/theme/gebo/lib/iCheck/skins/square/blue.css" type="text/css"/>
<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine-fr.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>
<script language="JavaScript" type="text/javascript" src="/BO/theme/gebo/js/ajaxupload.3.5.js"></script>
<script src="/BO/theme/gebo/lib/iCheck/icheck.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/gebo/lib/x-editable/bootstrap-editable/js/bootstrap-editable.min.js" type="text/javascript" charset="utf-8"></script>
<style>
	.mission-details:nth-of-type(1)
	{
		margin:0 0 10px;
	}
	
	.mission-details2
	{
		margin:10px 0 0;
	}
	
	.icon-time
	{
		margin-right: 5px;
		position: relative;
		top: 2px;
	}	
	
	.underline
	{
		padding: 10px;
	}
	
	.circle
	{
		padding: 5px 8px;
		border: 1px solid rgb(38,124,255);
		background-color: rgb(38,124,255);
		color: #fff;
		border-radius: 50px;
	}
	
	#sampletext_table td
	{
		font-size: 14px;
	}
	
	#atokens .btn{
		margin-top: 5px;
	}

	#atokens .well
	{
		padding: 10px;
	}
</style>
<script>
var theme = {/literal}"{$prod_step1.theme}"{literal};
var ebooker_delivery = {/literal}"{$ebooker_delivery}"{literal};
	$(document).ready(function(){
		
		// Load tokens 
		if(theme)
			loadtokens(false);
		
		//validation
		$("#delivery-prod-form1").validationEngine({prettySelect : true,useSuffix: "_chzn",onValidationComplete: function(form, status){
			if(status == true)
			{
				if(ebooker_delivery)
				{
				if($("#sampletext").val())
				return true;
				else
				{	
					$("#seeall").focus();
					$("#sampletxt_text").html("<span style='color:red'>Please select sample text</span>");
				}
				}
				else
					return true;
			}
	}});
		
	
		//icheck radio/checkbox
		$(".icheck").iCheck({
			checkboxClass: 'icheckbox_square-blue',
			radioClass: 'iradio_square-blue'
		});
		
		
		 $(".customselect").chosen({  allow_single_deselect:false,disable_search: true });
		 $("#category").chosen({  allow_single_deselect:false,disable_search: true });
		 
		 
		 $('input[name="correction"]').on('ifClicked', function (event) {
			var value=this.value;
			if(value=='external')
			{
				$("#external").show();
				$("#internal").hide();
			}	
			else
			{
				$("#external").hide();
				$("#internal").show();
			}	
			
		});
		
		//toggle writer price display
		$('#pricedisplaycheck').toggleButtons({label:{enabled: "Oui",disabled: "Non"}});
		
		$('input[name="AOtype"]').on('ifClicked', function (event) {
			var value=this.value;
			if(value=='public'){
				//$('#pricedisplaycheck').toggleButtons('setState', false); 
				//$("#pricedisplay").attr('disabled',"true");
				//$("#pricedisplaycheck").addClass('deactivate');
			}
			else{
				//$("#pricedisplay").removeAttr('disabled');
				//$("#pricedisplaycheck").removeClass('deactivate');
				//$('#pricedisplaycheck').toggleButtons('setState', true); 
			}				
			
		});
		
		//toggle correction price display
		$('#corrector_pricedisplaycheck').toggleButtons({label:{enabled: "Oui",disabled: "Non"}});
		
		$('input[name="correction_type"]').on('ifClicked', function (event) {
			var value=this.value;
			if(value=='public'){
				//$('#corrector_pricedisplaycheck').toggleButtons('setState', false); 
				//$("#corrector_pricedisplay").attr('disabled',"true");
				//$("#corrector_pricedisplaycheck").addClass('deactivate');
			}
			else{
				//$("#corrector_pricedisplay").removeAttr('disabled');
				//$("#corrector_pricedisplaycheck").removeClass('deactivate');
				//$('#corrector_pricedisplaycheck').toggleButtons('setState', true); 
			}				
			
		});
		
		//plag excel toggle
		$('input[name="plag_excel_file"]').on('ifClicked', function (event) {
			var value=this.value;
			if(value=='yes')
			{
				$("#plag_excel_div").show();				
			}	
			else
			{
				$("#plag_excel_div").hide();				
			}	
			
		});
		
		//delivery name edit		
		$("#edit_dname").click(function(e){
			e.stopPropagation();
			$('#delivery_name').editable('toggle');
		});
		 
		$('#delivery_name').editable({
            url: '/quotedelivery/update-deliveryname?session_id={/literal}{$smarty.get.session_id}{literal}',
            type: 'text',
            name: 'delivery_name',
            title: '',
			validate: function(value) {
               if($.trim(value) == '') return 'This field is required';
            }
        });	
		
		
		fncalculateRemainingArticles();
		
		
		$('body').on('hidden', '#sampletexts', function (){        
				
			});
		$('#sourcelang_nocheckbox').toggleButtons({label:{enabled: "Oui",disabled: "Non"}});	
		$('#sourcelang_nocheckbox_correction').toggleButtons({label:{enabled: "Oui",disabled: "Non"}});	
		
});		
//writing brief upload		
$(function(){		
		var btnUpload=$('#uploadspec_chzn');
		var status=$('#writing_spec_file_name');
		
		new AjaxUpload(btnUpload, {
			action: 'upload-writing-spec?session_id={/literal}{$smarty.get.session_id}{literal}',
			name: 'uploadfile',
			onSubmit: function(file, ext){
				if (! (ext && /^(doc|docx|xls|xlsx|pdf|csv|xml|rtf|zip)$/.test(ext))){
					$('#fileerr').html('Uniquement doc, docx, xls, xlsx, pdf, csv, xml, zip et rtf').css('color','#FF0000');
					return false;
				}				
				status.html('<img src="/BO/theme/gebo/img/ajax_loader.gif" />');
			},
			onComplete: function(file, response){//alert(response);
				if(response!="error"){
				status.html('').css('color','#000000');
					var fname=response.split("#");					
					status.html(fname[1]);
					$("#uploadspec").val(fname[1]);
					
				}
			}
		 });
	
		 
	});
		//correctiom brief upload		
$(function(){		
		var btnUpload=$('#upload-correction-spec_chzn');
		var status=$('#correction_spec_file_name');
		
		new AjaxUpload(btnUpload, {
			action: 'upload-correction-spec?session_id={/literal}{$smarty.get.session_id}{literal}',
			name: 'uploadfile',
			onSubmit: function(file, ext){
				if (! (ext && /^(doc|docx|xls|xlsx|pdf|csv|xml|rtf|zip)$/.test(ext))){
					$('#fileerr').html('Uniquement doc, docx, xls, xlsx, pdf, csv, xml, zip et rtf').css('color','#FF0000');
					return false;
				}		
				
				
				status.html('<img src="/BO/theme/gebo/img/ajax_loader.gif" />');
			},
			onComplete: function(file, response){//alert(response);
				if(response!="error"){
				status.html('').css('color','#000000');
					var fname=response.split("#");					
					status.html(fname[1]);
					$("#upload-correction-spec").val(fname[1]);					
				}
			}
		 });
	
		 
	});	
//calculating remaining articles by changing the packs and files	
function fncalculateRemainingArticles()
{
	var volume='{/literal}{$prod_step1.volume}{literal}';
	var files_pack=$("#files_pack").val();
	var total_article=$("#total_article").val();
	
	var remaining_articles=(volume-(files_pack*total_article));
	
	remaining_articles=remaining_articles >0 ? remaining_articles : 0;
	
	$("#remaining_articles").text(remaining_articles);
	
}



</script>
{/literal}
{if $misssionQuoteDetails|@count gt 0}
	{foreach from=$misssionQuoteDetails item=quoteMission name="quote"}	
	<input type="hidden" id="mvolume"	value="{$quoteMission.volume}">
	<input type="hidden" id="mvolume_max"	value="{$quoteMission.volume_max}">
	<div class="row-fluid">
		 <div class="span12">
			<h3 class="heading">
			<a href="/followup/prod?submenuId=ML13-SL4&cmid={$smarty.get.mission_id}">
				{if $quoteMission.product eq 'translation'}
					<b>{$quoteMission.product_name} {$quoteMission.product_type_name} {$quoteMission.language_source_name} vers {$quoteMission.language_dest_name} </b>
				{elseif $quoteMission.product eq 'redaction'}
					<b>{$quoteMission.product_name} {$quoteMission.product_type_name} en {$quoteMission.language_source_name}</b>
				{/if}
			</a>
				> Create New Delivery
				<span class="pull-right">
						<img src="/BO/theme/gebo/img/path-1.png" width="120" height="35" border="0" usemap="#Map" />
						<map name="Map" id="Map">
						</map>
				</span> 
			</h3>
		</div>
	</div>
	<div class="row-fluid">
		<div class="span9">
		<form class="form-horizontal"  action="/quotedelivery/save-prod1?mission_id={$smarty.get.mission_id}&session_id={$smarty.get.session_id}" method="POST" id="delivery-prod-form1" enctype="multipart/form-data">
		
			<input type="hidden" name="mission_id" value="{$smarty.get.mission_id}">
			
			<h2 class="heading">
				<i style="margin:5px;cursor:pointer" id="edit_dname" class="splashy-pencil"></i><a data-original-title="" data-placeholder="Required" data-placement="right" data-pk="1" data-type="text" style="margin-right:5px" id="delivery_name" href="#">{$prod_step1.title}</a>
			</h2>
			
			{include file="gebo/survey/mission_overview.phtml"}
			
			<!-- Writing Rules -->			
			<div class="mission-details2">			
				<div class="prod-mission-product">Writing Rules</div>
			</div>
			
			<div class="w-box">
				<div class="w-box-content cnt_a">
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label">Delivery Status</label>
							<div class="controls">
								<div class="span6">
									<div class="" id="">
											<label class="radio inline">
											<input type="radio" name="AOtype" class="icheck" checked="checked" value="public" {if $prod_step1.AOtype eq 'public'} checked{/if}/> 
												Public
											</label>
											<label class="radio inline">
											<input type="radio" name="AOtype" class="icheck" value="private" {if $prod_step1.AOtype eq 'private'} checked{/if}/> 
												Private
											</label>
									</div>
								</div>
							</div>
						</div>
					</div>
					
					{if $quoteMission.product eq 'translation'}
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label">Do not consider Source language</label>
							<div class="controls">
								<div id="sourcelang_nocheckbox">
									<input type="checkbox" {if $prod_step1.sourcelang_nocheck eq 'yes'}checked{/if} name="sourcelang_nocheck" value="yes">
								</div>
							</div>
						</div>
					</div>
					{/if}
					
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label" style="padding-top:5px">Cost (&euro;)</label>
							<div class="controls">
								<div class="span3">
									<!-- <div class="pull-center">Min</div> -->
									<div class="" id="">
										<input class="span12 validate[required,max[{$prod_step1.price_max_valid}],priceRange[#price_max]]" value="{$prod_step1.price_min|zero_cut:2}" type="text" name="price_min" id="price_min" placeholder="Min" />
									</div>
								</div>
								<div class="span3">
									<!-- <div class="pull-center">Max</div> -->
									<div class="" id="">
										<input class="span12 validate[required,max[{$prod_step1.price_max_valid}]]" value="{$prod_step1.price_max|zero_cut:2}" type="text" name="price_max" id="price_max"  placeholder="Max" />
									</div>
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label"><i class="icon-time"></i>Participation</label>
							<div class="controls">
								<div class="span5" >
								<input type="text" name="participation_time_hour" id="participation_time_hour" class="span7 validate[required]" value="{$prod_step1.participation_time_hour}" /> Heure(s)
								</div>
								<div class="span6" style="margin-left:0" >
								<input type="text" name="participation_time_min" id="participation_time_min" class="span6 validate[required]" value="{$prod_step1.participation_time_min}" /> Min(s)
								</div>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label"><i class="icon-time"></i>Selection</label>
							<div class="controls">
								<div class="span5" >
								<input type="text" name="selection_hour" id="selection_hour" class="span7 validate[required]" value="{$prod_step1.selection_hour}" /> Heure(s)
								</div>
								<div class="span6" style="margin-left:0" >
								<input type="text" name="selection_min" id="selection_min" class="span6 validate[required]" value="{$prod_step1.selection_min}" /> Min(s)
								</div>
							</div>
						</div>
					</div>
					{if $user_type == 'superadmin'}
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label">Afficher la fourchette de prix r&eacute;daction</label>
							<div class="controls">
								<div id="pricedisplaycheck">
									<input type="checkbox" {if $prod_step1.pricedisplay eq 'yes'}checked{/if} name="pricedisplay" value="yes">
								</div>
							</div>
						</div>
					</div>
					{/if}
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label">URLs &agrave; ne pas v&eacute;rifier dans la phase plagiat
										<div style="color:red">(S&eacute;par&eacute;es par des virgules)</div>
							</label>
							<div class="controls">	
								<textarea placeholder="Example:edit-place.com, www.edit-place.com" id="urlsexcluded" name="urlsexcluded">{$prod_step1.urlsexcluded}</textarea>
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label">Crit&egrave;res de notation vs refus</label>
							<div class="controls">	
								<p>Merci de s&eacute;lectionner entre 1 et {$refusal_reasons_max} crit&egrave;res de notation parmi les suivants : </p>
								<div class="row-fluid">
									{if $reasons1|@count gt 0}
										<div class="span4">
											{foreach item=reason from=$reasons1 key=index name="reason1"}
												<label class="checkbox">
													<input type="checkbox" {if $index|in_array:$prod_step1.refusalreasons}checked{/if} name="refusalreasons[]" value="{$index}" class="icheck validate[minCheckbox[1],maxCheckbox[{$refusal_reasons_max}]] " /> 
													{$reason}
												</label>
											{/foreach}
										</div>
									{/if}
									{if $reasons2|@count gt 0}
										<div class="span4">
											{foreach item=reason from=$reasons2 key=index}
												<label class="checkbox">
													<input type="checkbox"  {if $index|in_array:$prod_step1.refusalreasons}checked{/if}  name="refusalreasons[]" value="{$index}" class="icheck validate[minCheckbox[1],maxCheckbox[{$refusal_reasons_max}]]"/> 
													{$reason}
												</label>
											{/foreach}
										</div>
									{/if}
								</div>	
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label">Brief r&eacute;dactionnel</label>
							<div class="controls">
								<div id="uploadspec_chzn" class="span3">
									<span class="btn btn-file">
										<span class="fileupload-new"><i class="icon-adt_atach"></i>Add Brief</span>
										<input style="display:none" type="file" class="" name="file" value="{$prod_step1.writing_spec_file_name}">
									</span>
									<input type="hidden"class="validate[required]" id="uploadspec" value="{$prod_step1.writing_spec_file_name}">
									<div id="writing_spec_file_name">{$prod_step1.writing_spec_file_name}</div>				
								</div>
							</div>
						</div>
					</div>		
				</div>
			</div>
			{* Stencils start *}
			{if $quoteMission.client_id==$ebookerid && $quoteMission.stencils_ebooker == 'yes'}
			<div class="mission-details2">			
				<div class="prod-mission-product">Stencils Setup</div>
			</div>
			<div class="w-box">
				<div class="w-box-content cnt_a">
				<div class="row-fluid">
					<div class="span3">
					<p><strong><span class="circle">1</span> &nbsp;&nbsp;Select a theme</strong></p>
					<select name="theme" id="theme" class="customselect themes validate[required]" placeholder="Select theme" onchange="loadcategory()">
					   <option></option>
					   {* {html_options options=$sthemes selected=$prod_step1.theme} *}
					   {foreach from=$sthemes key=Id item="theme" name="sthemes"}
					   <option value={$Id} {if $prod_step1.theme eq $Id } selected="selected" {/if}>{$theme}</option>
					   {/foreach}
					</select>
					</div>
					<div class="span3">
					<p><strong><span class="circle">2</span> &nbsp;&nbsp;Select a category</strong></p>
					<select name="category" id="category" class="category validate[required]" placeholder="Select Category"  onchange="loadtokens(true)">
					  <option></option>
					  {*  {html_options options=$scat selected=$prod_step1.category} *}
					   {foreach from=$scat key=Id item="theme" name="sthemes"}
					   <option value={$Id} {if $prod_step1.category eq $Id } selected="selected" {/if}>{$theme}</option>
					   {/foreach}
					</select>
					</div>
					<div class="span6 pull-center">
					<p><strong><span class="circle">3</span> &nbsp;&nbsp;Select a Sample</strong></p>
					<div id="sampletxt_text">{$sampletexts}</div>
					<button type="button" class="btn btn-warning" {if !$sampletexts}disabled="disabled"{/if} id="seeall" onclick="getsampletexts()" name="seeall" value="">{if !$sampletexts}See all{else}Change Selection{/if}</button>
					<div id="atokens" style="margin-top:10px">
						
					</div>
					<input type="hidden" name="sampletext" id="sampletext" value="{$prod_step1.sampletext}" class="" />
					</div>
				</div>
				</div>
			</div>
			{/if}
			{* Stencils end *}
            <!--- *** added on 24.02.2016 *** --->
            {* bnp missions starts *}
            {if $quoteMission.bnp_mission == 'yes'}{*  $quoteMission.client_id==$ebookerid && *}
            <div class="mission-details2">
                <div class="prod-mission-product">BNP Setup</div>
            </div>
            <div class="w-box">
                <div class="w-box-content cnt_a">
                    <div class="row-fluid">
                        <div class="span3">
                            <p><strong><span class="circle">1</span> &nbsp;&nbsp;Select a City</strong></p>
                            <select name="city" id="city" class="city validate[required]" placeholder="Select city" >
                                <option></option>
                                {foreach from=$scitys key=Id item="city" name="scitys"}
                                <option value={$Id}  >{$city}</option>
                                {/foreach}<!--selected="selected"-->
                            </select>
                        </div>
                        <div class="span6 pull-center">
                            <p><strong><span class="circle">2</span> &nbsp;&nbsp;Select a Sample</strong></p>
                            <div id="sampletxt_text">{$sampletexts}</div>
                            <button type="button" class="btn btn-warning" id="seeall" onclick="getbnpsampletexts()" name="seeall" value="">{if !$sampletexts}See all{else}Change Selection{/if}</button>
                            <div id="atokens" style="margin-top:10px">

                            </div>
                            <input type="hidden" name="sampletext" id="sampletext" value="{$prod_step1.sampletext}" class="" />
                        </div>
                    </div>
                </div>
            </div>
            {/if}

            {* end of bnp missions starts *}
			<!-- Proofreading Rules -->
			{if $prod_step1.correction!='no'}
			<div class="mission-details2">			
				<div class="prod-mission-product">Proofreading Rules</div>
			</div>
			
			<div class="w-box">
				<div class="w-box-content cnt_a">
					{if $prod_step1.correction eq 'external'}
						<div class="row-fluid">
							<div class="alert alert-important">
								Les participations pour la correction seront ouvertes en m&ecirc;me temps pour la r&eacute;daction et pour la correction,<br>
								le correcteur, une fois s&eacute;lectionn&eacute;, devra attendre que le r&eacute;dacteur soumette son fichier pour d&eacute;marrer la correction
							</div>
						</div>
					{/if} 	
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label">Team in charge</label>
							<div class="controls">
								<div class="span6">
									<div class="" id="">
											<label class="radio inline">
											<input type="radio" disabled  name="correction" id="correction" value="internal" {if $prod_step1.correction eq 'internal'} checked{/if} class="icheck" /> 
												Internal
											</label>
											<label class="radio inline">
											<input type="radio" disabled  class="icheck" name="correction" id="correction" value="external" {if $prod_step1.correction eq 'external'} checked{/if} /> 
												External
											</label>
									</div>
								</div>
							</div>
						</div>
					</div>
					<div id="external" {if $prod_step1.correction eq 'internal'} class="hide" {/if}>
						<div class="row-fluid">
							<div class="control-group">
								<label class="control-label">Correction Status</label>
								<div class="controls">
									<div class="span6">
										<div class="" id="">
												<label class="radio inline">
												<input type="radio" name="correction_type" class="icheck" checked="checked" value="public" {if $prod_step1.correction_type eq 'public'} checked{/if}/> 
													Public&nbsp;&nbsp;&nbsp;
												</label>
												<label class="radio inline">
												<input type="radio" name="correction_type" class="icheck" value="private" {if $prod_step1.correction_type eq 'private'} checked{/if}/> 
													Private
												</label>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="row-fluid">
							<div class="control-group">
								<label class="control-label">Correction moderation</label>
								<div class="controls">
									<div class="span6">
										<div class="" id="">
												<label class="radio inline">
												<input type="radio" name="nomoderation" class="icheck" checked="checked" value="no" {if $prod_step1.nomoderation eq 'no'} checked{/if}/> 
													YES
												</label>
												<label class="radio inline">
												<input type="radio" name="nomoderation" class="icheck" value="yes" {if $prod_step1.nomoderation eq 'yes'} checked{/if}/> 
													NO
												</label>
										</div>
									</div>
								</div>
							</div>
						</div>
						
						{if $quoteMission.product eq 'translation'}
						<div class="row-fluid">
							<div class="control-group">
								<label class="control-label">Do not consider Source language </label>
								<div class="controls">
									<div class="span6">
										<div id="sourcelang_nocheckbox_correction">
											<input type="checkbox" {if $prod_step1.sourcelang_nocheck_correction eq 'yes'}checked{/if} name="sourcelang_nocheck_correction" value="yes">
										</div>
									</div>
								</div>
							</div>
						</div>
						{/if}
							
						<div class="row-fluid">
							<div class="control-group">
								<label class="control-label" style="padding-top:5px">Cost (&euro;)</label>
								<div class="controls">
									<div class="span3">
										<!-- <div class="pull-center">Min</div> -->
										<div class="" id="">
											<input class="span12  validate[required,max[{$prod_step1.correction_pricemax_valid}],priceRange[#correction_pricemax]]" value="{$prod_step1.correction_pricemin|zero_cut:2}" type="text" name="correction_pricemin" id="correction_pricemin" placeholder="Min" />
										</div>
									</div>
									<div class="span3">
										<!-- <div class="pull-center">Max</div> -->
										<div class="" id="">
											<input class="span12 validate[required,max[{$prod_step1.correction_pricemax_valid}]]" value="{$prod_step1.correction_pricemax|zero_cut:2}" type="text" name="correction_pricemax" id="correction_pricemax" placeholder="Max" />
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="row-fluid">
							<div class="control-group">
								<label class="control-label"><i class="icon-time"></i>Participation</label>
								<div class="controls">
									<div class="span5" >
									<input type="text" name="correction_participation_hour" id="correction_participation_hour" class="span7  validate[required]" value="{$prod_step1.correction_participation_hour}" /> Heure(s)
									</div>
									<div class="span6" style="margin-left:0" >
									<input type="text" name="correction_participation_min" id="correction_participation_min" class="span6 validate[required]" value="{$prod_step1.correction_participation_min}" /> Min(s)
									</div>
								</div>
							</div>
						</div>
						<div class="row-fluid">
							<div class="control-group">
								<label class="control-label"><i class="icon-time"></i>Selection</label>
								<div class="controls">
									<div class="span5" >
									<input type="text" name="correction_selection_hour" id="correction_selection_hour" class="span7  validate[required]" value="{$prod_step1.correction_selection_hour}" /> Heure(s)
									</div>
									<div class="span6" style="margin-left:0" >
									<input type="text" name="correction_selection_min" id="correction_selection_min" class="span6 validate[required]" value="{$prod_step1.correction_selection_min}" /> Min(s)
									</div>
								</div>
							</div>
						</div>	
						{if $prod_step1.correction eq 'external'}						
							
							<div class="row-fluid">
								<div class="control-group">
									<label class="control-label">Plagiarism Excel</label>
									<div class="controls">
										<div class="span4">
											<div class="" id="">
												<label class="radio inline">
												<input type="radio" name="plag_excel_file" class="icheck" value="yes" {if $prod_step1.plag_excel_file eq 'yes'} checked{/if}/> 
													YES&nbsp;&nbsp;&nbsp;
												</label>
												<label class="radio inline">
												<input type="radio" name="plag_excel_file" class="icheck" value="no" {if $prod_step1.plag_excel_file neq 'yes'} checked{/if}/> 
													NO
												</label>
											</div>
										</div>
									</div>
									<div class="controls" id="plag_excel_div" {if $prod_step1.plag_excel_file neq 'yes'} style="display:none"{/if}>
										<div class="span2" >
											<select name="plag_xls" class="span12 customselect" id="plag_xls">
												<option value="xls" {if $prod_step1.plag_xls eq 'xls'} selected {/if}>XLS</option>
												<option value="xlsx" {if $prod_step1.plag_xls eq 'xlsx'} selected {/if}>XLSX</option>
											</select>
										</div>
										<div class="span3">
											<input type="text" class="span12" id="xls_columns" value="{$prod_step1.xls_columns}" placeholder="# columns" name="xls_columns">
										</div>
									</div>
								</div>
							</div>
						{/if}	
						{*<div class="row-fluid">
							<div class="control-group">
								<label class="control-label"></label>
								<div class="controls">
									<label class="checkbox inline">
									<input type="checkbox" class="icheck" name="correction_launch" value="yes" {if $prod_step1.correction_launch eq 'yes'}checked{/if} id="correction_launch" style="margin-top:8px" /> 
										Launch the correction mission after receiving 
									</label>
									<input type="text" class="span2" id="launch_after_packs" value="{$prod_step1.launch_after_packs}"  name="launch_after_packs"> articles
								</div>
							</div>
						</div>*}
						{if $user_type == 'superadmin'}
						<div class="row-fluid">
							<div class="control-group">
								<label class="control-label">Afficher la fourchette de prix correction</label>
								<div class="controls">
									<div id="corrector_pricedisplaycheck">
										<input type="checkbox" {if $prod_step1.corrector_pricedisplay eq 'yes'}checked{/if} name="corrector_pricedisplay" value="yes">
									</div>
								</div>
							</div>
						</div>
						{/if}
						<div class="row-fluid">
							<div class="control-group">
								<label class="control-label">Brief correcteur</label>
								<div class="controls">
									<div id="upload-correction-spec_chzn" class="span3">
										<span class="btn btn-file">
											<span class="fileupload-new"><i class="icon-adt_atach"></i>Add Brief</span>
											<input type="file" class="" name="correction_file">
										</span>
										<input type="hidden"class="validate[required]" id="upload-correction-spec" value="{$prod_step1.correction_spec_file_name}">
										<div id="correction_spec_file_name">{$prod_step1.correction_spec_file_name}</div>								
									</div>
								</div>
							</div>
						</div>
					</div>
					{if $prod_step1.correction eq 'internal'}					
					<div id="internal">
						<div class="row-fluid">
							<div class="control-group">
								<label class="control-label">Plagiarism Excel</label>
								<div class="controls">
									<div class="span4">
										<div class="" id="">
												<label class="radio inline">
												<input type="radio" name="plag_excel_file" class="icheck" value="yes" {if $prod_step1.plag_excel_file eq 'yes'} checked{/if}/> 
													YES&nbsp;&nbsp;&nbsp;
												</label>
												<label class="radio inline">
												<input type="radio" name="plag_excel_file" class="icheck" value="no" {if $prod_step1.plag_excel_file neq 'yes'} checked{/if}/> 
													NO
												</label>
										</div>
									</div>
								</div>
								<div class="controls" id="plag_excel_div" {if $prod_step1.plag_excel_file neq 'yes'} style="display:none"{/if}>
									<div class="span2" >
										<select name="plag_xls" class="span12 customselect" id="plag_xls">
											<option value="xls" {if $prod_step1.plag_xls eq 'xls'} selected {/if}>XLS</option>
											<option value="xlsx" {if $prod_step1.plag_xls eq 'xlsx'} selected {/if}>XLSX</option>
										</select>
									</div>
									<div class="span3">
										<input type="text" class="span12" id="xls_columns" value="{$prod_step1.xls_columns}" placeholder="# columns" name="xls_columns">
									</div>
								</div>
							</div>
						</div>
					</div>	
					{/if}
				</div>
			</div>
			{/if}
			<!-- Files Rules -->
			
			<div class="mission-details2">			
				<div class="prod-mission-product">Files Rules</div>
			</div>
			
			<div class="w-box">
				<div class="w-box-content cnt_a">
				<div class="row-fluid">
					<div class="span6">
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label">#Files / Pack</label>
							<div class="controls">
								<input type="text" onkeyup="fncalculateRemainingArticles();" name="files_pack" id="files_pack" class="span4 validate[required]" value="{$prod_step1.files_pack}" />
							</div>
						</div>
					</div>
					<div class="row-fluid">
						<div class="control-group">
							<label class="control-label">#Pack to create</label>
							<div class="controls">
								<input type="text" onkeyup="fncalculateRemainingArticles();" name="total_article" id="total_article" class="span4 validate[required]" value="{$prod_step1.total_article}"/>
							</div>
						</div>
					</div>
					</div>
					<div class="span6 pull-center">
						<div class="row-fluid ">
							Remaining articles for this mission
							<h3>
								<span id="remaining_articles">{$prod_step1.remaining_articles}</span> / {$prod_step1.volume}
							</h3>
						</div>
						<hr style="width:150px;margin:10px auto;"/>
						<div class="row-fluid">
							Remaining Days
							<h3>
								{$prod_step1.mission_end_days}
							</h3>
						</div>
					</div>
				</div>
				</div>
			</div>
			<div class="control-group topset2">
				<div class="pull-center">
					<button class="btn btn-primary" id="step1_submit" type="submit">Save and schedule</button>
				</div>
			</div>
		</form>	
		</div>
		<div class="span3">
			{include file='gebo/survey/info.phtml'}
		</div>
	</div>
	{/foreach}
{/if}	
<!-- popup to show sample texts -->
<div class="container modal hide fade" id="sampletexts" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
		<h3>Sample texts</h3>
    </div>
    <div class="modal-body">
	
    </div>
    <div class="modal-footer">
    </div>
</div>
{literal}
<script type="text/javascript">
function loadcategory()
{
	var theme_id = $(".themes").val();
	$.post('/quotedelivery/get-category/',{"theme_id":theme_id},function(json){
		$(".category").html("");
		$(".category").append($("<option></option>").val('').text(""));
		for(var key in json) 
		{
			 $(".category").append($("<option></option>").val(json[key].cat_id).html(json[key].category_name));
		}
		$("#category").trigger("liszt:updated");
		
		//if(!json.length)
			$("#seeall").prop("disabled",true);
			$("#atokens, #sampletxt_text").html('');
			$("#seeall").text("See all");
			$("#sampletext, #seeall").val('');
	},'json');
}

function loadtokens(status)
{
	var cat_id = $("#category").val();
	if(cat_id)
	{
		$("#seeall").prop("disabled",false);
		var matokens = "";
		var oatokens = "";
		var hatokens = "";
		$.post('/quotedelivery/get-tokens',{"cat_id":$("#category").val()},function(json){
			if(status)
			{
				$("#seeall").text("See all");
				$("#atokens, #sampletxt_text").html('');
				$("#sampletext, #seeall").val('');
			}
				if(json.mtokens.length)
				matokens = '<div class="well"><h5>Mandatory Tokens</h5>';
				for(var key in json.mtokens) 
					matokens += '<label class="label label-info">'+json.mtokens[key]+'</label><br>';
				if(matokens)
				matokens += '</div>';
			
				if(json.otokens.length)
				oatokens = '<div class="well"><h5>Optional Tokens</h5>';
				for(var key in json.otokens) 
					oatokens += '<label class="label label-info">'+json.otokens[key]+'</label><br>';
				if(oatokens)
				oatokens += '</div>';
			
				if(json.htokens.length)
				hatokens = '<div class="well"><h5>Hidden Tokens</h5>';
				for(var key in json.otokens) 
					hatokens += '<label class="label label-info">'+json.htokens[key]+'</label><br>';
				if(hatokens)
				hatokens += '</div>';
			
				$("#atokens").html(matokens+oatokens+hatokens);
					
					},'json');
				
				
				
	}
	else
		$("#seeall").prop("disabled",true);
}

function getsampletexts()
{
	$('#sampletexts').modal('show');
	$('#sampletexts .modal-body').html('Please wait loading...');
	$.post('/quotedelivery/sample-texts',{"cat_id":$("#category").val(),"sample_id":$("#sampletext").val()},function(data){
					$("#sampletexts .modal-body").html(data);
					});
}
    function getbnpsampletexts(){
        $('#sampletexts').modal('show');
        $('#sampletexts .modal-body').html('Please wait loading...');
        $.post('/quotedelivery/sample-bnp-texts?city_id='+$("#city").val(),function(data){
            $("#sampletexts .modal-body").html(data);
        });
    }
</script>
{/literal}