{literal}
<!--<script type="text/javascript">
$(document).ready(function() {
gebo_peity.init();
});
gebo_peity = {
		init: function() {
			$.fn.peity.defaults.line = {
				strokeWidth: 1,
				delimeter: ",",
				height: 32,
				max: null,
				min: 0,
				width: 50
			};
			$.fn.peity.defaults.bar = {
				delimeter: ",",
				height: 32,
				max: null,
				min: 0,
				width: 50
			};
			$(".p_bar_up").peity("bar",{
				colour: "#6cc334"
			});
			$(".p_bar_down").peity("bar",{
				colour: "#e11b28"
			});
			$(".p_line_up").peity("line",{
				colour: "#b4dbeb",
				strokeColour: "#3ca0ca"
			});
			$(".p_line_down").peity("line",{
				colour: "#f7bfc3",
				strokeColour: "#e11b28"
			});
		}
	};
</script>-->

{/literal}

<div class="row-fluid">
	<div class="span12 tac">
		<ul class="ov_boxes">
			<li>
				<div class="p_bar_up p_canvas"><img src="/BO/theme/gebo/img/gCons/agent.png" alt="" /></div>
				<div class="ov_text">
					<strong>{$totalActiveClients}</strong>
					Clients
				</div>
			</li>
			<li>
				<div class="p_bar_down p_canvas"><img src="/BO/theme/gebo/img/gCons/agent.png" alt="" /></div>
				<div class="ov_text">
					<strong>{$totalActiveWriters}</strong>
					Contributors
				</div>
			</li>
			<li>
				<div class="p_line_up p_canvas"><img src="/BO/theme/gebo/img/gCons/addressbook.png" alt="" /></div>
				<div class="ov_text">
					<strong>{$TotalDeliveries}</strong>
					Deliveries
				</div>
			</li>
			<li>
				<div class="p_line_down p_canvas"><img src="/BO/theme/gebo/img/gCons/copy-item.png" alt="" /></div>
				<div class="ov_text">
					<strong>{$TotalArticles}</strong>
					Articles
				</div>
			</li>
		</ul>
	</div>
</div>

								
                    
<div class="row-fluid">
	<div class="span12">
		<ul class="dshb_icoNav tac">
			<li><a href="/user/users-list?submenuId=ML3-SL6" style="background-image: url(/BO/theme/gebo/img/gCons/multi-agents.png)">Users</a></li>
			<li><a href="/ao/ao-create1?submenuId=ML2-SL3" style="background-image: url(/BO/theme/gebo/img/gCons/edit.png)">Create AO</a></li>
			<!--<li><a href="javascript:void(0)" style="background-image: url(img/gCons/world.png)">Map</a></li>-->
			
			<!--<li><a href="javascript:void(0)" style="background-image: url(img/gCons/lab.png)">Lab</a>-->
			<li><a href="/processao/newaos-list?submenuId=ML2-SL1" style="background-image: url(/BO/theme/gebo/img/gCons/add-item.png)">{if $TotalNewAO} <span class="label label-info">+{$TotalNewAO}</span>{/if}New Deliveries</a></li>
			<li><a href="/processao/profiles-list?submenuId=ML2-SL2" style="background-image: url(/BO/theme/gebo/img/gCons/ID.png)">S&eacute;lection de profils</a></li>
		    <li><a href="/user/users-list?submenuId=ML3-SL6&tab=permissionstab" style="background-image: url(/BO/theme/gebo/img/gCons/configuration.png)">Permissions</a></li>
			
			<!--<li><a href="javascript:void(0)" style="background-image: url(img/gCons/add-item.png)"> Add New Page</a></li>-->
			<li><a href="/ao/configuration?submenuId=ML2-SL13" style="background-image: url(/BO/theme/gebo/img/gCons/processing-02.png)">Configuration</a></li>
		</ul>
	</div>
</div>			
	