<!DOCTYPE html>
<html lang="en" class="error_page">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>No Access</title>
    <!-- Bootstrap framework -->
    <link rel="stylesheet" href="bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" href="bootstrap/css/bootstrap-responsive.min.css" />
    <!-- main styles -->
    <link rel="stylesheet" href="css/style.css" />

    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Jockey+One" />

</head>
<body>

<div class="error_box">
    <h1>No permission</h1>
    <p>You are not permitted to access this page. Please contact site admin.</p>
    <a href="javascript:history.back()" class="back_link btn btn-small">Go back</a>
</div>

</body>
</html>