<script src="/BO/theme/gebo/lib/tinymce_4.2.5/js/tinymce/tinymce.min.js"></script>

<div class="row-fluid">
  <div class="span12" >
      <div class="tabbable">
          <div class="tab-content">
             <form method="POST" action="/template/jobs?submenuId=ML4-SL10" >
				  <div class="alert alert-warning" align="center"><b>ADD JOBS</b></div>
					<div id="" class="accordion">
							<div class="formSep">
								<div class="row-fluid">
									<div class="span9 form-inline">
									  <label class="span3">Job Title</label>
									  <input type="text" name="job_title" id="job_title" value="{$jobdetail[0].title}" placeholder="Job Title" class="span8 validate[required]"/>
									</div>
								</div>
							</div>
							
							<div class="formSep">
								<div class="row-fluid">
									<div class="span9 form-inline">
									  <label class="span3">Status</label>
									  <select name="status" id="status">
										<option value="active" {if $editteam[0].status=="active"}selected{/if}>Active</option>
										<option value="inactive" {if $editteam[0].status=="inactive"}selected{/if}>Inactive</option>
									</select>
									</div>
								</div>
							</div>
							
							<div class="formSep">
								<div class="row-fluid">
									<div class="span9 form-inline">
										<label class="span3">Summary</label><br/><br/>
										<textarea name="summary" id="summary" class="span3 auto_expand">{$jobdetail[0].summary}</textarea>
									 </div>
								</div>
							</div>
							
						<!----------------------------------------- About company------------------------------------------->
						<div class="accordion-group">
                            <div class="accordion-heading">
                                <a href="#aboutep_form" data-parent="#contrib_edit_forms" data-toggle="collapse" class="accordion-toggle">
                                    ABOUT EDIT-PLACE
                                </a>
                            </div>
							
                            <div class="accordion-body in collapse" id="aboutep_form">
                                <div class="accordion-inner">
                                        <div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
												  <input type="text" name="aboutep_title" id="aboutep_title" value="{$jobdetail[0].aboutep_title}" placeholder="Title" class="span8 validate[required]"/>
												 </div>
                                            </div>
                                        </div>
										<div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
													<textarea name="aboutep_desc" id="aboutep_desc" class="span6 auto_expand" style="float:right">{$jobdetail[0].aboutep_desc}</textarea>
												 </div>
                                            </div>
                                        </div>
								</div>
                            </div>
                        </div>
						
						<!----------------------------------------- Mission ------------------------------------------->
						<div class="accordion-group">
                            <div class="accordion-heading">
                                <a href="#mission_form" data-parent="#contrib_edit_forms" data-toggle="collapse" class="accordion-toggle">
                                    MISSION
                                </a>
                            </div>
							
                            <div class="accordion-body in collapse" id="mission_form">
                                <div class="accordion-inner">
                                        <div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
												  <input type="text" name="mission_title" id="mission_title" value="{$jobdetail[0].mission_title}" placeholder="Title" class="span8 validate[required]"/>
												 </div>
                                            </div>
                                        </div>
										<div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
													<textarea name="mission_desc" id="mission_desc" class="span6 auto_expand" style="float:right">{$jobdetail[0].mission_desc}</textarea>
												 </div>
                                            </div>
                                        </div>
								</div>
                            </div>
                        </div>
						
						<!----------------------------------------- The team------------------------------------------->
						<div class="accordion-group">
                            <div class="accordion-heading">
                                <a href="#team_form" data-parent="#contrib_edit_forms" data-toggle="collapse" class="accordion-toggle">
                                    THE TEAM
                                </a>
                            </div>
							
                            <div class="accordion-body in collapse" id="team_form">
                                <div class="accordion-inner">
                                        <div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
												  <input type="text" name="team_title" id="team_title" value="{$jobdetail[0].team_title}" placeholder="Title" class="span8 "/>
												 </div>
                                            </div>
                                        </div>
										<div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
													<textarea name="team_desc" id="team_desc" class="span6 auto_expand">{$jobdetail[0].team_desc}</textarea>
												 </div>
                                            </div>
                                        </div>
								</div>
                            </div>
                        </div>
						
						<!----------------------------------------- What will i do ?------------------------------------------->
						<div class="accordion-group">
                            <div class="accordion-heading">
                                <a href="#willdo_form" data-parent="#contrib_edit_forms" data-toggle="collapse" class="accordion-toggle">
                                    WHAT WILL I DO?
                                </a>
                            </div>
							
                            <div class="accordion-body in collapse" id="willdo_form">
                                <div class="accordion-inner">
                                        <div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
												  <input type="text" name="willdo_title" id="willdo_title" value="{$jobdetail[0].willdo_title}" placeholder="Title" class="span8"/>
												 </div>
                                            </div>
                                        </div>
										<div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
													<textarea name="willdo_desc" id="willdo_desc" class="span6 auto_expand">{$jobdetail[0].willdo_desc}</textarea>
												 </div>
                                            </div>
                                        </div>
								</div>
                            </div>
                        </div>
						
						<!----------------------------------------- Will not do ------------------------------------------->
						<div class="accordion-group">
                            <div class="accordion-heading">
                                <a href="#willnotdo_form" data-parent="#contrib_edit_forms" data-toggle="collapse" class="accordion-toggle">
                                    YOU WILL NOT DO THE FOLLOWING
                                </a>
                            </div>
							
                            <div class="accordion-body in collapse" id="willnotdo_form">
                                <div class="accordion-inner">
                                        <div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
												  <input type="text" name="willnotdo_title" id="willnotdo_title" value="{$jobdetail[0].willnotdo_title}" placeholder="Title" class="span8"/>
												 </div>
                                            </div>
                                        </div>
										<div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
													<textarea name="willnotdo_desc" id="willnotdo_desc" class="span6 auto_expand">{$jobdetail[0].willnotdo_desc}</textarea>
												 </div>
                                            </div>
                                        </div>
								</div>
                            </div>
                        </div>
						
						<!----------------------------------------- Profile ------------------------------------------->
						<div class="accordion-group">
                            <div class="accordion-heading">
                                <a href="#profile_form" data-parent="#contrib_edit_forms" data-toggle="collapse" class="accordion-toggle">
                                    PROFILE
                                </a>
                            </div>
							
                            <div class="accordion-body in collapse" id="profile_form">
                                <div class="accordion-inner">
                                        <div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
												  <input type="text" name="profile_title" id="profile_title" value="{$jobdetail[0].profile_title}" placeholder="Title" class="span8"/>
												 </div>
                                            </div>
                                        </div>
										<div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
													<textarea name="profile_desc" id="profile_desc" class="span6 auto_expand">{$jobdetail[0].profile_desc}</textarea>
												 </div>
                                            </div>
                                        </div>
								</div>
                            </div>
					    </div>  
					</div>
					
					<!----------------------------------------- Skills ------------------------------------------->
						<div class="accordion-group">
                            <div class="accordion-heading">
                                <a href="#skills_form" data-parent="#contrib_edit_forms" data-toggle="collapse" class="accordion-toggle">
                                    SKILLS
                                </a>
                            </div>
							
                            <div class="accordion-body in collapse" id="skills_form">
                                <div class="accordion-inner">
                                        <div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
												  <input type="text" name="skills_title" id="skills_title" value="{$jobdetail[0].skills_title}" placeholder="Title" class="span8"/>
												 </div>
                                            </div>
                                        </div>
										<div class="formSep">
                                            <div class="row-fluid">
                                                <div class="span8 form-inline">
													<textarea name="skills_desc" id="skills_desc" class="span6 auto_expand">{$jobdetail[0].skills_desc}</textarea>
												 </div>
                                            </div>
                                        </div>
								</div>
                            </div>
					    </div>  
					</div>
					</div>
					
					<input type="hidden" name="jobid" id="jobid" value="{$jobdetail[0].id}" />
					<input type="submit" name="submit_add" value="Save" id="submit_add"  class="btn btn-info pull-right gap" />
			</form>
		</div>
      </div>
  </div>
</div>   

{literal}
<script type="text/javascript"> 
	$(document).ready(function() {
        $("#status").chosen({ allow_single_deselect: false,search_contains: true  });

	
	tinymce.init({
			selector: "textarea",
			theme: "modern",
			plugins: [
				 "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
				 "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
				 "save table contextmenu directionality emoticons template paste textcolor"
		   ],
		   content_css: "css/content.css",
		   toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | l      ink image | print preview media fullpage | forecolor backcolor emoticons", 
		   style_formats: [
				{title: 'Bold text', inline: 'b'},
				{title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
				{title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
				{title: 'Example 1', inline: 'span', classes: 'example1'},
				{title: 'Example 2', inline: 'span', classes: 'example2'},
				{title: 'Table styles'},
				{title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
			]
		 }); 
		 });
</script>				
{/literal}  