<link rel="stylesheet" href="/BO/theme/gebo/js/validation-engine/validationEngine.jquery.css" type="text/css"/>
<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine-fr.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>
{literal}
<script type="text/javascript" >
	$(document).ready(function() {
		$("#templatetype").chosen({disable_search:true});
		$("#type").chosen({disable_search:true});
		$("#active").chosen({disable_search:true});
		
		$("#templateform").validationEngine({prettySelect : true,useSuffix: "_chzn"});

	});
	
	
</script>
<style>
	input,textarea {text-transform:none;}
</style>
{/literal}

<form  action="/template/savevalidationtemplate?submenuId=ML4-SL6" method="post" id="templateform" name="templateform">	
	<table cellpadding="4" cellspacing="4" align="center">
		<tr><td>&nbsp;</td></tr>
		<tr>
			<td>Template Type</td>
			<td><span>
				<select name="templatetype" id="templatetype" data-placeholder="Select" class="validate[required]">
					 <option value=""></option>
					<option value="redaction"{if $valTempDetails[0].templatetype eq 'redaction'} selected {/if}>R&eacute;daction</option>
					<option value="translation"{if $valTempDetails[0].templatetype eq 'translation'} selected{/if}>Traduction</option>
				</select></span>
			</td>
		</tr>
		<tr>
			<td>Type</td>
			<td><span>
				<select name="type" id="type" data-placeholder="Select" class="validate[required]" >
					 <option value=""></option>
					<option value="refuse"{if $valTempDetails[0].type eq 'refuse'} selected{/if}>Refus</option>
					<option value="information"{if $valTempDetails[0].type eq 'information'} selected {/if}>Information</option>
				</select></span>
			</td>
		</tr>
		<tr>
			<td>Titre</td>
			<td><span><input type="text" id="title" name="title" value="{$valTempDetails[0].title|utf8_encode}" class="span4 validate[required]"/></span></td>
		</tr>
		<tr>
			<td valign="top">Texte</td>
			<td><textarea id="content" name="content" value="" class="span4" rows="8">{$valTempDetails[0].content|utf8_encode}</textarea></td>
		</tr>	
		<tr>
			<td>Statut</td>
			<td>
				<select name="active" id="active">
					<option value="yes"{if $valTempDetails[0].active eq 'yes'} selected=selected {/if}>Actif</option>
					<option value="no"{if $valTempDetails[0].active eq 'no'} selected=selected {/if}>Inactif</option>
                </select>  
			</td>
		</tr>
		<tr>
			<td></td>
			<td>	
				<input type="hidden" id="templateid" name="templateid" value="{$valTempDetails[0].identifier}">
				<input type="submit" id="template_submit" name="template_submit" value="Ajouter" class="btn btn-info"/>
				<input type="button" id="close_pop" name="close_pop" value="Fermer" class="btn btn-info" data-dismiss="modal" />
			</td>
		</tr>
	</table>		
</form>

