{literal}
<script type="text/javascript" >
	$(document).ready(function() {
		$('#template_writing').dataTable({
				"sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
				"bPaginate": false,
				"aaSorting": [[ 0, "asc" ]],
				"aoColumns": [
					{ "sType": "formatted-num" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" }
				]
		});
		
		$('#template_translation').dataTable({
				"sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
				"bPaginate": false,
				"aaSorting": [[ 0, "asc" ]],
				"aoColumns": [
					{ "sType": "formatted-num" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" },
					{ "sType": "string" }
				]
		});
	} );

    function getTemplateDetails(valtempId)
    {
        if(valtempId != 'new')
        {
            var target_page = "/template/addvalidationtemplate?valtempId="+valtempId;
            $.post(target_page, function(data){ 
               $("#edittemplatecontent").html(data);
               $("#template_submit").val('Mettre à jour');    
            });
        }
        else
        {
            var target_page = "/template/addvalidationtemplate?valtempId="+valtempId;
            $.post(target_page, function(data){ 
				$("#edittemplatecontent").html(data);
				$("#template_submit").val('Ajouter');
            });
        }
    } 
	
	function defaultchecked(tempId)
	{
		var checkedval=$("input[name='selected_"+tempId+"']:checked").val();
		if(checkedval=="yes")
			checked="yes";
		else
			checked="no";
			
		$.ajax({
			type: 'GET',
			url: '/template/defaultchecktemplate',
			data: 'templateid=' + tempId+'&checked='+checked,
			success: function(data)
			{ 
				smoke.alert("Updated Successfully !!");
			}
		});
	}
</script>
{/literal}


<div class="row-fluid">
	<div class="span12">
		<h3 class="heading">Templates</h3>
	    <div align="right" style="padding:10px;">
			<!--<a href="javascript:void(0);" data-toggle="modal" data-target="#edittemplate" class="btn btn-info" onclick="return getTemplateDetails('new');">
				Nouveau template
			</a>-->
		</div>
		
		<div class="span6" style="margin-left:2px">
			<h4>Crit&egrave;res pour la r&eacute;daction</h4><br/>
			<table class="table table-bordered table-striped table_vam" id="template_writing" >
				<thead>
					<tr>
						<th>ID N&deg;</th>
						<th>Titre du mail de refus</th>
						<th>PR&Eacute;SELECTION</th>
						<th>Status</th>
						<th>ACTIONS</th>
					</tr>
				</thead>
				<tbody>
					{foreach from=$writingtemplates item=writing_item name=writing_loop}
					  <tr>
						   <td>{$smarty.foreach.writing_loop.index+1}</td>
						   <td style="text-align:left">{$writing_item.title|stripslashes}</td>
						   <td>
								<input type="checkbox" name="selected_{$writing_item.identifier}" id="selected_{$writing_item.identifier}" value="yes" {if $writing_item.selected == 'yes'}checked{/if} {if $writing_item.active == 'no'}disabled{/if} onClick="defaultchecked('{$writing_item.identifier}');"/>
						   </td>
						   <td>{if $writing_item.active == 'yes'}Active{else}Inactive{/if}</td>
						   <td>
								<a href="javascript:void(0);" data-toggle="modal" data-target="#edittemplate" onclick="return getTemplateDetails({$writing_item.identifier});">
									<i class="splashy-application_windows_edit"></i>
								</a>
						   </td>
					  </tr>
					{/foreach}
				</tbody>
			</table>
		</div>
		
		<div class="span6" style="float:right;margin-left:5px">
			<h4>Crit&egrave;res pour la traduction</h4><br/>
			<table class="table table-bordered table-striped table_vam" id="template_translation" >
				<thead>
					<tr>
						<th>ID N&deg;</th>
						<th>Titre du mail de refus</th>
						<th>PR&Eacute;SELECTION</th>
						<th>Status</th>
						<th>ACTIONS</th>
					</tr>
				</thead>
				<tbody>
					{foreach from=$translationtemplates item=translation_item name=translation_loop}
					  <tr>
						   <td>{$smarty.foreach.translation_loop.index+1}</td>
						   <td style="text-align:left">{$translation_item.title|stripslashes}</td>
						   <td>
								<input type="checkbox" name="selected_{$translation_item.identifier}" id="selected_{$translation_item.identifier}"  value="yes" {if $translation_item.selected == 'yes'}checked{/if} {if $translation_item.active == 'no'}disabled{/if} onClick="defaultchecked('{$translation_item.identifier}');"/>
						   </td>
						   <td>{if $translation_item.active == 'yes'}Active{else}Inactive{/if}</td>
						   <td>
								<a href="javascript:void(0);" data-toggle="modal" data-target="#edittemplate" onclick="return getTemplateDetails({$translation_item.identifier});">
									<i class="splashy-application_windows_edit"></i>
								</a>
						   </td>
					  </tr>
					{/foreach}
				</tbody>
			</table>
		</div>
	</div>
</div>	

	<!--Add/Edit template-->
	<div class="modal hide fade" id="edittemplate" style="width:710px !important">
		<div class="modal-header">
			<button class="close" data-dismiss="modal">&times;</button>
			<h3>Validation templates</h3>
		</div>
		<div class="modal-body" id="edittemplatecontent" style="max-height:500px !important">
		</div>
		<div class="modal-footer">
		</div>
	</div>