{literal}
<script type="text/javascript">
    $.extend({
        password: function (length, special) {
            var iteration = 0;
            var password = "";
            var randomNumber;
            if(special == undefined){
                var special = false;
            }
            while(iteration < length){
                randomNumber = (Math.floor((Math.random() * 100)) % 94) + 33;
                if(!special){
                    if ((randomNumber >=33) && (randomNumber <=47)) { continue; }
                    if ((randomNumber >=58) && (randomNumber <=64)) { continue; }
                    if ((randomNumber >=91) && (randomNumber <=96)) { continue; }
                    if ((randomNumber >=123) && (randomNumber <=126)) { continue; }
                }
                iteration++;
                password += String.fromCharCode(randomNumber);
            }
            return password;
        }
    });
$(document).ready(function() {
    $('#generate').click(function(e){
        var password = $.password(8,false);
        $('#password').val(password);
        e.preventDefault();

    });
    $("#newusertab").addClass('active');
    $(".uni_style").uniform();
    gebo_validation.reg();

});


function checkEmailExist()
{
    var email = $("#email").val();
    var target_page = "/ftv/email-exits?email="+email;
    $.post(target_page, function(data){ alert(data);
        var data1 = data.trim();
        if(data1 == "yes")
        {
            smoke.alert("email id is already exist");
            $("#emai").val('');
            return false;
        }
        else
        {
            return true;
        }
    });
}
//* validation
gebo_validation = {
    reg: function() {
        reg_validator = $('.form_validation_reg').validate({
            onkeyup: false,
            errorClass: 'error',
            validClass: 'valid',
            highlight: function(element) {
                $(element).closest('div').addClass("f_error");
            },
            unhighlight: function(element) {
                $(element).closest('div').removeClass("f_error");
            },
            errorPlacement: function(error, element) {
                if(element.attr("id") == 'accessto') {
                    $("#contains_err").html(error);
                    $('.error').css("font-size", "10px");
                    $('.error').css("padding-top", "5px");
                    $('.error').css("font-weight", "bold");
                    $('.error').css("color", "#C62626");
                }
                else{
                    $(element).closest('div').append(error);
                }
               // $(element).closest('div').append(error);
                $('.error').css("font-size", "10px");
                $('.error').css("padding-top", "5px");
            },
            rules: {
                first_name: { required: true, minlength: 3 },
                last_name: { required: true, minlength: 2 },
                login: { required: true, minlength: 2 },
                password: { required: true, minlength: 2 },
                phone_number: { required: true },
                address2: { required: true, minlength: 5 },
                country: { required: true, minlength: 2 },
                email: { required: true, minlength: 3 },
                "accessto[]":"required",
                type: { valueNotEquals: "default" } ,
                status: { valueNotEquals: "default" }
            },
            /*submitHandler: function(form) {
                if(!$('#accessto_edito').attr('checked') || !$('#accessto_chaine').attr('checked'))
                {
                    smoke.alert('please define Access');
                }
            },*/

            invalidHandler: function(form, validator) {
                $.sticky("There are some errors. Please correct them and submit again.", {autoclose : 5000, position: "top-center", type: "st-error" });
            }
        })
    }
};

</script>
{/literal}
<h3 class="heading">{if $smarty.get.contactId eq ''} Cr&eacute;ation d'un nouveau {else} Edit {/if} Ftv Contact</h3>
<div class="row-fluid">
  <div class="span12" >
      <form class="form_validation_reg" {if $smarty.get.submenuId eq 'ML11-SL5' || $smarty.get.submenuId eq 'ML11-SL4'} action="/ftvchaine/ftvch-contact-creation?submenuId={$submenuId}" {else} action="/ftv/ftv-contact-creation?submenuId={$submenuId}" {/if}  style="padding-left: 50px;" method="post" id="user" name="user" enctype="multipart/form-data">
          <div class="formSep">
              <div class="row-fluid">
                  <div class="span8 form-inline">
                      <label class="span4">Email <span class="f_req">*</span></label>
                      <input type="text" name="email" id="email" value="{if $smarty.get.contactId neq ''}{$contactdetails[0].email_id}{/if}" />
                  </div>
              </div>
          </div>
          <div class="formSep">
              <div class="row-fluid">
                  <div class="span8 form-inline">
                      <label class="span4">Password<span class="f_req">*</span></label>
                      <span><input type="text" name="password" id="password" value="{if $smarty.get.contactId neq ''}{$contactdetails[0].password}{/if}"/></span>
                      <a  class="btn form-inline" id="generate">G&eacute;n&eacute;rer mot de passe</a>
                  </div>
              </div>
          </div>
          <div class="formSep">
              <div class="row-fluid">
                  <div class="span8 form-inline">
                      <label class="span4">First name <span class="f_req">*</span></label>
                      <input type="text" name="first_name" id="first_name" value="{if $smarty.get.contactId neq ''}{$contactdetails[0].first_name}{/if}" />
                  </div>
              </div>
          </div>
          <div class="formSep">
              <div class="row-fluid">
                  <div class="span8 form-inline">
                      <label class="span4">Last name <span class="f_req">*</span></label>
                      <input type="text" name="last_name" id="last_name" value="{if $smarty.get.contactId neq ''}{$contactdetails[0].last_name}{/if}" />
                  </div>
              </div>
          </div>
          <div class="formSep">
              <div class="row-fluid">
                  <div class="span8 form-inline">
                      <label class="span4">Access to<span class="f_req">*</span></label>
                      <label class="uni-checkbox">
                          Edito<input type="checkbox" name="accessto[]" id="accessto" class="uni_style" value="edito" {if $contactdetails[0].ftvtype eq 'edito' || $contactdetails[0].ftvtype eq 'both'} checked {/if} />
                      </label>
                      <label class="uni-checkbox">
                          Chaine<input type="checkbox" name="accessto[]" id="accessto" class="uni_style" value="chaine" {if $contactdetails[0].ftvtype eq 'chaine' || $contactdetails[0].ftvtype eq 'both'}checked{/if} />
                      </label>
                      <div id="contains_err" ></div>
                  </div>
              </div>
          </div>

      <div class="formSep">
              <div class="row-fluid">
                  <div class="span5 form-inline">
                      {if $smarty.get.contactId neq ''}
<!--   <a href="/ftv/ftv-contact-creation?submenuId={$submenuId}&contactId={$smarty.get.contactId}&edit=yes" name="useredit"  class="btn btn-success pull-right" >Udate Contact</a> -->
                         <input type="hidden" name="contactId" id="contactId" value="{$smarty.get.contactId}" />
                         <input type="hidden" name="edit" id="edit" value="yes" />
                        <button type="submit" name="usersubmit"  class="btn btn-success pull-right" >Update Contact</button>
                      {else}
                         <button type="submit" name="usersubmit"  class="btn btn-success pull-right" >Create New Contact</button>
                      {/if}
                  </div>
              </div>
          </div>
      </form>
  </div>
</div>

<div style="visibility:hidden" >
    <form id="user_login_form" name="user_login_form" method="post" action="" target="_blank">
        <input type="text" id="login_name" name="login_name" value="">
        <input type="password" id="login_password" name="login_password" value="{$user_detail[0].password}" >
        <input type="submit" value="Login" />
    </form>
</div>

{literal}
<script type="text/javascript" >
    function connect_fo(user,email,pwd)
    {
        document.forms["user_login_form"].action="http://mmm-new.edit-place.com/index/userfologin";
        $('#login_name').val(email);
        $('#login_password').val(pwd);
        document.forms["user_login_form"].submit();
    }
</script>
{/literal}


