{literal}
<link rel="stylesheet" href="/BO/theme/gebo/css/jquery.multiselect.filter.css" type="text/css"/>
<link rel="stylesheet" href="/BO/theme/gebo/css/jquery.multiselect.css" type="text/css"/>
<script src="/BO/theme/gebo/js/jquery.multiselect.filter.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/gebo/js/jquery.multiselect.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript" >
    function getUrlVars()
    {
        var vars = [], hash;

        var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
        for(var i = 0; i < hashes.length; i++)
        {
            hash = hashes[i].split('=');
            vars.push(hash[0]);
            vars[hash[0]] = hash[1];
        }
        return vars;
    }

    function getArrayUrl()
    {
        // our test url
        var url =$(location).attr('href');
        // filtering the string..
        var paramsList = url.slice(url.indexOf("?")+1,url.length) ;    //alert(paramsList);
        ///return paramsList;
        var filteredList =  paramsList.split("&") ;
        // an object to store arrays
        var objArr = {} ;

        // the below loop is obvious... we just remove the [] and +.. and split into pair of key and value.. and store as an array...
        for (var i=0, l=filteredList.length; i <l; i +=1 ) {
            // alert(filteredList[i]);
            var param = decodeURIComponent(filteredList[i].replace("[]","")).replace(/\+/g," ") ;       //alert(param);
            var pair = param.split("=") ;
            if(!objArr[pair[0]]) {  objArr[pair[0]] = [] ;}
            objArr[pair[0]].push(pair[1]);

        }
        return  objArr;

    }


    var ctype = getUrlVars()["counttype"];
    var count = getUrlVars()["count"];
    $(function() {
        $('#dp_start').datepicker({
            language : 'fr'
        }).on('changeDate', function(ev) {
            var dateText = $(this).val();
            //data('date');

            var endDateTextBox = $('#dp_end');
            if (endDateTextBox.val() != '') {
                var testStartDate = new Date(dateText);
                var testEndDate = new Date(endDateTextBox.val());
                if (testStartDate > testEndDate) {
                    endDateTextBox.val(dateText);
                }
            } else {
                endDateTextBox.val(dateText);
            };
            $('#dp_end').datepicker('setStartDate', dateText);
            $('#dp_start').datepicker('hide');
        });
        $('#dp_end').datepicker({
            language : 'fr'
        }).on('changeDate', function(ev) {
            var dateText = $(this).val();
            //data('date');
            var startDateTextBox = $('#dp_start');
            if (startDateTextBox.val() != '') {
                var testStartDate = new Date(startDateTextBox.val());
                var testEndDate = new Date(dateText);
                if (testStartDate > testEndDate) {
                    startDateTextBox.val(dateText);
                }
            } else {
                startDateTextBox.val(dateText);
            };
            $('#dp_start').datepicker('setEndDate', dateText);
            $('#dp_end').datepicker('hide');
        });
    });
    $(document).ready(function() {

        $("#ong_search").click(function() {
            $("#search_block").toggle();
        });

        $("#sel_type").chosen({
            allow_single_deselect : true,
            search_contains : true
        });
        $("#contribname").chosen({
            allow_single_deselect : true,
            search_contains : true
        });
        $("#paid_type").chosen({
            allow_single_deselect : true,
            search_contains : true
        });
        /*
         $('#dp_start').datepicker({
         language : 'fr'
         }).on('changeDate', function(ev) {
         var dateText = $(this).val();
         //data('date');

         var endDateTextBox = $('#dp_end');
         if (endDateTextBox.val() != '') {
         var testStartDate = new Date(dateText);
         var testEndDate = new Date(endDateTextBox.val());
         if (testStartDate > testEndDate) {
         endDateTextBox.val(dateText);
         }
         } else {
         endDateTextBox.val(dateText);
         };
         $('#dp_end').datepicker('setStartDate', dateText);
         $('#dp_start').datepicker('hide');
         });
         $('#dp_end').datepicker({
         language : 'fr'
         }).on('changeDate', function(ev) {
         var dateText = $(this).val();
         //data('date');
         var startDateTextBox = $('#dp_start');
         if (startDateTextBox.val() != '') {
         var testStartDate = new Date(startDateTextBox.val());
         var testEndDate = new Date(dateText);
         if (testStartDate > testEndDate) {
         startDateTextBox.val(dateText);
         }
         } else {
         startDateTextBox.val(dateText);
         };
         $('#dp_start').datepicker('setEndDate', dateText);
         $('#dp_end').datepicker('hide');
         });
         */
        /////date picker for the date of paid invoices///
        $('#paiddp_start').datepicker({
            language : 'fr'
        }).on('changeDate', function(ev) {
            var dateText = $(this).val();
            //data('date');

            var endDateTextBox = $('#paiddp_end');
            if (endDateTextBox.val() != '') {
                var testStartDate = new Date(dateText);
                var testEndDate = new Date(endDateTextBox.val());
                if (testStartDate > testEndDate) {
                    endDateTextBox.val(dateText);
                }
            } else {
                endDateTextBox.val(dateText);
            };
            $('#paiddp_end').datepicker('setStartDate', dateText);
            $('#paiddp_start').datepicker('hide');
        });
        $('#paiddp_end').datepicker({
            language : 'fr'
        }).on('changeDate', function(ev) {
            var dateText = $(this).val();
            //data('date');
            var startDateTextBox = $('#paiddp_start');
            if (startDateTextBox.val() != '') {
                var testStartDate = new Date(startDateTextBox.val());
                var testEndDate = new Date(dateText);
                if (testStartDate > testEndDate) {
                    startDateTextBox.val(dateText);
                }
            } else {
                startDateTextBox.val(dateText);
            };
            $('#paiddp_start').datepicker('setEndDate', dateText);
            $('#paiddp_end').datepicker('hide');
        });

        $('#select_rows').click(function() {
            /*for (var i = 1; i <= {/literal}{$paginator|@count}{literal}; i++) {
             if($('#row_sel'+i).length)
             {
             if($('#select_rows').is(':checked')){
             if(! $('#row_sel'+i).is(':checked')){$('#row_sel'+i).click();}
             }
             else
             {
             if($('#row_sel'+i).is(':checked')){$('#row_sel'+i).click();}
             }
             }
             }*/
            //alert('#select_rows');

            if($("#select_rows").attr('checked'))
            {
                var $b = $('input[type=checkbox]');
                $b.attr('checked', true);
            }
            else
            {
                var $b = $('input[type=checkbox]');
                $b.attr('checked', false);
            }

            for (var i = 1; i <= {/literal}{$paginator|@count}{literal}; i++) {
                if($('#row_sel'+i).length)
                {
                    if($("#select_rows").attr('checked'))
                        $('#row_sel'+i).closest( "span" ).prop("class","uni-checked");
                    else
                        $('#row_sel'+i).closest( "span" ).prop("class","");
                }
            }
            calculateTotal();
        });
    });
    jQuery.fn.dataTableExt.oSort['payable-asc'] = function(a, b) {//alert('a='+a);alert('b='+b);
        a = a.replace('<span class="label label-inverse pull-right">', '');
        a = a.replace('</span>', '');
        a = replaceAll(a, ' ', '');
        a = a.replace(',', '.');
        a = a*1;
        b = b.replace('<span class="label label-inverse pull-right">', '');
        b = b.replace('</span>', '');
        b = replaceAll(b, ' ', '');
        b = b.replace(',', '.');
        b = b*1;
        var c = ((a < b) ? -1 : ((a > b) ? 1 : 0));
        return c;
    };
    jQuery.fn.dataTableExt.oSort['payable-desc'] = function(a, b) {//alert('a='+a);alert('b='+b);
        a = a.replace('<span class="label label-inverse pull-right">', '');
        a = a.replace('</span>', '');
        a = replaceAll(a, ' ', '');
        a = a.replace(',', '.');
        a = a*1;
        b = b.replace('<span class="label label-inverse pull-right">', '');
        b = b.replace('</span>', '');
        b = replaceAll(b, ' ', '');
        b = b.replace(',', '.');
        b = b*1;
        var c = ((a < b) ? 1 : ((a > b) ? -1 : 0));
        return c;
    };
    function clearAll()
    {
        $("#dp_start").val('');
        $("#dp_end").val('');
        $("#contribname").val('');
        $("#invoicename").val('');
        $("#sel_type").val('').trigger("liszt:updated");
        $("#paid_type").val('').trigger("liszt:updated");
        $("#contribname").val('').trigger("liszt:updated");
    }
    function replaceAll(string, token, newtoken) {
        if(token!=newtoken)
            while(string.indexOf(token) > -1) {
                string = string.replace(token, newtoken);
            }
        return string;
    }
    /* added by naseer on 15-10-2015*/
    function loadFtvContacts(val){
        console.log(val+ "initiated");
        var ajax_url = "/ftv/load-ftvcontacts?&type="+val;
        $.ajax({
            type: 'POST',
            url: ajax_url,
            success: function (data) {
                console.log(data);
                $("#contact_div").empty().append(data);
                $("#contactname").multiselect();
                $("#contactname").multiselectfilter();

            }
        });


    }
    function download_xlsx(){
        console.log("Download initiated");
        var url = window.location.href;
        var url = url.replace('ftv-timeline?','ftv-timeline-download-xlsx?download=yes&')
        window.location.href = url;

    }
</script>

<style>
    .label{font-size: 12px!important;}
</style>
{/literal}

<div class="row-fluid">
    <div class="span12">
        <h3 class="heading">FTV Time Extraction</h3>
        <div class=" well clearfix" id="search_block">
            <div class="row-fluid">
                <form action="/ftv/ftv-timeline?submenuId={$submenuId}" method="post" id="searchform" name="searchform" >
                    <input type="hidden" id="submenuId" name="submenuId"  value="ML5-SL3"/>


                    <div class="span12">
                        <table>
                            <tr>
                                <td><label>From Date :</label></td>
                                <td><label>To Date :</label></td>
                            </tr>
                            <tr>
                                <td>
                                    <span class="sepV_c" >
                                        <input type="text" placeholder="start date" id="dp_start" name="pdstart_date" readonly data-date-format="dd-mm-yyyy" value="{$smarty.post.pdstart_date}"/>
                                    </span>
                                </td>
                                <td>
                                    <span class="sepV_c">
                                        <input type="text"  placeholder="end date" id="dp_end" name="pdend_date" readonly data-date-format="dd-mm-yyyy" value="{$smarty.post.pdend_date}"/>
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <span class="sepV_c">
                                        <label>FTV type</label>
                                        <select name="sel_type" id="sel_type" data-placeholder="Select FTV type" onchange="loadFtvContacts(this.value);">
                                            <option value=""></option>
                                            <option value="edito" {if $smarty.post.sel_type eq 'Paypal'} selected{/if}>Edito</option>
                                            <option value="chaine" {if $smarty.post.sel_type eq 'PP'} selected{/if}>Chaine</option>
                                        </select>
                                    </span>
                                </td>
                                <td>
                                    <span class="sepV_c" style="display: none;">
                                        <label>Client Details</label>
                                        <!--<select name="clientname[]" id="clientname" multiple="multiple" style="width:250px;" Onchange="updatecontribtype();">
                                            {if $publish_langarray|@count>0}
                                                {foreach from=$Contrib_langs item=langitem key=langkey}
                                                    {if in_array($langkey,$publish_langarray)}
                                                        <option value="{$langkey}" selected>{$langitem}</option>
                                                    {else}
                                                        <option value="{$langkey}">{$langitem}</option>
                                                    {/if}
                                                {/foreach}
                                            {else}
                                                {foreach from=$Contrib_langs item=langitem key=langkey}
                                                <option value="{$langkey}" selected>{$langitem}</option>
                                                {/foreach}
                                            {/if}
                                        </select>-->
                                        <div id="contact_div">

                                        </div>
                                        <!--<select id="contactname" name="contactname[]"  multiple="multiple" data-placeholder="FTV Contact">

                                            {foreach from=$client_invoiced item=client key=clientkey}

                                            {if $clientkey==$smarty.post.clientname}

                                            <option value="{$clientkey}" selected>{$client}</option>

                                            {else}

                                            <option value="{$clientkey}">{$client}</option>

                                            {/if}

                                            {/foreach}
                                        </select>-->
                                    </span>
                                </td>
                            </tr>

                            <tr>
                                <td colspan="2">
                                    <button class="btn btn-danger pull-center" id="search" name="search" type="submit" value="search" >
                                        Search
                                    </button>

                                    <button class="btn btn-info pull-center" id="clear" name="clear" type="button" value="clear" onclick="clearAll();" >
                                        Clear
                                    </button>
                                </td>
                            </tr>
                        </table>


                    </div>

                </form>

            </div>
        </div>
        <div class="results">
            {if $nores}
                <h1> No Results Found in database </h1>
            {else}
                <table class="table table-striped table-bordered dTableR">
                    <tr style="background-color: #0063DC;">
                        <th>identifier</th>
                        <th>Request by</th>
                        <th>assigned_to</th>
                        <th>request_object</th>
                        <th>assigned_at</th>
                        <th>pause - resume</th>
                        <th>closed_at</th>
                        <th>cancelled_at</th>
                        <th>ftvtype</th>
                        <th>active</th>
                        <th>In hrs</th>
                    </tr>
                    {foreach from=$paginator key=paginator_key item=paginator_item name=paginator_loop}
                        <tr>
                            <td>{$paginator_item.identifier}</td>
                            <td>{$paginator_item.contactname}</td>
                            <td>{$paginator_item.assignedname}</td>
                            <td>{$paginator_item.request_object}</td>
                            <td>{$paginator_item.assigned_at}</td>
                            <td>{$paginator_item.mid_time}</td>
                            <td>{$paginator_item.closed_at}</td>
                            <td>{$paginator_item.cancelled_at}</td>
                            <td>{$paginator_item.ftvtype}</td>
                            <td>{$paginator_item.active}</td>
                            {if $paginator_item.finaltime == 'NOVALUE'}
                                <td style="background-color: #ff0000;">{$paginator_item.finaltime}</td>
                            {else}
                                <td>{$paginator_item.finaltime}</td>
                            {/if}
                        </tr>
                    {/foreach}
                </table>
            <div>
                <table width="100%" >
                    <tr>
                        <th align="left"><button type="button" class="btn btn-success" onclick="download_xlsx();">Download XLSX</button></th>
                        <th align="right">Total Time : {$total_time}</th>
                    </tr>
                </table>
            </div>
            {/if}<!--nores-->
        </div><!-- .result -->
    </div>
</div>

<div class="modal4 hide fade" id="artprofile">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">
            &times;
        </button>
        <h3>Article Profiles</h3>
    </div>
    <div class="modal-body"></div>
    <div class="modal-footer"></div>
</div>

