{literal}

<script type="text/javascript">
$(document).ready(function() {
   // $(".uni_style").uniform();
    $('#contactgrid').dataTable({
        "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
        "sPaginationType": "bootstrap",
        "aaSorting": [[ 0, "asc" ]],
        "aoColumns": [
            { "sType": "formatted-num" },
            { "sType": "string" },
            { "sType": "string" },
            { "sType": "string" },
            { "sType": "natural" },
            { "sType": "natural" }
        ]
    });
    /*$('#contactgrid').dataTable({
        "sPaginationType": "bootstrap",
        "iDisplayLength" : 25,
        "sDom": "<'row'<'span4'l><'span4'T><'span4'f>r>t<'row'<'span6'i><'span6'p>>",
        "aoColumns": [
            { "sType": "formatted-num" },
            { "sType": "string" },
            { "sType": "string" },
            { "sType": "formatted-num" },
            { "sType": "string" }
        ],
        "aaSorting": [[ 0, "asc" ]],
        "oTableTools": {
            "aButtons": [
                "copy",
                "print",
                {
                    "sExtends":    "collection",
                    "sButtonText": 'Sauvegarder <span class="caret" />',
                    "aButtons":    [ "csv", "xls", "pdf" ]
                }
            ],
            "sSwfPath": "/BO/theme/gebo/lib/datatables/extras/TableTools/media/swf/copy_csv_xls_pdf.swf"
        }
    });*/

});
function checkEmailExist()
{
    var email = $("#email").val();
    var target_page = "/user/email-exits?email="+email;
    $.post(target_page, function(data){ //alert(data);
        var data1 = data.trim();
        if(data1 == "yes")
        {
            smoke.alert("email id is already exist");
            $("#emai").val('');
            return false;
        }
        else
        {

            return true;
        }
    });
}
</script>
{/literal}
<h3 class="heading">Ftv Contacts<a href="/ftv/ftv-contact-creation?submenuId=ML11-SL1" class="label label-inverse alignright">Cr&eacute;er un contact</a></h3>
<div class="row-fluid">
    <div class="span12">
      <!--///////////////////////////////////////////////////////////////////////////////////////////////////////////////////-->
      <table id="contactgrid" class="table table-bordered table-striped table_vam">
          <thead>
          <tr>
              <th>SL.NO</th>
              <th>Email</th>
              <th>Nom</th>
              <th>Access to</th>
              <th>cr&eacute;&eacute; le</th>
              <th>Actions</th>
          </tr>
          </thead>
          <tbody>
          {foreach from=$ftvcontactsdetails item=ftvcontact name=usergrid}
          <tr>
              <td>{$smarty.foreach.usergrid.index+1}</td>
              <td>{$ftvcontact.email_id}</td>
              <td>{$ftvcontact.first_name} {$ftvcontact.last_name}</td>
              <td>{$ftvcontact.ftvtype}</td>
              <td>{$ftvcontact.created_at|date_format:"%d/%m/%Y"}</td>
              <td><a  href="ftv-contact-creation?submenuId={$submenuId}&contactId={$ftvcontact.identifier}"  class="hint--left hint--info" data-hint="edit profile"><i class="icon-pencil"></i> </a></td>
          </tr>
          {/foreach}
          </tbody>
      </table>
  </div>
</div>

<div style="visibility:hidden" >
    <form id="user_login_form" name="user_login_form" method="post" action="" target="_blank">
        <input type="text" id="login_name" name="login_name" value="">
        <input type="password" id="login_password" name="login_password" value="{$user_detail[0].password}" >
        <input type="submit" value="Login" />
    </form>
</div>


{literal}
<script type="text/javascript" >
    function connect_fo(user,email,pwd)
    {
        document.forms["user_login_form"].action="http://mmm-new.edit-place.com/index/userfologin";
        $('#login_name').val(email);
        $('#login_password').val(pwd);
        document.forms["user_login_form"].submit();
    }
</script>
{/literal}


