{literal}
<script type="text/javascript" charset="utf-8" src="/BO/theme/gebo/js/datempicker.js"></script>
<script type="text/javascript" >
	$(document).ready(function() {
	    
        var tab = getParameterByName('tab', $(location).attr('href'));
        if(tab == '')
            $("#categorytab").addClass('active');
        else
            $("#"+tab).addClass('active');
            
        $('#cattarifftable').dataTable({
            "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            "sPaginationType": "bootstrap",
            "aaSorting": [[ 0, "asc" ]],
            "aoColumns": [
                { "sType": "formatted-num" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" }
            ]
        });
            
        $('#lantarifftable').dataTable({
            "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            "sPaginationType": "bootstrap",
            "aaSorting": [[ 0, "asc" ]],
            "aoColumns": [
                { "sType": "formatted-num" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" }
            ]
        });
	});
	function deletetariff(id)
	{
        smoke.confirm('Do you really want to delete this quote ?',function(e){
            if (e){
                window.location = "/tariff/delete-tariff?id="+id ;
            }else{
                return false;
            }
        }, {ok:"OUI", cancel:"NON"}) ;
        return false;
	}
</script>
{/literal}

<div class="row-fluid">
	<div class="span12">
    	<h3 class="heading">voir les citations<div style="display:inline;float:right"><button onclick="window.location='/tariff/add-tariff?submenuId=ML3-SL12'" class="btn btn-success" name="back">Add tariff</button></div></h3>
        {if $successMsg neq ''}<div class="alert alert-success"><b>{$successMsg}</b></div>{/if}
    	<div class="tabbable">
            <ul class="nav nav-tabs">
              <li {if $smarty.get.tab == 'categorytab' || $smarty.get.tab == ''} class="active" {/if}><a href="#categorytab" data-toggle="tab" class="lable-danger"><strong>Category tariffs</strong></a></li>
              <li {if $smarty.get.tab == 'languagetab'} class="active" {/if}><a href="#languagetab" data-toggle="tab" class="lable-info"><strong>Language tariffs</strong></a></li>
            </ul>
            <div class="tab-content">
                 <div id="categorytab" class="tab-pane" >
                    <table class="table table-bordered table-striped table_vam" id="cattarifftable" >
                        <thead>
                            <tr>
                               <th>S.NO</th>
                               <th>Cat&eacute;gorie</th>
                               <th>prix/mot (1 mois)</th>
                               <th>prix/mot (3 mois)</th>
                               <th>Intervalle de Urgence</th>
                               <th>urgence(%)</th>
                               <th>Modifier</th>
                            </tr>
                        </thead>
                        <tbody>
                        {if $tarrifflist_c|@count>0}
                            {foreach from=$tarrifflist_c item=tarriff_item name=tarriff_loop}
                                <tr id="tr{$tarriff_item.id}">
                                    <td>{$smarty.foreach.tarriff_loop.index+1}</td>
                                    <td>{$tarriff_item.category}</td>
                                    <td>{$tarriff_item.price_word_1_month}</td>
                                    <td>{$tarriff_item.price_word_3_month}</td>
                                    <td>{$tarriff_item.urgency_interval}</td>
                                    <td>{$tarriff_item.urgency_percent}</td>
                                    <td><a href="/tariff/edit-tariff?submenuId=ML3-SL12&id={$tarriff_item.id}" class="hint--left hint--info" data-hint="Edit Tariff"><img class="splashy-application_windows_edit"></a>&nbsp;<a href="/tariff/delete-tariff?submenuId=ML3-SL12&id={$tarriff_item.id}" class="hint--left hint--info" data-hint="Delete Tariff" onclick="return deletetariff({$tarriff_item.id});"><img class="splashy-application_windows_remove"></a></td>
                                </tr>
                            {/foreach}
                        {/if}
                        </tbody>
                    </table>
                </div>
                 <div id="languagetab" class="tab-pane" >
                    <table class="table table-bordered table-striped table_vam" id="lantarifftable" >
                        <thead>
                            <tr>
                               <th>S.NO</th>
                               <th>langue</th>
                               <th>prix/mot (1 mois)</th>
                               <th>prix/mot (3 mois)</th>
                               <th>Intervalle de Urgence</th>
                               <th>urgence(%)</th>
                               <th>Modifier</th>
                            </tr>
                        </thead>
                        <tbody>
                        {if $tarrifflist_l|@count>0}
                            {foreach from=$tarrifflist_l item=tarriff_item name=tarriff_loop}
                                <tr id="tr{$tarriff_item.id}">
                                    <td>{$smarty.foreach.tarriff_loop.index+1}</td>
                                    <td>{$tarriff_item.language}</td>
                                    <td>{$tarriff_item.price_word_1_month}</td>
                                    <td>{$tarriff_item.price_word_3_month}</td>
                                    <td>{$tarriff_item.urgency_interval}</td>
                                    <td>{$tarriff_item.urgency_percent}</td>
                                    <td><a href="/tariff/edit-tariff?submenuId=ML3-SL12&id={$tarriff_item.id}" class="hint--left hint--info" data-hint="Edit Tariff"><img class="splashy-application_windows_edit"></a>&nbsp;<a href="/tariff/delete-tariff?submenuId=ML3-SL12&id={$tarriff_item.id}" class="hint--left hint--info" data-hint="Delete Tariff" onclick="return deletetariff({$tarriff_item.id});"><img class="splashy-application_windows_remove"></a></td>
                                </tr>
                            {/foreach}
                        {/if}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>	


