{literal}
<script type="text/javascript">
$(document).ready(function() {
	$("#ep_users").chosen({ allow_single_deselect: true,search_contains: true });
	$(".assign_pop_over").popover({trigger: 'click'});
});	
//archieve ticket
	function archieveMsg(ticket_id){
	
		var msg = "Souhaitez-vous archiver ce message ?";
		smoke.confirm(msg,function(e){
			if (e){
					window.location.href = "/mastermails/classifymail?&ticket="+ticket_id;           
				}
			else{
				return false;
			}
		});
	
	}

	function fnassignTicket(ticket_id,ep_user_id)
	{				
		var msg = "Do you want to assign this ticket to some other user ?";
		smoke.confirm(msg,function(e){
			if (e){
					var target="/mastermails/assign-ticket?ticket_id="+ticket_id+"&ep_user_id="+ep_user_id;
					$.post(target,function(response){
						var obj = $.parseJSON(response);
						//alert(response);
						
						if(obj.status=='same_user')
						{
							smoke.alert("Please assign ticket to some other user it is currently assigned to same user");
						}
						else if(obj.status=='success')
						{
							location.reload(); 
						}
					});      
				}
			else{
				return false;
			}
		});	
	
	}
	
</script>
<style type="text/css">
#contentwrapper
{
	text-transform:none;
}
</style>
{/literal}
<div class="row-fluid">
	<div class="span12">
		<h3 class="heading">
			Syst&egrave;me de Messages :: Liste des messages re&ccedil;us
		</h3>
		{if $user_type eq 'superadmin' OR $loginName eq 'akeslassy' OR $loginName eq 'mfouris' OR $loginName eq 'julien'}
		<div  id="search_block">
			<form action={$smarty.server.REQUEST_URI} method="get" id="searchform" name="searchform" >				
				 <input type="hidden" id="submenuId" name="submenuId"  value="{$submenuId}"/>				  
				 <table id="searchtable" cellspacing="5" cellpadding="5">
					<tr>
						<td>S&eacute;lectionner EP :</td>
						<td>
							<select name="ep_user_id" id="ep_users" onChange="this.form.submit();"  data-placeholder="S&eacute;lectionner EP">
								<option value=''></option>
								{html_options  options=$EP_contacts  selected=$ep_user_id}	
							</select>
						</td>											
					</tr>
				</table>
			</form>
		</div>
		{/if}
		<div class="mbox">									
			<div class="tab-pane active" id="mbox_inbox">
				<table data-msg_rowlink="a" class="table table_vam mbox_table dTableR" id="dt_inbox">
					<thead>
						<tr>
							<th class="table_checkbox"><input type="checkbox" data-tableid="dt_inbox" class="select_msgs" name="select_msgs"></th>							
							<th><i class="splashy-mail_light"></i></th>
							<th>Objet</th>
							<th>Emetteur</th>
							<th>Destinataire</th>
							<th>Date</th>
							<th>Action</th>
						</tr>
					</thead>
					<tbody>
						{if $paginator|@count gt 0}
							{foreach from=$paginator key=MainMenu_key item=message name=MainMenu_loop}
								{if $message.status eq 0}
									<tr class="unread">
								{else}
									<tr>
								{/if}	
									<td class="nohref"><input type="checkbox" class="select_msg" name="msg_sel" value="{$message.messageId}"></td>									
									<td>{if $message.status eq 0}<i class="splashy-mail_light"></i>{else}<i class="splashy-mail_light_stuffed"></i>{/if}</td>
									<td><a href="/mastermails/view-mail/?submenuId={$submenuId}&mailaction=inboxview&page={$smarty.request.page}&message={$message.messageId}&ticket={$message.ticket_id}&recipientid={$message.recipientid}">{$message.Subject}</a></td>
									<td><span>{$message.sendername}</span></td>
									<td><span>{$message.recipient}</span></td>
									<td>{$message.receivedDate}</td>
									<td>
										
										<a class="hint--left  hint--info" data-hint="R&eacute;pondre" href="/mastermails/reply-mail?submenuId={$submenuId}&mailaction=reply&reply_message={$message.messageId}&ticket={$message.ticket_id}&recipientid={$message.recipientid}"><i class="icon-pencil"></i></a>
										<a class="hint--left  hint--warning" data-hint="View" href="/mastermails/view-mail/?submenuId={$submenuId}&mailaction=inboxview&page={$smarty.request.page}&message={$message.messageId}&ticket={$message.ticket_id}&recipientid={$message.recipientid}"><i class="icon-eye-open"></i></a>
										<a class="hint--left  hint" data-hint="Clore la discussion" onclick="archieveMsg('{$message.ticket_id}');"><i class="splashy-folder_classic_down" ></i></a>											
										{if $user_type eq 'superadmin' OR $loginName eq 'akeslassy' OR $loginName eq 'mfouris' OR $loginName eq 'julien'}								
											{if $message.receiverId eq $admin_user_id OR $message.assigned_before}
												<a class="btn btn-danger assign_pop_over" data-content='<select name="assign_{$message.ticket_id}" id="assign_ticket_{$message.ticket_id}" onChange="fnassignTicket({$message.ticket_id},this.value);">	
	{html_options  options=$assign_contacts  selected=$message.receiverId}	
</select>' data-html="true" data-original-title="Assign Ticket" data-placement="left">Assign</a>
											{/if}
										{/if}
										
									</td>
								</tr>
							
							{/foreach}
						{/if}
						
					</tbody>
				</table>    
			</div>					
		</div>
	</div>		
	</div>


<!-- hide elements -->
<div class="hide">
	<!-- actions for inbox -->
	<!--<div class="dt_inbox_actions">
		<div class="btn-group">
			<a href="javascript:void(0)" class="btn" title="Answer"><i class="icon-pencil"></i></a>
			<a href="javascript:void(0)" class="btn" title="Forward"><i class="icon-share-alt"></i></a>
			<a href="#" class="delete_msg btn" title="Delete" data-tableid="dt_inbox"><i class="icon-trash"></i></a>
		</div>
	</div>-->	
	<!-- confirmation box -->
	<div id="confirm_dialog">
		<div class="cbox_content">
			<div class="sepH_c tac"><strong>Are you sure you want to delete this message(s)?</strong></div>
			<div class="tac">
				<a href="#" class="btn btn-gebo confirm_yes">Yes</a>
				<a href="#" class="btn confirm_no">No</a>
			</div>
		</div>
	</div>
</div>
			
	