{literal}
<script type="text/javascript">
$(document).ready(function() {
	$("#ep_users").chosen({ allow_single_deselect: true,search_contains: true });
    $("#type").chosen({
        allow_single_deselect: true,
        search_contains : true
    });
    $("#language").chosen({
        allow_single_deselect: true,
        search_contains : true
    });
    $("#category").chosen({
        allow_single_deselect: false,
        search_contains : true
    });
    $("#wrtype").chosen();
    $("#crtype").chosen();
        /*jQuery("#wrtype").multiselect({noneSelectedText: "S&eacute;lectionner le statut du r&eacute;dacteur", height:100});
        jQuery("#wrtype").multiselectfilter();
        
        jQuery("#crtype").multiselect({noneSelectedText: "S&eacute;lectionner le statut du correcteur", height:70});
        jQuery("#crtype").multiselectfilter();*/
{/literal}
    {if $categ neq ''}
{literal}
    $('#targetdiv').show();
{/literal}
    {foreach from=$categ item=catitm key=catkey}
{literal}
        $("#{/literal}{$catkey}{literal}").slider({
            range: "min",
            value: 100,
            min: 1,
            max: 100,
            slide: function( event, ui ) {
                $( "#percentage_{/literal}{$catkey}{literal}").val( ui.value );
            }
        });
        $( "#percentage_{/literal}{$catkey}{literal}").val($("#{/literal}{$catkey}{literal}").slider( "value" ) );
{/literal}
    {/foreach}
{/if}   
{literal}
});	
//Archieve Message
	function archieveMsg(ticket_id){
	
		var msg = "Souhaitez-vous archiver ce message ?";
		smoke.confirm(msg,function(e){
			if (e){
					window.location.href = "/mastermails/masterclassifymail?&ticket="+ticket_id;
				}
			else{
				return false;
			}
		});
	
	}
	function showSearch()
    {
       $("#searchblock").toggle();
    }
    function srchtype(val)
    {
        if(val == 'client')
        {
            //$('#contribRow').addClass('sepV_c clientRow');
            $(".sepV_c.clientRow").css("display", "none");
        }
        else
        {
            //$('#contribRow').removeClass('clientRow');
            $(".sepV_c.clientRow").css("display", "block");
        }
    }
    //form clear
    function clearAll()
    {
        $("#type").val('');$("#ep_users").val('');$("#language").val('');
        $("#category").val('');$("#wrtype").val('');$("#crtype").val('');
        $("#type").val('0').trigger("liszt:updated");
        $("#ep_users").val('0').trigger("liszt:updated");
        $("#language").val('0').trigger("liszt:updated");
        $("#category").val('0').trigger("liszt:updated");
        $("#wrtype").val('0').trigger("liszt:updated");
        $("#crtype").val('0').trigger("liszt:updated");
        $(".sepV_c.clientRow").css("display", "none");
        $("#targetdiv").html('');
        $("#targetdiv").css("display", "none");
    }
    
///////////adding percentages values for categories
var selectedarray = [];
//* sliders
function categoryList()
{        // alert(mycategs);
    var count = $("#category :selected").length;
    if(count > 0)
    {
        var opts=$("#category :selected").text();
        var optsvalues=$("#category :selected").val();
       //alert(selectedarray); alert(optsvalues);   alert($.inArray(optsvalues, selectedarray));
        
        if(optsvalues.trim() != '')
        {
            $('#targetdiv').show();
            if(($.inArray(optsvalues, selectedarray) == -1 && $.inArray(opts, selectedarray) == -1))
            {
                var newdiv = '<div id=div_'+optsvalues+' style="float:left;width:225px;padding-right:35px;"><div>' + opts + '</div><div class="ui_slider span9" ondblclick="getIds(this.id);" id='+optsvalues+' ></div><input type="text" class="span3" style="position:relative;top:-15px;left:10px;" id=percentage_'+optsvalues+' name=categ['+optsvalues+']></input>' +
                        '<button  class="close" type="button" id=skill_close_'+optsvalues+' value='+optsvalues+'  >&times;</button></div>'
                $('#targetdiv').append(newdiv);
                $("#"+optsvalues).slider({
                    range: "min",
                    value: 1,
                    min: 1,
                    max: 100,
                    slide: function( event, ui ) {
                        $( "#percentage_"+optsvalues ).val( ui.value );
                    }
                });
                $( "#percentage_"+optsvalues ).val($( "#"+optsvalues ).slider( "value" ) );
    
            }
            selectedarray.push(opts);
            $('#targetdiv').show();
        }
    }
}
/**closing the  categories with sliders**/
$("[id^=skill_close_]").live('click', function(i) {
    var id = $(this).attr('value');
    selectedarray.splice($.inArray(id, selectedarray), 1);
    $("#div_"+id).remove();
    if ($.trim( $('#targetdiv').text() ).length === 0) {
        $('#targetdiv').hide();
    }
});
</script>
<style type="text/css">
#contentwrapper
{
	text-transform:none;
}
{/literal}{if $type neq 'contributor'}{literal}.clientRow{display:none;}{/literal}{/if}{literal}
</style>
{/literal}
<div class="row-fluid">
	<div class="span12">
		<h3 class="heading">
			Syst&egrave;me de Messages :: Liste des messages envoy&egrave;s
			<a href="#searchblock" onclick="showSearch();"  class="label label-inverse alignright">Search</a>
		</h3>
		
        <div class="well clearfix" id="searchblock">
          <form action={$smarty.server.REQUEST_URI} method="get" id="searchform" name="searchform">
             <input type="hidden" id="submenuId" name="submenuId"  value="{$submenuId}"/>
        {if $user_type eq 'superadmin'}
             <span class="sepV_c">
                 <select name="ep_user_id" id="ep_users" data-placeholder="S&eacute;lectionner sender">
                    <option value=""> </option>
                    {html_options  options=$EP_contacts selected=$sender}  
                 </select>
             </span>
        {else}
            <input type="hidden" name="ep_user_id" value="{$admin_user_id}">
        {/if}
             <span class="sepV_c">
                 <select name="type" id="type" data-placeholder="S&eacute;lectionner type" onchange="srchtype(this.value)">
                    <option value=""> </option>
                    <option value="client" {if $type eq 'client'}selected{/if}>client</option>
                    <option value="contributor" {if $type eq 'contributor'}selected{/if}>contributor</option>
                 </select>
             </span>
             <span class="sepV_c clientRow" id="contribRow">
                 <select name="wrtype[]" id="wrtype" multiple="multiple" style="width:300px;" data-placeholder="S&eacute;lectionner le statut du r&eacute;dacteur">
                    <option value="senior" {$wrtype1}>senior</option><option value="junior" {$wrtype2}>junior</option><option value="sub-junior" {$wrtype3}>sub-junior</option>
                 </select>
             </span>
             <span class="sepV_c clientRow" id="contribRow">
                 <select name="crtype[]" id="crtype" multiple="multiple" style="width:250px;" data-placeholder="S&eacute;lectionner le statut du correcteur">
                    <option value="senior" {$crtype1}>senior</option><option value="junior" {$crtype2}>junior</option>
                 </select>
             </span>
             <span class="sepV_c clientRow" id="contribRow">
                 <select name="language" id="language" class="chzn_a" data-placeholder="S&eacute;lectionner langue">
                    {foreach from=$ep_language_list item=langitm key=langkey}
                        <option value=""> </option>
                        <option value="{$langkey}" {if $langkey eq $language}selected{/if}>{$langitm}</option>
                    {/foreach}
                 </select>
             </span>
             <span class="sepV_c clientRow" id="contribRow" style="height:60px;">&nbsp;</span>
             <span class="sepV_c clientRow" id="contribRow">
                 <select name="category" id="category" class="chzn_b" data-placeholder="S&eacute;lectionner categorie" onchange="categoryList();">
                    <option value=""> </option>
                    {foreach from=$ep_categories_list item=catitm key=catkey}
                        <option value="{$catkey}" {if $catkey eq $category}selected{/if}>{$catitm}</option>
                    {/foreach}
                 </select>
             </span>
             <span class="sepV_c clientRow" id="contribRow" style="width:100%;">
                 <div class="alert alert-info span9 hide" id="targetdiv" style="width:100%;">
{if $categ neq ''}
    {foreach from=$categ item=catitm key=catkey}
        <div id=div_{$catkey} style="float:left;width:225px;padding-right:35px;">
            <div>{$catitm}</div>
            <div class="ui_slider span9" ondblclick="getIds(this.id);" id={$catkey} ></div>
            <input type="text" class="span2" style="position:relative;top:-15px;left:10px;" id=percentage_{$catkey} name=categ[{$catkey}]></input>
            <button  class="close" type="button" id=skill_close_{$catkey} value={$catkey} >&times;</button></div>
    {/foreach}
{/if}
                 </div>
             </span>
             <span class="sepV_c">
                <button value="search" type="submit" name="search" id="search" class="btn btn-danger pull-center">Search</button>
                <button onclick="clearAll();" value="clear" type="button" name="clear" id="clear" class="btn btn-info pull-center">Clear</button>   
             </span>
          </form>
        </div>
		
		<div class="mbox">									
			<div class="tab-pane active" id="mbox_outbox">
				<table data-msg_rowlink="a" class="table table_vam mbox_table dTableR" id="dt_outbox">
					<thead>
						<tr>
							<th class="table_checkbox"><input type="checkbox" data-tableid="dt_outbox" class="select_msgs" name="select_msgs"></th>							
							<th><i class="splashy-mail_light"></i></th>
							<th>Objet</th>
							<th>Emetteur</th>							
							<th>Destinataire</th>
							<th>Date</th>
							<!--<th>Action</th>-->
						</tr>
					</thead>
					<tbody>
						{if $paginator|@count gt 0}
							{foreach from=$paginator key=MainMenu_key item=message name=MainMenu_loop}
								
								<tr>								
									<td class="nohref"><input type="checkbox" class="select_msg" name="msg_sel"></td>									
									<td>{if $message.status eq 0}<i class="splashy-mail_light"></i>{else}<i class="splashy-mail_light_stuffed"></i>{/if}</td>
									<td><a href="/mastermails/view-mail/?submenuId={$submenuId}&mailaction=sentboxview&page={$smarty.request.page}&message={$message.messageId}&ticket={$message.ticket_id}&recipientid={$message.recipientid}">{$message.Subject}</a></td>
									<td><span>{$message.sendername}</span></td>
									<td><span>{$message.recipient}</span></td>
									<td>{$message.receivedDate}</td>
									<!--<td>
										<div class="btn-group">
											<a class="btn btn-info  hint--left  hint--info" data-hint="R&eacute;pondre" href="/mastermails/reply-mail?submenuId={$submenuId}&mailaction=reply&reply_message={$message.messageId}&ticket={$message.ticket_id}&recipientid={$message.recipientid}"><i class="icon-pencil"></i></a>
										</div>	
									</td>-->
								</tr>
							
							{/foreach}
						{/if}
						
					</tbody>
				</table>    
			</div>					
		</div>
	</div>		
	</div>


<!-- hide elements -->
<div class="hide">	
	<!-- actions for outbox -->
	<div class="dt_outbox_actions">
		<!--<div class="btn-group">
			<a href="javascript:void(0)" class="btn" title="Resend"><i class="icon-share-alt"></i></a>
			<a href="#" class="delete_msg btn" title="Delete" data-tableid="dt_outbox"><i class="icon-trash"></i></a>
		</div>-->
	</div>	
	<!-- confirmation box -->
	<div id="confirm_dialog">
		<div class="cbox_content">
			<div class="sepH_c tac"><strong>Are you sure you want to delete this message(s)?</strong></div>
			<div class="tac">
				<a href="#" class="btn btn-gebo confirm_yes">Yes</a>
				<a href="#" class="btn confirm_no">No</a>
			</div>
		</div>
	</div>
</div>
			
	