<table class="table selecttable" id="selecttable">
	<thead>
		<tr>
			<th>Writers</th>
			<th>Max delivery</th>
			<th>Price per art.</th>
			{if $show_quiz eq 'yes'}
			<th>Quiz winners</th>
			{/if}
			<th>Article with marks</th>
			<th></th>
		</tr>
	</thead>
	{if $participation_details|@count gt 0}
		{foreach from=$participation_details item=row name="pd" }
			{assign var=hire value=true}
			<tr>
				<td style="width:20%">
					<div class="imageHolder">
						<img class="media-object  img-circle" width="50px" height="50px"  src="{$fo_path}/{$row.image}" >
						<span class="caption label label-level">
							<i class="icon-bookmark"></i>
							{$row.profiletype}
						</span>
					</div>
					<div class="nameHolder">
						<b>{$row.first_name|utf8_encode}&nbsp;{$row.last_name|utf8_encode}</b>
					</div>
				</td>									
				<td><img src="/BO/theme/gebo/img/gCons/copy-item.png" alt="" /><div class="text">{$row.articles_per_week}/week</div></td>
				<td><img src="/BO/theme/gebo/img/gCons/dollar.png" alt="" /><div class="text">{$row.price_user|zero_cut:2} &euro; / art	</div></td>
				{if $row.link_quiz && $row.quiz}
					
					{if $row.qualified eq 'yes' && $row.percent eq '100'}
					<td>
						<img src="/BO/theme/gebo/img/gCons/button_ok.png" alt="" />
						<div class="text">Quizz {$row.num_correct} / {$row.num_total}</div>
					{elseif $row.qualified eq 'yes'}
					<td>
						<img src="/BO/theme/gebo/img/gCons/button_ok_orange.png" alt="" />
						<div class="text">Quizz {$row.num_correct} / {$row.num_total}</div>
					{else}
						<td class="disable_hire">
						{assign var=hire value=false}
						<div class="smiley">:(</div>
						<div class="text">Lost</div>
					{/if}
					</td>
				{/if}				
				<td>
					{if $row.article_path}
					<a class="btn btn-small" href="/contractmission/download-file?filename={$row.article_name}&recruitmenttestartid={$row.rpid}&recruitmenttestart={$row.article_path}"><i class="splashy-download"></i> Article Test</a>
					{elseif $smarty.now>$row.article_submit_expires}
						<strong>Article Test Time Out</strong>
					{else}
					<span id="time_{$row.article_submit_expires}_{$row.rpid}" class="alert alert-danger">
						<i class="icon-time"></i>
						<span id="time_{$row.rpid}"></span>
					</span>
					{/if}
				</td>				
				<td>
					<input type="checkbox" name="hire[]" value="{$row.rpid}" data-prompt-position="topLeft:-120" {if $row.is_hired == 'yes'} checked="checked" {/if}  class="validate[minCheckbox[1]]" {if !$hire}disabled="disabled"{/if} /> <!-- class="validate[minCheckbox[{$row.no_contrib}],maxCheckbox[{$row.no_contrib}]]" -->
					<label>{if $row.is_hired == 'yes'} Hired {else} Hire {/if}</label>
				</td>
			</tr>
		{/foreach}
	{else}
		<tr>
			<td colspan="5">No Participants Found</td>
		</tr>
	{/if}
</table>
	{literal}
<script type="text/javascript">

	$(".disable_hire").closest("tr").addClass('changebackground');
	

$('input[name="hire[]"]').each(function(){
			var self = $(this),
			  label = self.next(),
			  label_text = label.text();

			label.remove();
			self.iCheck({
			  checkboxClass: 'icheckbox_line-grey',
			  radioClass: 'iradio_line-grey',
			  insert: '<div class="icheck_line-icon"></div>' + label_text
			});
		  });

	
		  
{/literal}
{if $participation_details|@count gt 0}
{literal}
	  //data table
	$('#selecttable').dataTable({
             "bPaginate":   false,
             "bSort":   false,
            "aoColumns": [
                null,
                null,
                null,                
                {/literal}{if $show_quiz eq 'yes'}{literal}
                null,
				{/literal}
				{/if}				
				{literal}
				null,
                null,
            ]
        });
{/literal}
{/if}
{literal}
</script>
{/literal}