{literal}
<script language="JavaScript" type="text/javascript" src="/BO/theme/gebo/lib/flot/jquery.flot.curvedLines.min.js"></script>
<script src="/BO/theme/gebo/js/profile-validaterr.js"></script>
<script type="text/javascript">
    (function($) {
		$.fn.extend( {
			limiter: function(limit, elem) {
				$(this).on("keyup focus", function() {
					setCount(this, elem);
				});
				function setCount(src, elem) {
					var chars = src.value.length;
					/*if (chars > limit) {
						src.value = src.value.substr(0, limit);
						chars = limit;
					}*/
					//elem.html( chars+'/'+(limit - chars) );
					elem.html(chars);
				}
				setCount($(this)[0], elem);
			}
		});
	})(jQuery);

	/**closing the  categories with sliders**/
    var skill=0;
    $("[id^=skill_close_]").live('click', function(i) {

        var parentDiv=$(this).parents("div:first").attr('id');
        var closeDiv=$("#"+parentDiv).children(".close").attr('id');
        if($("[id^=skill_more_]").size()>1)
        {
            $("#"+parentDiv).remove();
            var skill =  $("[id^=skill_close_]").length-1;
            $("#addmore_skill_link").attr("onClick","addnewrow("+skill+")");
        }
        else
        {
            $("#"+closeDiv).hide();
        }
    });
    /**closing the  languages more with sliders**/
    var language=0;
    $("[id^=language_close_]").live('click', function() {

        var parentDiv=$(this).parents("div:first").attr('id');
        var closeDiv=$("#"+parentDiv).children(".close").attr('id');
        if($("[id^=language_more_]").size()>1)
        {
            $("#"+parentDiv).remove();
            var language =  $("[id^=language_close_]").length-1;
            $("#addmore_language_link").attr("onClick","addnewLanguage("+language+")");
        }
        else
        {
            $("#"+closeDiv).hide();
        }
    });
    $(document).ready(function() {
		var elem = $("#contributortestcomment_count");
		$("#contributortestcomment").limiter(70, elem);

        var tab = getParameterByName('tab', $(location).attr('href'));
		
          $("#"+tab).addClass('active');

        $("#language_more").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#favourite_category").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#language").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#moy_user_type").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#moy_language").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#stats_language").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#graph_language").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#moy_category").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#stats_category").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#graph_category").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#crtmoy_user_type").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#crtmoy_language").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#crtstats_language").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#crtgraph_language").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#crtmoy_category").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#crtstats_category").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#crtgraph_category").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#nationality").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#country").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#profession").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#education").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#period_Day").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#period_Month").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#period_Year").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#start_month").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#end_month").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#start_train_month").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#end_train_month").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#country").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#end_train_month").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#clients").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#deliveries").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#sorttype").chosen({ allow_single_deselect: false,search_contains: true  });
        $("#pay_type").chosen({ allow_single_deselect: false,search_contains: true  });
        $(".uni_style").uniform();
        gebo_validation.reg();
        gebo_sliders.init();
        gebo_charts.fl_m();
        gebo_charts.fl_crtm();
        $( ".jobtypedetails" ).each(function(j) {
            $("#ep_job_"+j).chosen({ allow_single_deselect: false,search_contains: true  });
        });

        /*$( ".ep_cates" ).each(function(j) {
            $("#ep_category_"+j).chosen({ allow_single_deselect: false,search_contains: true  });
        });
        $( ".ep_langmore" ).each(function(j) {
            $("#ep_language_"+j).chosen({ allow_single_deselect: false,search_contains: true  });
        });*/
        //Royalties pop up css change
        var top=$(window).scrollTop();
        $('#billing-ajax').css('top', (parseInt(60) + ((top*2)/$(window).height())) + '%');
        //destroy the Modal object before subsequent toggles
        $('body').on('hidden', '.modal', function () {
            $(this).removeData('modal');
            $(".datepicker").hide();
        });
        //date picker in cart page
        $("[id^=date_limit_]").each(function(i) {
            var myDate=new Date();
            myDate.setDate(myDate.getDate()-1);
            $(this).datepicker({
                format: 'dd/mm/yyyy',
                startDate: myDate
            });
        });
        //date picker in cart page
        $("[id^=poll_date_limit_]").each(function(i) {
            var myDate=new Date();
            myDate.setDate(myDate.getDate()-1);
            $(this).datepicker({
                format: 'dd/mm/yyyy',
                startDate: myDate
            });
        });
        //Prev Next in Offer pop up
        $("[id^=to_modal_]").live('click',function(e) {
            e.preventDefault();
            var href = $(this).attr('href');
            $("#viewOffer-ajax").removeData('modal');
            $('#viewOffer-ajax .modal-body').load(href);
            $("#viewOffer-ajax").modal();
            $(".modal-backdrop:gt(0)").remove();
        });
        $('#writermissions').dataTable({
            "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            "sPaginationType": "bootstrap",
            "aaSorting": [[ 0, "asc" ]],
            "aoColumns": [
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "natural" },
                { "sType": "natural" },
                { "sType": "natural" },
                { "sType": "natural" },
                { "sType": "natural" },

            ]

        });
        $('#correctormissions').dataTable({
            "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            "sPaginationType": "bootstrap",
            "aaSorting": [[ 0, "asc" ]],
            "aoColumns": [
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "natural" },
                { "sType": "natural" },
                { "sType": "natural" },
                { "sType": "natural" },
                { "sType": "natural" },

            ]

        });
        $('#dp').datepicker();
        gebo_datepicker = {
            init: function() {
                $('#dp').datepicker();
            }
        };
    });

    //* sliders
    gebo_sliders = {
        init: function(){
//* default slider
            $( ".ui_slider1" ).each(function(j) {
                // read initial values from markup and remove that
                var value = parseInt( $( this ).text(), 10 );
                if(isNaN(value))
                    value=50;
                //alert(i+'--'+value);
                $( this ).empty().slider({
                    range: "min",
                    value: value,
                    min: 1,
                    max: 100,
                    slide: function( event, ui ) {
                        $( "#slider-skill_number_"+j ).val( ui.value +"%");
                    }
                });
                $( "#slider-skill_number_"+j ).val( $( "#slider-skill_"+j ).slider( "value" ) +"%" );
                skill=j;
            });
            $( ".ui_slider2" ).each(function(j) {
                // read initial values from markup and remove that
                var value = parseInt( $( this ).text(), 10 );
                if(isNaN(value))
                    value=50;
                //alert(i+'--'+value);
                $( this ).empty().slider({
                    range: "min",
                    value: value,
                    min: 1,
                    max: 100,
                    slide: function( event, ui ) {
                        $( "#slider-language_number_"+j ).val( ui.value +"%");
                    }
                });
                $( "#slider-language_number_"+j ).val( $( "#slider-language_"+j ).slider( "value" ) +"%" );
                skill=j;
            });
          }
    };
    function fnchangeProfession(other)
    {
        var myindex  = other.selectedIndex;
        var SelValue = other.options[myindex].value;
        if(SelValue=='option5')
        {
            $("#otherProfession").show();
        }
        else
        {
            $("#otherProfession").hide();
            $("#profession_other").val('');
        }
    }
    function showtype2(sho)
    {
        if(sho=='yes')
            $("#type2block").show();
        else
        {
            $("#type2block").hide();
            $("#profile_type").removeAttr('checked');
        }
    }
    function EditContribInfo(userid)
    {
        var utype=$('#user_type').val();
        var user=$('#user_list').val();
        /*target_page = "/ao/editusercontrib?user="+user+"&utype="+utype;
        query = $("#myForm").serialize();
         $.get(target_page, query, function(data){
                $("#fade").show();
                $("#pop-box-edit").show();
                $("#pop-box-edit").html(data);
              {$user_detail[0].email}      /user/contributor-edit?submenuId=ML3-SL6&mode=view&userId=130724134912292
        });*/
        window.open(
                "/user/contributor-edit?submenuId=ML3-SL6&mode=edit&userId="+userid,
                '_self'
        );
    }
    function showhistory(userid)
    {
        target_page = "/user/userhistory?user="+userid;
        query = $("#myForm").serialize();
        $.get(target_page, query, function(data){
            $("#showhistory").modal('show');
        });
    }
    //* validation
    gebo_validation = {
        reg: function() {
            reg_validator = $('.form_validation_reg').validate({
                onkeyup: false,
                errorClass: 'error',
                validClass: 'valid',
                highlight: function(element) {
                    $(element).closest('div').addClass("f_error");
                    $(element).closest('div').css("color", "black");
                },
                unhighlight: function(element) {
                    $(element).closest('div').removeClass("f_error");
                },
                errorPlacement: function(error, element) {
                    $(element).closest('div').append(error);
                    $('.error').css("font-size", "10px");
                    $('.error').css("padding-top", "5px");
                    $('.error').hide();
                },
                rules: {
                    email: { required: true, minlength: 5 },
                    first_name: { required: true, minlength: 2 },
                    last_name: { required: true, minlength: 2},
                    password: { required: true, minlength: 6 },
                    //profession: { required: true, minlength: 4 },
                    //university: { required: true, minlength: 5 },
                    //phone_number: { required: true, minlength: 5},
                    //address: { required: true, minlength: 5 },
                    //city: { required: true, minlength: 3 },
                    //degree: { required: true, minlength: 3 },

                    //payinfo:"required" ,
                   /* ssn: {required: function(element) {
                        return $('input:radio[name=payinfo]:checked').val()=='ssn';   }
                    },
                    company_number: {required: function(element) {
                        return $('input:radio[name=payinfo]:checked').val()=='comp_num';  }
                    },
                    VAT_number: {required: function(element) {
                        return $('input:radio[name=payinfo]:checked').val()=='comp_num' && $('input[name=vat_check]').is(":checked");  }
                    },
                     //payment_type:"required",
                    paypal_id:	{required: function(element) {
                        return $('input:radio[name=payment_type]:checked').val()=='paypal'; }
                    },
                    rib_id_1: { required: true, minlength: 3 },
                    rib_id_2: { required: true, minlength: 3 },
                    rib_id_3: { required: true, minlength: 3 },
                    rib_id_4: { required: true, minlength: 3 },
                    rib_id_5: { required: true, minlength: 3 },
                    rib_id_6: { required: true, minlength: 3 },
                    rib_id_7: { required: true, minlength: 3 }*/
					contributortestcomment:	{required: function(element) {
                        return $('input:radio[name=contributortest]:checked').val()=='yes'; },
						minlength:70
                    },
					contributortestmark:	{required: function(element) {
                        return $('input:radio[name=contributortest]:checked').val()=='yes'; }
                    }
                },
                invalidHandler: function(form, validator) {
                    $.sticky("There are some errors. Please corect them and submit again.", {autoclose : 5000, position: "top-center", type: "st-error" });
                }

            });
        }
    };
    //$("#addmore_skill_link").click(function(){       alert("hi");
    function addnewrow(category)
    {
        var skill=category;
        var cloned =$("#addmore_skill_link");// $('#skill_more_'+skill);
        $("#skill_more_"+skill).clone().attr('id', 'skill_more_'+(++skill) ).insertBefore( cloned );
        // alert(skill);
        /*unselect the selected one**/
        $('#skill_more_'+skill+' select').attr('id','ep_category_'+skill);
       // $('#skill_more_'+skill+' select').attr('id','ep_category_'+skill+'_chzn');
        $('#skill_more_'+skill+' option:selected').removeAttr("selected");


        var slider_number=$('#skill_more_'+skill+' input');
        var slider=$('#skill_more_'+skill+' .ui_slider1');
        $('#skill_more_'+skill+' .muted').attr('for','slider-skill_number_'+skill);
        slider.attr('id','slider-skill_'+skill);
        slider_number.attr('id','slider-skill_number_'+skill);
        $( "#slider-skill_"+skill).html('');

        $('#skill_more_'+skill+' .close').attr('id','skill_close_'+skill);
        $('#skill_more_'+skill+' .close').show();
        $("#addmore_skill_link").attr("onClick","addnewrow("+skill+")");
        /**resetting the div**/
        clearChildren(document.getElementById('skill_more_'+skill));
        // Slider Skills
        var slider_val=skill;
        $( "#slider-skill_"+slider_val).slider({
            range: "min",
            value: 10,
            min: 1,
            max: 100,
            slide: function( event, ui ) {
                $( "#slider-skill_number_"+slider_val ).val( ui.value +"%");
            }
        });
        $( "#slider-skill_number_"+slider_val).val( $( "#slider-skill_"+slider_val ).slider( "value" ) +"%" );

    }
    function addnewLanguage(langmore)
    {
        var language=langmore;
        var cloned =$("#addmore_language_link");// $('#languageage_more_'+language);
        $("#language_more_"+language).clone().attr('id', 'language_more_'+(++language) ).insertBefore( cloned );
        /*unselect the selected one**/
        $('#language_more_'+language+' select').attr('id','ep_language_'+language);
        $('#language_more_'+language+' option:selected').removeAttr("selected");

        var slider_number=$('#language_more_'+language+' input');
        var slider=$('#language_more_'+language+' .ui_slider2');
        $('#language_more_'+language+' .muted').attr('for','slider-language_number_'+language);
        slider.attr('id','slider-language_'+language);
        slider_number.attr('id','slider-language_number_'+language);
        $( "#slider-language_"+language).html('');

        $('#language_more_'+language+' .close').attr('id','language_close_'+language);
        $('#language_more_'+language+' .close').show();
        $("#addmore_language_link").attr("onClick","addnewLanguage("+language+")");
        /**resetting the div**/
        clearChildren(document.getElementById('language_more_'+language));
        // Slider languages
        var slider_val=language;
        $( "#slider-language_"+slider_val).slider({
            range: "min",
            value: 10,
            min: 1,
            max: 100,
            slide: function( event, ui ) {
                $( "#slider-language_number_"+slider_val ).val( ui.value +"%");
            }
        });
        $( "#slider-language_number_"+slider_val).val( $( "#slider-language_"+slider_val ).slider( "value" ) +"%" );

    }
    /****************add more jobs*********************/
    $("[id^=job_close_]").live('click', function() {
        var DivId = $(this).attr('id');
        var parentDiv=$(this).parents("div:first").attr('id');
        var job_identifier=$(this).attr('rel');
        var closeDiv=$("#"+parentDiv).children(".close").attr('id');
        var job =  $("[id^=job_close_]").length-1;
        $("#addmore_job_link").attr("onClick","addJob("+job+")");
        if(!job_identifier)
            $("#"+parentDiv).remove();
        else
        {
            if($("[id^=job_more_]").size()>1)
            {
               // $("#"+parentDiv).html('<center>'+bigLoader+' Deleting... </center>');
                ajaxProfileUpdate('job',job_identifier,parentDiv);
            }
            else
            {
                $("#"+closeDiv).hide();
            }
        }
    });

    //$("#addmore_job_link").click(function(){    alert("masiv");
    function addJob(jobno)
    {
        var job= jobno;
        var cloned =$("#addmore_job_link");
        $("#job_more_"+job).clone().attr('id', 'job_more_'+(++job) ).insertBefore( cloned );
        $('#job_more_'+job+' .collapse').addClass('in');
        $('#job_more_'+job+' .close').attr('id','job_close_'+job);
        $('#job_more_'+job+' .close').show();
        $('#job_more_'+job+' .close').attr('rel','');
        $('#job_more_'+job+' .collapse').attr('id','stillWorkingThere_'+job);
        $('#job_more_'+job+' input:checkbox').attr('data-target','#stillWorkingThere_'+job);
        $("#addmore_job_link").attr("onClick","addJob("+job+")");
        clearChildren(document.getElementById('job_more_'+job));
    }
    //});
    /****************add more Trainings****************/
    $("[id^=training_close_]").live('click', function() {
        var DivId = $(this).attr('id');
        var parentDiv=$(this).parents("div:first").attr('id');
        var training_identifier=$(this).attr('rel');
        var closeDiv=$("#"+parentDiv).children(".close").attr('id');
        var training =  $("[id^=training_close_]").length-1;
        $("#addmore_training_link").attr("onClick","addTraining("+training+")");
        if(!training_identifier)
            $("#"+parentDiv).remove();
        else
        {
            if($("[id^=training_more_]").size()>1)
            {
               // $("#"+parentDiv).html('<center>'+bigLoader+' Deleting... </center>');
                ajaxProfileUpdate('education',training_identifier,parentDiv);
            }
            else
            {
                $("#"+closeDiv).hide();
            }
        }
    });
    //$("#addmore_training_link").click(function(){
    function addTraining(trainingno)
    {
        var training =   trainingno;
        var cloned =$("#addmore_training_link");
        $("#training_more_"+training).clone().attr('id', 'training_more_'+(++training) ).insertBefore( cloned );
        //$("#training_more_"+training+").clone().attr('id', 'training_more_'+(++training) ).insertBefore( cloned );
        //$('#training_more_'+training+' .clone').attr('id', 'training_more_'+(++training) ).insertBefore( cloned );
        $('#training_more_'+training+' .collapse').addClass('in');
        $('#training_more_'+training+' .close').attr('id','training_close_'+training);
        $('#training_more_'+training+' .close').show();
        $('#training_more_'+training+' .close').attr('rel','');
        $('#training_more_'+training+' .collapse').attr('id','stillTrainingThere_'+training);
        $('#training_more_'+training+' input:checkbox').attr('data-target','#stillTrainingThere_'+training);
        $("#addmore_training_link").attr("onClick","addTraining("+training+")");
        clearChildren(document.getElementById('training_more_'+training));
    }
    /** ajax function to delete profile data**/
    function ajaxProfileUpdate(type,identifier,divid)
    {
        var target_page = "/user/delete-profile-data?type="+type+"&identifier="+identifier;
        $.post(target_page, function(data){  //alert(data);
            //sleep(4000);
            $("#"+divid).remove();

        });
    }

    /*reset all childs of a div**/
    function clearChildren(element) {
        for (var i = 0; i < element.childNodes.length; i++) {
            var e = element.childNodes[i];
            if (e.tagName) switch (e.tagName.toLowerCase()) {
                case 'input':
                    switch (e.type) {
                        case "radio":
                        case "checkbox": e.checked = false; break;
                        case "button":
                        case "submit":
                        case "image": break;
                        default: e.value = ''; break;
                    }
                    break;
                case 'select': e.selectedIndex = 0; break;
                case 'textarea': e.innerHTML = ''; break;
                default: clearChildren(e);
            }
        }
    }
    /**toggle for payment infos**/
    $('input[type=radio]').live('click', function () {

        var payment_type = $("input:radio[name ='payment_type']:checked").val();
        var country = $("#country").val();
        var payinfo=$('input:radio[name=payinfo]:checked').val();

        if (this.checked && $(this).val() == 'ssn')
        {
            $(this).addClass('in');
            $("#siretNum").removeClass('in');
            $("#siretNum").css('height','0px');

            if(payment_type=='virement' && country!=38)
            {
                $("#c_out_france").show();
                $("#c_france").hide();
            }
            else if(payment_type=='virement')
            {
                $("#c_out_france").hide();
                $("#c_france").show();
            }

            if(country!=38)
            {
                $("#cheque_radio").hide();
                $("#cheque_radio").find("input:radio:checked").removeProp('checked');
            }
            else
                $("#cheque_radio").show();
        }
        else if (this.checked && $(this).val() == 'comp_num')
        {
            $(this).addClass('in');
            $("#national-InsuranceNum").removeClass('in');
            $("#national-InsuranceNum").css('height','0px');

            if(payment_type=='virement'  && country!=38)
            {
                $("#c_out_france").show();
                $("#c_france").hide();
            }
            else if(payment_type=='virement')
            {
                $("#c_out_france").hide();
                $("#c_france").show();
            }
            if(country!=38)
            {
                $("#cheque_radio").hide();
                $("#cheque_radio").find("input:radio:checked").removeProp('checked');
            }
            else
                $("#cheque_radio").show();
        }
        else if (this.checked && $(this).val() == 'out_france')
        {
            $("#national-InsuranceNum").removeClass('in');
            $("#national-InsuranceNum").css('height','0px');
            $("#siretNum").removeClass('in');
            $("#siretNum").css('height','0px');


            if(payment_type=='virement'  || country!=38)
            {
                $("#c_out_france").show();
                $("#c_france").hide();
            }
            else if(payment_type=='virement')
            {
                $("#c_out_france").hide();
                $("#c_france").show();
            }
            $("#cheque_radio").hide();
            $("#cheque_radio").find("input:radio:checked").removeProp('checked');

        }
        else if (this.checked && $(this).val() == 'virement')
        {
            var payinfo = $("input:radio[name ='payinfo']:checked").val();
            if(payinfo=='out_france' || country!=38)
            {
                $("#c_out_france").show();
                $("#c_france").hide();
            }
            else
            {
                $("#c_out_france").hide();
                $("#c_france").show();
            }
        }
        else if (this.checked && $(this).val() == 'paypal' || this.checked && $(this).val() == 'cheque' )
        {
            $("#c_out_france").hide();
            $("#c_france").hide();
        }

    });
    function changeCountry()
    {
        var country=$("#country").val();
        var payment_type = $("input:radio[name ='payment_type']:checked").val();
        //alert(country+"--"+payment_type);
        if(country!=38)
        {
            $("#cheque_radio").hide();
            $("#cheque_radio").find("input:radio:checked").removeProp('checked');
            if(payment_type=='virement')
            {
                $("#c_out_france").show();
                $("#c_france").hide();
            }
        }
        else
        {
            $("#cheque_radio").show();
            if(payment_type=='virement')
            {
                $("#c_out_france").hide();
                $("#c_france").show();
            }
        }
    }
    $("input:radio[name=payinfo]").click(function(){
        var selected=$(this).val();

        if(selected=='comp_num')
        {
            $('label[for="ssn"]').hide();
            $('label[for="company_number"]').show();
            if(!$("#ssn").val().match(/^([0-9]{15})?$/))
                $("#ssn").val('');
        }
        else if(selected=='ssn')
        {
            $('label[for="company_number"]').hide();
            $('label[for="ssn"]').show();
            if(!$("#company_number").val().match(/^([0-9]{14})?$/))
                $("#company_number").val('');
        }
        else
        {
            $('label[for="company_number"]').hide();
            $('label[for="ssn"]').hide();
        }

    });
  function getMoyennes(userid)
  {
     var moy_user = $("#moy_user_type").val();
      var moy_lang = $("#moy_language").val();
      var moy_categ = $("#moy_category").val();
      var userid = userid;
      if($("#moy_user_type").val() != '0'){
          var target_page = "/user/moyennes?userid="+userid+"&moy_user="+moy_user;
          $.post(target_page, function(data){  //alert(data);
          $("#moy_stats").text(data);
          });
      }
      if($("#moy_language").val() != '0'){
          var target_page = "/user/moyennes?userid="+userid+"&moy_lang="+moy_lang;
          $.post(target_page, function(data){  //alert(data);
          $("#moy_lang_stats").text(data);
          });
      }
      if($("#moy_category").val() != '0'){
          var target_page = "/user/moyennes?userid="+userid+"&moy_categ="+moy_categ;
          $.post(target_page, function(data){  //alert(data);
          $("#moy_categ_stats").text(data);
          });
      }


  }
function getStatistics(userid)
{
    var stats_lang = $("#stats_language").val();
    var stats_categ = $("#stats_category").val();
    var userid = userid;
    var target_page = "/user/statistics?userid="+userid+"&stats_lang="+stats_lang+"&stats_categ="+stats_categ;
    $.post(target_page, function(data){  //alert(data);
       var obj = $.parseJSON(data);
        $("#selected").text(obj[0]+"/"+obj[3]+" ("+(obj[0]/obj[3]).toFixed(2)+" %)");
        $("#validated").text(obj[4]+"/"+obj[3]+" ("+(obj[4]/obj[3]).toFixed(2)+" %)");
        $("#republished").text(obj[5]+"/"+obj[3]+" ("+(obj[5]/obj[3]).toFixed(2)+" %)");
        $("#refusedreasons").text(obj[12]+" "+obj[7]+"/"+obj[8]+" ("+(obj[7]/obj[8]).toFixed(2)+" %)");
        $("#refusedreasonscrt").text(obj[13]+" "+obj[11]+"/"+obj[8]+" ("+(obj[11]/obj[8]).toFixed(2)+" %)");
        $("#refused").text(obj[1]+"/"+obj[3]+" ("+(obj[1]/obj[3]).toFixed(2)+" %)");
        $("#notsubmited").text(obj[6]+"/"+obj[3]+" ("+(obj[6]/obj[3]).toFixed(2)+" %)");
        $("#numclients").text(obj[9]);
        $("#clientlist").text(obj[10]);
    });

}
    function getStatisticsGraph(userid)
    {
        var stats_lang = $("#stats_language").val();
        var stats_categ = $("#stats_category").val();
        var userid = userid;

        if($("#stats_language").val() != ''){
            $("#stats_category").chosen({ allow_single_deselect: true,search_contains: true  });
            var target_page = "/user/marksContributorGraph?userid="+userid+"&stats_lang="+stats_lang;
            $.post(target_page, function(data){ // alert(data);
                var obj = $.parseJSON(data);

            });
        }
        if($("#stats_category").val() != ''){
            $("#stats_language").chosen({ allow_single_deselect: true,search_contains: true  });
            var target_page = "/user/statistics?userid="+userid+"&stats_categ="+stats_categ;
            $.post(target_page, function(data){ // alert(data);
                var obj = $.parseJSON(data);

            });
        }

    }
    function getCrtMoyennes(userid)
    {
        var crtmoy_user = $("#crtmoy_user_type").val();
        var crtmoy_lang = $("#crtmoy_language").val();
        var crtmoy_categ = $("#crtmoy_category").val();
        var userid = userid;
        if($("#crtmoy_user_type").val() != '0'){
            var target_page = "/user/correctormoyennes?userid="+userid+"&crtmoy_user="+crtmoy_user;
            $.post(target_page, function(data){  //alert(data);
                $("#crtmoy_stats").text(data);
            });
        }
        if($("#crtmoy_language").val() != '0'){
            var target_page = "/user/correctormoyennes?userid="+userid+"&crtmoy_lang="+crtmoy_lang;
            $.post(target_page, function(data){  //alert(data);
                $("#crtmoy_lang_stats").text(data);
            });
        }
        if($("#crtmoy_category").val() != '0'){
            var target_page = "/user/correctormoyennes?userid="+userid+"&crtmoy_categ="+crtmoy_categ;
            $.post(target_page, function(data){  //alert(data);
                $("#crtmoy_categ_stats").text(data);
            });
        }


    }
    function getCrtStatistics(userid)
    {
        var crtstats_lang = $("#crtstats_language").val();
        var crtstats_categ = $("#crtstats_category").val();
        var userid = userid;
        var target_page = "/user/correctorstatistics?userid="+userid+"&crtstats_lang="+crtstats_lang;
        $.post(target_page, function(data){ //alert(data);
            var obj = $.parseJSON(data);
            $("#crtselected").text(obj[0]+"/"+obj[3]+" ("+(obj[0]/obj[3]).toFixed(2)+")");
            $("#crtvalidated").text(obj[4]+"/"+obj[3]+" ("+(obj[4]/obj[3]).toFixed(2)+")");
            $("#crtrepublished").text(obj[5]+"/"+obj[3]+" ("+(obj[5]/obj[3]).toFixed(2)+")");
            $("#crtrefusedreasons").text(obj[12]+" "+obj[7]+"/"+obj[8]+" ("+(obj[7]/obj[8]).toFixed(2)+")");
            $("#crtrefusedreasonscrt").text(obj[13]+" "+obj[10]+"/"+obj[8]+" ("+(obj[10]/obj[8]).toFixed(2)+")");
            $("#crtrefused").text(obj[1]+"/"+obj[3]+" ("+(obj[1]/obj[3]).toFixed(2)+")");
            $("#crtnotsubmited").text(obj[6]+"/"+obj[3]+" ("+(obj[6]/obj[3]).toFixed(2)+")");
            $("#crtnumwriter").text(obj[9]);
        });

    }
    function changeGraph(userid, type)
    {
        if(type == 'writer'){
            var stats_lang = $("#graph_language").val();
            var stats_categ = $("#graph_category").val();
            var stats_date = $("#dp1").val();
        }else{
            var stats_lang = $("#crtgraph_language").val();
            var stats_categ = $("#crtgraph_category").val();
            var stats_date = $('input[name=crtgraph_date]').val();
        }
        var userid = userid;
        var target_page = "/user/bousergraph?userid="+userid+"&type="+type+"&stats_lang="+stats_lang+"&stats_categ="+stats_categ+"&stats_date="+stats_date;
        $.post(target_page, function(data){
            if(type == 'writer')
               $("#writergraph").html(data);
            else
               $("#correctorgraph").html(data);
        });
    }

	function showremarks(param)
	{
		if(param=='yes')
			$("#remarksblock").show();
		else
			$("#remarksblock").hide();
	}
    /* added by naseer on 31-07-2015 */
    function toggle_com_siren(){
        if($("#com_country").val() == 38){
            $("#com_siren_label").show();
        }
        else{
            $("#com_siren_label").hide();
        }
    }

    function toggle_details(val){
        $(".details").hide();
        $("#"+val).show();
        $("#options_group").val('selected');
    }

	</script>
{/literal}
<div class="row-fluid">
 <div class="span12" style="">
  <div class="tabbable">
  <ul class="nav nav-tabs">
      <li {if $smarty.get.tab == 'editcontrib' || $smarty.get.tab == ''} class="active" {/if}><a href="#editcontrib" data-toggle="tab" class="lable-success"><i class="icon-pencil"></i>&nbsp;<strong>Edit</strong></a></li>

      <li {if $smarty.get.tab == 'viewcontrib'} class="active" {/if}><a href="#viewcontrib" data-toggle="tab" class="lable-danger"><i class="icon-eye-open"></i>&nbsp;<strong>View</strong></a></li>
      <li {if $smarty.get.tab == 'writerstats'} class="active" {/if}><a href="#writerstats" data-toggle="tab" class="lable-danger"><i class="icon-eye-open"></i>&nbsp;<strong>Statistiques R&eacute;dacteur</strong></a></li>
      <li {if $smarty.get.tab == 'correctorstats'} class="active" {/if}><a href="#correctorstats" data-toggle="tab" class="lable-danger"><i class="icon-eye-open"></i>&nbsp;<strong>Statistiques Correcteur</strong></a></li>
      <li {if $smarty.get.tab == 'writersarts'} class="active" {/if}><a href="#writersarts" data-toggle="tab" class="lable-danger"><i class="icon-eye-open"></i>&nbsp;<strong>Suivi R&eacute;dacteur</strong></a></li>
      <li {if $smarty.get.tab == 'correctorarts'} class="active" {/if}><a href="#correctorarts" data-toggle="tab" class="lable-danger"><i class="icon-eye-open"></i>&nbsp;<strong>Suivi Correcteur</strong></a></li>
      <!--<a href="#searchblock"  onclick="showSearch();"  class="pull-left"><i class="splashy-zoom"></i></a>-->
      <a class="label label-inverse pull-right" href="/user/users-list?submenuId=ML3-SL6&tab=contributorstab">retour</a>
  </ul>


  <div class="tab-content" style="overflow: hidden;">
    <div id="editcontrib" class="tab-pane">
        <h3 class="heading alert alert-info">
            {if $user_detail[0].first_name != ''}
            {$user_detail[0].first_name}&nbsp;{$user_detail[0].last_name}
            {else}
            {$user_detail[0].email}
            {/if}
        </h3>
        <form name="" class="form_validation_reg"  autocomplete="off"  action="/user/contributor-edit?submenuId={$submenuId}&mode=edit&userId={$smarty.get.userId}" method="post">

			<!-- User test -->
			<div class="formSep">

            </div>
            <div class="formSep">
                <div class="row-fluid">
                    <div class="span6 form-inline">
                        <label class="span4">Date de naissance</label>
                        {html_select_date end_year="1950" start_year='-1' field_order="DMY" time=$user_detail[0].dob field_separator=&nbsp; day_extra='id="period_Day"' month_extra='id="period_Month"' year_extra='id="period_Year"' class="span2"}
                    </div>
                    <div class="span6 form-inline">
                        <label class="span4">Langue de r&eacute;daction 1</label>
                        <select  name="language" id="language">{html_options options=$language_array selected=$user_detail[0].language}</select>
                    </div>
                </div>
            </div>

            <div class="formSep">
                <div class="row-fluid">
                    <div class="span6 form-inline">
                        <label class="span4">Nationalit&eacute;</label>
                        <select name="nationality" id="nationality">{html_options options=$nationality_array selected=$user_detail[0].nationality}</select>
                    </div>
                    <div class="span6 form-inline">
                        <label class="span4">T&eacute;l&eacute;phone </label>
                        <input type="text" name="phone_number" id="phone_number" value="{$user_detail[0].phone_number}" />
                    </div>
                </div>
            </div>
            <div class="formSep">
                <div class="row-fluid">
                    <div class="span6 form-inline">
                        <label class="span4">Adresse </label>
                        <input type="text" name="address" id="address" value="{$user_detail[0].address}"/>
                    </div>
                    <div class="span6 form-inline">
                        <label class="span4">Ville </label>
                        <input type="text" name="city" id="city" value="{$user_detail[0].city}" />
                    </div>
                </div>
            </div>
            <div class="formSep">
                <div class="row-fluid">
                    <div class="span6 form-inline">
                        <label class="span4">Code Postal</label>
                        <input type="text" name="zipcode" id="zipcode" value="{$user_detail[0].zipcode}" />
                    </div>
                    <div class="span6 form-inline">
                        <label class="span4">Pays</label>
                        <select size="1" name="country" id="country" onchange=changeCountry();>
                            <option value=""></option>
                            {html_options options=$country_array selected=$user_detail[0].country }
                        </select>
                    </div>
                </div>
            </div>
            <div class="formSep">
                <div class="row-fluid">
                    <div class="span6 form-inline">
                        <label class="span4"><strong>Subscription (nl)</strong> </label>
                        <label class="uni-radio"><input type="radio" name="subscribe" value="yes" class="uni_style" {if $user_detail[0].subscribe== "yes"}checked{/if} />Yes&nbsp; </label>
                        <label class="uni-radio"><input type="radio" name="subscribe" value="no" class="uni_style" {if $user_detail[0].subscribe == "no" }checked{/if} />No  </label>
                    </div>
                    <div class="span6 form-inline">
                        <label class="span4"><strong>Subscription (alert)</strong> </label>
                        <label class="uni-radio"><input type="radio" name="alert_subscribe" value="yes" class="uni_style" {if $user_detail[0].alert_subscribe== "yes"}checked{/if} />Yes&nbsp; </label>
                        <label class="uni-radio"><input type="radio" name="alert_subscribe" value="no" class="uni_style" {if $user_detail[0].alert_subscribe == "no" }checked{/if} />No  </label>
                    </div>
                </div>
            </div>
            <hr />
            <div class="formSep">
                <div class="row-fluid">
                    <div class="span6 form-inline">
                        <label class="span4">Cat&eacute;gories pr&eacute;f&eacute;r&eacute;es</label>
                        {foreach from=$category_more key=kcategory item=percent name="moreSkills}
                        {assign var=skill_index value=$smarty.foreach.moreSkills.index}
                        <!-- Start, new skill row -->
                        <div class="addmore form-inline span12" id="skill_more_{$skill_index}">
                            <select class="ep_cates span4" name="ep_category[]" id="ep_category_{$smarty.foreach.moreSkills.index}" style="bottom:10px;position:relative;">
                                <option value="">S&eacute;lectionnez une comp&eacute;tence</option>
                                {html_options  options=$category_array selected=$kcategory}
                            </select>
                            <label for="slider-skill_number_{$smarty.foreach.moreSkills.index}" class="muted" style="bottom:10px;position:relative;">Votre niveau :</label>
                            <input type="text" id="slider-skill_number_{$smarty.foreach.moreSkills.index}" value="{$percent}" name="category_slider_more[]" style="bottom:10px;position:relative;" class="span2"/>
                            <button  class="close" type="button" id="skill_close_{$skill_index}" style="padding-right:25%" {if $category_more|@count lt 2} style="display:none"{/if}>&times;</button>
                            <div class="sepH_c span8">
                                <div id="slider-skill_{$smarty.foreach.moreSkills.index}" class="ui_slider1">{$percent}</div>
                                <span class="pull-left legend muted">D&eacute;butant</span> <span class="pull-right legend muted">Expert</span>
                            </div>
                        </div>
                        {/foreach}
                        <p class="addmore-button" id="addmore_skill_link" onclick="addnewrow({$skill_index});" ><a class="btn btn-link btn-small"><i class="icon-plus"></i> Ajouter une comp&eacute;tence</a></p>
                    </div>
                    <div class="span6 form-inline">
                        <label class="span4">Langues more</label>
                        {foreach from=$language_more key=lang item=percent name="moreLanguage}
                        {assign var=lang_index value=$smarty.foreach.moreLanguage.index}
                        <!-- Start, new language row -->
                        <div class="addmore form-inline span12" id="language_more_{$lang_index}">
                            <select class="ep_langmore span4" name="language_more[]" id="ep_language_{$smarty.foreach.moreLanguage.index}" style="bottom:10px;position:relative;">
                                <option value="">S&eacute;lectionnez une langue</option>
                                {html_options  options=$language_array selected=$lang}
                            </select>
                            <label for="slider-language_number_{$smarty.foreach.moreLanguage.index}" class="muted" style="bottom:10px;position:relative;">Votre niveau :</label>
                            <input type="text" id="slider-language_number_{$smarty.foreach.moreLanguage.index}" value="{$percent}" name="lang_slider_more[]" style="bottom:10px;position:relative;" class="span2"/>
                            <button  class="close" type="button" id="language_close_{$lang_index}" style="padding-right:25%" {if $language_more|@count lt 2} style="display:none"{/if}>&times;</button>
                            <div class="sepH_c span8">
                                <div id="slider-language_{$smarty.foreach.moreLanguage.index}" class="ui_slider2">{$percent}</div>
                                <span class="pull-left legend muted">D&eacute;butant</span> <span class="pull-right legend muted">Expert</span>
                            </div>
                        </div>
                        {/foreach}
                        <p class="addmore-button" id="addmore_language_link" onclick="addnewLanguage({$lang_index});"><a class="btn btn-link btn-small"><i class="icon-plus"></i> Ajouter une langue</a></p>
                    </div>
                </div>
            </div>
            <hr />
            <!-- Start, Job module -->
            <div class="formSep">
                <div class="row-fluid">
                    <div class="control-group">
                        <label class="control-label span2 offset1" for=""><strong>Exp&eacute;riences professionnelles <span class="error">*</span></strong>
                            <br><span id="job_error"></span>
                        </label>
                        <div class="controls span8">
                            {foreach from=$jobDetails item=job name="job_details"}
                            {assign var=job_index value=$smarty.foreach.job_details.index+1}
                            <!-- Start, job row -->
                            <div class="addmore" id="job_more_{$job_index}">
                                <button  class="close" type="button" id="job_close_{$job_index}" rel="{$job.identifier}"  {if $jobDetails|@count lt 2} style="display:none"{/if}>&times;</button>
                                <label><input class="span5" type="text" id="JobName_{$job_index}" value="{$job.title}" name="job_title[]" placeholder="Intitul&eacute; du poste"></label>
                                <label><input class="span5" type="text" id="CompanyName_{$job_index}" value="{$job.institute}" name="job_institute[]" placeholder="Nom de l'entreprise"></label>
                                <select class="span5 jobtypedetails" name="ep_job[]" id="ep_job_{$job_index}">
                                    <option value="">S&eacute;lectionner le type de contrat</option>
                                    <option value="cdi" {if $job.contract=='cdi'}selected{/if}>CDI</option>
                                    <option value="cdd" {if $job.contract=='cdd'}selected{/if}>CDD</option>
                                    <option value="freelance" {if $job.contract=='freelance'}selected{/if}>Freelance</option>
                                    <option value="intern" {if $job.contract=='intern'}selected{/if}>Interim</option>
                                    <option value="stage" {if $job.contract=='stage'}selected{/if}>Stage</option>
                                </select>
                                <div class="clearfix">
                                    <div class="container-field span5">
                                        <label>
                                            <span class="span3">D&eacute;but</span>
                                        </label>
                                        <select class="start_month input-small inline" name="start_month[]" id="start_month">
                                            <option value="1" {if $job.from_month=='1'}selected{/if}>Janvier</option>
                                            <option value="2" {if $job.from_month=='2'}selected{/if}>F&eacute;vrier</option>
                                            <option value="3" {if $job.from_month=='3'}selected{/if}>Mars</option>
                                            <option value="4" {if $job.from_month=='4'}selected{/if}>Avril</option>
                                            <option value="5" {if $job.from_month=='5'}selected{/if}>Mai</option>
                                            <option value="6" {if $job.from_month=='6'}selected{/if}>Juin</option>
                                            <option value="7" {if $job.from_month=='7'}selected{/if}>Juillet</option>
                                            <option value="8" {if $job.from_month=='8'}selected{/if}>Ao&ucirc;t</option>
                                            <option value="9" {if $job.from_month=='9'}selected{/if}>Septembre</option>
                                            <option value="10" {if $job.from_month=='10'}selected{/if}>Octobre</option>
                                            <option value="11" {if $job.from_month=='11'}selected{/if}>Novembre</option>
                                            <option value="12" {if $job.from_month=='12'}selected{/if}>D&eacute;cembre</option>
                                        </select>
                                        &nbsp;&nbsp;<input class="input-small inline" type="text" id="start_year_{$job_index}" placeholder="Ann&eacute;e" value="{$job.from_year}" name="start_year[]" style="position:relative;top: -7px;">

                                        <div class="collapse {if $job.still_working !='yes'} in {/if}" id="stillWorkingThere_{$job_index}">
                                            <label>
                                                <span class="span3">Fin</span>
                                            </label>
                                            <select class="end_month input-small inline" name="end_month[]" id="end_month">
                                                <option value="1" {if $job.to_month=='1'}selected{/if}>Janvier</option>
                                                <option value="2" {if $job.to_month=='2'}selected{/if}>F&eacute;vrier</option>
                                                <option value="3" {if $job.to_month=='3'}selected{/if}>Mars</option>
                                                <option value="4" {if $job.to_month=='4'}selected{/if}>Avril</option>
                                                <option value="5" {if $job.to_month=='5'}selected{/if}>Mai</option>
                                                <option value="6" {if $job.to_month=='6'}selected{/if}>Juin</option>
                                                <option value="7" {if $job.to_month=='7'}selected{/if}>Juillet</option>
                                                <option value="8" {if $job.to_month=='8'}selected{/if}>Ao&ucirc;t</option>
                                                <option value="9" {if $job.to_month=='9'}selected{/if}>Septembre</option>
                                                <option value="10" {if $job.to_month=='10'}selected{/if}>Octobre</option>
                                                <option value="11" {if $job.to_month=='11'}selected{/if}>Novembre</option>
                                                <option value="12" {if $job.to_month=='12'}selected{/if}>D&eacute;cembre</option>
                                            </select>
                                            &nbsp;&nbsp;<input class="input-small inline" type="text" id="end_year_{$job_index}" placeholder="Ann&eacute;e" value="{$job.to_year}" name="end_year[]" style="position:relative;top: -7px;">

                                        </div>
                                        <label class="uni-checkbox">
                                            <input type="checkbox" id="still_working_{$job_index}" class="uni_style" data-target="#stillWorkingThere_1" data-toggle="collapse" {if $job.still_working =='yes'} checked {/if}  name="still_working[]">J'occupe toujours ce poste
                                        </label>
                                        <input type="hidden" name="job_identifier[]" value="{$job.identifier}">
                                    </div>
                                </div>
                            </div>
                            <!-- end, job row -->
                            {/foreach}
                            <p class="addmore-button" id="addmore_job_link" onclick="addJob({$job_index});"><a class="btn btn-link btn-small"><i class="icon-plus"></i> Ajouter une exp&eacute;rience</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End, Job -->
            <hr />
            <!-- Start, Training module -->
            <div class="formSep">
                <div class="row-fluid">
                    <div class="control-group">
                        <label class="control-label span2 offset1" for=""><strong>Formation <span class="error">*</span></strong>
                            <br><span id="edu_error"></span>
                        </label>
                        <div class="controls span8">
                            {foreach from=$educationDetails item=education name="edu_details"}
                            {assign var=edu_index value=$smarty.foreach.edu_details.index+1}
                            <!-- Start, School row -->
                            <div class="addmore" id="training_more_{$edu_index}">
                                <button  class="close" type="button" id="training_close_{$edu_index}" rel="{$education.identifier}" {if  $educationDetails|@count lt 2} style="display:none"{/if}>&times;</button>
                                <label><input class="span5" type="text" id="trainingName_{$edu_index}" value="{$education.title}" name="training_title[]" placeholder="Intitul&eacute; de la formation"></label>
                                <label><input class="span5" type="text" id="trainingSchoolName_{$edu_index}" value="{$education.institute}" name="training_institute[]" placeholder="Ecole, universit&eacute;, etc..."></label>
                                <div class="clearfix">
                                    <div class="container-field span5">
                                        <label>
                                            <span class="span3">D&eacute;but</span>
                                        </label>
                                        <select class="start_train_month input-small inline" name="start_train_month[]" id="start_train_month">
                                            <option value="1" {if $education.from_month=='1'}selected{/if}>Janvier</option>
                                            <option value="2" {if $education.from_month=='2'}selected{/if}>F&eacute;vrier</option>
                                            <option value="3" {if $education.from_month=='3'}selected{/if}>Mars</option>
                                            <option value="4" {if $education.from_month=='4'}selected{/if}>Avril</option>
                                            <option value="5" {if $education.from_month=='5'}selected{/if}>Mai</option>
                                            <option value="6" {if $education.from_month=='6'}selected{/if}>Juin</option>
                                            <option value="7" {if $education.from_month=='7'}selected{/if}>Juillet</option>
                                            <option value="8" {if $education.from_month=='8'}selected{/if}>Ao&ucirc;t</option>
                                            <option value="9" {if $education.from_month=='9'}selected{/if}>Septembre</option>
                                            <option value="10" {if $education.from_month=='10'}selected{/if}>Octobre</option>
                                            <option value="11" {if $education.from_month=='11'}selected{/if}>Novembre</option>
                                            <option value="12" {if $education.from_month=='12'}selected{/if}>D&eacute;cembre</option>
                                        </select>
                                        &nbsp;&nbsp;<input class="input-small inline" type="text" placeholder="Ann&eacute;e" id="start_train_year_{$edu_index}" value="{$education.from_year}" name="start_train_year[]" style="position:relative;top: -7px;">

                                        <div class="collapse  {if $education.still_working !='yes'} in {/if}" id="stillTrainingThere_{$edu_index}">
                                            <label>
                                                <span class="span3">Fin</span>
                                            </label>
                                            <select class="end_train_month input-small inline" name="end_train_month[]" id="end_train_month">
                                                <option value="1" {if $education.to_month=='1'}selected{/if}>Janvier</option>
                                                <option value="2" {if $education.to_month=='2'}selected{/if}>F&eacute;vrier</option>
                                                <option value="3" {if $education.to_month=='3'}selected{/if}>Mars</option>
                                                <option value="4" {if $education.to_month=='4'}selected{/if}>Avril</option>
                                                <option value="5" {if $education.to_month=='5'}selected{/if}>Mai</option>
                                                <option value="6" {if $education.to_month=='6'}selected{/if}>Juin</option>
                                                <option value="7" {if $education.to_month=='7'}selected{/if}>Juillet</option>
                                                <option value="8" {if $education.to_month=='8'}selected{/if}>Ao&ucirc;t</option>
                                                <option value="9" {if $education.to_month=='9'}selected{/if}>Septembre</option>
                                                <option value="10" {if $education.to_month=='10'}selected{/if}>Octobre</option>
                                                <option value="11" {if $education.to_month=='11'}selected{/if}>Novembre</option>
                                                <option value="12" {if $education.to_month=='12'}selected{/if}>D&eacute;cembre</option>
                                            </select>
                                            &nbsp;&nbsp;<input class="input-small inline" type="text" id="end_train_year_{$edu_index}" placeholder="Ann&eacute;e" value="{$education.to_year}" name="end_train_year[]" style="position:relative;top: -5px;">
                                        </div>
                                        <label class="uni-checkbox">
                                            <input type="checkbox" id="still_training_{$edu_index}" class="uni_style" data-target="#stillTrainingThere_{$edu_index}" name="still_training[]" data-toggle="collapse" {if $education.still_working =='yes'} checked {/if}>Je suis toujours en formation
                                        </label>
                                        <input type="hidden" name="training_identifier[]" value="{$education.identifier}">
                                    </div>
                                </div>
                            </div>
                            <!-- end, school row -->
                            {/foreach}
                            <p class="addmore-button" id="addmore_training_link" onclick="addTraining({$edu_index});" ><a  class="btn btn-link btn-small"><i class="icon-plus"></i> Ajouter une formation</a></p>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End, Training module -->
            <hr />
                <!-- Start, billing info module -->
                <div class="formSep" id="pay_info_type">
                    <div class="row-fluid">
                        <div class="control-group">
                            <label class="control-label span2 offset1" for=""><strong>Informations de facturation {if $smarty.get.profile eq 'invoice'}<span class="error">*</span>{/if}</strong> <span class="help-block">Cette information pourra &ecirc;tre renseign&eacute;e &agrave; l'&eacute;dition de la 1&egrave;re facture</span></label>
                            <div class="controls span8">
                                <label class="uni-radio">
                                    <input type="radio" name="payinfo" value="ssn" class="uni_style" {if $pay_info_type=='ssn'} checked class="collapsed" {/if} data-target="#national-InsuranceNum" data-toggle="collapse">Droit d'auteur (AGESSA).
                                </label>
                                <!-- if AGESSA is true, display the input "National Insurance number" -->
                                <div id="national-InsuranceNum" {if $pay_info_type=='ssn'} class="collapse in out" {else} class="collapse out" {/if}>
                                <i class="icon-arrow-right"></i> <input type="text" class="span4" placeholder="Num&eacute;ro de s&eacute;curit&eacute; sociale" name="ssn" id="ssn" value="{$SSN}">
                            </div>

                            <label class="uni-radio">
                                <input type="radio" name="payinfo" value="comp_num" class="uni_style" {if $pay_info_type=='comp_num'} checked class="collapsed" {/if} data-target="#siretNum" data-toggle="collapse">Autoentrepreneur
                            </label>
                            <!-- if Autoentrepreneur is true, display the input "SIRET number" -->
                            <div id="siretNum" {if $pay_info_type=='comp_num'} class="collapse in out" {else} class="collapse out" {/if}>
                            <i class="icon-arrow-right"></i> <input type="text" class="span4" placeholder="Votre n&deg; de Siret pour les factures" name="company_number" id="company_number" value="{$company_number}">
                            <label class="uni-checkbox"><input type="checkbox"  name="vat_check" class="uni_style" data-target="#TVANum" data-toggle="collapse" value="YES" id="vat_check" {if $vat_check=='YES' } checked {/if}>Cochez cette case si vous &ecirc;tes soumis &agrave; la TVA</label>
                            <div id="TVANum" {if $vat_check=='YES'} class="collapse in out" {else} class="collapse out" {/if}>
                            <i class="icon-arrow-right"></i> <input type="text" class="span4" placeholder="TVA" name="VAT_number" id="VAT_number" value="{if $vat_check=='YES'}{$VAT_number}{/if}" >
                        </div>
                    </div>
                    <label class="uni-radio">
                        <input type="radio" name="payinfo" value="out_france" class="uni_style" {if $pay_info_type=='out_france'} checked {/if}>Statut hors France
                        <div class="help-block">Pour ce statut, une adresse postale &eacute;trang&egrave;re suffit, merci de v&eacute;rifier qu'elle est bien renseign&eacute;e. Merci de cocher le syst&egrave;me de paiement par virement. Les frais bancaires seront &agrave; votre charge. </div>
                    </label>
                    <br>
                    <span id="payinfo_error"></span>
                </div>
              </div>
              </div>
             </div>
             <!-- End, billing info module 9949666110-->


            <hr />
             <!-- Start, payment info module -->
             <div class="formSep">
                 <div class="row-fluid">
                     <div class="control-group">
                         <label class="control-label span2 offset1" for=""><strong>Choix de r&eacute;mun&eacute;ration {if $smarty.get.profile eq 'invoice'}<span class="error">*</span>{/if} </strong></label>
                         <div class="controls span8">
                             <label class="uni-radio">
                                 <input type="radio" value="paypal" class="uni_style" {if $payment_type == 'paypal'}checked class="collapsed"{/if} name="payment_type" data-target="#paypalEmail" data-toggle="collapse">Paypal
                             </label>
                             <!-- if Payapl is true, display the input "paypal email" -->
                             <div id="paypalEmail" {if $payment_type=='paypal'} class="collapse in out" {else} class="collapse out" {/if} >
                             <i class="icon-arrow-right"></i> <input type="text" class="span4" placeholder="paypal email" name="paypal_id" id="paypal_id" value="{$paypal_id}">
                         </div>
                         <label class="uni-radio" id="cheque_radio" {if $pay_info_type=='out_france' || $user_detail[0].country!=38} style="display:none" {/if}>
                         <input type="radio" value="cheque" class="uni_style" {if $payment_type == 'cheque'}checked{/if} name="payment_type">Ch&egrave;que
                         </label>
                         <label class="uni-radio">
                             <input type="radio" value="virement" class="uni_style" {if $payment_type == 'virement'}checked{/if} name="payment_type">Virement bancaire
                         </label>
                         <!-- if virement is true, display the input "paypal email" -->
                         <div id="virementId" {if $payment_type=='virement'} class="collapse in out" {else} class="collapse in" {/if} >
                         <div id="c_france" {if $pay_info_type!='out_france' && $payment_type == 'virement' && $user_detail[0].country==38 }style="display:block"{else}style="display:none"{/if}>
                         <i class="icon-arrow-right"></i>
                         <input type="text" value="{$rib_id_1}"  placeholder="Nom de l'&eacute;tablissemen" name="rib_id_1" id="rib_id_1"/>
                         <input type="text" value="{$rib_id_2}"  placeholder="Code Banque" name="rib_id_2" id="rib_id_2"/>
                         <input type="text" value="{$rib_id_3}"  placeholder="Code Guichet" name="rib_id_3" id="rib_id_3"/>
                         <input type="text" value="{$rib_id_4}"  placeholder="Num&eacute;ro de compte" name="rib_id_4" id="rib_id_4"/>
                         <input type="text" value="{$rib_id_5}"  placeholder="Cl&eacute; RIB" name="rib_id_5"  id="rib_id_5"/>
                     </div>
                     <div  id="c_out_france" {if ($pay_info_type=='out_france' && $payment_type == 'virement') || $user_detail[0].country!=38 }style="display:block"{else}style="display:none"{/if}>
                     <i class="icon-arrow-right"></i>
                     <input type="text" value="{$rib_id_6}"  placeholder="BIC" name="rib_id_6" id="rib_id_6"/>
                     <input type="text" value="{$rib_id_7}"  placeholder="IBAN" name="rib_id_7" id="rib_id_7"/>
                 </div>
             </div>
             <br>
             <span id="payment_error"></span>
            </div>
            </div>
            </div>
            </div>


            <hr />
            <!-- added by naseer on 31-07-2015 -->
            <!-- company details -->
            <div class="formSep">
                <div class="row-fluid" >
                    <!-- passport and id card details-->
                    <div class="control-group">
                        <label class="radio controls span1 offset1">
                            <input type="radio" type="radio" name="options_flag" id="reg_check" value="reg_check" onclick="toggle_details('reg_check_details');" {if  $user_detail[0].options_flag eq 'reg_check'}checked{/if}>
                        </label>
                        <label class="span2" for="reg_check">
                            <strong>En cours d'immatriculation </strong>
                        </label>
                        <div class="controls span8">
                            <div id="reg_check_details" class="details {if  $user_detail[0].options_flag neq 'reg_check'}hide{/if}">
                                <label><input class="span5" id="passport_no" name="passport_no" placeholder="Num&eacute;ro de passeport" value="{ $user_detail[0].passport_no}"></label>
                                <label><input class="span5" id="id_card" name="id_card" placeholder="Carte d'identit&eacute;" value="{ $user_detail[0].id_card}"></label>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="formSep">
                <div class="row-fluid" >
                    <div class="control-group">
                        <label class="radio controls span1 offset1">
                            <input type="radio" type="radio" name="options_flag"  id="com_check" value="com_check" onchange="toggle_details('company_details');" {if  $user_detail[0].options_flag eq 'com_check'}checked{/if}>
                        </label>
                        <label class="span2 " for="com_check">
                            <strong>Soci&eacute;t&eacute; </strong>
                        </label>

                        <div class="controls span8">
                            <div id="company_details" class="details {if  $user_detail[0].options_flag neq 'com_check'}hide{/if}">
                                <label><input class="span5" id="com_name" name="com_name" placeholder="D&eacute;nomination sociale" value="{ $user_detail[0].com_name}"><span class="error">*</span></label>
                                <label><input class="span5" id="com_address" name="com_address" placeholder="Adresse" value="{ $user_detail[0].com_address}"><span class="error">*</span></label>
                                <label><input class="span5" id="com_city" name="com_city" placeholder="Ville" value="{ $user_detail[0].com_city}"><span class="error">*</span></label>
                                <label><input class="span5" id="com_zipcode" name="com_zipcode" placeholder="Code postal" value="{ $user_detail[0].com_zipcode}"><span class="error">*</span></label>
                                <label>
                                    <select class="span5" name="com_country" id="com_country" onchange="toggle_com_siren();">
                                        <option value="">Pays</option>
                                        {html_options  options=$nationality_array selected= $user_detail[0].com_country}
                                    </select><span class="error">*</span>
                                </label>
                                <label id="com_siren_label"  {if  $user_detail[0].com_country neq "38"}style="display: none;"{/if}>
                                <input class="span5" name="com_siren" id="com_siren" placeholder="Siren" value="{$user_detail[0].com_siren}" /><span class="error">*</span>
                                </label>

                                <label><input class="span5" id="com_tva_number" name="com_tva_number" placeholder="Num&eacute;ro de TVA Intracommunautaire" value="{$user_detail[0].com_tva_number}"><span class="error">*</span></label>
                                <label><input class="span5" id="com_phone" name="com_phone" placeholder="T&eacute;l&eacute;phone" value="{$user_detail[0].com_phone}"><span class="error">*</span></label>
                            </div>
                        </div>
                    </div>

                    {* <!--<div class="control-group">
                                    <label class="control-label span2 offset1" for=""><strong>Num&eacute;ro SIREN<span class="error">*</span></strong></label>
                                    <div class="controls span8">
                                        <div class="form">
                                            <label><input type="text" placeholder="Num&eacute;ro SIREN" class="inline input-large" value="{$siren_number}" name="siren_number" id="siren_number"></label>
                                        </div>
                                    </div>
                                </div> --> *}
                </div>
            </div>
            <div class="formSep">
                <div class="row-fluid" >
                    <div class="control-group">

                        <label class="radio controls span1 offset1">
                            <input  type="radio" type="radio" name="options_flag" id="tva_check" value="tva_check" onchange="toggle_details('tva_details');"  {if  $user_detail[0].options_flag == 'tva_check'}checked{/if} >
                        </label>
                        <label class="controls span2 " for="tva_check">
                            <strong>Auto-entrepreneur</strong>
                        </label>
                        </label>
                        <div class="controls span6">
                            <div id="tva_details" class="details {if  $user_detail[0].options_flag neq 'tva_check'}hide{/if}">
                                <div id="tvanumber" >
                                    <label>
                                        <input type="text" class="span4" placeholder="Num&eacute;ro de TVA Intracommunautaire" name="tav_number" id="tav_number" value="{ $user_detail[0].tva_number}">
                                    </label>
                                </div>
                                <span id="payinfo_error"></span>
                            </div>
                        </div>
                    </div>
                    <div class="control-group" align="center">
                        <input style="width:0px; height: 0px; border-color:#FFF; box-shadow: none;" type="text"  id="option_group" name="option_group"  value="">
                    </div>
                </div>
            </div>

            <!-- company details ends here -->
            <hr />
            <!-- bo user editables -->

            <div class="formSep">
                <div class="row-fluid">
                    <div class="span6 form-inline">
                        <label class="span4">Status </label>
                        <label class="uni-radio"> <input type="radio" name="status" value="Active" class="uni_style" {if $user_detail[0].status == "Active"}checked{/if}/>Active&nbsp;   </label>
                        <label class="uni-radio"><input type="radio" name="status" value="Inactive" class="uni_style" {if $user_detail[0].status == "Inactive"}checked{/if}/>Inactive   </label>
                    </div>
                    <div class="span6 form-inline">
                        <label class="span4">Type </label>
                        <label class="uni-radio"> <input type="radio" name="profile_type" value="senior" class="uni_style"{if $user_detail[0].profile_type == "senior"}checked{/if}/>Senior&nbsp; </label>
                        <label class="uni-radio"> <input type="radio" name="profile_type" value="junior" class="uni_style"{if $user_detail[0].profile_type == "junior"}checked{/if}/>Junior&nbsp; </label>
                        <label class="uni-radio"> <input type="radio" name="profile_type" value="sub-junior" class="uni_style" {if $user_detail[0].profile_type == "sub-junior"}checked{/if}/>Sub Junior </label>
                    </div>
                </div>
            </div>
            <div class="formSep">
                <div class="row-fluid">
                    <div class="span6 form-inline">
                        <label class="span4">Corrector </label>
                        <label class="uni-radio"><input type="radio" name="type2" value="yes" class="uni_style" {if $user_detail[0].type2== "corrector"}checked{/if} onClick="showtype2('yes');"/>Yes&nbsp; </label>
                        <label class="uni-radio"><input type="radio" name="type2" value="no" class="uni_style" {if $user_detail[0].type2 == "no" || $user_detail[0].type2 == ""}checked{/if} onClick="showtype2('no');"/>No  </label>
                        <div id="type2block" {if $user_detail[0].type2==""}style="display:none;"{/if}></div>
                    </div>
                    <div class="span6 form-inline">
                        <label class="span4">Corrector Statut</label>
                        <label class="uni-radio"><input type="radio" name="profile_type2" value="senior" class="uni_style" {if $user_detail[0].profile_type2 == "senior"}checked{/if}/>Senior&nbsp;  </label>
                        <label class="uni-radio"> <input type="radio" name="profile_type2" value="junior" class="uni_style" {if $user_detail[0].profile_type2 == "junior" || $user_detail[0].profile_type2 == ""}checked{/if}/>Junior  </label>
                    </div>
                </div>
            </div>
            <div class="formSep">
                <div class="row-fluid">
                    <div class="span6 form-inline">
                        <label class="span4">Black list </label>
                        <label class="uni-radio"><input type="radio" name="blackstatus" value="yes" class="uni_style" {if $user_detail[0].blackstatus == "yes"}checked{/if}/>Yes&nbsp; </label>
                        <label class="uni-radio"><input type="radio" name="blackstatus" value="no" class="uni_style" {if $user_detail[0].blackstatus == "no"}checked{/if}/>No</label>
                    </div>
                </div>
            </div>
            <hr />
            <!-- User test -->
            <div class="formSep">
                <div class="row-fluid">
                    <div class="span6 form-inline">
                        <label class="span5">Ce contributeur a &eacute;t&eacute; test&eacute;</label>
                        <label class="uni-radio"> <input type="radio" name="contributortest" value="yes" class="uni_style" {if $user_detail[0].contributortest == "yes"}checked{/if} onClick="showremarks('yes');" />Oui&nbsp;   </label>
                        <label class="uni-radio"><input type="radio" name="contributortest" value="no" class="uni_style" {if $user_detail[0].contributortest == "no"}checked{/if} onClick="showremarks('no');" />Non   </label>
                    </div>
                    <div class="span6 form-inline" id="remarksblock" {if $user_detail[0].contributortest=="no"}style="display:none;"{/if}>
                        <div style="float:left">
                            <textarea name="contributortestcomment" id="contributortestcomment" placeholder="Commentaire (Obligatoire, 70 caract&egrave;res minimum)" rows="5" style="width:300px">{$user_detail[0].contributortestcomment}</textarea>
                            <span id="contributortestcomment_count" style="vertical-align:top"></span>
                        </div>
                        {assign var="foo" value="1"}
                        <div>
                            <select name="contributortestmark" id="contributortestmark" style="width:80px;margin-left:90px">
                                <option value="">Note</option>
                                {while $foo < 21}
                                <option value="{$foo}" {if $user_detail[0].contributortestmarks == $foo}selected{/if}>{$foo}</option>
                                {$foo++}
                                {/while}
                            </select>
                        </div>
                    </div>
                </div>
            </div>

            <!-- end of bo user editables -->
            <div class="formSep">
                <div class="row-fluid">
                    <div class="span6 form-inline">
                        <input type="submit" name="submit_contrib" value="Submit" id="submit_contrib" class="btn btn-info pull-right"> </input>
                    </div>
                </div>
            </div>
            <input type="hidden" name="prev_profile" id="prev_profile" value="{$user_detail[0].profile_type}" />
            <input type="hidden" name="prev_profile2" id="prev_profile2" value="{$user_detail[0].profile_type2}" />
            <input type="hidden" name="userId" id="userId" value="{$smarty.get.userId}" />
        </form>
    </div>

<!------------------------------------------------------------- Contributor view ---------------------------------------------------->
    <div id="viewcontrib" class="tab-pane">
        {literal}<style>#view_table td{text-align: left;}</style>{/literal}
        <table class="table table-striped table-bordered table-condensed span8" id="view_table" >
            <tr>
                <td colspan="2">
                    <div class="row-fluid ">
                       <div class="pull-left">
                            <h3 >{if $user_detail[0].first_name != ''}
                                {$user_detail[0].first_name}&nbsp;{$user_detail[0].last_name}
                                {else}
                                {$user_detail[0].email}
                                {/if} </h3>
                            <div style="height:10px;"></div>
                            <!--<button onclick="EditContribInfo('{$user_detail[0].user_id}');" class="btn btn-info" name="editcontrib" type="button"> Edit profile</button>-->
                            <a data-toggle="modal" data-target="#showhistory" href="/user/user-history?user={$user_detail[0].user_id}" class="btn btn-success">history</a>
                            <a class="btn btn-warning" data-hint="Commenter"  data-target="#comments" data-toggle="modal"  name="send_comment"  href="/proofread/getallbousercomments?userId={$user_detail[0].user_id}" >Comment</a>
                            <button onclick="connect_fo('contrib');" class="btn btn-danger" name="editclient" type="button"> Connect to fo </button>
                        </div>
                        <div class="pull-right " style="height:70px;">
                            <img alt="contributor pic" src="{$user_pic}" class="fileupload-new thumbnail1 pull-right">
                        </div>
                    </div>
                </td>
            </tr>
            <tr>
                <td  colspan="2" >
                    <div class="row-fluid">
                        <h4>INFORMATIONS PERSONNELLES</h4>
                        <dl>
                            <dd><strong>Email :</strong> {$user_detail[0].email}</dd>
                            {if $groupId eq 1}
                            <dd><strong>Password :</strong> {$user_detail[0].password}</dd>
                            {/if}
                            <br />
                            <dd><strong>Date de naissance :</strong> {$user_detail[0].dob|date_format:"%d/%m/%Y"}</dd>
                            <dd><strong>Langue de r&eacute;daction 1 :</strong> {$language}</dd>
                            <dd><strong>Langue de r&eacute;daction 2 :</strong> {$user_detail[0].language_more|replace:',':', '}</dd>
                            <dd>
                                <address>
                                    <strong>Adresse :</strong> {$user_detail[0].address}
                                    <br />
                                    <strong>Ville :</strong> {$user_detail[0].city}, Code Postal : {$user_detail[0].zipcode}
                                    <br />
                                    <strong>Nationalit&eacute; :</strong> {$nationality}
                                    <br />
                                    <strong>T&eacute;l&eacute;phone :</strong> {$user_detail[0].phone_number}
                                </address>
                            </dd>
                            <dd><strong>Subscription (nl) :</strong> {$user_detail[0].subscribe}</dd>
                            <dd><strong>Subscription (alert) :</strong> {$user_detail[0].alert_subscribe}</dd>
                            <dd><strong>Pays :</strong> {$country_name}</dd>
                        </dl>
                    </div>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <strong>Cat&eacute;gories pr&eacute;f&eacute;r&eacute;es </strong>: {$user_detail[0].category_more|replace:',':', '}
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <strong>Experience </strong>: {if $educationDetailsview neq ""}
                    <table class="table table-striped table-bordered table-condensed">
                        <tr class="alpbold"><td>Designation</td><td>Company</td><td>Duration</td></tr>
                        {foreach from=$educationDetailsview key=exp_key item=exp_item}
                        <tr><td>{$exp_item.title}</td><td>{$exp_item.institute}</td><td>{$exp_item.start_date} to {$exp_item.end_date}</td></tr>
                        {/foreach}
                    </table>
                    {else}
                    not available
                    {/if}
                </td>
            </tr>
            <!--<tr>
                <td colspan="2">
                    <h4>Formation</h4>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <h4>Informations de facturation</h4>
                </td>
            </tr>
            <tr>
                <td colspan="2">
                    <h4>Choix de r&eacute;mun&eacute;ration</h4>
                </td>
            </tr>-->


            <tr>
                <td colspan="2">
                    <strong>Status : </strong>{$user_detail[0].status}<br />
                    <strong>Type : </strong>{$user_detail[0].profile_type}<br />
                    <strong>Corrector : </strong>{if $user_detail[0].type2==""}no{else}{$user_detail[0].type2}{/if}<br />
                    {if $user_detail[0].type2=="corrector"}
                        <strong>Corrector Statut : </strong>{$user_detail[0].profile_type2}<br />
                    {/if}
                    <strong>Black list : </strong>{$user_detail[0].blackstatus}<br />
                    <strong>Pr&eacute;nom : </strong>{$user_detail[0].first_name}<br />
                    <strong>Nom : </strong>{$user_detail[0].last_name}<br />
                    {if $user_detail[0].profession=='option5'}
                        <strong>Profession : </strong>{$profession}<br />
                    {/if}
                    <strong>University : </strong>{$user_detail[0].university}<br />
                    <strong>Niveau d'&eacute;tudes : </strong>{$education}<br />
                    <strong>Diplôme obtenu : </strong>{$user_detail[0].degree}<br />
                </td>

            <tr>
                <td class="span3"><span class="pull-right alpbold">Download CV</span> </td>
                <td class="span9"><span class="pull-left ">{if $user_detail[0].cv_file neq ""}
                <a href="/ao/users?submenuId={$submenuId}&cv_path={$user_detail[0].cv_file}" >download</a>
                {else} not available {/if}
                </span></td>
            </tr>
            <tr>
               </td>
            </tr>
            <tr>
                <td class="span3"><span class="pull-right alpbold">Texte de pr&eacute;sentation</span></td>
                <td class="span9"><span class="pull-left ">{$user_detail[0].self_details|wordwrap:30}</span></td>
            </tr>
            <tr>
                <td class="span3"><span class="pull-right alpbold">Payment</span></td>
                <td class="span9"><span class="pull-left ">
                {if $pay_info_type!='out_france' && $payment_type == 'virement' && $user_detail[0].country==38 }
                    {if ($rib_id_1 neq '') && ($rib_id_2 neq '') && ($rib_id_3 neq '') && ($rib_id_4 neq '') && ($rib_id_5 neq '')}
                        <div><strong>RIB : </strong>{$rib_id_1} {$rib_id_2} {$rib_id_3} {$rib_id_4} {$rib_id_5} </div>
                    {/if}
                {else}
                    {if ($rib_id_6 neq '') && ($rib_id_7 neq '')}
                        <div><strong>BIC : </strong>{$rib_id_6} <strong>IBAN :</strong> {$rib_id_7}</div>
                    {/if}
                {/if}
                </td>
            </tr>
			<tr>
                <td class="span3"><span class="pull-right alpbold">Download Contract</span></td><td class="span9"><span class="pull-left "><a href="/ongoing/download-contract?user_id={$user_detail[0].user_id}" >Download</a></span></td>
            </tr>
			<tr>
				 <td class="span3"><span class="pull-right alpbold">Ce contributeur a &eacute;t&eacute; test&eacute;</td>
				 <td class="span9">
					<span class="pull-left ">
						{if $user_detail[0].contributortest=="yes"}
							Oui
							<!--<br><b>Comment</b>: {$user_detail[0].contributortestcomment}<br>
							<b>Marks</b>: {$user_detail[0].contributortestmarks}-->
						{else}
							Non
						{/if}
					</span>
				</td>
			</tr>



        </table>
    </div>
    <!-- writer statistics-->
    <div id="writerstats" class="tab-pane">

        <div class="formSep">
            <div class="row-fluid">
                <div class="span4 form-inline">
                    <label class="span4">Filtrer par langue(s) </label>
                    <select  id=graph_language name=graph_language   data-placeholder="Select Langue" onchange="changeGraph('{$smarty.get.userId}', 'writer');">
                        <option value="0"> </option>
                        {html_options  id=language options=$language_array selected=$language }
                    </select>
                </div>
                <div class="span4 form-inline">
                    <label class="span4">Filtrer par cat&eacute;gorie(s) </label>
                    <select  name="graph_category" id="graph_category" data-placeholder="select category" onchange="changeGraph('{$smarty.get.userId}', 'writer');">
                        <option value=""></option>
                        {html_options options=$category_array selected=$user_detail[0].category}
                    </select>
                </div>
                <div class="span4 form-inline">
                    <label class="span4">Date </label>
                    <input type="text" name="graph_date" onchange="changeGraph('{$smarty.get.userId}', 'writer');" placeholder="select date" id="dp1" readonly data-date-format="dd-mm-yyyy" value="{$smarty.get.startdate}"/>
                </div>
            </div>
        </div>
        <div class="formSep" id="writergraph">
            <div class="row-fluid">
                <div class="span6" style="width: 600px;">
                    <h3 class="heading pull-center">Mark</h3>
                    <div id="monthlyGraph" style="height:270px;width:100%;margin:15px auto 0"></div>
                    <!-- <div id="fl_m" style="height:270px;width:100%;margin:15px auto 0"></div>-->
                </div>
            </div>
        </div>
        <div class="formSep">
            <div class="row-fluid">
                <div class="span6">
                    <h3 class="heading pull-center">Moyennes</h3>
                    <table class="table table-striped table-bordered table-condensed span9">
                        <tr>
                            <td class="span3"><span class="pull-right alpbold">G&eacute;n&eacute;rale :</span></td>
                            <td class="span9"><span class="pull-left ">
                                    <select  name="moy_user_type" id="moy_user_type" onchange="getMoyennes('{$smarty.get.userId}')">
                                        <option value="0">ALL</option>
                                        <option value="1">Correcteur FO</option>
                                        <option value="2">Edit-Place (internal correction)</option>
                                    </select>
                                </span><span class="alert alert-error pull-right" style="padding:10px;margin-bottom:0px;font: bold;" id="moy_stats"></span></td>
                        </tr>
                        <tr>
                            <td class="span3"><span class="pull-right alpbold">Langue(s) : </span></td>
                            <td class="span9"><span class="pull-left ">
                                    <select  name="moy_language" id="moy_language" data-placeholder="select language" onchange="getMoyennes('{$smarty.get.userId}')">
                                        <option value="0"> </option>
                                        {html_options  id=language options=$language_array selected=$language }
                                    </select>
                                </span><span class="alert alert-info pull-right" style="padding:10px;margin-bottom:0px;font: bold;" id="moy_lang_stats"></span></td>
                        </tr>
                        <tr>
                            <td class="span3"><span class="pull-right alpbold">Cat&eacute;gorie(s) :</span></td>
                            <td class="span9"><span class="pull-left ">
                                    <select  name="moy_category" id="moy_category" data-placeholder="select category" onchange="getMoyennes('{$smarty.get.userId}')">
                                        <option value="0"></option>
                                        {html_options options=$category_array selected=$user_detail[0].language}
                                    </select>
                                </span><span class="alert alert-success pull-right" style="padding:10px;margin-bottom:0px;font: bold;" id="moy_categ_stats"></span></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="formSep">
            <h3 class="heading pull-center bold">Statistiques</h3>
            <div class="row-fluid">

                <div class="span6 form-inline">
                    <label class="span4">Filtrer par langue(s)</label>
                    <select  name="stats_language" id="stats_language" data-placeholder="select language" onchange="getStatistics('{$smarty.get.userId}')">
                        <option value="">  </option>
                        {html_options  options=$language_array  }
                    </select>
                </div>
                <div class="span6 form-inline">
                    <label class="span4">Filtrer par cat&eacute;gorie(s)</label>
                    <select  name="stats_category" id="stats_category" data-placeholder="select category" onchange="getStatistics('{$smarty.get.userId}')">
                        <option value=""> </option>
                        {html_options options=$category_array }
                    </select>
                </div>
            </div>
        </div>

        <label class="span5 alert alert-info" >Nombre de s&eacute;lections / total participations : <span id="selected">{$selected_arts}/{$total_parts}
            ({if $selected_arts && $total_parts neq "" }{$selected_arts/$total_parts|string_format:"%.2f"}{else}0{/if} %)</span></label>
        <label class="span5 alert alert-danger" >Nombre d'articles valid&eacute;s : <span id="validated">{$published_arts}/{$total_parts}
            ({if $published_arts && $total_parts neq "" }{$published_arts/$total_parts|string_format:"%.2f"}{else}0{/if} %)</span></label>
        <label class="span5 alert alert-success" >Nombre d'articles refus&eacute;s pour resoumission : <span id="republished">{$republished}/{$total_parts}
            ({if $republished && $total_parts neq "" }{$republished/$total_parts|string_format:"%.2f"}{else}0{/if} %)</span></label>
        <label class="span5 alert alert-success" id="">Raison du refus pour resoumission la plus fr&eacute;quente : <span id="refusedreasons">{$freqtempreason}  {$freqtempreasoncount}/{$total_refusalreasons}
            ({if $freqtempreasoncount && $total_refusalreasons neq "" }{$freqtempreasoncount/$total_refusalreasons|string_format:"%.2f"}{else}0{/if} %)<a class="hint--bottom hint--info" data-hint="Refuse reasons"  data-target="#refusereasonslist" data-toggle="modal"  name="send_comment"  href="/user/refused-reasons?userid={$smarty.get.userId}&type=temp" >Voir plus</a></span></label>
        <label class="span5 alert alert-info">Nombre d'articles refus&eacute;s :<span id="refused"> {$refused_arts}/{$total_parts}
            ({if $refused_arts && $total_parts neq "" }{$refused_arts/$total_parts|string_format:"%.2f"}{else}0{/if} %)</span></label>
        <label class="span5 alert alert-gebo">Raison du refus la plus fr&eacute;quente  : <span id="refusedreasonscrt"> {$freqpermreason}  {$freqpermreasoncount}/{$total_refusalreasons}
            ({if $freqpermreasoncount && $total_refusalreasons neq "" }{$freqpermreasoncount/$total_refusalreasons|string_format:"%.2f"}{else}0{/if} %) <a class="hint--bottom hint--info" data-hint="Refuse reasons corrector"  data-target="#refusereasonslist" data-toggle="modal"  name="send_comment"  href="/user/refused-reasons?userid={$smarty.get.userId}&type=perm" >Voir plus</a></span></label>
        <label class="span5 alert alert-success">Nombre de retards :<span id="notsubmited"> {$arts_notsubmited}/{$total_parts}
            ({if $arts_notsubmited && $total_parts neq "" }{$arts_notsubmited/$total_parts|string_format:"%.2f"}{else}0{/if} %)</span></label>
        <label class="span5 alert alert-info">Nombre de clients avec lesquels il a travaill&eacute; :<span id="numclients"> {$num_clients}</span></label>
        <label class="span5 alert alert-info">Noms des clients : <span id="clientlist">{$client_list}</span></label>
    </div>
       <!--statistics in corrector aspect-->
    <div id="correctorstats" class="tab-pane">

   <div class="formSep">
        <div class="row-fluid">
            <div class="span4 form-inline">
                <label class="span4">Filtrer par langue(s) </label>
                <select  id=crtgraph_language name=crtgraph_language   data-placeholder="Select Langue" onchange="changeGraph('{$smarty.get.userId}', 'corrector');">
                    <option value="0"> </option>
                    {html_options  id=language options=$language_array selected=$language }
                </select>
            </div>
            <div class="span4 form-inline">
                <label class="span4">Filtrer par cat&eacute;gorie(s) </label>
                <select  name="crtgraph_category" id="crtgraph_category" data-placeholder="select category" onchange="changeGraph('{$smarty.get.userId}', 'corrector');">
                    <option value=""></option>
                    {html_options options=$category_array selected=$user_detail[0].category}
                </select>
            </div>
            <div class="span4 form-inline">
                <label class="span4">Date </label>
                <input type="text" name="crtgraph_date" onchange="changeGraph('{$smarty.get.userId}', 'corrector');" placeholder="select date" id="dp" readonly data-date-format="dd-mm-yyyy" value="{$smarty.get.startdate}"/>
            </div>
        </div>
    </div>
    <div class="formSep" id="correctorgraph">
        <div class="row-fluid">
            <div class="span6" id="cstmm">
                <h3 class="heading pull-center">Mark</h3>
                <div id="crtmonthlyGraph" style="height:270px;width:100%;margin:15px auto 0"></div>
                <!-- <div id="fl_m" style="height:270px;width:100%;margin:15px auto 0"></div>-->
            </div>

        </div>
    </div>
    <div class="formSep">
        <div class="row-fluid">
            <div class="span6">
                <h3 class="heading pull-center">Moyennes</h3>
                <table class="table table-striped table-bordered table-condensed span9">
                    <tr>
                        <td class="span3"><span class="pull-right alpbold">G&eacute;n&eacute;rale :</span></td>
                        <td class="span9"><span class="pull-left ">
                                    <select  name="crtmoy_user_type" id="crtmoy_user_type" onchange="getCrtMoyennes('{$smarty.get.userId}')">
                                        <option value="0">ALL</option>
                                        <option value="1">Correcteur FO</option>
                                        <option value="2">Edit-Place (internal correction)</option>
                                    </select>
                                </span><span class="alert alert-error pull-right" style="padding:10px;margin-bottom:0px;font: bold;" id="crtmoy_stats"></span></td>
                    </tr>
                    <tr>
                        <td class="span3"><span class="pull-right alpbold">Langue(s) : </span></td>
                        <td class="span9"><span class="pull-left ">
                                    <select  name="crtmoy_language" id="crtmoy_language" data-placeholder="select language" onchange="getCrtMoyennes('{$smarty.get.userId}')">
                                        <option value="0"> </option>
                                        {html_options  id=language options=$language_array selected=$language }
                                    </select>
                                </span><span class="alert alert-info pull-right" style="padding:10px;margin-bottom:0px;font: bold;" id="crtmoy_lang_stats"></span></td>
                    </tr>
                    <tr>
                        <td class="span3"><span class="pull-right alpbold">Cat&eacute;gorie(s) :</span></td>
                        <td class="span9"><span class="pull-left ">
                                    <select  name="crtmoy_category" id="crtmoy_category" data-placeholder="select category" onchange="getCrtMoyennes('{$smarty.get.userId}')">
                                        <option value="0"></option>
                                        {html_options options=$category_array selected=$user_detail[0].language}
                                    </select>
                                </span><span class="alert alert-success pull-right" style="padding:10px;margin-bottom:0px;font: bold;" id="crtmoy_categ_stats"></span></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="formSep">
        <h3 class="heading pull-center bold">Statistiques</h3>
        <div class="row-fluid">

            <div class="span6 form-inline">
                <label class="span4">Filtrer par langue(s)</label>
                <select  name="crtstats_language" id="crtstats_language" data-placeholder="select language" onchange="getCrtStatistics('{$smarty.get.userId}')">
                    <option value=""> </option>
                    {html_options  id=language options=$language_array selected=$language }
                </select>
            </div>
            <div class="span6 form-inline">
                <label class="span4">Filtrer par cat&eacute;gorie(s)</label>
                <select  name="crtstats_category" id="crtstats_category" data-placeholder="select category" onchange="getCrtStatistics('{$smarty.get.userId}')">
                    <option value=""></option>
                    {html_options options=$category_array selected=$user_detail[0].category}
                </select>
            </div>
        </div>
    </div>

    <label class="span4 alert alert-info" >Nombre de s&eacute;lections / total participations : <span id="crtselected">{$crtselected_arts}/{$crttotal_parts}
            ({if $crtselected_arts && $crttotal_parts neq ''}{$crtselected_arts/$crttotal_parts}{else}0{/if} %)</span></label>
    <label class="span6 alert alert-danger" >Nombre d'articles valid&eacute;s : <span id="crtvalidated">{$crtpublished_arts}/{$crttotal_parts}
            ({if $crtpublished_arts && $crttotal_parts neq ''}{$crtpublished_arts/$crttotal_parts}{else}0{/if} %)</span></label>
    <label class="span4 alert alert-success" >Nombre d'articles refus&eacute;s pour resoumission : <span id="crttimeout">{$crtrepublished}/{$crttotal_parts}
            ({if $crtrepublished && $crttotal_parts neq ''}{$crtrepublished/$crttotal_parts}{else}0{/if} %)</span></label>
    <label class="span6 alert alert-success" id="">Raison du refus la plus fr&eacute;quente :<span id="crtrefusedreasons"> {$freqcrttempreason} {$freqcrttempreasoncount}/{$crttotal_refusalreasons}
            ({if $crtrefusalreasons && $crttotal_refusalreasons neq ''}{$crtrefusalreasons/$crttotal_refusalreasons|string_format:"%.2f"}{else}0{/if} %)</span><a class="hint--bottom hint--info" data-hint="Refuse reasons"  data-target="#refusereasonslist" data-toggle="modal"  name="send_comment"  href="/user/refused-reasons?userid={$smarty.get.userId}&type=crttemp" >Voir plus</a></label>
    <label class="span4 alert alert-info">Nombre d'articles refus&eacute;s :<span id="crtrefused"> {$crtrefused_arts}/{$crttotal_parts}
            ({if $crtrefused_arts && $crttotal_parts neq ''}{$crtrefused_arts/$crttotal_parts}{else}0{/if} %)</span></label>
    <label class="span6 alert alert-gebo">Raison du refus la plus fr&eacute;quente :<span id="crtrefusedreasonspercent"> {$freqpermreason} {$freqcrtpermreasoncount}/{$crttotal_refusalreasons}
            ({if $crtrefusalreasons && $crttotal_refusalreasons neq ''}{$crtrefusalreasons/$crttotal_refusalreasons}{else}0{/if} %) </span><a class="hint--bottom hint--info" data-hint="Refuse reasons"  data-target="#refusereasonslist" data-toggle="modal"  name="send_comment"  href="/user/refused-reasons?userid={$smarty.get.userId}&type=crtperm" >Voir plus</a></label>
    <label class="span4 alert alert-success">Nombre de retards :<span id="crtnotsubmited"> {$crtarts_notsubmited}/{$crttotal_parts}
            ({if $crtarts_notsubmited && $crttotal_parts neq ''}{$crtarts_notsubmited/$crttotal_parts}{else}0{/if} %)</span></label>
    <label class="span6 alert alert-info">Nombre de r&eacute;dacteurs not&eacute;s :<span id="crtnumwriters"> {$crtnum_writers} <a class="hint--bottom hint--info" data-hint="Writers List"  data-target="#writerlist" data-toggle="modal"  name="send_comment"  href="/user/writer-list?userid={$smarty.get.userId}" >Voir plus</a></span></label>

</div>
    <div id="writersarts" class="tab-pane" >
        <div class="hide" id="searchblock" >
            <div class="row-fluid">
                <form action={$smarty.server.REQUEST_URI} method="get" id="searchform" name="searchform" >
                    <input type="hidden" id="submenuId" name="submenuId"  value="{$submenuId}"/>
                    <input type="hidden" id="userId" name="userId"  value="{$smarty.get.userId}" />
                    <input type="hidden" id="tab" name="tab"  value="writersarts" />
                    <!--<div class="row-fluid">-->
					<span class="sepV_c">
						<input type="text" placeholder="From" id="dp1" name="startdate" readonly data-date-format="dd-mm-yyyy" value="{$smarty.get.startdate}"/>
					</span>
					<span class="sepV_c">
						<input type="text"  placeholder="To" id="dp2" name="enddate" readonly data-date-format="dd-mm-yyyy" value="{$smarty.get.enddate}"/>
					</span>
					<span class="sepV_c">
						<select name="client_id" id="clients" data-placeholder="Clients" onChange="fnloaddeliveries(this.value);">
                            {html_options  options=$client_array  selected=$smarty.get.client_id}
                        </select>
					</span>
					<span class="sepV_c"  id="aolistall">
						<select name="ao_id" id="deliveries" data-placeholder="Deliveries">
                            {html_options  options=$delivery_array  selected=$smarty.get.ao_id  selected=$smarty.get.ao_id}
                        </select>

					</span>
					<span class="sepV_c">
						<select id="sorttype" name="sorttype" data-placeholder="Trier par">
                            <option value=""></option>
                            <option value="all" {if $smarty.get.sorttype eq 'all'}selected{/if}>ALL</option>
                            <option value="onging" {if $smarty.get.sorttype eq 'onging'}selected{/if}>Ongoing</option>
                            <option value="close" {if $smarty.get.sorttype eq 'close'}selected{/if}>Closed</option>
                            <option value="new" {if $smarty.get.sorttype eq 'new'}selected{/if}>New</option>
                        </select>
					</span>
					<span class="sepV_c">
						<select id="pay_status" name="pay_status" data-placeholder="Payment Status">
                            <option value=""></option>
                            <option value="all" {if $smarty.get.pay_status eq 'all'}selected{/if}>ALL</option>
                            <option value="paid" {if $smarty.get.pay_status eq 'paid'}selected{/if}>Paid</option>
                            <option value="notpaid" {if $smarty.get.pay_status eq 'notpaid'}selected{/if}>Pending</option>
                        </select>
					</span>
                    <!--</div>
                    <div class="row-fluid">-->
					<span class="sepV_c">
						<button class="btn btn-danger pull-center" id="search" name="search" type="submit" value="search" >Search</button>
						<button class="btn btn-info pull-center" id="clear" name="clear" type="button" value="clear" onclick="clearAll();" >Clear</button>
					</span>
                    <!--</div>-->
                </form>

            </div>
        </div>
       <table id="writermissions" class="table table-bordered table-striped table_vam"  >
            <thead>
            <tr>
                <th>Nom de l'article</th>
                <th>Nom de l'annonce</th>
                <th>Nom du client</th>
                <th>Etat</th>
                <th>Correcteur</th>
                <th>Chef de projet</th>
                <th>Langue</th>
                <th>Cat&eacute;gories</th>
                <th>Notes</th>
            </tr>
            </thead>
            <tbody>
            {if $writerstatsarticles neq 'NO'}
            {foreach from=$writerstatsarticles key=writerarts_key item=writerarts_item name=writerarts_loop}
            <tr>
                <td>{$writerarts_item.title|utf8_decode}</td>
                <td>{$writerarts_item.deliveryName|utf8_decode}</td>
                <td>{$writerarts_item.client|utf8_decode}</td>
                <td>{$writerarts_item.lateststatus}</td>
                <td>{if $writerarts_item.corrector neq ''}{$writerarts_item.corrector}{else}-{/if}</td>
                <td>{$writerarts_item.projectManager|utf8_decode}</td>
                <td>{$writerarts_item.language|utf8_decode}</td>
                <td>{$writerarts_item.category|utf8_decode}</td>
                <td>{if $writerarts_item.marks neq ''} {$writerarts_item.marks}/10 <a class="hint--bottom hint--info" data-hint="Commenter" data-target="#markscomments" data-toggle="modal"  name="send_comment"  href="/user/recentcommentsmarks?partid={$writerarts_item.id}&type=writer&userid={$crtarts_item.userId}" >
                        <i class="splashy-comments_reply"></i></a>{else} Nill {/if}</td>
            </tr>
            {/foreach}
            {/if}
            </tbody>
        </table>
    </div>
    <div id="correctorarts" class="tab-pane" >
        <div class="hide" id="searchblock" >
            <div class="row-fluid">
                <form action={$smarty.server.REQUEST_URI} method="get" id="searchform" name="searchform" >
                    <input type="hidden" id="submenuId" name="submenuId"  value="{$submenuId}"/>
                    <input type="hidden" id="userId" name="userId"  value="{$smarty.get.userId}" />
                    <input type="hidden" id="tab" name="tab"  value="writersarts" />
                    <!--<div class="row-fluid">-->
					<span class="sepV_c">
						<input type="text" placeholder="From" id="dp1" name="startdate" readonly data-date-format="dd-mm-yyyy" value="{$smarty.get.startdate}"/>
					</span>
					<span class="sepV_c">
						<input type="text"  placeholder="To" id="dp2" name="enddate" readonly data-date-format="dd-mm-yyyy" value="{$smarty.get.enddate}"/>
					</span>
					<span class="sepV_c">
						<select name="client_id" id="clients" data-placeholder="Clients" onChange="fnloaddeliveries(this.value);">
                            {html_options  options=$client_array  selected=$smarty.get.client_id}
                        </select>
					</span>
					<span class="sepV_c"  id="aolistall">
						<select name="ao_id" id="deliveries" data-placeholder="Deliveries">
                            {html_options  options=$delivery_array  selected=$smarty.get.ao_id  selected=$smarty.get.ao_id}
                        </select>

					</span>
					<span class="sepV_c">
						<select id="sorttype" name="sorttype" data-placeholder="Trier par">
                            <option value=""></option>
                            <option value="all" {if $smarty.get.sorttype eq 'all'}selected{/if}>ALL</option>
                            <option value="onging" {if $smarty.get.sorttype eq 'onging'}selected{/if}>Ongoing</option>
                            <option value="close" {if $smarty.get.sorttype eq 'close'}selected{/if}>Closed</option>
                            <option value="new" {if $smarty.get.sorttype eq 'new'}selected{/if}>New</option>
                        </select>
					</span>
					<span class="sepV_c">
						<select id="pay_status" name="pay_status" data-placeholder="Payment Status">
                            <option value=""></option>
                            <option value="all" {if $smarty.get.pay_status eq 'all'}selected{/if}>ALL</option>
                            <option value="paid" {if $smarty.get.pay_status eq 'paid'}selected{/if}>Paid</option>
                            <option value="notpaid" {if $smarty.get.pay_status eq 'notpaid'}selected{/if}>Pending</option>
                        </select>
					</span>
                    <!--</div>
                    <div class="row-fluid">-->
					<span class="sepV_c">
						<button class="btn btn-danger pull-center" id="search" name="search" type="submit" value="search" >Search</button>
						<button class="btn btn-info pull-center" id="clear" name="clear" type="button" value="clear" onclick="clearAll();" >Clear</button>
					</span>
                    <!--</div>-->
                </form>

            </div>
        </div>
    <table id="correctormissions" class="table table-bordered table-striped table_vam"  >
        <thead>
        <tr>
            <th>Nom de l'article</th>
            <th>Nom de l'annonce</th>
            <th>Nom du client</th>
            <th>Etat</th>
            <th>R&eacute;dacteur</th>
            <th>Chef de projet</th>
            <th>Langue</th>
            <th>Cat&eacute;gories</th>
            <th>Note donn&eacute;e au r&eacute;dacteur</th>
        </tr>
        </thead>
        <tbody>
        {if $crtstatsarticles neq 'NO'}
        {foreach from=$crtstatsarticles key=crtarts_key item=crtarts_item name=wcrtarts_loop}
        <tr>
            <td>{$crtarts_item.title|utf8_decode}</td>
            <td>{$crtarts_item.deliveryName|utf8_decode}</td>
            <td>{$crtarts_item.client|utf8_decode}</td>
            <td>{$crtarts_item.lateststatus}</td>
            <td>{$crtarts_item.writer}</td>
            <td>{$crtarts_item.projectManager|utf8_decode}</td>
            <td>{$crtarts_item.language|utf8_decode}</td>
            <td>{$crtarts_item.category|utf8_decode}</td>
            <td>{if $crtarts_item.marks neq ''} {$crtarts_item.marks}/10 <a class="hint--bottom hint--info" data-hint="Commenter" data-target="#markscomments" data-toggle="modal"  name="send_comment"  href="/user/recentcommentsmarks?partid={$crtarts_item.id}&userid={$crtarts_item.userId}" >
                    <i class="splashy-comments_reply"></i></a> {else} Nill {/if}</td>
        </tr>
        {/foreach}
        {/if}
        </tbody>
    </table>
</div>
   </div>
  </div>
</div>

<div style="visibility:hidden" >
    <form id="user_login_form" name="user_login_form" method="post" action="" target="_blank">
        <input type="text" id="login_name" name="login_name" value="{$user_detail[0].email}">
        <input type="password" id="login_password" name="login_password" value="{$user_detail[0].password}" >
        <input type="submit" value="Login" />
    </form>
</div>
<!--///for the contributor history popup///-->
<div class="modal hide fade" id="showhistory">
    <div class="modal-header">
        <button class="close" onclick="closePopup('showhistory');" >&times;</button>
        <h3>Contributor history</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>
<!--///for the contributor history popup///-->
<div class="modal hide fade" id="refusereasonslist">
    <div class="modal-header">
        <button class="close" onclick="closePopup('refusereasonslist');" >&times;</button>
        <h3>Refuse Reasons List</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>
<!--///for the writer list where the corrector connected to///-->
<div class="modal hide fade" id="writerlist">
    <div class="modal-header">
        <button class="close" onclick="closePopup('writerlist');" >&times;</button>
        <h3>Writers List</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>

    <!--///BO user send comments to for the participant ///-->
<div class="modal hide fade" id="comments">
    <div class="modal-header">
        <button class="close" onclick="closePopup('comments');">&times;</button>
        <h3>Write Comments</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">

    </div>
</div>
<!--///BO recent marks comments for the user ///-->
<div class="modal hide fade" id="markscomments">
    <div class="modal-header">
        <button class="close" onclick="closePopup('markscomments');">&times;</button>
        <h3>Recent Commentaire</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">

    </div>
</div>
{literal}
<script type="text/javascript" >
	function connect_fo(user)
    {
        document.forms["user_login_form"].action="http://ep-test.edit-place.com/index/userfologin";
        //$('#login_name').val(email);
        //$('#login_password').val(pwd);
        document.forms["user_login_form"].submit();
    }

    $(document).ready(function() {
        gebo_charts.fl_crtm();
        gebo_charts.fl_m();
        /* added Naseer Pasha on 30-07-2015*/
        /* function to validate the form before subbmitting */
        $( ".form_validation_reg *" ).keyup(function() {
            if($("#passport_no").val().length >= 1 || $("#id_card").val().length >= 1){
                $("#submit_contrib").prop('disabled',false);
                $("#passport_no_error").hide();
                console.log("ok to proceed");
            }
            else{
                $("#submit_contrib").prop('disabled',true);
                $("#passport_no_error").show();
                console.log("error");
            }
        });

    });
    //* charts
    gebo_charts = {
        fl_m : function() {
            // Setup the placeholder reference
            var elem = $('#monthlyGraph');
            {/literal}{$dates}{literal}
                for (var i = 0; i < d2.length; ++i) {d2[i][0] += 60 * 120 * 1000};

                var options = {
                    lines: { show: true },
                    points: { show: true },
                    yaxes: [
                        {min: 0},
                        {max: 10},
                        {position: "left"}
                    ],
                    xaxis: {
                        mode: "time",
                        timeformat: "%b %y",
                        minTickSize: [1, "month"],
                        autoscaleMargin: 0.10

                    },
                    grid: { hoverable: true },
                    legend: { position: 'nw' },
                    colors: [ "#3ca0ca" ]
                };

                // Setup the flot chart using our data
                fl_d_plot = $.plot(elem,
                    [
                        {   data: d2,
                            label: "Users marks",
                            yaxis: 2,
                            points: { show: true },
                            stack: null
                        }
                    ], options);

                // Create a tooltip on our chart
                elem.qtip({
                    prerender: true,
                    content: 'Loading...', // Use a loading message primarily
                    position: {
                        viewport: $(window), // Keep it visible within the window if possible
                        target: 'mouse', // Position it in relation to the mouse
                        adjust: { x: 11 } // ...but adjust it a bit so it doesn't overlap it.
                    },
                    show: false, // We'll show it programatically, so no show event is needed
                    style: {
                        classes: 'ui-tooltip-shadow ui-tooltip-tipsy',
                        tip: false // Remove the default tip.
                    }
                });

                // Bind the plot hover
                elem.on('plothover', function(event, coords, item) {
                    // Grab the API reference
                    var self = $(this),
                        api = $(this).qtip(),
                        previousPoint, content,

                    // Setup a visually pleasing rounding function
                        round = function(x) { return Math.round(x * 1000) / 1000; };

                    // If we weren't passed the item object, hide the tooltip and remove cached point data
                    if(!item) {
                        api.cache.point = false;
                        return api.hide(event);
                    }

                    // Proceed only if the data point has changed
                    previousPoint = api.cache.point;
                    if(previousPoint !== item.seriesIndex)
                    {
                        // Update the cached point data
                        api.cache.point = item.seriesIndex;

                        // Setup new content
                        content = item.series.label +': '+ round(item.datapoint[1]);

                        // Update the tooltip content
                        api.set('content.text', content);

                        // Make sure we don't get problems with animations
                        api.elements.tooltip.stop(1, 1);

                        // Show the tooltip, passing the coordinates
                        api.show(coords);
                    }
                });
        },
        fl_crtm : function() {
            // Setup the placeholder reference
            var elem = $('#crtmonthlyGraph');
               {/literal}{$crtdates}{literal}
               for (var i = 0; i < d2.length; ++i) {d2[i][0] += 60 * 120 * 1000};
                var options = {
                    lines: { show: true },
                    points: { show: true },
                    yaxes: [
                        {min: 0},
                        {max: 10},
                        {position: "left"}
                    ],
                    xaxis: {
                        mode: "time",
                        timeformat: "%b %y",
                        minTickSize: [1, "month"],
                        autoscaleMargin: 0.10

                    },
                    grid: { hoverable: true },
                    legend: { position: 'nw' },
                    colors: [ "#3ca0ca" ]
                };
                // Setup the flot chart using our data
                fl_d_plot = $.plot(elem,
                    [
                        {   data: d2,
                            label: "Users marks",
                            yaxis: 2,
                            points: { show: true },
                            stack: null
                        }
                    ], options);

                // Create a tooltip on our chart
                elem.qtip({
                    prerender: true,
                    content: 'Loading...', // Use a loading message primarily
                    position: {
                        viewport: $(window), // Keep it visible within the window if possible
                        target: 'mouse', // Position it in relation to the mouse
                        adjust: { x: 11 } // ...but adjust it a bit so it doesn't overlap it.
                    },
                    show: false, // We'll show it programatically, so no show event is needed
                    style: {
                        classes: 'ui-tooltip-shadow ui-tooltip-tipsy',
                        tip: false // Remove the default tip.
                    }
                });
                // Bind the plot hover
                elem.on('plothover', function(event, coords, item) {
                    // Grab the API reference
                    var self = $(this),
                        api = $(this).qtip(),
                        previousPoint, content,

                    // Setup a visually pleasing rounding function
                        round = function(x) { return Math.round(x * 1000) / 1000; };

                    // If we weren't passed the item object, hide the tooltip and remove cached point data
                    if(!item) {
                        api.cache.point = false;
                        return api.hide(event);
                    }

                    // Proceed only if the data point has changed
                    previousPoint = api.cache.point;
                    if(previousPoint !== item.seriesIndex)
                    {
                        // Update the cached point data
                        api.cache.point = item.seriesIndex;

                        // Setup new content
                        content = item.series.label +': '+ round(item.datapoint[1]);

                        // Update the tooltip content
                        api.set('content.text', content);

                        // Make sure we don't get problems with animations
                        api.elements.tooltip.stop(1, 1);

                        // Show the tooltip, passing the coordinates
                        api.show(coords);
                    }
                });
        }
    }

</script>
<style>
    #dailyGraph, #weeklyGraph, #monthlyGraph, #cdailyGraph, #cweeklyGraph, #cmonthlyGraph {width: 90%; margin: 15px auto 0px; padding: 0px; }
    #cstmm{float: left;display: block; position: relative;}
    .dailyChart, .weeklyChart, .monthlyChart, .cdailyChart, .cweeklyChart, .cmonthlyChart{cursor: pointer;}
</style>
{/literal}

