{literal}
<script type="text/javascript" charset="utf-8" src="/BO/theme/gebo/js/jQuery.fileinput.js"></script>

<link rel="stylesheet" href="/BO/theme/gebo/js/validation-engine/validationEngine.jquery.css" type="text/css"/>
<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine-fr.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>

<style type="text/css">
.mod .error { display:none !important;	}
.errordisp { color: #C62626; font-size: 11px; font-weight: 700; }
.mod { background: none repeat scroll 0 0 #FFFFFF; border-color: #E4E4E4 #E4E4E4 #BBBBBB; border-image: none; border-radius: 4px; border-style: solid; border-width: 1px; box-shadow: 0 1px 1px rgba(0, 0, 0, 0.086); margin-bottom: 15px; overflow: hidden; padding: 12px; }
select { width: 300px !important; }
</style>

<script language="javascript">

$.extend({
  password: function (length, special) {
    var iteration = 0;
    var password = "";
    var randomNumber;
    if(special == undefined){
        var special = false;
    }
    while(iteration < length){
        randomNumber = (Math.floor((Math.random() * 100)) % 94) + 33;
        if(!special){
            if ((randomNumber >=33) && (randomNumber <=47)) { continue; }
            if ((randomNumber >=58) && (randomNumber <=64)) { continue; }
            if ((randomNumber >=91) && (randomNumber <=96)) { continue; }
            if ((randomNumber >=123) && (randomNumber <=126)) { continue; }
        }
        iteration++;
        password += String.fromCharCode(randomNumber);
    }
    return password;
  }
});

$(document).ready(function() {
	
    $("#create").validationEngine(); 
	//$(".uni_style").uniform();
	//$(".uni_checkstyle").uniform();
		
	//updateAoList();
	
	//Add More client Contacts
	var contact=1;
	
	$("[id^=contactclose_]").live('click', function() {
			var DivId = $(this).attr('id');
			var parentDiv=$(this).parents("div:first").attr('id');
			var client_identifier=$(this).attr('rel');
			var closeDiv=$("#"+parentDiv).children(".close").attr('id');
			if(!client_identifier)
				$("#"+parentDiv).remove();
			else
			{	
				smoke.confirm("Do you really want to delete this contact ?",function(e){
					if (e)
					{
						if($("[id^=sccontact_]").size()>1)
						{
							$("#"+parentDiv).html('<center><img alt="" src="/BO/theme/gebo/img/ajax_loader.gif"> Deleting Contact... </center>');
							ajaxProfileUpdate('sccontact',client_identifier,parentDiv,'');
						}	
						else
						{
							$("#"+parentDiv).html('<center><img alt="" src="/BO/theme/gebo/img/ajax_loader.gif"> Deleting Contact... </center>');
							ajaxProfileUpdate('sccontact',client_identifier,parentDiv,'final');	
							
						}
					}
					else
					{
						return false;
					}
				});				
			}	
				
		});	
	
	$("[id^=sccontact_]" ).each(function(z) {
			var cid=this.id.split("_");
			$("#bouser_"+cid[1]).chosen({allow_single_deselect: true});
			$("#clients_"+cid[1]).chosen({search_contains: true});
			$("#langauge_ao_"+cid[1]).chosen({search_contains: true});
			$("#ao_"+cid[1]).chosen({search_contains: true});
		
			//if($("input[name='allao_"+cid[1]+"']:checked").val()!="all")
			updateAoList(cid[1]);    
				
			contact=++z;
	});
			
	$("#addmore_cc_link").click(function(){
		var cloned =$("#addmore_cc_link");		
		$("#sccontact").clone().attr('id', 'sccontact_'+(++contact) ).insertBefore( cloned );	
		$('#sccontact_'+contact).show();	
		
		$('#sccontact_'+contact+' select[id="bouser_0"]').attr('id','bouser_'+contact);	
		$('#sccontact_'+contact+' select[id="bouser_'+contact+'"]').attr('onChange','showconnectFO('+contact+',"add")');	
		$('#sccontact_'+contact+' select[id="clients_0"]').attr('id','clients_'+contact);	
		$('#sccontact_'+contact+' select[id="clients_'+contact+'"]').attr('onChange','updateAoList('+contact+')');	
		$('#sccontact_'+contact+' select[id="langauge_ao_0"]').attr('id','langauge_ao_'+contact);
		$('#sccontact_'+contact+' select[id="langauge_ao_'+contact+'"]').attr('onChange','updateAoList('+contact+')');
		$('#sccontact_'+contact+' select[id="ao_0"]').attr('id','ao_'+contact);
			$("#bouser_"+contact).chosen({allow_single_deselect: true});
			$("#clients_"+contact).chosen({search_contains: true});
			$("#langauge_ao_"+contact).chosen({search_contains: true});
			$("#ao_"+contact).chosen({search_contains: true});
			
				$('#sccontact_'+contact+' input[id="newbouserval_0"]').attr('id','newbouserval_'+contact);
				$('#sccontact_'+contact+' div[id="foconnect_0"]').attr('id','foconnect_'+contact);
				
		$('#sccontact_'+contact+' select[id="bouser_'+contact+'"]').attr('name','bouser['+(contact-1)+']');			
		$('#sccontact_'+contact+' select[id="clients_'+contact+'"]').attr('name','clients['+(contact-1)+'][]');		
		$('#sccontact_'+contact+' select[id="langauge_ao_'+contact+'"]').attr('name','langauge_ao['+(contact-1)+'][]');		
		$('#sccontact_'+contact+' select[id="ao_'+contact+'"]').attr('name','ao['+(contact-1)+'][]');		
		//$('#sccontact_'+contact+' [id="allao_0"]').attr('name','allao_'+contact);		
		////$('#sccontact_'+contact+' [id="allao_0"]').attr('id','allao_'+contact);		
		//$('#sccontact_'+contact+' [id="allao_'+contact+'"]').attr('onClick','updateAoList('+contact+')');
		
		$('#sccontact_'+contact+' [id="ao_list_div_0"]').attr('id','ao_list_div_'+contact);	
		$('#sccontact_'+contact+' [id="aolistappend_0"]').attr('id','aolistappend_'+contact);	
		//$('#sccontact_'+contact+' [id="span_ao_list_0"]').attr('id','span_ao_list_'+contact);	
		$('#sccontact_'+contact+' [id="error_0"]').attr('id','error_'+contact);	
		$('#sccontact_'+contact+' .close').attr('id','contactclose_'+contact);
		$('#sccontact_'+contact+' .close').show();
		$('#sccontact_'+contact+' .close').attr('rel','');	
		
		$('#sccontact_'+contact+' .uni_style').attr('name','cstatus_visible['+(contact-1)+'][]');	
		//$('#sccontact_'+contact+' [type="radio"]').attr('name','user_visible['+(contact-1)+']');	
		
		$('#sccontact_'+contact+' [id="bouserblock_0"]').attr('id','bouserblock_'+contact);	
		//$('#sccontact_'+contact+' [id="addnewbouser_0"]').attr('onClick','addnewbouser('+contact+')');	
		//$('#sccontact_'+contact+' [id="addnewbouser_0"]').attr('id','addnewbouser_'+contact);	
		//clearChildren(document.getElementById('sccontact_'+contact));	

		//Bo user detail block
		$('#sccontact_'+contact+' input[id="bolast_name_0"]').attr('name','bolast_name['+(contact-1)+']');	
		$('#sccontact_'+contact+' input[id="bolast_name_0"]').attr('id','bolast_name_'+contact);	
		$('#sccontact_'+contact+' input[id="bofirst_name_0"]').attr('name','bofirst_name['+(contact-1)+']');	
		$('#sccontact_'+contact+' input[id="bofirst_name_0"]').attr('id','bofirst_name_'+contact);	
			$('#sccontact_'+contact+' input[id="boemail_0"]').attr('name','boemail['+(contact-1)+']');	
		$('#sccontact_'+contact+' input[id="boemail_0"]').attr('id','boemail_'+contact);	
			$('#sccontact_'+contact+' input[id="bopassword_0"]').attr('name','bopassword['+(contact-1)+']');	
		$('#sccontact_'+contact+' input[id="bopassword_0"]').attr('id','bopassword_'+contact);	
			
		$('#sccontact_'+contact+' [id="cgenerate_0"]').attr('onClick','generatebopwd('+contact+')');	
		$('#sccontact_'+contact+' [id="cgenerate_0"]').attr('id','cgenerate_'+contact);	
		
		$("#sccontact_"+contact+"_chzn .chzn-single span").html('Liste Odigeo bo user');
		$("#sccontact_"+contact+"_chzn .chzn-single").addClass('chzn-default');
		
		$("#sccontact_"+contact+"_chzn .chzn-single .search-choice-close").hide();
		$("#sccontact_"+contact).find("option:selected").removeAttr("selected");	
		
		$('#sccontact_'+contact+' div[id="statuscheck_0"]').attr('id','statuscheck_'+contact);		
		$('#sccontact_'+contact+' input[id="checkallstatus_0"]').attr('name','checkallstatus_'+contact);	
		$('#sccontact_'+contact+' [id="checkallstatus_0"]').attr('onClick','selectALL('+contact+')');		
		$('#sccontact_'+contact+' input[id="checkallstatus_0"]').attr('id','checkallstatus_'+contact);	
			
	});	
});

/** ajax function to delete super client contact data**/
function ajaxProfileUpdate(type,identifier,divid,last)
{
        var target_page = "/user/delete-sc-contact?type="+type+"&identifier="+identifier;		
		$.post(target_page, function(data){					
				//alert(data);
				sleep(4000);
				$("#"+divid).remove();
				if(last=='final')
					location.reload();
			});
}
function sleep(ms)
{
	var dt = new Date();
	dt.setTime(dt.getTime() + ms);
	while (new Date().getTime() < dt.getTime());
}
/*reset all childs of a div**/	
function clearChildren(element) {
   for (var i = 0; i < element.childNodes.length; i++) {
      var e = element.childNodes[i];
      if (e.tagName) switch (e.tagName.toLowerCase()) {
         case 'input':
            switch (e.type) {
               case "radio":
               case "checkbox": e.checked = false; break;
               case "button":
               case "submit":
               case "image": break;
               default: e.value = ''; break;
            }
            break;
         case 'select': e.selectedIndex = 0; break;
         case 'textarea': e.innerHTML = ''; break;
         default: clearChildren(e);
      }
   }
}

function updateAoList(index)
{
		var languages=$("select#langauge_ao_"+index).val();
		var clients=$("select#clients_"+index).val();
		
		if(languages!=null && clients!=null)
		{
			var target_page="/user/get-deliveriescontact?languages="+languages+"&clients="+clients+"&index="+index;
			
			$.get(target_page,function(data){
				data=$.trim(data);
				$("#aolistappend_"+index).html(data);
				$(".ao").chosen({search_contains: true});     
				$("#ao_list_div_"+index).show();
			});
		}

}

function validate_SCcreation_step2() 
{
	var errstep2=0; 
	
	$("[id^=sccontact_]" ).each(function(z) {
	
		var cid=this.id.split("_");
		var bouser=$("#bouser_"+cid[1]).val();
		var client=$("#clients_"+cid[1]).val();
		var lang=$("#langauge_ao_"+cid[1]).val();
		var ind=cid[1]-1;
		var status=$('input[name="cstatus_visible['+ind+'][]"]:checked').serialize();
		var ref=$("#refid").val();
		var looperr=0;
		var requiredArray= new Array("writing_progress","correction_ongoing","stage2","published_client","published","closed");
		
		if(client==null || lang==null || status=="")
		{
			errstep2++;
			looperr++;
		}
		
		//Status validation
		var chkArray = [];
		
			$('input:checkbox[name="cstatus_visible['+ind+'][]"]:checked').each(function() {
				chkArray.push($(this).val());
			});
		
		//alert(chkArray.length);
		if(chkArray.length>0)
		{		
			var checkerr=0;
			
			$.each( requiredArray, function( key, value ) {
				if(jQuery.inArray(value,chkArray)==-1)  
				{
					checkerr++;
				}
			});
			
			looperr=looperr+checkerr;
			errstep2=errstep2+checkerr;
		}
		
		if(client!=null)
		{
			for (var c = 0; c < client.length; c++) 
			{	
				var radopt=$("input[name='aotype["+ind+"]["+client[c]+"]']:checked").val();   
				
				if(radopt=="")
				{
					errstep2++;
					looperr++;
				}
				else if(radopt=="select")
				{
					var customao=$("#ao_"+client[c]+"_"+cid[1]).val();
					if(customao==null || customao.length==0)
					{
						errstep2++;
						looperr++;
					}
				}
				//alert("beforeajx"+errstep2);
				//Check bouser client combination permission
				//if(bouser!="" || bouser!="undefined")
				if(bouser.length>0)
				{
					var clientidentifier=client[c];
					var checkedtext="";
					$.ajax({
						  type: 'POST',
						  url: '/user/checkbouserpermission',
						  data: {bo_user:bouser,clientid:clientidentifier},
						  async:false,
						  cache:false,
						  timeout:3000,
						  success: function(msg)
						  {
						
							msgval=msg.split("#");//alert(msgval);
							if((ref=="" && msgval[0]>0) || (ref!="" && msgval[0]>1 ))
							{
								if(msgval[1]=="all" || msgval[1]=="future")
								{
									if(msgval[1]!=radopt)
									{
										var overwrite1=$("input[name='overwrite_"+clientidentifier+"_"+cid[1]+"']:checked").val();
										if(overwrite1=="on")
											var checkedtext="checked";
										$("#err_"+clientidentifier+"_"+cid[1]).html("<span style=color:red>Already has "+msgval[1]+"</span> <input type=checkbox name=overwrite_"+clientidentifier+"_"+cid[1]+" id=overwrite_"+clientidentifier+"_"+cid[1]+" "+checkedtext+"/>Overwrite");
										if(overwrite1!="on")
										{
											errstep2=errstep2+1;
										}
									}
									else
										$("#err_"+clientidentifier+"_"+cid[1]).html("");
								}
								else
								{
									if(radopt=="all" || radopt=="future")
									{	
										var overwrite1=$("input[name='overwrite_"+clientidentifier+"_"+cid[1]+"']:checked").val();
										if(overwrite1=="on")
											var checkedtext="checked";
										$("#err_"+clientidentifier+"_"+cid[1]).html("<span style=color:red>Already has "+msgval[1]+"</span> <input type=checkbox name=overwrite_"+clientidentifier+"_"+cid[1]+" id=overwrite_"+clientidentifier+"_"+cid[1]+" "+checkedtext+"/>Overwrite");
									
										if(overwrite1!="on")
										{
											errstep2=errstep2+1;
										}
									}
									else
										$("#err_"+clientidentifier+"_"+cid[1]).html("");
								}						
							}
								
						  },
					});
				}
				
			}
		}
		if(looperr>0)
			$("#error_"+cid[1]).html("* fields are mandatory");
		else
			$("#error_"+cid[1]).html("");
		
	});
		if(errstep2>0)  
		 return false; 
		else
		 return true;
		//	return false;
}

function addnewbouser(num)
{
	var clonedcl=$("#bouserblock_"+num);
	$("#newbouser").clone().attr('id', 'newbouser_'+(num) ).insertAfter( clonedcl );	
	$('#newbouser_'+num).show();	
		$('#newbouserval_'+num).val(1);
		$('#newbouser_'+num+' input[id="bolast_name_0"]').attr('name','bolast_name['+(num-1)+']');	
	$('#newbouser_'+num+' input[id="bolast_name_0"]').attr('id','bolast_name_'+num);	
		$('#newbouser_'+num+' input[id="bofirst_name_0"]').attr('name','bofirst_name['+(num-1)+']');	
	$('#newbouser_'+num+' input[id="bofirst_name_0"]').attr('id','bofirst_name_'+num);	
		$('#newbouser_'+num+' input[id="boemail_0"]').attr('name','boemail['+(num-1)+']');	
	$('#newbouser_'+num+' input[id="boemail_0"]').attr('id','boemail_'+num);	
		$('#newbouser_'+num+' input[id="bopassword_0"]').attr('name','bopassword['+(num-1)+']');	
	$('#newbouser_'+num+' input[id="bopassword_0"]').attr('id','bopassword_'+num);	
	
	$('#newbouser_'+num+' [id="cgenerate_0"]').attr('onClick','generatebopwd('+num+')');	
	$('#newbouser_'+num+' [id="cgenerate_0"]').attr('id','cgenerate_'+num);	
	
	$("#bouser_"+num+"_chzn .chzn-single span").html('Liste Odigeo bo user');
	$("#bouser_"+num+"_chzn .chzn-single").addClass('chzn-default');
	
	$("#bouser_"+num+"_chzn .chzn-single .search-choice-close").hide();
	$("#bouser_"+num).find("option:selected").removeAttr("selected");
	$("#addnewbouser_"+num).hide();
}

function generatebopwd(loop)
{
	var password = $.password(8,false);	
	$('#sccontact_'+loop+' input[id="bopassword_'+loop+'"]').val(password);
	 e.preventDefault();
}

function selectallao(cnt)
{
	if($("input[name='aoall_"+cnt+"']:checked").val()=="on")
	{
		//$("#ao_"+cnt).find("option:selected").removeAttr("selected");
		$("#ao_"+cnt).attr("disabled",true);
	}	
	
}

function validateao(nn)
{
	var aoval=$("#ao_"+nn).val();  
	if(aoval)
	{
		for (var i = 0; i < aoval.length; i++) {
			if(aoval[i]=="all")
			{
				var aoarray = new Array();
				aoarray.push('all');
				$("#ao_"+nn).val(aoarray);
				//$("#ao_"+nn+"_chzn .chzn-choices").html('<li id="ao_1_chzn_c_1" class="search-choice"><span>ALL</span><a class="search-choice-close" rel="1" href="javascript:void(0)"></a></li>');
			}
		}
	
	}
}

function connect_chiefOdigeo_FO(user,email,pass)
{
	window.open('http://mmm-new.edit-place.com/index/userchieflogin?login_name='+email+'&login_password='+pass); 
}

function showconnectFO(iid,act)
{
	var bou=$('#bouser_'+iid).val();
	
	if(bou!="")
	{
		$.ajax({
				  type: 'POST',
				  url: '/user/updatebouserblock',
				  data: {bouser:bou},
				  
				  success: function(msg)
				  {
					msgarray=msg.split("#");
					if(act=='edit')
					{
						msgtext='<a href="javascript:void(0);" onclick="connect_chiefOdigeo_FO(\''+$.trim(msgarray[0])+'\',\''+msgarray[1]+'\',\''+msgarray[2]+'\');"><i class="splashy-contact_grey"></i></a>';
						$("#foconnect_"+iid).html("");
						$("#foconnect_"+iid).html(msgtext);  
					}
					$("#bolast_name_"+iid).val(msgarray[4]);
					$("#bofirst_name_"+iid).val(msgarray[3]);
					$("#boemail_"+iid).val(msgarray[1]);
					$("#bopassword_"+iid).val(msgarray[2]);
					$("#boemail_"+iid).attr('readonly',true);	
					$("#boemail_"+iid).removeAttr('class');	
				  }
		});
	}
	else
	{
		$("#bolast_name_"+iid).val("");
		$("#bofirst_name_"+iid).val("");
		$("#boemail_"+iid).val("");
		$("#bopassword_"+iid).val("");
		$("#boemail_"+iid).removeAttr('readonly');	
		$("#boemail_"+iid).attr('class','validate[required,custom[email],ajax[ajaxEmailValidate]]');
	}
}

function selectALL(indx)
{
   if($("#checkallstatus_"+indx).attr('checked'))
   {
	  var $b = $('#statuscheck_'+indx+' input[type=checkbox]');
	  $b.attr('checked', true);
   }
   else
   {
	   var $b = $('#statuscheck_'+indx+' input[type=checkbox]');  
	   $b.attr('checked', false);
   }
}

function toggleselect(loop,clt)
{
	var loop1=loop-1;
	var rad=$("input[name='aotype["+loop1+"]["+clt+"]']:checked").val();   
	if($.trim(rad)=="select")
	{
		$("#clientblock_"+clt+"_"+loop).show();
	}
	else
		$("#clientblock_"+clt+"_"+loop).hide();
}

</script>	
{/literal}	

<div class="row-fluid">    
	<div class="span12">
		<h3 class="heading">SELECT CONTACTS</h3>
		<form class="form_validation_reg" action="/user/superclientcreate-step3?submenuId=ML9-SL1" id="create" method="post" id="user" name="user" enctype="multipart/form-data" onSubmit="return validate_SCcreation_step2();">
			<input type="hidden" name="refid" id="refid" value="{$refid}" />
			<div class="mod" id="sccontact" style="display:none;">		
				<button  class="close" type="button" id="contactclose_0" rel=""   style="display:none">&times;</button>
				<div class="formSep"  id="bouserblock_0">
					<div class="row-fluid">
						<div class="span8 form-inline" >
							<label class="span4">BO User <span class="f_req">*</span></label>						
							<select data-placeholder="Liste Odigeo bo user" name="bouser[0]" id="bouser_0" class="span6" onChange="showconnectFO('0',add);">
								<option value=""></option>
								{foreach from=$bouser_array item=bouser}
									<option value="{$bouser.identifier}">{$bouser.email}</option>
								{/foreach}
							</select>	
							<input type="hidden" id="newbouserval_0" value="0" />
						</div>					
					</div>
				</div>
				<div class="formSep">
					<div class="row-fluid">
						<div class="span4 form-inline">
							<label class="span4">Nom <span class="f_req">*</span></label>
							<span><input type="text" name="bolast_name[0]" id="bolast_name_0" class="validate[required]" /></span>
						</div>	
						<div class="span7 form-inline">
							<label class="span2">Pr&eacute;nom <span class="f_req">*</span></label>
							<span><input type="text" name="bofirst_name[0]" id="bofirst_name_0" class="validate[required]" /></span>
						</div>						
						
					</div>
				</div>				
				<div class="formSep">
					<div class="row-fluid">
						<div class="span4 form-inline">
							<label class="span4">Adresse email <span class="f_req">*</span></label>
							<span><input type="text" name="boemail[0]" id="boemail_0" class="validate[required,custom[email],ajax[ajaxEmailValidate]]" /></span>
						</div>
						<div class="span7 form-inline">
							<label class="span2">Password <span class="f_req">*</span></label>
							<span><input type="text" name="bopassword[0]" id="bopassword_0" class="validate[required]" /></span>
							<a class="btn" id="cgenerate_0" onClick="generatebopwd(0);">G&eacute;n&eacute;rer mot de passe</a>
						</div>	
					</div>
				</div>
				<div class="formSep">
					<div class="row-fluid">
						<div class="span8 form-inline">
							<label class="span4">Langue(s) affich&eacute;e(s) <span class="f_req">*</span></label>						
							<select multiple data-placeholder="Choose language..." class="span6" name="langauge_ao[0][]" id="langauge_ao_0" onChange="updateAoList(0);">
								{html_options  options=$language_step1 selected=$super_client.langauge_ao}	
							</select>	
						</div>					
					</div>  
				</div>	
				
				<div class="formSep">
					<div class="row-fluid">
						<div class="span8 form-inline">  
							<label class="span4">Qui g&egrave;re-t-il comme clients <span class="f_req">*</span></label>						
							<select multiple data-placeholder="Liste des clients" name="clients[0][]" id="clients_0" class="span6" onChange="updateAoList(0);">
								{html_options  options=$clients_step1  selected=$super_client.clients}
							</select>	
						</div>					
					</div>
				</div>			
				
				<div class="formSep" id="ao_list_div_0" style="display:none;">
					<div class="row-fluid">
						<div class="span11 form-inline">
							<label class="span3">S&eacute;lectionner un appel d'offre <span class="f_req">*</span></label>
							<div id="aolistappend_0">
								
							</div>
							</span>
						</div>					
					</div>
				</div>
				<div class="formSep">
					<div class="row-fluid">
						<div class="span10">
							<label class="span4">Affichage de la liste des statuts <span class="f_req">*</span></label>						
							<div class="span4" id="statuscheck_0">
								{if in_array('participation_ongoing',$status_step1)}
								<label class="uni-checkbox">
									<input type="checkbox"  value="participation_ongoing" name="cstatus_visible[0][]" class="uni_style"  />
									Participations en cours
								</label>
								{/if}
								{if in_array('pending_selection',$status_step1)}
								<label class="uni-checkbox">
									<input type="checkbox" value="pending_selection" name="cstatus_visible[0][]" class="uni_style" />
									En attente de s&eacute;lection
								</label>
								{/if}
								{if in_array('writing_progress',$status_step1)}
								<label class="uni-checkbox">
									<input type="checkbox" value="writing_progress" name="cstatus_visible[0][]" class="uni_style" />
									R&eacute;daction en cours <span class="f_req">*</span>
								</label>
								{/if}
								{if in_array('time_out',$status_step1)}
								<label class="uni-checkbox">
									<input type="checkbox" value="time_out" name="cstatus_visible[0][]" class="uni_style" />
									Article non envoy&eacute;
								</label>
								{/if}
								{if in_array('plag_exec',$status_step1)}
								<label class="uni-checkbox">
									<input type="checkbox" value="plag_exec" name="cstatus_visible[0][]" class="uni_style" />
									V&eacute;rification du non plagiat
								</label>
								{/if}
								{if in_array('disapproved',$status_step1)}
								<label class="uni-checkbox">
									<input type="checkbox" value="disapproved" name="cstatus_visible[0][]" class="uni_style" />
									Article en reprise
								</label>
								{/if}
								{if in_array('correction_ongoing',$status_step1)}
								<label class="uni-checkbox">
									<input type="checkbox" value="correction_ongoing" name="cstatus_visible[0][]" class="uni_style"  />
									Correction en cours <span class="f_req">*</span>
								</label>
								{/if}
								{if in_array('stage2',$status_step1)}
								<label class="uni-checkbox">
									<input type="checkbox" value="stage2" name="cstatus_visible[0][]" class="uni_style" />
									En attente de validation (EP) <span class="f_req">*</span>
								</label>
								{/if}
								{if in_array('published_client',$status_step1)}
								<label class="uni-checkbox">
									<input type="checkbox" value="published_client" name="cstatus_visible[0][]" class="uni_style"  />
									En attente de validation (Client) <span class="f_req">*</span>
								</label>
								{/if}
								{if in_array('published',$status_step1)}
								<label class="uni-checkbox">
									<input type="checkbox" value="published" name="cstatus_visible[0][]" class="uni_style" />
									Valid&eacute; <span class="f_req">*</span>
								</label>
								{/if}
								{if in_array('refused_client',$status_step1)}
								<label class="uni-checkbox">
									<input type="checkbox" value="refused_client" name="cstatus_visible[0][]" class="uni_style" />
									Refused by Client
								</label>
								{/if}
								{if in_array('closed',$status_step1)}
								<label class="uni-checkbox">
									<input type="checkbox" value="closed" name="cstatus_visible[0][]" class="uni_style" />
									Close <span class="f_req">*</span>
								</label>
								{/if}
							</div>
							<div class="span2" style="vertical-align:top;"><input type="checkbox" name="checkallstatus_0" id="checkallstatus_0" onClick="selectALL('0');" value="checkallpermissions"/>&nbsp;<strong>Checkall</strong></div>
						</div>					
					</div>
				</div>
				<div id="error_0" class="errordisp span8 pull-right"></div>
			</div>
			
			<div id="newbouser" style="display:none;">
				<div class="formSep">
					<div class="row-fluid">
						<div class="span4 form-inline">
							<label class="span4">Nom <span class="f_req">*</span></label>
							<span><input type="text" name="bolast_name[0]" id="bolast_name_0" class="validate[required]" /></span>
						</div>	
						<div class="span7 form-inline">
							<label class="span2">Pr&eacute;nom <span class="f_req">*</span></label>
							<span><input type="text" name="bofirst_name[0]" id="bofirst_name_0" class="validate[required]" /></span>
						</div>						
						
					</div>
				</div>				
				<div class="formSep">
					<div class="row-fluid">
						<div class="span4 form-inline">
							<label class="span4">Adresse email <span class="f_req">*</span></label>
							<span><input type="text" name="boemail[0]" id="boemail_0" class="validate[required,custom[email],ajax[ajaxEmailValidate]]" /></span>
						</div>
						<div class="span7 form-inline">
							<label class="span2">Password <span class="f_req">*</span></label>
							<span><input type="text" name="bopassword[0]" id="bopassword_0" class="validate[required]" /></span>
							<a class="btn" id="cgenerate_0" onClick="generatebopwd(0);">G&eacute;n&eacute;rer mot de passe</a>
						</div>	
					</div>
				</div>
			</div>

			<div id="client_contacts">
			{if $clients|@count gt 0}
				{section name=contact_loop loop=$clients|@count} 
				{assign var=sc_index value=$smarty.section.contact_loop.index+1}
				
				<div class="mod" id="sccontact_{$sc_index}">		
					<button  class="close" type="button" id="contactclose_{$sc_index}" rel="{$contact.contact_id}"  {if $clients|@count lt 1} style="display:none"{/if}>&times;</button>
					<div class="formSep"  id="bouserblock_{$sc_index}">
						<div class="row-fluid">
							<div class="span8 form-inline">
								<label class="span4">BO User <span class="f_req">*</span></label>						
								<select data-placeholder="Liste Odigeo bo user" name="bouser[{$smarty.section.contact_loop.index}]" id="bouser_{$sc_index}" class="span6" onChange="showconnectFO('{$sc_index}','edit');" >
									<option value=""></option>
									{foreach from=$bouser_array item=bouser}
										<option value="{$bouser.identifier}" {if $bouser.identifier==$bo_user[$smarty.section.contact_loop.index]}selected{/if} >{$bouser.email}</option>
									{/foreach}
								</select>	
								<!--<a class="btn" id="addnewbouser_{$sc_index}" style="vertical-align:top" onClick="addnewbouser({$sc_index});"><i class="icon-plus"></i></a>-->
								<input type="hidden" id="newbouserval_{$sc_index}" value="0" />
								<div id="foconnect_{$sc_index}" style="float:right;padding-right:90px">
									{if $bo_user[$smarty.section.contact_loop.index]!=""}
										<a href="javascript:void(0);" onclick="connect_chiefOdigeo_FO('{$bo_user[$smarty.section.contact_loop.index]}','{$bo_user_email[$smarty.section.contact_loop.index]}','{$bo_user_password[$smarty.section.contact_loop.index]}');"><i class="splashy-contact_grey"></i></a>
									{/if}
								</div>
							</div>					
						</div>
					</div>
					<div class="formSep">
						<div class="row-fluid">
							<div class="span4 form-inline">
								<label class="span4">Nom <span class="f_req">*</span></label>
								<span><input type="text" name="bolast_name[{$smarty.section.contact_loop.index}]" id="bolast_name_{$sc_index}" value="{$bolast_name[$smarty.section.contact_loop.index]}" class="validate[required]" /></span>
							</div>	
							<div class="span7 form-inline">
								<label class="span2">Pr&eacute;nom <span class="f_req">*</span></label>
								<span><input type="text" name="bofirst_name[{$smarty.section.contact_loop.index}]" id="bofirst_name_{$sc_index}" class="validate[required]" value="{$bofirst_name[$smarty.section.contact_loop.index]}"/></span>
							</div>						
							
						</div>
					</div>				
					<div class="formSep">
						<div class="row-fluid">
							<div class="span4 form-inline">
								<label class="span4">Adresse email <span class="f_req">*</span></label>
								<span><input type="text" name="boemail[{$smarty.section.contact_loop.index}]" id="boemail_{$sc_index}" readonly value="{$bo_user_email[$smarty.section.contact_loop.index]}"/></span>
							</div>
							<div class="span7 form-inline">
								<label class="span2">Password <span class="f_req">*</span></label>
								<span><input type="text" name="bopassword[{$smarty.section.contact_loop.index}]" id="bopassword_{$sc_index}" class="validate[required]" value="{$bo_user_password[$smarty.section.contact_loop.index]}"/></span>
								<a class="btn" id="cgenerate_{$sc_index}" onClick="generatebopwd({$sc_index});">G&eacute;n&eacute;rer mot de passe</a>
							</div>	
						</div>
					</div>
					<div class="formSep">
						<div class="row-fluid">
							<div class="span8 form-inline">
								<label class="span4">Langue(s) affich&eacute;e(s) <span class="f_req">*</span></label>						
								<select multiple data-placeholder="Choose a language..." class="span6" name="langauge_ao[{$smarty.section.contact_loop.index}][]" id="langauge_ao_{$sc_index}" onChange="updateAoList({$sc_index});">
									{html_options  options=$language_step1 selected=$langauge_ao[$smarty.section.contact_loop.index]}	
								</select>	
							</div>					
						</div>  
					</div>	
					<div class="formSep">
						<div class="row-fluid">
							<div class="span8 form-inline">
								<label class="span4">Qui g&egrave;re-t-il comme clients <span class="f_req">*</span></label>						
								<select multiple data-placeholder="Liste des clients" name="clients[{$smarty.section.contact_loop.index}][]" id="clients_{$sc_index}" class="span4" onChange="updateAoList({$sc_index});">
									{html_options  options=$clients_step1  selected=$clients[$smarty.section.contact_loop.index]}
								</select>	
							</div>					
						</div>
					</div>	
					<div class="formSep" id="ao_list_div_{$sc_index}">
						<div class="row-fluid">
							<div class="span11 form-inline">
								<label class="span3">S&eacute;lectionner un appel d'offre <span class="f_req">*</span></label>						
								<div id="aolistappend_{$sc_index}">
									<!--
									<select id="ao_{$sc_index}" class="span6" name="ao[{$smarty.section.contact_loop.index}][]" data-placeholder="Choose AO..." multiple >
										{foreach from=$deliveries item=delivery}
											{if in_array($delivery.id,$ao[$smarty.section.contact_loop.index])}
												<option value="{$delivery.id}" selected>{$delivery.title}</option>
											{else}
												<option value="{$delivery.id}">{$delivery.title}</option>
											{/if}
										{/foreach}
									</select>-->
								</div>
							</div>					
						</div>  
					</div>
					<div class="">
						<div class="row-fluid">
							<div class="span10">
								<label class="span4">Affichage de la liste des statuts <span class="f_req">*</span></label>
								<div class="span4" id="statuscheck_{$sc_index}">								
									{if in_array('participation_ongoing',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox"  value="participation_ongoing" name="cstatus_visible[{$smarty.section.contact_loop.index}][]" class="uni_style" {if in_array('participation_ongoing',$cstatus_visible[$smarty.section.contact_loop.index])} checked {/if} />
										Participations en cours
									</label>
									{/if}
									{if in_array('pending_selection',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="pending_selection" name="cstatus_visible[{$smarty.section.contact_loop.index}][]" class="uni_style"{if in_array('pending_selection',$cstatus_visible[$smarty.section.contact_loop.index])} checked {/if} />
										En attente de s&eacute;lection
									</label>
									{/if}
									{if in_array('writing_progress',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="writing_progress" name="cstatus_visible[{$smarty.section.contact_loop.index}][]" class="uni_style" {if in_array('writing_progress',$cstatus_visible[$smarty.section.contact_loop.index])} checked {/if} />
										R&eacute;daction en cours <span class="f_req">*</span>
									</label>
									{/if}
									{if in_array('time_out',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="time_out" name="cstatus_visible[{$smarty.section.contact_loop.index}][]" class="" {if in_array('time_out',$cstatus_visible[$smarty.section.contact_loop.index])} checked {/if} />
										Article non envoy&eacute;
									</label>
									{/if}
									{if in_array('plag_exec',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="plag_exec" name="cstatus_visible[{$smarty.section.contact_loop.index}][]" class="" {if in_array('plag_exec',$cstatus_visible[$smarty.section.contact_loop.index])} checked {/if} />
										V&eacute;rification du non plagiat
									</label>
									{/if}
									{if in_array('disapproved',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="disapproved" name="cstatus_visible[{$smarty.section.contact_loop.index}][]" class="uni_style" {if in_array('disapproved',$cstatus_visible[$smarty.section.contact_loop.index])} checked {/if} />
										Article en reprise
									</label>
									{/if}
									{if in_array('correction_ongoing',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="correction_ongoing" name="cstatus_visible[{$smarty.section.contact_loop.index}][]" class="uni_style" {if in_array('correction_ongoing',$cstatus_visible[$smarty.section.contact_loop.index])} checked {/if} />
										Correction en cours <span class="f_req">*</span>
									</label>
									{/if}
									{if in_array('stage2',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="stage2" name="cstatus_visible[{$smarty.section.contact_loop.index}][]" class="uni_style" {if in_array('stage2',$cstatus_visible[$smarty.section.contact_loop.index])} checked {/if} />
										En attente de validation (EP) <span class="f_req">*</span>
									</label> 
									{/if}
									{if in_array('published_client',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="published_client" name="cstatus_visible[{$smarty.section.contact_loop.index}][]" class="uni_style" {if in_array('published_client',$cstatus_visible[$smarty.section.contact_loop.index])} checked {/if} />
										En attente de validation (Client) <span class="f_req">*</span>
									</label>
									{/if}
									{if in_array('published',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="published" name="cstatus_visible[{$smarty.section.contact_loop.index}][]" class="uni_style" {if in_array('published',$cstatus_visible[$smarty.section.contact_loop.index])} checked {/if} />
										Valid&eacute; <span class="f_req">*</span>
									</label>
									{/if}
									{if in_array('refused_client',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="refused_client" name="cstatus_visible[{$smarty.section.contact_loop.index}][]" class="uni_style" {if in_array('refused_client',$cstatus_visible[$smarty.section.contact_loop.index])} checked {/if} />
										Refused by Client
									</label>
									{/if}
									{if in_array('closed',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="closed" name="cstatus_visible[{$smarty.section.contact_loop.index}][]" class="uni_style" {if in_array('closed',$cstatus_visible[$smarty.section.contact_loop.index])} checked {/if} />
										Close <span class="f_req">*</span>
									</label>
									{/if}
								</div>
								<div class="span2" style="vertical-align:top;"><input type="checkbox" name="checkallstatus_{$sc_index}" id="checkallstatus_{$sc_index}" onClick="selectALL('{$sc_index}');" value="checkallpermissions"/>&nbsp;<strong>Checkall</strong></div>
							</div>					
						</div>
					</div>
					
					<div id="error_{$sc_index}" class="errordisp span8 pull-right"></div>
				</div>	
				{/section}
			{else}
				<div class="mod" id="sccontact_1">		
					<button  class="close" type="button" id="contactclose_1" rel=""   style="display:none">&times;</button>
					<div class="formSep" id="bouserblock_1">
						<div class="row-fluid" >
							<div class="span8 form-inline">
								<label class="span4">BO User <span class="f_req">*</span></label>						
								<select data-placeholder="Liste Odigeo bo user" name="bouser[0]" id="bouser_1" class="span6" onChange="showconnectFO('1','add');">
									<option value=""></option>
									{foreach from=$bouser_array item=bouser}
										<option value="{$bouser.identifier}">{$bouser.email}</option>
									{/foreach}
								</select>	
								<!--<a class="btn" id="addnewbouser_1" style="vertical-align:top" onClick="addnewbouser(1);"><i class="icon-plus"></i></a>-->
								<input type="hidden" id="newbouserval_1" value="0" />
							</div>	
						</div>
					</div>
					<div class="formSep">
						<div class="row-fluid">
							<div class="span4 form-inline">
								<label class="span4">Nom <span class="f_req">*</span></label>
								<span><input type="text" name="bolast_name[0]" id="bolast_name_1" class="validate[required]" /></span>
							</div>	
							<div class="span7 form-inline">
								<label class="span2">Pr&eacute;nom <span class="f_req">*</span></label>
								<span><input type="text" name="bofirst_name[0]" id="bofirst_name_1" class="validate[required]" /></span>
							</div>						
							
						</div>
					</div>				
					<div class="formSep">
						<div class="row-fluid">
							<div class="span4 form-inline">
								<label class="span4">Adresse email <span class="f_req">*</span></label>
								<span><input type="text" name="boemail[0]" id="boemail_1" class="validate[required,custom[email],ajax[ajaxEmailValidate]]" /></span>
							</div>
							<div class="span7 form-inline">
								<label class="span2">Password <span class="f_req">*</span></label>
								<span><input type="text" name="bopassword[0]" id="bopassword_1" class="validate[required]" /></span>  
								<a class="btn" id="cgenerate_1" onClick="generatebopwd(1);">G&eacute;n&eacute;rer mot de passe</a>
							</div>	
						</div>
					</div>
					<div class="formSep">
						<div class="row-fluid">
							<div class="span8 form-inline">
								<label class="span4">Langue(s) affich&eacute;e(s) <span class="f_req">*</span></label>						
								<select multiple data-placeholder="Choose language..." class="span6" name="langauge_ao[0][]" id="langauge_ao_1" onChange="updateAoList(1);">
									{html_options  options=$language_step1 selected=$super_client.langauge_ao}	
								</select>	
							</div>					
						</div>  
					</div>	
					<div class="formSep">
						<div class="row-fluid">
							<div class="span8 form-inline">
								<label class="span4">Qui g&egrave;re-t-il comme clients <span class="f_req">*</span></label>  						
								<select multiple data-placeholder="Liste des clients" name="clients[0][]" id="clients_1" class="span6" onChange="updateAoList(1);">
									{html_options  options=$clients_step1  selected=$super_client.clients}
								</select>	
							</div>					
						</div>
					</div>		
					<div class="formSep" id="ao_list_div_1" style="display:none;">
						<div class="row-fluid">
							<div class="span11 form-inline">
								<label class="span3">S&eacute;lectionner un appel d'offre <span class="f_req">*</span></label>
								<div id="aolistappend_1" >
									<!--<select id="ao_1" class="span6" name="ao[0][]" data-placeholder="Choose AO..." multiple >
										{foreach from=$deliveries item=delivery}
											<option value="{$delivery.id}">{$delivery.title}</option>
										{/foreach}
									</select>-->
								</div>
							</div>					
						</div>
					</div>
					
					<div class="formSep">
						<div class="row-fluid">
							<div class="span10">
								<label class="span4">Affichage de la liste des statuts <span class="f_req">*</span></label>						
								<div class="span4" id="statuscheck_1">
									{if in_array('participation_ongoing',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox"  value="participation_ongoing" name="cstatus_visible[0][]" class="uni_style"  />
										Participations en cours
									</label>
									{/if}
									{if in_array('pending_selection',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="pending_selection" name="cstatus_visible[0][]" class="uni_style" />
										En attente de s&eacute;lection
									</label>
									{/if}
									{if in_array('writing_progress',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="writing_progress" name="cstatus_visible[0][]" class="uni_style"  />
										R&eacute;daction en cours <span class="f_req">*</span>
									</label>
									{/if}
									{if in_array('time_out',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="time_out" name="cstatus_visible[0][]" class="uni_style" />
										Article non envoy&eacute;
									</label>
									{/if}
									{if in_array('plag_exec',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="plag_exec" name="cstatus_visible[0][]" class="uni_style" />
										V&eacute;rification du non plagiat
									</label>
									{/if}
									{if in_array('disapproved',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="disapproved" name="cstatus_visible[0][]" class="uni_style"  />
										Article en reprise
									</label>
									{/if}
									{if in_array('correction_ongoing',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="correction_ongoing"  name="cstatus_visible[0][]" class="uni_style"  />
										Correction en cours <span class="f_req">*</span>
									</label>
									{/if}
									{if in_array('stage2',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="stage2" name="cstatus_visible[0][]" class="uni_style"  />
										En attente de validation (EP) <span class="f_req">*</span>
									</label>
									{/if}
									{if in_array('published_client',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="published_client" name="cstatus_visible[0][]" class="uni_style" />
										En attente de validation (Client) <span class="f_req">*</span>
									</label>
									{/if}
									{if in_array('published',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="published" name="cstatus_visible[0][]" class="uni_style" />
										Valid&eacute; <span class="f_req">*</span>
									</label>
									{/if}
									{if in_array('refused_client',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="refused_client" name="cstatus_visible[0][]" class="uni_style" />
										Refused by Client
									</label>
									{/if}
									{if in_array('closed',$status_step1)}
									<label class="uni-checkbox">
										<input type="checkbox" value="closed" name="cstatus_visible[0][]" class="uni_style"  />
										Close <span class="f_req">*</span>
									</label>
									{/if}
								</div>
								<div class="span2" style="vertical-align:top;"><input type="checkbox" name="checkallstatus_1" id="checkallstatus_1" onClick="selectALL('1');" value="checkallpermissions"/>&nbsp;<strong>Checkall</strong></div>
							</div>					
						</div>
					</div>
					
					<div id="error_1" class="errordisp span8 pull-right"></div>
				</div>
			{/if}
				<div class="addmore-button" id="addmore_cc_link" style="float:right"><a class="btn"><i class="icon-plus"></i></a></div> 
			</div>
					
			<div class="formSep" style="clear:both;padding-left:200px;">
				<div class="row-fluid">
					<div class="span4 form-inline">
						<a class="btn btn-success pull-left" href="/user/superclientcreate-step1?submenuId=ML9-SL1&back=1">Retour</a><div class="span1">&nbsp;</div>
						<button type="submit" name="superclient_create" class="btn btn-success pull-right">Aller en &eacute;tape 3</button>
					</div>
				</div>
			</div>
			<input type="hidden" name="modify" id="modify" value="{$modval}" />
		</form>
	</div>
</div>	