{literal}
<script type="text/javascript" >
$(document).ready(function() {
    $('#paymentsgrid').dataTable( {
        "sPaginationType": "bootstrap",
        "aaSorting": [ [0,'asc'] ],
        "iDisplayLength": 10,
        "bLengthChange": false,
        "aoColumns": [
            null,
            null,
            null,
            null,
            null
        ]
    } );
});
function pay(userid, month, year, currency)
{
    smoke.confirm("Do you want to proceed with payment?", function(e){
        if (e){
           // var target_page = "/hrm/pay-expense?batchId="+batchid+"&currency="+currency;
            var target_page="/hrm/pay-expense?userid="+userid+"&month="+month+"&year="+year+"&currency="+currency+" ";
            $.post(target_page, function(data){ //alert(data);
                var data1 = $.trim(data);
                if(data1 == 'done')
                     location.reload();
                else
                     smoke.alert('action was not successful');

            });

        }else{
            return false;
        }
    });
}
</script>
{/literal}
<h3 class="heading">Expenses Payments</h3>
<table id="paymentsgrid" class="table table-bordered table-striped table_vam ">
    <thead>
    <tr>
        <th>Sl.no</th>
        <th>Name</th>
        <th>Total Amount</th>
        <th>Month</th>

        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    {if $payments neq 'NO'}
    {foreach from=$payments key=payments_key item=payments_item name=payments_loop}
    <tr>
        <td>{$smarty.foreach.payments_loop.index+1}</td>
        <td><a href="/user/user-edit?submenuId=ML10-SL3&tabblock=edituser&userId={$payments_item.user_id}">{$payments_item.expenses_by}</a></td>
        <td><a data-toggle="modal" data-target="#expense" href="/hrm/expenses-details-pop-up?userid={$payments_item.created_by}&month={$payments_item.expense_date|date_format:'%m'}&year={$payments_item.expense_date|date_format:'%Y'}&currency={$payments_item.expense_currency}"><span class="label label-important" style="cursor:pointer;"><strong>{$payments_item.total}{if $payments_item.expense_currency eq 'euro'} &euro;{else} &pound;{/if}</strong></span></a></td>
        <td><span class="label label-gebo">{$payments_item.expense_date|date_format:"%B,  %Y"}</td>

        <td><!--<a href="javascript:void(0);" style="cursor: pointer;" onclick="acceptRefuse('accept', '{$payments_item.identifier}');"><button class="btn hint--bottom hint--info" data-hint="Accept"><i class="splashy-thumb_up"></i></button></a>
            <a href="javascript:void(0);" style="cursor:pointer;" onclick="acceptRefuse('refuse', '{$payments_item.identifier}');"><button class="btn hint--bottom hint--info" data-hint="Refuser"><i class="splashy-thumb_down"></i></button></a>
            {if $payments_item.expense_invoice neq ''}
            <a href="/BO/download_expense_invoice.php?expId={$payments_item.identifier}" class="btn hint--bottom hint--info" data-hint="download invoice"><i class="splashy-arrow_large_down"></i></a>
            {/if}-->

            {if $payments_item.topay neq 'no'}
            <a style="cursor: pointer;" onclick="pay('{$payments_item.created_by}',{$payments_item.expense_date|date_format:'%m'}, {$payments_item.expense_date|date_format:'%Y'}, '{$payments_item.expense_currency}');"><button class="btn hint--bottom hint--info" data-hint="Pay"><i class="splashy-thumb_up"></i></button></a>
            {else}
             <span class="label label-info">   No Action </span>
            {/if}
        </td>
    </tr>
    {/foreach}
    {/if}
    </tbody>
</table>
<!--///expenses detials///-->
<div class="modal4 hide fade" id="expense">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Expenses Details</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>




