{literal}
<script type="text/javascript" >
    $(document).ready(function() {
        $('#expdetailsgrid').dataTable( {
            "sPaginationType": "bootstrap",
            "aaSorting": [ [0,'asc'] ],
            "iDisplayLength": 10,
            "bLengthChange": false,
            "aoColumns": [
                null,
                null,
                null,
                null,
                null
            ]
        } );
    });
    function acceptRefuse(statusp, id)
    {
        if(statusp == 'accept')
            var status = 'accepted';
        else
            var status = 'refused';
        smoke.confirm("Do you want to "+statusp+"?", function(e){
            if (e){

                var target_page = "/hrm/accept-refuse-expense?expenseId="+id+"&status="+status;
                $.post(target_page, function(data){// alert(data);
                    var data1 = $.trim(data);
                    if(data1 == 'done'){
                        location.reload();
                       /* var userid = $("#userid").val();
                        var month = $("#month").val();
                        var year = $("#year").val();
                        var currency = $("#currency").val();
                        var href="/hrm/expenses-details-pop-up?userid="+userid+"&month="+month+"&year="+year+"&currency="+currency+" ";
                        $("#expense").removeData('modal');
                        $('#expense .modal-body').load(href);
                        $("#expense").modal();
                        $(".modal-backdrop:gt(0)").remove();*/
                    }
                    else
                        smoke.alert('action was not successful');

                });

            }else{
                return false;
            }
        });
    }
</script>
{/literal}
<h3 class="heading">Detials of <strong >{$username}</strong> spent in {if $currency eq 'euro'} &euro;{else}&pound;{/if}</h3>
<table id="expdetailsgrid" class="table table-bordered table-striped table_vam ">
    <thead>
    <tr>
        <th>Sl.no</th>
        <th>Name</th>
        <th>Amount</th>
        <th>Date</th>
        <th>Action</th>
    </tr>
    </thead>
    <tbody>
    <input id="userid" type="hidden" value="{$userid}" />
    <input id="year" type="hidden" value="{$year}" />
    <input id="month" type="hidden" value="{$month}" />
    <input id="currency" type="hidden" value="{$currency}" />
    {if $payments neq 'NO'}
    {foreach from=$payments key=payments_key item=payments_item name=payments_loop}
    <tr>
        <td>{$smarty.foreach.payments_loop.index+1}</td>
        <td>{$payments_item.expense_name}</td>
        <td><span class="label label-success">{$payments_item.expense_amount} {if $payments_item.expense_currency eq 'euro'} &euro;{else}&pound;{/if}</span></td>
        <td>{$payments_item.expense_date|date_format:"%d/%m/%Y"|upper}</td>
        <td><!--<a href="javascript:void(0);" style="cursor: pointer;" onclick="acceptRefuse('accept', '{$payments_item.identifier}');"><button class="btn hint--bottom hint--info" data-hint="Accept"><i class="splashy-thumb_up"></i></button></a>-->
            {if $payments_item.status eq NULL}
            <a href="javascript:void(0);" style="cursor:pointer;" onclick="acceptRefuse('refuse', '{$payments_item.identifier}');"><button class="btn hint--bottom hint--info" data-hint="Refuser"><i class="splashy-thumb_down"></i></button></a>
            {elseif $payments_item.status eq 'accepted'}
            <span class="label label-inverse">Payed</span>
            {else}
            <span class="label label-important">Refused</span>
            {/if}
            {if $payments_item.expense_invoice neq ''}
            <a href="/BO/download_expense_invoice.php?expId={$payments_item.identifier}" class="btn hint--bottom hint--info" data-hint="download invoice"><i class="splashy-arrow_large_down"></i></a>
            {/if}
        </td>
    </tr>
    {/foreach}
    {/if}
    </tbody>
</table>


<!--///expenses detials///-->
<div class="modal4 hide fade" id="expense">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Expenses Details</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>

