{literal}
<!-- custom scrollbar plugin -->

<link rel="stylesheet" href="/BO/theme/gebo/js/validation-engine/validationEngine.jquery.css" type="text/css"/>
<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine-fr.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>
<link href="/BO/theme/gebo/css/jquery.datetimepicker.css" rel="stylesheet">
<script src="/BO/theme/gebo/js/jquery.datetimepicker.js" type="text/javascript" charset="utf-8"></script>
<script>
	var editor=false;
	$(document).ready(function() 
	{	
		
		$("#splitturnoverform").validationEngine('attach');	
		
		$('.filter-list').hide();
		 
		var client_id={/literal}{if $smarty.get.clientid}{$smarty.get.clientid} {else}{literal}""{/literal}{/if}{literal};
		
		$("#yearlist").chosen({allow_single_deselect:false,search_contains: true});
	  	  
		$("#all_clients").chosen({allow_single_deselect:true,search_contains: true });
			  
		$("#all_sales").chosen({allow_single_deselect:true,search_contains: true});
		
		$("#product_type").chosen({allow_single_deselect:true,search_contains: true,disable_search: true});
		
		$("#product_name").chosen({allow_single_deselect:true,search_contains: true,disable_search: true});
			
		 
			  
		 //search form submit
		$('#search-filter').live('click', function(evt, params) {
				$("#search_form").submit();
		});
	
	  if(client_id)
	  {
		 	 //validation
		$("#product_status").chosen({allow_single_deselect:true,search_contains: true,disable_search: true});
		$("#product_status_load").chosen({allow_single_deselect:true,search_contains: true,disable_search: true});
		 	
		var product='{/literal}{if $smarty.get.product}{$smarty.get.product} {else}{literal}{/literal}{/if}{literal}';
		var p_type='{/literal}{if $smarty.get.p_type}{$smarty.get.p_type} {else}{literal}{/literal}{/if}{literal}';
			  // Edit if the td value Empty
			  $("[id^=splitturnover_]").live('keypress', function(event)
			  {
				  
				  	$("#splitturnoverform").validationEngine('validate');	
					if(event.which==13) 
					{
						
						 var floatRegex = /^[0-9.,]+$/;
						 var monthid = $(this).attr('id');		
						 var split_id = monthid.split('_');
						 var spitval=$(this).val();
						
							if (spitval.match(floatRegex)!=null) 
							 {     
								 $("#splitturnover_"+split_id[1]+'_'+split_id[2]+'_'+split_id[3]).closest('td').html('<img style="text-align:center;" src="/BO/theme/gebo/img/ajax_loader.gif">');
								missionsplitmonth(split_id[1],split_id[2],split_id[3],spitval,client_id,product,p_type);    
								editor=false;                   
							 }
							else
							{ 
								editor=true;
								
							}
							
					}
							
			  });
		
		
			$("#back-button").show();
			$('.filter-list').show();
			/*$('#client_details_view').dataTable({
						"sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
						"iDisplayLength" : 50,
						 "aaSorting": [],
						"bSortCellsTop": true,
						"aoColumns": [
							{  "sType": "string" ,"bSortable": false},
							{ "sType": "string","bSortable": false},
							{ "sType": "natural","bSortable": false },
							{ "sType": "natural" ,"bSortable": false},
							{ "sType": "natural" ,"bSortable": false},
							{ "sType": "natural" ,"bSortable": false},
							{ "sType": "natural" ,"bSortable": false},
							{ "sType": "natural" ,"bSortable": false},
							{ "sType": "natural" ,"bSortable": false},
							{ "sType": "natural" ,"bSortable": false},
							{ "sType": "natural" ,"bSortable": false},
							{ "sType": "natural" ,"bSortable": false},
							{ "sType": "natural" ,"bSortable": false},
							{ "sType": "natural" ,"bSortable": false},
							{ "sType": "natural" ,"bSortable": false}
						]
						   
						});*/
					
										
		
				//chart Integration
			
				var randomScalingFactor = function(){ return Math.round(Math.random()*100)};
		
						var lineChartData = {
							
							labels : ["JAN","FEB","MAR","APR","MAY","JUN","JUIL","AUG","SEP","OCT","NOV", "DEC"],
							datasets : [
							{
								label: "turnover",
								fillColor : "rgba(240,240,240,0)",
								strokeColor : "rgba(240,240,240,1)",
								pointColor : "rgba(240,240,240,1)",
								pointStrokeColor : "#fff",
								pointHighlightFill : "#fff",
								pointHighlightStroke : "rgba(240,240,240,1)",
								data : [parseFloat($("#month_01").val().replace(',','.')),parseFloat($("#month_02").val().replace(',','.')),parseFloat($("#month_03").val().replace(',','.')),
								parseFloat($("#month_04").val().replace(',','.')),parseFloat($("#month_05").val().replace(',','.')),parseFloat($("#month_06").val().replace(',','.')),parseFloat($("#month_07").val().replace(',','.')),
								parseFloat($("#month_08").val().replace(',','.')),parseFloat($("#month_09").val().replace(',','.')),parseFloat($("#month_10").val().replace(',','.')),
								parseFloat($("#month_11").val().replace(',','.')),parseFloat($("#month_12").val().replace(',','.'))]
							}
							]

						};
						options = {
						responsive: true,
						maintainAspectRatio: true
						};

					
						window.onload = function()
						{
							var ctx = document.getElementById("canvas").getContext("2d");
							ctx.width = window.innerWidth-6;
							
								window.myLine = new Chart(ctx).Line(lineChartData, options);
							
						}	
					
				
			
		}
		else
		{
		
				$("#client_details_view").hide();
				$("#back-button").hide();
				$("#date-search").show();
				$('#contract-invoice').show();
				$('.filter-list').show();
				$('#contract-invoice').dataTable({
							"sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
							"sPaginationType": "bootstrap",
							"iDisplayLength" : 1000,
							 "aaSorting": [[ 0, "asc" ]],
							"aoColumns": [
								{ "sType": "string"  },
								{ "sType": "string"  },
								{ "sType": "natural" },
								{ "sType": "natural" },
								{ "sType": "natural" },
								{ "sType": "natural" },
								{ "sType": "natural" },
								{ "sType": "natural" },
								{ "sType": "natural" },
								{ "sType": "natural" },
								{ "sType": "natural" },
								{ "sType": "natural" },
								{ "sType": "natural" },
								{ "sType": "natural" },
								{ "sType": "natural" }
							]
							});	
					
		}
	
	var user_type='{/literal}{$user_type}{literal}';
	
	if(user_type=='superadmin' || user_type=='facturation'){
		
		
		
		$('#client_details_view td.mission-val').on('click',function(e)
		{
			$(".formError").css("display","none");
			 					
			if(editor==false)
			{
				var tdwidth= $(this).width();
				
						$("#client_details_view td.mission-val").find('input').css("display","none");
						$("#client_details_view td.mission-val").find('p').show();	
										
						if($(this).find('input').val()!="")
						{
						$(this).find('p').hide();
						$(this).find('input').css("display","block");
						}
						else
						{
						$(this).find('p').hide();
						$(this).find('input').css("display","block");
						}
						$(this).find(".formError").css("display","block");
						if(tdwidth)
						{
						$(this).css("width",tdwidth);
						$(this).find('input').css("width",tdwidth-22);
						
						}
						
			}
			
		});
		
		$(document).mouseup(function (e) {
			
		if ($(e.target).has("#client_details_view").length > 0) {
			$('#client_details_view td.mission-val').find(".formError").css("display","none");
			$("#client_details_view td.mission-val").find('input').css("display","none");
			$("#client_details_view td.mission-val").find('p').show();	
			}
			});
		$("#client_details_view td").on('click',function (e) {
			if(!$(this).hasClass('mission-val'))
			{
			$('#client_details_view td.mission-val').find(".formError").css("display","none");
			$("#client_details_view td.mission-val").find('input').css("display","none");
			$("#client_details_view td.mission-val").find('p').show();	
			}
		
			});
			
	}
	
	
	
		var dateNow = new Date();
	$('#start_date').datetimepicker({
		   	format:'Y-m-d',
			lang:'fr',
			defaultDate: dateNow,
			timepicker:false		
		});
	$('#end_date').datetimepicker({
		   	format:'Y-m-d',
			lang:'fr',
			defaultDate: dateNow,
			timepicker:false		
		});
		
		
		$("#cost_display").on('change',function(){
			if($("#cost_display").is(':checked')){
			$('.cost_detail').css("display","block");
			}else{
			$('.cost_detail').css("display","none");
				}
			
			});


		
		$("#product_status").on('change',function(){

			prodstatus=$(this).val();
			if(prodstatus=='ongoing')
			{
				$('.closed').addClass('hidden');
				$('.validated').addClass('hidden');
				$('.ongoing').removeClass('hidden');
			}
			else if(prodstatus=='closed')
			{
				$('.ongoing').addClass('hidden');
				$('.closed').removeClass('hidden');
				$('.validated').removeClass('hidden');
			}
			else
			{
				$('.missionRow').removeClass('hidden');
			}


			});

		onloadstaus=$('#product_status').val();
			
			if(onloadstaus=='ongoing')
			{
				$('.closed').addClass('hidden');
				$('.validated').addClass('hidden');
				$('.ongoing').removeClass('hidden');
			}
			else if(onloadstaus=='closed')
			{
				$('.ongoing').addClass('hidden');
				$('.closed').removeClass('hidden');
				$('.validated').removeClass('hidden');
			}
			else
			{
				$('.onloadstaus').removeClass('hidden');
			}

		
});

			
		function Changewithturnover(element)
		{
			status=element.value;
			currenthref=location.href;
			ahref=currenthref.replace(/(&status=)[^\&]+/, '');
			window.location.href=ahref+'&status='+status;
		}
		

	function missionsplitmonth(mission_id,month_year,contract_id,spitval,client_id,product,p_type){
			var val=spitval.replace(',','.');
		if(val!=0){
			
			$.post('/turnover/update-followp-turnover/',{
					'mission_id':mission_id,
					'month_year':month_year,
					'contract_id': contract_id,
					'turnover': val,
					'fil-product': product,
					'fil-p_type': p_type,
					'clientid':client_id
					},function(data){
						if(data)
						{
						$("#client_contract_details").html(data);
							
						}	 
					})
			
			}
		
		}	
		
		$(document).on("click",".sales_details",function(){

			$("#salesProfileView").modal('show');
			$("#salesProfileView").removeClass( "hide" ).addClass("in");
			
	});
		$(document).on("click",".monthActionList a",function(){
			$("#contractmonthly").modal('show');
			$("#contractmonthly").removeClass( "hide" ).addClass("in");
			
	});
		$(document).on("click",".close",function(){

			$(".modal-backdrop").modal('hide');
					
	});
		$(document).on("click",".modal-backdrop",function(){

			$(".modal-backdrop").modal('hide');
					
	});
	 $('body').on('hidden', '.modal', function () {
        $(this).removeData('modal');
		//$('.modal-body').html('');
		$("body").css("overflow", "auto");
    });
	
		
	$(document).on('change',"#cost_display",function(){
		
		
		 if($("#cost_display").is(":checked") &&  $("#margin_display").prop("checked")==false){
			 $('th.missionhead').attr("colspan","2");
			 $('.cost_detail').show();
			
			}
			else if(($("#margin_display").is(":checked")) && ($("#cost_display").is(":checked")))
			{
				$('th.missionhead').attr("colspan","3");
				$('.margin_detail').show();
				$('.cost_detail').show();
				
					}
			else{
				if($("#margin_display").is(":checked")){
						$('.cost_detail').hide();
						$('th.missionhead').attr("colspan","2");
					}else{
					$('.cost_detail').hide();
					$('.margin_detail').hide();
					$('th.missionhead').attr("colspan","1");
						}
			
			}
		
		});
		
	$(document).on('change',"#margin_display",function(){
		
	 if($("#margin_display").is(":checked") && $("#cost_display").prop("checked")==false)
		 {
				$('th.missionhead').attr("colspan","2");
				 $('.margin_detail').show();
				
				
		}
		else if($("#margin_display").is(":checked") && $("#cost_display").is(":checked"))
			{
				
				$('.cost_detail').show();
				$('.margin_detail').show();
				$('th.missionhead').attr("colspan","3");
				
				
				
		}
		else{
			if($("#cost_display").is(":checked")){
					$('.margin_detail').hide();
					$('th.missionhead').attr("colspan","2");
				}
				else{
					$('.cost_detail').hide();
					$('.margin_detail').hide();
					$('th.missionhead').attr("colspan","1");
					}
			}
		
		});
		
		
				
</script>
<style>
	.wrapper .table thead th {
    background-color: inherit !important;
	}
	.image {
     height: 50px;
    text-align: center;
    width: 50px;
	}
  #search-filter,input#start_date,input#end_date,#back-button{
	  margin-bottom: 23px;
  }
  
  input.turnover{
	  margin-bottom: 23px;
  }
  
.fullscreen {
    left: 0 !important;
    margin-left: 0 !important;
    top: 0 !important;
    width: 99%;
}
img.image{
	margin:5px;
	}
.modal-backdrop.fade.in{
	opacity: 0.8 !important;
	}
 p.entered_val{
	color:#FF0000 !important;
	}
.wrapper table {
   width: 100% !important;
   border-collapse: separate !important;
  }
 
td.mission-val{
text-align:center;
}
.wrapper table thead th:last-child {
    background-color: #1fbba6 !important;
}

.wrapper table th, table td{
	padding: 8px ;
	}
.realtotal{
    color: #89c0f7;
    font-weight: bold;
    text-transform: uppercase;
}
.realtotal a{
font-size: 26px;
 }


</style>


{/literal}
<section id="WrapSection">

	
		<div class="row-fluid">
					<h1>Theorical Turnover {$invoce}  {$default_year}  {if $client_details.client_name} {$client_details.client_name}{/if}
						<!--{if $totalturnoverexpeuro} {$totalturnoverexpeuro|zero_cut_t:2} &euro; ({$totalturnoverexppound|zero_cut_t:2} &pound;) {/if} -->
					</h1>
					
				</div>
		<div style="margin-top:20px">
			<form name="search_form" id="search_form" method="get" action="">
				<select data-placeholder="Years" id="yearlist" class='yearselect' name="year" >
									<option></option>
										{foreach from=$year_list item=year name=year_loop}
										{if $year eq $default_year}
										   <option value="{$year}" selected="selected" >{$year}</option>
										   {else}
										   <option value="{$year}" >{$year}</option>
										   {/if}
										{/foreach}
									</select>
				{if $smarty.get.clientid}
							
								<input type="hidden" value="{$smarty.get.clientid}" name="clientid">	
								
									<span style="display:none">{$salesownerdetail.sales_details|@asort}</span>
									
									<select data-placeholder="All Sales" id="all_sales" class='saleselect' name="sales_id" >
										<option></option>
										{foreach from=$salesownerdetail.sales_details item=user name=users key=usrkey}
											{if $usrkey eq $smarty.get.sales_id}
												<option value="{$usrkey}" selected="selected">{$user}</option>
											{else}
												<option value="{$usrkey}" >{$user}</option>
											{/if}
										{/foreach}
									</select>
									
									<select data-placeholder="All Mission Type" id="product_type" class='producttypeselect' name="p_type" >
										<option></option>
									{foreach from=$procuct_type_array item=type_item name=product_loop key=product_type_key}
											{if $product_type_key eq $smarty.get.p_type}
											<option value="{$product_type_key}" selected="selected">{$type_item}</option>
											{else}
											<option value="{$product_type_key}" >{$type_item}</option>
											{/if}
									{/foreach}
									</select>
									
									<select data-placeholder="All Mission Product" id="product_name" class='productselect' name="product">
										<option></option>
										{foreach from=$product_total_array item=type_item name=product_loop key=product_key}
											{if $product_key eq $smarty.get.product}
											<option value="{$product_key}" selected="selected">{$type_item}</option>
											{else}
											<option value="{$product_key}" >{$type_item}</option>
											{/if}
									{/foreach}
										
									</select>

									
					{else}
							
							<select data-placeholder="All Clients" id="all_clients" class='clientselect' name="client_id" >
								<option></option>
										{foreach from=$client_list item=user name=users key=userkey}
										{if $userkey eq $smarty.get.client_id}
										<option value="{$userkey}" selected="selected">{$user}</option>
										{else}
										<option value="{$userkey}" >{$user}</option>
									{/if}
								{/foreach}
							</select>
							<span style="display:none">{$salesownerdetail.sales_details|@asort}</span>
							
							<select data-placeholder="All Sales" id="all_sales" class='saleselect' name="sales_id" >
								<option></option>
									{foreach from=$salesownerdetail.sales_details item=user name=users key=usrkey}
										{if $usrkey eq $smarty.get.sales_id}
											<option value="{$usrkey}" selected="selected">{$user}</option>
										{else}
											<option value="{$usrkey}" >{$user}</option>
										{/if}
									{/foreach}
							</select>
							<!-- {*<span id="date-search" style="display:none">
							<span id="start_text"><input type="text" id="start_date" placeholder="Start Date" name="start_date" value="{$smarty.get.start_date}" class="validate[required]"></span>
							<span id="end_text"><input type="text" id="end_date" name="end_date" placeholder="End Date"  value="{$smarty.get.end_date}" class="validate[required]"></span>
							</span>*}   -->
					{/if}
					<a class="btn btn-gebo pull-center" id="search-filter" >Search</a>
					<a class="btn btn-info pull-right" href="/turnover/split-month-turnover?submenuId=ML13-SL3" style="display:none;"  id="back-button" >Back</a>
					</form>
				</div>
	<div class="row-fluid wrapper">
			<table class="table table-hover table-bordered" id="contract-invoice" style="display:none;">
						<thead>
							<tr class="displayDatas">
							    <th>Code</th>
							    <th style="width:250px">Client Name</th>
							   {foreach from=$month_array_val item=monthhead name=monthloop }
							    <th>{$monthhead}</th>
							   {/foreach}
							   <th class="total-row">TOTAL <span class="yearTotal">{$default_year}</span></th>
							  
							</tr>
						</thead>
						
					{if $quotecontractlist|@count>0}

					<tbody>
                    {assign var='total_euro_01' value=0}
                    {assign var='total_euro_02' value=0}
                    {assign var='total_euro_03' value=0}
                    {assign var='total_euro_04' value=0}
                    {assign var='total_euro_05' value=0}
                    {assign var='total_euro_06' value=0}
                    {assign var='total_euro_07' value=0}
                    {assign var='total_euro_08' value=0}
                    {assign var='total_euro_09' value=0}
                    {assign var='total_euro_10' value=0}
                    {assign var='total_euro_11' value=0}
                    {assign var='total_euro_12' value=0}
                    {assign var='total_pounds_01' value=0}
                    {assign var='total_pounds_02' value=0}
                    {assign var='total_pounds_03' value=0}
                    {assign var='total_pounds_04' value=0}
                    {assign var='total_pounds_05' value=0}
                    {assign var='total_pounds_06' value=0}
                    {assign var='total_pounds_07' value=0}
                    {assign var='total_pounds_08' value=0}
                    {assign var='total_pounds_09' value=0}
                    {assign var='total_pounds_10' value=0}
                    {assign var='total_pounds_11' value=0}
                    {assign var='total_pounds_12' value=0}
                    {assign var=toconcount value=1}
				{foreach from=$quotecontractlist item=contract_item name=contracts_loop}
				{assign var=conclient_id value=$contract_item.client_id}
							
							<tr>
								<td>{$contract_item.client_code}</td>
								<td><span class="hidden">{$contract_item.client_name}</span><a href="/turnover/split-month-turnover?submenuId=ML13-SL3&clientid={$contract_item.client_id}&year={$default_year}&sales_id={$smarty.get.sales_id}">{$contract_item.client_name}</a></td>
								{foreach from=$contract_item.monthlist name=split_loop item=split_month_item}
                                    {assign var=month_year value=$default_year|cat:'-'|cat:$split_month_item}
                                    <td>{$contract_item.splitmonth.$conclient_id.euro.$month_year|zero_cut_t:2} &euro;<br>{$contract_item.splitmonth.$conclient_id.pounds.$month_year|zero_cut_t:2} &pound;</td>
                                       {if $split_month_item eq "01"}
                                        {assign var='total_euro_01' value=$total_euro_01+$contract_item.splitmonth.$conclient_id.euro.$month_year}
                                        {elseif $split_month_item eq "02"}
                                        {assign var='total_euro_02' value=$total_euro_02+$contract_item.splitmonth.$conclient_id.euro.$month_year}
                                        {elseif $split_month_item eq "03"}
                                        {assign var='total_euro_03' value=$total_euro_03+$contract_item.splitmonth.$conclient_id.euro.$month_year}
                                        {elseif $split_month_item eq "04"}
                                        {assign var='total_euro_04' value=$total_euro_04+$contract_item.splitmonth.$conclient_id.euro.$month_year}
                                        {elseif $split_month_item eq "05"}
                                        {assign var='total_euro_05' value=$total_euro_05+$contract_item.splitmonth.$conclient_id.euro.$month_year}
                                        {elseif $split_month_item eq "06"}
                                        {assign var='total_euro_06' value=$total_euro_06+$contract_item.splitmonth.$conclient_id.euro.$month_year}
                                        {elseif $split_month_item eq "07"}
                                        {assign var='total_euro_07' value=$total_euro_07+$contract_item.splitmonth.$conclient_id.euro.$month_year}
                                        {elseif $split_month_item eq "08"}
                                        {assign var='total_euro_08' value=$total_euro_08+$contract_item.splitmonth.$conclient_id.euro.$month_year}
                                        {elseif $split_month_item eq "09"}
                                        {assign var='total_euro_09' value=$total_euro_09+$contract_item.splitmonth.$conclient_id.euro.$month_year}
                                        {elseif $split_month_item eq "10"}
                                        {assign var='total_euro_10' value=$total_euro_10+$contract_item.splitmonth.$conclient_id.euro.$month_year}
                                        {elseif $split_month_item eq "11"}
                                        {assign var='total_euro_11' value=$total_euro_11+$contract_item.splitmonth.$conclient_id.euro.$month_year}
                                        {elseif $split_month_item eq "12"}
                                        {assign var='total_euro_12' value=$total_euro_12+$contract_item.splitmonth.$conclient_id.euro.$month_year}
                                        {/if}
                                        {if $split_month_item eq "01"}
                                        {assign var='total_pounds_01' value=$total_pounds_01+$contract_item.splitmonth.$conclient_id.pounds.$month_year}
                                        {elseif $split_month_item eq "02"}
                                        {assign var='total_pounds_02' value=$total_pounds_02+$contract_item.splitmonth.$conclient_id.pounds.$month_year}
                                        {elseif $split_month_item eq "03"}
                                        {assign var='total_pounds_03' value=$total_pounds_03+$contract_item.splitmonth.$conclient_id.pounds.$month_year}
                                        {elseif $split_month_item eq "04"}
                                        {assign var='total_pounds_04' value=$total_pounds_04+$contract_item.splitmonth.$conclient_id.pounds.$month_year}
                                        {elseif $split_month_item eq "05"}
                                        {assign var='total_pounds_05' value=$total_pounds_05+$contract_item.splitmonth.$conclient_id.pounds.$month_year}
                                        {elseif $split_month_item eq "06"}
                                        {assign var='total_pounds_06' value=$total_pounds_06+$contract_item.splitmonth.$conclient_id.pounds.$month_year}
                                        {elseif $split_month_item eq "07"}
                                        {assign var='total_pounds_07' value=$total_pounds_07+$contract_item.splitmonth.$conclient_id.pounds.$month_year}
                                        {elseif $split_month_item eq "08"}
                                        {assign var='total_pounds_08' value=$total_pounds_08+$contract_item.splitmonth.$conclient_id.pounds.$month_year}
                                        {elseif $split_month_item eq "09"}
                                        {assign var='total_pounds_09' value=$total_pounds_09+$contract_item.splitmonth.$conclient_id.pounds.$month_year}
                                        {elseif $split_month_item eq "10"}
                                        {assign var='total_pounds_10' value=$total_pounds_10+$contract_item.splitmonth.$conclient_id.pounds.$month_year}
                                        {elseif $split_month_item eq "11"}
                                        {assign var='total_pounds_11' value=$total_pounds_11+$contract_item.splitmonth.$conclient_id.pounds.$month_year}
                                        {elseif $split_month_item eq "12"}
                                        {assign var='total_pounds_12' value=$total_pounds_12+$contract_item.splitmonth.$conclient_id.pounds.$month_year}
                                        {/if}

                                {/foreach}
							   <td style="text-align:right">{$contract_item.splitmonth.$conclient_id.euro.turnover} &euro;<br>{$contract_item.splitmonth.$conclient_id.pounds.turnover|zero_cut_t:2} &pound;</td>
								{assign var=toconcount value=$toconcount+1}
								</tr>
							
				{/foreach}
				<tbody>
                <tfoot>
                <tr class="alert-info">
                    <td colspan="2">Total</td>
                    <td style="text-align:center">{$total_euro_01|zero_cut_t:2} &euro;<br/>{$total_pounds_01|zero_cut_t:2} &pound;</td>
                    <td style="text-align:center">{$total_euro_02|zero_cut_t:2} &euro;<br/>{$total_pounds_02|zero_cut_t:2} &pound;</td>
                    <td style="text-align:center">{$total_euro_03|zero_cut_t:2} &euro;<br/>{$total_pounds_03|zero_cut_t:2} &pound;</td>
                    <td style="text-align:center">{$total_euro_04|zero_cut_t:2} &euro;<br/>{$total_pounds_04|zero_cut_t:2} &pound;</td>
                    <td style="text-align:center">{$total_euro_05|zero_cut_t:2} &euro;<br/>{$total_pounds_05|zero_cut_t:2} &pound;</td>
                    <td style="text-align:center">{$total_euro_06|zero_cut_t:2} &euro;<br/>{$total_pounds_06|zero_cut_t:2} &pound;</td>
                    <td style="text-align:center">{$total_euro_07|zero_cut_t:2} &euro;<br/>{$total_pounds_07|zero_cut_t:2} &pound;</td>
                    <td style="text-align:center">{$total_euro_08|zero_cut_t:2} &euro;<br/>{$total_pounds_08|zero_cut_t:2} &pound;</td>
                    <td style="text-align:center">{$total_euro_09|zero_cut_t:2} &euro;<br/>{$total_pounds_09|zero_cut_t:2} &pound;</td>
                    <td style="text-align:center">{$total_euro_10|zero_cut_t:2} &euro;<br/>{$total_pounds_10|zero_cut_t:2} &pound;</td>
                    <td style="text-align:center">{$total_euro_11|zero_cut_t:2} &euro;<br/>{$total_pounds_11|zero_cut_t:2} &pound;</td>
                    <td style="text-align:center">{$total_euro_12|zero_cut_t:2} &euro;<br/>{$total_pounds_12|zero_cut_t:2} &pound;</td>
                    <th class="total-row" style="text-align:right"><span class="yearTotal">{$totalturnoverexpeuro|zero_cut_t:2} &euro;<br>{$totalturnoverexppound|zero_cut_t:2} &pound;</span></th>

                </tr>
                </tfoot>
				{/if}
				
					</table>
				</div>
				{if $client_details|@count>0}
				
				<div id="clientFocus" class="row-fluid" >
					
						<div class="clientFocusHeader">					
							<h3 id="myModalLabel" ><strong>{$client_details.client_name}-{$default_year}</strong></h3>
							</div>
						<canvas id="canvas" width="1291px" height="309px;"  class='img-responsive' ></canvas>
												
				
				<div id="client_contract_details">
					
					<form method="POST" name="splitturnoverform" id="splitturnoverform" enctype="multipart/form-data" class="form-horizontal">
					<select data-placeholder="All Mission status" id="product_status" class='productstatus' name="product_status">
					<option></option>
										<option value="all" {if $smarty.get.status eq 'all'}selected="selected"{/if}>All</option>
											<option value="ongoing" {if $smarty.get.status eq 'ongoing' || ($smarty.get.status neq 'closed' && $smarty.get.status neq 'all')}selected="selected"{/if}>ongoing</option>
								<option value="closed" {if $smarty.get.status eq 'closed'}selected="selected"{/if}>closed</option>
											
									</select>

					<select data-placeholder="All Mission status affect turnover" id="product_status_load" class='productstatus' name="status" onchange="Changewithturnover(this);">
					<option></option>
								<option value="all" {if $smarty.get.status eq 'all'}selected="selected"{/if}>All</option>
									<option value="ongoing" {if $smarty.get.status eq 'ongoing' || ($smarty.get.status neq 'closed' && $smarty.get.status neq 'all')}selected="selected"{/if}>ongoing</option>
						<option value="closed" {if $smarty.get.status eq 'closed'}selected="selected"{/if}>closed</option>
											
									</select>
				<table class="focusTable" id="client_details_view">
					<thead>
						<tr>
						    <th >SALES</th>
							<th ><span class="pull-left">CLIENT/CONTRACTS</span></th>
							{foreach from=$month_array_val item=monthhead name=monthloop key=mkey}
							<th class="months">{$monthhead}<span class="monthViewCta">
								<i class="fa fa-plus" id="monthActions"></i>
								<div class="monthActionList">
									<a role="button" href="/turnover/contract-monthly-details?client_id={$client_details.client_id}&month={$default_year}-{$mkey}{if $smarty.get.status}&status={$smarty.get.status}{/if}" tabindex="-1" data-toggle="modal"  data-target="#contractmonthly"  data-hint="{$salesownerdetail.$quotecontract_id.sales_owner}"><i class="fa fa-eye"></i></a>						
								</div>
							</span>	</th>
							{/foreach}
						    <th class="months">TOTAL </th>
						</tr>
					</thead>
					<tbody>
					<tr class="contractRow">
					{assign var=client_identifier value=$client_details.client_id}	
					<td></td>
					<td><span class="contractName pull-left">{$client_details.client_name}</span></td>
						{foreach from=$monthlist item=month_item name=month_loop}
						{assign var=month_year value=$default_year|cat:'-'|cat:$month_item}
						<td class="months"><div class="dataFocus">
								<span class="singleData">{if $contract_details.totalclient.$client_identifier.$month_year eq 0}
								{$contract_details.totalclient.$client_identifier.$month_year|zero_cut_t:2}
								<input type="hidden" id="month_{$month_item}"  value="0">
								{else}
								{$contract_details.totalclient.$client_identifier.$month_year|zero_cut_t:2}
								<input type="hidden" id="month_{$month_item}"  value="{$contract_details.totalclient.$client_identifier.$month_year}">
							{/if}</span>	
							</div>
						</td>
						
					{/foreach}
					 <td class="months"><div class="dataFocus">
								<span class="singleData">{if $contract_details.totalclient.$client_identifier.turnover eq 0}
								{$contract_details.totalclient.$client_identifier.turnover|zero_cut_t:2}
								{else}
							    {$contract_details.totalclient.$client_identifier.turnover|zero_cut_t:2} &{$contract_details.totalclient.$client_identifier.sales_suggested_currency};
						{/if}</span>	
							</div>
					</td>	
					</tr>	
					
					
					{foreach from=$contract_details item=contract_item name=contract_loop}
						{assign var=quotecontract_id value=$contract_item.quotecontractid}
					{if $quotecontract_id neq ""}
					<tr class="contractRow active {$quotecontract_id}">					
							<td>
							<a class="hint--right sales_details" href="/turnover/sales-details?sales_id={$salesownerdetail.$quotecontract_id.sales_creator_id}" role="button" data-toggle="modal"  data-target="#salesProfileView"  data-hint="{$salesownerdetail.$quotecontract_id.sales_owner}">
								<img src="{$fo_path}profiles/bo/{$salesownerdetail.$quotecontract_id.sales_creator_id}/logo.jpg?123" class="image rd_30" alt="{$salesownerdetail.$quotecontract_id.sales_owner}"></a>
							</td>
							<td>
								<span class="contractName pull-left ">							
									<a href="/contractmission/contract-edit?contract_id={$quotecontract_id}&submenuId=ML13-SL3">{$contract_item.contractname}</a>
								</span>
							</td>
							
								{foreach from=$monthlist item=month_item name=month_loop}
								{assign var=month_year value=$default_year|cat:'-'|cat:$month_item}
								<td><div class="dataFocus">
								<span class="singleData">{if $contract_details.contract_Contrat_details.$quotecontract_id.$month_year eq 0}
								{$contract_details.contract_Contrat_details.$quotecontract_id.$month_year|zero_cut_t:2}{else}
								{$contract_details.contract_Contrat_details.$quotecontract_id.$month_year|zero_cut_t:2}
								{/if}</span>	
							</div>
								</td>
								
							{/foreach}
							 <td ><div class="dataFocus">
								<span class="singleData">
								 {if $contract_details.contract_Contrat_details.$quotecontract_id.turnover eq 0}
									   {$contract_details.contract_Contrat_details.$quotecontract_id.turnover|zero_cut_t:2}
									   {else}
										{$contract_details.contract_Contrat_details.$quotecontract_id.turnover|zero_cut_t:2} &{$contract_details.contract_Contrat_details.$quotecontract_id.sales_suggested_currency};
								{/if}</span>	
							</div>
							</td>		
							</tr>
								{assign var=missioncount value=0}
								{assign var=mission_array value=""}
								{assign var=mission_array value=$contract_details.contract_Contrat_details.$quotecontract_id}
								{foreach from=$mission_array item=mission_item name=mission_loop}
								{assign var=mission_id value=$mission_item}
								{if $mission_id neq "" && $mission_array.$mission_id.mission_type && $mission_array.$mission_id|is_array }
							<tr class="missionRow active {$mission_id} {$mission_array.$mission_id.cm_status}">
									<td>
									{if $mission_array.$mission_id.assigned_to}
									<a class="hint--right" data-hint="{$mission_array.$mission_id.assigned_name}">
									<img src="{$fo_path}profiles/bo/{$mission_array.$mission_id.assigned_to}/logo.jpg?123" class="image rd_30" alt="{$mission_array.$mission_id.assigned_name}"  >
									</a>
									{else}
										-
									{/if}
									</td>
								<td ><span class="contractName pull-left">{$mission_array.$mission_id.mission_type}</span></td>
													{foreach from=$monthlist item=mission_month_item name=mission_month_item_loop}
															{assign var=mission_month_year value=$default_year|cat:'-'|cat:$mission_month_item}
															{if $mission_array.$mission_id.$mission_month_year eq 0}
																<td class="mission-val"><div class="dataFocus">
														<span class="singleData"><p >{$mission_array.$mission_id.$mission_month_year|zero_cut_t:2}</p>
														<input type="text" class="validate[required, custom[onlyCommaSp]]" id="splitturnover_{$mission_id}_{$mission_month_year}_{$quotecontract_id}" style="display:none;" /></td>
															</span></div>{else}
																<td class="mission-val" ><div class="dataFocus">
															<span class="singleData">
																	{assign var=followup value=$mission_month_year|cat:'-from_followup'}
																{if $mission_array.$mission_id.$followup eq 1}
																<p class="entered_val">{$mission_array.$mission_id.$mission_month_year|zero_cut_t:2}</p>
																<input type="text"  class="validate[required, custom[onlyCommaSp]]" id="splitturnover_{$mission_id}_{$mission_month_year}_{$quotecontract_id}" value="{$mission_array.$mission_id.$mission_month_year+0}" style="display:none;"/>
																{else}
																{$mission_array.$mission_id.$mission_month_year|zero_cut_t:2}
																{/if}
																</span></div></td>
																{/if}
															
													{/foreach}
												<td><div class="dataFocus">
															<span class="singleData">
													 {if $mission_array.$mission_id.turnover eq 0}
														   {$mission_array.$mission_id.turnover|zero_cut_t:2}
														   {else}
															{$mission_array.$mission_id.turnover|zero_cut_t:2} &{$contract_details.contract_Contrat_details.$quotecontract_id.sales_suggested_currency};
													{/if}</span></div>
												</td>	
													
											
										</tr>
										{/if}
										{assign var=missioncount value=$missioncount+1}
							{/foreach}
							
			{/if}
		{/foreach}
				    </tbody>
				</table>
				
				<!-- MOdel Popup for sales details -->
				
				</form>
				</div>
				</div>
				<div class="row-fluid">
					<div class="modal hide fade" id="salesProfileView"  aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1">
							
						<div class="modal-body">
							
						</div>
					</div>
				</div>
				 <div class="row-fluid">
					<div class="modal hide fade fullscreen" id="contractmonthly"  aria-hidden="true" aria-labelledby="myModalLabel" role="dialog" tabindex="-1">
						 
						<div class="modal-body">
							<div style="text-align:center"><b>Please Wait Loading ...</b></div>
						</div>
					</div>
					</div>
		
				{/if}
				<a class="btn btn-default" href="/turnover/split-month-report?download=pdf{if $smarty.get.client_id}&client_id={$smarty.get.client_id}{/if}{if $default_year}&year={$default_year}{/if}{if $smarty.get.sales_id}&sales_id={$smarty.get.sales_id}{/if}{if $smarty.get.clientid}&client_id={$smarty.get.clientid}{/if}{if $smarty.get.product}&product={$smarty.get.product}{/if}{if $smarty.get.p_type}&p_type={$smarty.get.p_type}{/if}{if $smarty.get.status}&status={$smarty.get.status}{/if}">Export PDF</a>
			<a class="btn btn-primary" href="/turnover/split-month-report{if $default_year}?year={$default_year}{/if}{if $smarty.get.client_id}&client_id={$smarty.get.client_id}{/if}{if $smarty.get.sales_id}&sales_id={$smarty.get.sales_id}{/if}{if $smarty.get.clientid}&client_id={$smarty.get.clientid}{/if}{if $smarty.get.product}&product={$smarty.get.product}{/if}{if $smarty.get.p_type}&p_type={$smarty.get.p_type}{/if}{if $smarty.get.status}&status={$smarty.get.status}{/if}">Export XLS</a> 
		
	</section>
{literal}
	<script>
		$(document).ready(function(){
				
				$('body').on('hidden', '#contractmonthly', function (){        
					$(this).removeData('modal');				
					$('.modal-body',this).html('<div style="text-align:center"><b>Please Wait Loading ...</b></div>');		
					$("body").css("overflow", "auto");    
				});
				
		});
	
	</script>
{/literal}


