{literal}
    <script type="text/javascript" >
// Read a page's GET URL variables and return them as an associative array.
function getUrlVars()
{
    var vars = [], hash;
    var hashes = window.location.href.slice(window.location.href.indexOf('?') + 1).split('&');
    for(var i = 0; i < hashes.length; i++)
    {
        hash = hashes[i].split('=');
        vars.push(hash[0]);
        vars[hash[0]] = hash[1];
    }
    return vars;
}
$(function(){
$( "#print_invoice" ).click(function(){

    $( "#logo" ).show();
    $( "#tag1" ).show();
    $( "#tag2" ).show();
    $( "#invoicePrint" ).print();
});
});
$(function(){

   if(getUrlVars()["print"]=='yes')
   {

	$( "#logo" ).show();
    $( "#tag1" ).show();
    $( "#tag2" ).show();
    $( "#invoicePrint" ).print();
    }
 });
</script>
<style type="text/css">
 .table td {
    border-top: 1px solid #DDDDDD;
    line-height: 20px;
    padding: 8px;
    text-align: center;
    vertical-align: top;
}
</style>
{/literal}

<div class="row-fluid"  id="invoicePrint" >
	<div class="span12">
		 <table style="width: 100%;float:left;" cellpadding="5" cellspacing="5">
            <tr>
                <td colspan="2"><img src="http://ep-test.edit-place.com/FO/images/logo-edit-place-old.png" style="background-repeat: no-repeat;" width="279px" height="49px"/><br>
                67-70 Charlotte Road<br><br>EC2A 3PE LONDRES - UK
                </td>
                <td>&nbsp;</td>
                <td style="text-align:left;background-color:#FFF;font-size:12pt;float:right;width:250px;">
                    <b>Bon de commande</b><br><br>
                    #{$invoice_identifier}<br><br>
                    Date: {$date_invoice} 
                </td>
            </tr>                   
            <tr>
                <td colspan="4">&nbsp;</td>
            </tr>
            <tr>                        
                 <td colspan="2" style="font-size: 12pt;">
                    {$address} <br>
                     <b>D&eacute;tails de paiement :</b><br><br>
                    {$full_name}<br><br>
                    {$payinfo_number}
                    {$bank_account_name}
                    {$remuneration}
                </td>
                <td>&nbsp;</td>
                <td style="text-align:left;background-color:#FFF;font-size:12pt;float:right;width:250px;">
                    <b>Bon de commande adress&eacute; &agrave; :</b><br><br>
                    <b>Edit-Place Uk</b><br>
                    67-70 Charlotte Road<br>
					EC2A 3PE London<br>
					England<br><br>
					VAT : GB 182 0572 18	
                </td>
            </tr>            
        </table> 

		<table style="width: 100%;float:left;" cellpadding="5" cellspacing="5">
            <tr>
                <td>&nbsp;</td>
            </tr>
            <tr>
                <td>&nbsp;</td>
            </tr>
        </table>		
		<table class="table table-hover">
			
				{$invoice_details_pdf}

				{$tax_details_pdf}

				{$final_invoice_amount}

				{$bank_transfer_price}

				{$total_transfer_amount}
			</tbody>
		</table>

		<div style="width:100%;float:left;">
            <table style="width: 50%;padding-top:0px;float:left;">                    
                <tr>                        
                    <td style="text-align: left;background-color:#FFF;padding:10px;font-size: 12pt;">
                        Merci
                    </td>
                </tr>                   
            </table>
        </div> 		
</div>
</div>
{if $smarty.get.print neq 'yes'}
<div>
	<a class="btn btn-gebo" href="/stats/downloadinvoice?submenuId={$submenuId}&invoiceid={$invoice_identifier|replace:'ep_invoice_':''}"><i class="splashy-arrow_large_down"></i> T&eacute;l&eacute;charger ma facture</a>
	<a class="btn btn-gebo " name="print_invoice" id="print_invoice"><i class="splashy-printer"></i> Imprimer</a>
</div>		
{/if}
		