{literal}
<script type="text/javascript" >
    $(document).ready(function() {
        if ($('#stats-newsletter').length) {
            $('#stats-newsletter').dataTable({
                "sPaginationType" : "bootstrap",
                "iDisplayLength" : 25,
                "sDom" : "<'row'<'span4'l><'span4'T><'span4'f>r>t<'row'<'span6'i><'span6'p>>",
                "aoColumns" : [{
                    "sType" : "formatted-num"
                }, {
                    "sType" : "string"
                }, {
                    "sType" : "string"
                }, {
                    "sType" : "string"
                }],
                "aaSorting" : [[0, "asc"]],
                "oTableTools" : {
                    "aButtons" : ["copy", "print", {
                        "sExtends" : "collection",
                        "sButtonText" : 'Save <span class="caret" />',
                        "aButtons" : ["csv", "xls", "pdf"]
                    }],
                    "sSwfPath" : "/BO/theme/gebo/lib/datatables/extras/TableTools/media/swf/copy_csv_xls_pdf.swf"
                }
            });
        }

        $("#user").chosen({
            allow_single_deselect : true,
            search_contains : true
        });
    });
    
    function userFilter(userid)
    {
        if(userid > 0)
        {
            window.location='/stats/newsletter-details?submenuId=ML2-SL13&user_id='+userid;
        }
    }
</script>
{/literal}

<div class="row-fluid">
    <div class="span12">
        <h3 class="heading">Statistiques : Newsletter Details</h3>
        <div id="search_block">           
             <table cellspacing="5" cellpadding="5" id="searchtable">
                <tbody>
                    <tr>
                        <td>s&#233;lectionner :</td>
                        <td>
                            <select class="span8" id="user" name="user" data-placeholder="Select user" onchange="userFilter(this.value)" style="width: 100%;">
                                <option value=""></option>{$users}
                            </select>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row-fluid">
    <div class="span8 form-inline">
        <label class="span2">Name :</label><div class="span5"><strong>{$userinfo[0].first_name}&nbsp;{$userinfo[0].last_name}</strong></div>

        <label class="span2">Email :</label><div class="span3"><strong>{$userinfo[0].email}</strong></div>
    </div>
</div>
<div class="row-fluid">
    <div class="span12">

        <table class="table table-striped table-bordered dTableR" id="stats-newsletter">
            <thead>
                <th>S.No.</th>
                <th>Date of nl</th>
                <th>Status</th>
                <th>Opened at</th>
            </thead>
            <tbody>
                {foreach from=$newsletters key=newsletter_key item=newsletter_item name=newsletter_loop}
                <tr>
                    <td>{$smarty.foreach.newsletter_loop.index+1}</td>
                    <td>{$newsletter_item.created_at}</td>
                    <td>{if $newsletter_item.viewed_at neq ''}opened{else}not opened{/if}</td>
                    <td>{if $newsletter_item.viewed_at neq ''}{$newsletter_item.viewed_at}{/if}</td>
                </tr>
                {/foreach}
            </tbody>
        </table>
    </div>
</div>