{literal}
<script type="text/javascript" >

    $(document).ready(function() {	
	
       if($('#article_list').length) {
                $('#article_list').dataTable({
                    "sPaginationType": "bootstrap",
					"iDisplayLength" : {/literal}{$paginationlimit}{literal},
                     "sDom": "<'row'<'span4'l><'span4'T><'span4'f>r>t<'row'<'span6'i><'span6'p>>",
					"aoColumns": [
						{ "sType": "formatted-num" },
						{ "sType": "string" },
						{ "sType": "string" },
						{ "sType": "string" },
						{ "sType": "eu_date" },
						{ "sType": "string" }
					],
					"aaSorting": [[ 0, "asc" ]],
                    "oTableTools": {
                        "aButtons": [
                            "copy",
                            "print",
                            {
                                "sExtends":    "collection",
                                "sButtonText": 'Save <span class="caret" />',
                                "aButtons":    [ "csv", "xls", "pdf" ]
                            }
                        ],
                        "sSwfPath": "/BO/theme/gebo/lib/datatables/extras/TableTools/media/swf/copy_csv_xls_pdf.swf"
                    }
                });
            }
    });
</script>
{/literal}

<!--Bread Crumbs-->
<nav>
	<div id="jCrumbs" class="breadCrumb module">
		<ul>
			<li>
				<a href="/index"><i class="icon-home"></i></a>
			</li>
			<li>
				<a>Boursorama</a>
			</li>
			<li>
				Articles
			</li>			
		</ul>
	</div>
</nav>

<div class="row-fluid">
  <div class="span12">
    <h3 class="heading">Articles
		<a class="btn btn-gebo1 pull-right" href="/contract/create-article?submenuId=ML7-SL3">
			<i class="splashy-application_windows_add"></i>
			<span style="vertical-align: text-bottom;"> Cr&eacute;er un nouveau</span>
		</a>
	</h3>	    
       
	<table class="table table-striped table-bordered dTableR" id="article_list">
		<thead>
			<tr>
				<th>S.No.</th>
				<th>Titre de l'article</th>
				<th>Client</th>
				<th>Titre de la livraison</th>
				<th>Date de livraison</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
		{if $paginator|@count gt 0}
			{foreach from=$paginator item=article name=article_loop}
				<tr>
				   <td>{$smarty.foreach.article_loop.index+1} </td>
				   <td>{$article.title|stripslashes}</td>
				   <td id="email">{if $article.company_name neq ''}{$article.company_name} {else} <a href="javascript:void(0);" title="{$article.email}">{$article.email|truncate:16:"...":true}</a>{/if}</td>
				   <td>{$article.delivery|stripslashes}</td>
				   <td>{$article.delivery_date|date_format:$dateformat}</td>
				   <td>
					<a class="sepV_a" href="/contract/create-article?submenuId=ML7-SL3&action=edit&aid={$article.id}"><i class="icon-pencil  hint--left  hint--info" data-hint="Edit"></i></a>
					<a class="sepV_a" href="/contract/create-article?submenuId=ML7-SL3&action=clone&aid={$article.id}"><i class="splashy-document_copy  hint--left  hint--info" data-hint="Clone"></i></a>
				   </td>
				   
				</tr>

		{/foreach}		 
		{/if}	
					
		</tbody>
	</table>
                        
  </div>
</div>    