<div style="min-height:100%;margin:0;padding:0;width:100%;background-color:#f5f5f5">
    <center>
        <table align="center" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%" style="border-collapse:collapse;height:100%;margin:0;padding:0;width:100%;background-color:#f5f5f5">
            <tbody><tr>
                <td align="center" valign="top" style="height:100%;margin:0;padding:10px;width:100%;border-top:0">


                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;border:0;max-width:600px!important">
                        <tbody><tr>
                            <td valign="top" style="background-color:#f5f5f5;border-top:0;border-bottom:0;padding-top:9px;padding-bottom:9px"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                    <tbody>
                                    <tr>
                                        <td valign="top" style="padding:9px 0px">




                                            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                                <tbody><tr>
                                                    <td valign="top" style="padding:0">
                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse">
                                                            <tbody><tr>
                                                                <td valign="top">


                                                                    <img src="http://admin-ep.edit-place.com/BO/theme/gebo/css/images/workplace.png">




                                                                </td>
                                                            </tr>
                                                            </tbody></table>
                                                        <table align="right" border="0" cellpadding="0" cellspacing="0" width="396" style="border-collapse:collapse">
                                                            <tbody><tr>
                                                                <td valign="top" style="font-size:20px;word-break:break-word;color:#454545;font-family:Helvetica;line-height:150%;text-align:right">
                                                                    Contract Release Form
                                                                </td>
                                                            </tr>
                                                            </tbody></table>
                                                    </td>
                                                </tr>
                                                </tbody></table>




                                        </td>
                                    </tr>
                                    </tbody>
                                </table></td>
                        </tr>
                        <tr>
                            <td valign="top" style="background-color:#ffffff;border-top:0;border-bottom:0;padding-top:9px;padding-bottom:0"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                    <tbody>
                                    <tr>
                                        <td valign="top" style="padding:9px">


                                            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                                <tbody><tr>
                                                    <td valign="top" style="padding:0 9px">
                                                        <table align="right" border="0" cellpadding="0" cellspacing="0" style="border-collapse:collapse">
                                                            <tbody><tr>
                                                                <td valign="top">


                                                                    <img alt="" src="https://ci4.googleusercontent.com/proxy/nBax5cJICRy95wmauXXE1sNomoVoaslgMrIiBL7cZ-rGSK99wE_EuRZlbrxDdulFSj7eJtq12hbbKi9SKqd7AhVNe8z2UCp9PEKtWcedlD_vckhD8ouLDZtsa-d8sx1BDqMF_23TO0-GU0XISs_SA6rVyB-uevuEk0g3VuM=s0-d-e1-ft#https://gallery.mailchimp.com/821af2272a84fe61007066d52/images/3bc2eb5e-c18b-4e20-85b3-07b56b239cc4.png" width="90" style="max-width:90px;border:0;min-height:auto;outline:none;text-decoration:none;vertical-align:bottom" class="CToWUd">


                                                                </td>
                                                            </tr>
                                                            </tbody></table>
                                                        <table align="left" border="0" cellpadding="0" cellspacing="0" width="264" style="border-collapse:collapse">
                                                            <tbody><tr>
                                                                <td valign="top" style="word-break:break-word;color:#454545;font-family:Helvetica;font-size:16px;line-height:150%;text-align:left">
                                                                    <span style="font-size:14px">$Client name</span><br>
                                                                    <strong>$Contract name</strong>
                                                                </td>
                                                            </tr>
                                                            </tbody></table>
                                                    </td>
                                                </tr>
                                                </tbody></table>





                                        </td>
                                    </tr>
                                    </tbody>
                                </table><table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse;table-layout:fixed!important">
                                    <tbody>
                                    <tr>
                                        <td style="min-width:100%;padding:0px 18px 10px">
                                            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-top-width:1px;border-top-style:solid;border-top-color:#eaeaea;border-collapse:collapse">
                                                <tbody><tr>
                                                    <td>
                                                        <span></span>
                                                    </td>
                                                </tr>
                                                </tbody></table>

                                        </td>
                                    </tr>
                                    </tbody>
                                </table></td>
                        </tr>
                        <tr>
                            <td valign="top">
                                <table align="center" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse;background-color:#ffffff;border-top:0;border-bottom:0;padding-top:0;padding-bottom:0">
                                    <tbody><tr>
                                        <td valign="top">

                                            <table align="right" border="0" cellpadding="0" cellspacing="0" width="400" style="border-collapse:collapse;background-color:#ffffff;border-top:0;border-bottom:0;padding-top:0;padding-bottom:0">
                                                <tbody><tr>
                                                    <td><table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                                            <tbody>
                                                            <tr>
                                                                <td valign="top">

                                                                    <table align="left" border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                                                        <tbody><tr>

                                                                            <td valign="top" style="padding-top:9px;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#454545;font-family:Helvetica;font-size:16px;line-height:150%;text-align:left">

                                                                                <p style="margin:10px 0;padding:0;color:#454545;font-family:Helvetica;font-size:16px;line-height:150%;text-align:left">
                                                                                    {$message.comment}
                                                                                </p>

                                                                            </td>
                                                                        </tr>
                                                                        </tbody></table>

                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table></td>
                                                </tr>
                                                </tbody></table>

                                            <table align="left" border="0" cellpadding="0" cellspacing="0" width="200" style="border-collapse:collapse;background-color:#ffffff;border-top:0;border-bottom:0;padding-top:0;padding-bottom:0">
                                                <tbody><tr>
                                                    <td valign="top"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                                            <tbody>
                                                            <tr>
                                                                <td valign="top">

                                                                    <table align="left" border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                                                        <tbody><tr>

                                                                            <td valign="top" style="padding-top:9px;padding-right:18px;padding-bottom:9px;padding-left:18px;word-break:break-word;color:#656565;font-family:Helvetica;font-size:12px;line-height:150%;text-align:left">

                                                                                <p style="line-height:20.8px;margin:10px 0;padding:0;color:#656565;font-family:Helvetica;font-size:12px;text-align:left"><span style="font-size:14px">Customer contact details</span><br>
                                                                                    <br>
                                                                                    <strong><span style="font-size:14px">$contact-name</span></strong><br>
                                                                                    <span style="line-height:20.8px">Directrice éditoriale et de la communication&nbsp;</span></p>

                                                                                <p style="line-height:20.8px;margin:10px 0;padding:0;color:#656565;font-family:Helvetica;font-size:12px;text-align:left"><span><a href="tel:06%2064%2022%2063%2066" style="color:#00a2ff;font-weight:normal;text-decoration:underline" target="_blank">06 64 22 63 66</a></span></p>

                                                                                <p style="line-height:20.8px;margin:10px 0;padding:0;color:#656565;font-family:Helvetica;font-size:12px;text-align:left"><span><a href="mailto:flavie.deprez@carenews.com" style="color:#00a2ff;font-weight:normal;text-decoration:underline" target="_blank">flavie.deprez@carenews.com</a></span></p>

                                                                            </td>
                                                                        </tr>
                                                                        </tbody></table>

                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table><table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse;table-layout:fixed!important">
                                                            <tbody>
                                                            <tr>
                                                                <td style="min-width:100%;padding:5px 18px 10px">
                                                                    <table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-top-width:1px;border-top-style:solid;border-top-color:#eaeaea;border-collapse:collapse">
                                                                        <tbody><tr>
                                                                            <td>
                                                                                <span></span>
                                                                            </td>
                                                                        </tr>
                                                                        </tbody></table>

                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table><table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                                            <tbody>
                                                            <tr>
                                                                <td valign="top" style="padding-top:9px;padding-right:18px;padding-bottom:9px;padding-left:18px">

                                                                    <table align="right" border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:collapse">
                                                                        <tbody><tr>
                                                                            <td align="center" valign="top" style="padding-top:0px;padding-right:0px;padding-bottom:0;padding-left:0px">



                                                                                <a href="http://www.admin.com" target="_blank"> <img alt="" src="https://ci5.googleusercontent.com/proxy/jsWcmQ8ROtF1HIH-9qn6YRQrPoSnzwO5UaK4NDfuXThVI8KTj12mk2DYY8nLTeVaWneR0c8qXt8Wv--8fF5DFYBQAyFFLRbO9UoyMJHA_ipCDGw24xIapXcN1XVnqRIDEOI79D1Gs9_56SsfQq-ApkhgM2QRtzU2Zr9NYE8=s0-d-e1-ft#https://gallery.mailchimp.com/821af2272a84fe61007066d52/images/1e16672e-d366-4322-9c80-b88f168795b0.png" width="38" style="max-width:38px;border:0;min-height:auto;outline:none;text-decoration:none;vertical-align:bottom" class="CToWUd"></a>


                                                                            </td>
                                                                        </tr>
                                                                        <tr>
                                                                            <td valign="top" style="padding:9px 18px;color:#454545;font-family:Helvetica;font-size:14px;font-weight:normal;text-align:center;word-break:break-word;line-height:150%" width="146">
                                                                                <a href="http://www.admin.com" style="color:#00a2ff;font-weight:normal;text-decoration:underline" target="_blank"><span style="color:#00a2ff">Download the PO</span></a>
                                                                            </td>
                                                                        </tr>
                                                                        </tbody></table>




                                                                </td>
                                                            </tr>
                                                            </tbody>
                                                        </table></td>
                                                </tr>
                                                </tbody></table>

                                        </td>
                                    </tr>
                                    </tbody></table>
                            </td>
                        </tr>
                        <tr>
                            <td valign="top" style="background-color:#fafafa;border-top:2px solid #eaeaea;border-bottom:0;padding-top:9px;padding-bottom:9px"><table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">

                                    <tbody>
                                    <tr>
                                        <td valign="top">


                                            <table align="left" border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                                <tbody><tr>

                                                    <td style="padding-top:9px;padding-left:18px;padding-bottom:9px;padding-right:18px">

                                                        <table border="0" cellpadding="18" cellspacing="0" width="100%" style="min-width:100%!important;border:3px solid #eeeeee;background-color:#ffffff;border-collapse:collapse">
                                                            <tbody><tr>
                                                                <td valign="top" style="color:#454545;font-family:Helvetica;font-size:14px;font-weight:normal;line-height:150%;text-align:left;word-break:break-word">
                                                                    <span style="color:#000000"><span style="font-size:20px">Mission list</span></span><br>
                                                                    <br>
                                                                    <span style="color:#a9a9a9;line-height:20.8px">TECHNICAL</span><br style="line-height:20.8px">
                                                                    <span style="font-size:14px;line-height:20.8px"><strong>XML feed generation</strong></span><br style="line-height:20.8px">
                                                                    <br style="line-height:20.8px">
                                                                    <span style="color:#a9a9a9;line-height:20.8px">CONTENT STRATEGIST</span><br style="line-height:20.8px">
                                                                    <span style="font-size:14px;line-height:20.8px"><strong>Audit SEO french website</strong></span><br>
                                                                    <br>
                                                                    <span style="color:#a9a9a9">PRODUCTION</span><br>
                                                                    <span style="font-size:14px"><strong>450 - Writing SEO Articles in french</strong></span><br>
                                                                    <span style="line-height:1.6em">5 weekly articles during the first 3 months</span><br>
                                                                    <br>
                                                                    <span style="font-size:14px;line-height:20.8px"><strong>100 - Translation Guides from french to english (UK)</strong></span><br style="line-height:20.8px">
                                                                    <span style="line-height:1.6em">Oneshot - 90 days</span><br>
                                                                    &nbsp;
                                                                </td>
                                                            </tr>
                                                            </tbody></table>
                                                    </td>
                                                </tr>
                                                </tbody></table>



                                        </td>
                                    </tr>
                                    </tbody>
                                </table><table border="0" cellpadding="0" cellspacing="0" width="100%" style="min-width:100%;border-collapse:collapse">
                                    <tbody>
                                    <tr>
                                        <td style="padding-top:0;padding-right:18px;padding-bottom:18px;padding-left:18px" valign="top" align="center">
                                            <table border="0" cellpadding="0" cellspacing="0" width="100%" style="border-collapse:separate!important;border-radius:3px;background-color:#2baadf">
                                                <tbody>
                                                <tr>
                                                    <td align="center" valign="middle" style="font-family:Arial;font-size:16px;padding:15px">
                                                        <a title="View contract" href="http://admin-ep.edit-place.com/quote/quote-followup?quote_id=150928173637928&amp;submenuId=ML13-SL2" style="font-weight:bold;letter-spacing:normal;line-height:100%;text-align:center;text-decoration:none;color:#ffffff;display:block" target="_blank">View contract</a>
                                                    </td>
                                                </tr>
                                                </tbody>
                                            </table>
                                        </td>
                                    </tr>
                                    </tbody>
                                </table></td>
                        </tr>
                        </tbody></table>


                </td>
            </tr>
            </tbody></table>
        <br><br><img alt="" src="https://ci6.googleusercontent.com/proxy/OcN-uZIjJ8QRfHQTnQ1pD6jEJ2Zi2nllKRdYyDzhtFzv0KkcarrCh3CdjIfg-PcGgdXyWkbs5UNkxel4YvPsIp03-eYANOoUpujIGYPCSO_WpF9mxBBKJP5MtR2RQ5WAYkjoibCfd2DnFKsRBU9EUkaYowfwIJ5dbUR0fQ8=s0-d-e1-ft#https://gallery.mailchimp.com/821af2272a84fe61007066d52/images/839d1318-b077-4938-a4c4-63d519e84e84.png" width="132" style="max-width:146px;border:0;min-height:auto;outline:none;text-decoration:none;vertical-align:bottom" class="CToWUd"><br><br><br>
    </center><div class="yj6qo"></div><div class="adL">
    </div></div>