{literal}
<style>
	.btn1
	{
		padding:0px 12px;
	}
	
	.mission-details
	{
		margin:0 0 15px;
	}
	
	.delete
	{
		cursor:pointer;
	}
	
	.headercolor tr th
	{
		background-color:#f1f1f1;
	}
	
	.btnmargin
	{
		margin-top: 5px;
	}
	
	.capitalise
	{
		text-transform: capitalize;
	}	
	
	#correction
	{
		width: 183px;
	}
	
	
	td .alert-info
	{
		padding:2px;
	}
	
	.assignuser
	{
		padding: 15px 15px 20px 18px;
		margin: 0 25px 0 0;
		text-align:center;
	}
	
	.assignuser:hover {background-color: #fff;border-radius: 3px;}
	
	#addshot .showshot
	{
		display:block !important;
		margin-top:10px;
	}
	
	.errortempo
	{
		border: 1px solid #d90501 !important;
		box-shadow: none !important;
	}
	
	.free-mission
	{
		font-weight: bold;
	}
	
	.free-mission input[type="radio"] 
	{
		margin-top: -2px;
	}
</style>
<link rel="stylesheet" href="/BO/theme/gebo/lib/iCheck/skins/square/blue.css" type="text/css"/>
<script src="/BO/theme/gebo/lib/iCheck/icheck.min.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/gebo/js/jquery.MultiFileQuote.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="/BO/theme/gebo/js/validation-engine/validationEngine.jquery.css" type="text/css"/>
<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine-fr.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>
<link rel="stylesheet" href="/BO/theme/gebo/lib/iCheck/skins/square/blue.css" type="text/css"/>
<script src="/BO/theme/gebo/lib/iCheck/icheck.min.js" type="text/javascript" charset="utf-8"></script><script src="/BO/theme/gebo/js/jquery.MultiFileQuote.js" type="text/javascript" charset="utf-8"></script>
<script>
var prodsubmit= true;
var private_mission ={/literal}{if $launch_recuritement=='yes' || $launch_survey=="yes"}false{else}true{/if}{literal};
var nbarticles ={/literal}"{$prod_mission_details.volume}"{literal};
var mtype ={/literal}"{$smarty.get.type}"{literal};
var writing_cost_glob ={/literal}"{$writing}"{literal};
var correction_cost_glob ={/literal}"{$proofreading}"{literal};
var other_cost_glob ={/literal}"{$autre}"{literal};
var techfiles = 0,stafffiles=0;var quote_files = 0;var seo_files = 0;var prodfiles= 0;
/* To delete files from Quote and missions */
//to delete quote missions
 $(document).on("click",".delete",function(){
	var id_identifier = $(this).attr("rel");
     var id = $(this).attr("id");
	/* if(confirm("Are you sure? Want to delete this File"))
		{
			$(this).closest("tr").remove();
			$(".onsuccessrep").html("<tr><td>Please Wait Deleting File.</td></tr>");
			$.post("/quote/delete-document",{"identifier":id_identifier,"assignmission":true},function(result){
					$(".onsuccessrep").html(result);
			}); 
		}	*/
		
		smoke.confirm("Are you sure? Want to delete this File",function(e)
			{
				if(e)
				{
                    $("#"+id).closest("tr").remove();
                    //$(".onsuccessrep").html("<tr><td>Please Wait Deleting File.</td></tr>");
					$.post("/quote/delete-document",{"identifier":id_identifier,"assignmission":true,"zip_req":true},function(result){
                        /*added by naseer on 06-11-2015*/
                        //refreshing the page for temp sake//
                        //location.reload();

                        //$(".onsuccessrep").html(result);

							seo_files--;
							if(quote_files==0 && seo_files==0)
							{
								$(".zipdownload").hide();
							}
					}); 
				}
			})
	}) 
    // to delete quotefiles
	$(document).on("click",".deletequote",function(){
	var id_identifier = $(this).attr("rel");
        var id = $(this).attr("id");
	
		smoke.confirm("Are you sure? Want to delete this File",function(e)
			{
				if(e)
				{
                    $("#"+id).closest("tr").remove();
                    //$(".onsuccessrepquote").html("<tr><td>Please Wait Deleting File.</td></tr>");
					$.post("/quote/delete-document-quote",{"identifier":id_identifier,"assignmission":true,"zip_req":true},function(result){
                        /*added by naseer on 06-11-2015*/
                        //refreshing the page for temp sake//
                        //location.reload();
							//$(".onsuccessrepquote").html(result);
							quote_files--;
							if(mtype=="tech")
								var reqfiles = techfiles;
							else if(mtype=="staff")
								var reqfiles = stafffiles;
							else
								var reqfiles = seo_files;
							if(quote_files==0 && reqfiles==0)
							{
								$(".zipdownload").hide();
							}
					}); 
				}
			})
	}) 
	//to delete techfiles
	$(document).on("click",".deletetech",function(){
	var id_identifier = $(this).attr("rel");
        var id = $(this).attr("id");
	
		smoke.confirm("Are you sure? Want to delete this File",function(e)
			{
				if(e)
				{
                    $("#"+id).closest("tr").remove();
                    //$(".onsuccessrep").html("<tr><td>Please Wait Deleting File.</td></tr>");
					$.post("/quote/delete-document-tech",{"identifier":id_identifier,"zip_req":true},function(result){
							//$(".onsuccessrep").html(result);
							techfiles--;
							if(quote_files==0 && techfiles==0)
									$(".zipdownload").hide();
					}); 
				}
			})
	}) 
	//to delte staff files
	
		
	$(document).on("click",".deletestaff",function(){
	var id_identifier = $(this).attr("rel");
        var id = $(this).attr("id");
	
		smoke.confirm("Are you sure? Want to delete this File",function(e)
			{
				if(e)
				{
                    $("#"+id).closest("tr").remove();
                    //$(".onsuccessrep").html("<tr><td>Please Wait Deleting File.</td></tr>");
					$.post("/contractmission/delete-document-staff",{"identifier":id_identifier,"zip_req":true},function(result){
                        /*added by naseer on 06-11-2015*/
                        //refreshing the page for temp sake//
                        //location.reload();
                        	//$(".onsuccessrep").html(result);
							stafffiles--;
							if(quote_files==0 && stafffiles==0)
									$(".zipdownload").hide();
					}); 
				}
			})
	})
    //to delte prod files
    $(document).on("click",".deleteprod",function(){
        var id_identifier = $(this).attr("rel");
        var id = $(this).attr("id");
        smoke.confirm("Are you sure? Want to delete this File",function(e)
        {
            if(e)
            {
                $("#"+id).closest("tr").remove();
                //$(".onsuccessrepquote ").html("<tr><td>Please Wait Deleting File.</td></tr>");
                $.post("/contractmission/delete-document-prod",{"identifier":id_identifier,"zip_req":true},function(result){
                    /*added by naseer on 06-11-2015*/
                    //refreshing the page for temp sake//
                    //location.reload();
                    //$(".onsuccessrepquote").html(result);
                    prodfiles--;
                    if(quote_files==0 && prodfiles==0)
                        $(".zipdownload").hide();
                });
            }
        })
    })
	/* Used to remove disabled from after calling validation engine */
function removeDisabled(){	setTimeout(function(){$(".MultiFile-applied").removeAttr("disabled");}, 1000);	}
	$(document).ready(function(){

		$(".freelance").on('ifChecked',function(){
			$('.freelance-section').removeClass('hidden');
		});
		$(".freelance").on('ifUnchecked',function(){
			$('.freelance-section').addClass('hidden');
		});
		$("input[name='freelance_mission']").on('ifChecked ifUnchecked',function(){

			if($(this).val()=='yes')
			{
				$('.freelance-yes').removeClass('hidden');
			}
			else
			{
				$('.freelance-yes').addClass('hidden');
			}
		});
		
		/* $("input[name='assignuser']").each(function(){
		var self = $(this),
		  label = self.next(),
		  label_text = label.text();

		label.remove();
		self.iCheck({
		  radioClass: 'iradio_line-blue',
		  insert: '<div class="icheck_line-icon"></div><div class="change">' + label_text +'</div>',
		});
	  }); */
	  
	   $("input[name='assignuser'], input[name='freelance_mission']").iCheck({
		   radioClass: 'iradio_square-blue',
		   increaseArea: '50%' 
		  });
	  $("#correction").chosen({  allow_single_deselect:false,disable_search: true });
	  //$(".cselect").chosen({  allow_single_deselect:false,disable_search: true });
	  $(".uni_style").uniform();
		$("#assignmission").validationEngine({prettySelect : true,useSuffix: "_chzn",onValidationComplete: function(form, status){
			if(status == true)
			{
				if($("#missiontype").val()=="prod" && $("#tempooption").val()=="yes")
				{
					checkMax();
					if(prodsubmit)
						return true;
				}
				else
					return true;
			}
	}});  
$("#closequote").validationEngine();	  
$("#newstaff").validationEngine();	  
jQuery('#newcomment').attr('data-prompt-position','topLeft');
jQuery('#newcomment').data('promptPosition','topLeft');
jQuery('#staffcomment').attr('data-prompt-position','topLeft');
jQuery('#staffcomment').data('promptPosition','topLeft');

		/* To check for Recruitment and Survey */
		
		$(".launch").click(function(){
			if($(".launch:checked").val()=="recruitment")
			{
				$(".privatedelivery").attr('checked','checked');
				private_mission = false;
			}
			else if($(".launch:checked").val()=="survey")
			{
				$(".privatedelivery").removeAttr('checked');
				private_mission = false;
			}
			else
				private_mission = true; 
		})
		
		$(".privatedelivery").click(function(){
			return private_mission;
		});
		
		quote_files = parseInt($(".onsuccessrepquote tr").length);
		if(mtype=="tech")
			techfiles = $(".onsuccessrep tr").length;
		else if(mtype=="seo")
			seo_files = $(".onsuccessrep tr").length;
		else if(mtype=="prod")
			prodfiles = $(".onsuccessrepquote tr").length;
		else
			stafffiles = $(".onsuccessrep tr").length;
	});
	
	$(document).on('keyup','.keyup',function(){
		var writing_cost = $("#writing").val();
		var correction_cost = $("#proofreading").val();
		var othercost = $("#othercost").val();
		if(writing_cost!="")
			writing_cost = parseFloat(writing_cost.replace(",","."));
		else
			writing_cost = 0;
		if(correction_cost!="")
			correction_cost = parseFloat(correction_cost.replace(",","."));
		else
			correction_cost = 0;
		
		if(othercost!="")
			othercost = parseFloat(othercost.replace(",","."));
		else
			othercost = 0;
		
		if($("#merge_writing_cost:checked").length || $("#merge_proofreading_cost:checked").length)
		{
			//correction_cost = 0;
			othercost = 0;
		}
		
		/* if($("#merge_proofreading_cost:checked").length)
		{
			othercost = 0;
		} */
		
		var value = writing_cost+correction_cost+othercost;
		$("#cost_max").val(value.toFixed(2));

	});

	$(document).on('click','.merge',function(){
		var writing_cost = $("#writing").val();
		var correction_cost = $("#proofreading").val();
		var othercost = $("#othercost").val();
		
		if(othercost!="")
			othercost = parseFloat(othercost.replace(",","."));
		else
			othercost = 0;
		
		if(writing_cost!="")
			writing_cost = parseFloat(writing_cost.replace(",","."));
		else
			writing_cost = 0;
		
		if(correction_cost!="")
			correction_cost = parseFloat(correction_cost.replace(",","."));
		else
			correction_cost = 0;
		
		othercost_add = othercost;
		
		/* if($("#merge_writing_cost:checked").length && $(this).attr('id')=="merge_writing_cost")
		{
			writing_cost += othercost;	
		}
		else if($(this).attr('id')=="merge_writing_cost")
		{
			writing_cost -= othercost;
		}
		
		if($("#merge_proofreading_cost:checked").length && $(this).attr('id')=="merge_proofreading_cost")
		{
			correction_cost += othercost;
		}
		else if($(this).attr('id')=="merge_proofreading_cost")
			correction_cost -= othercost;*/
		
		if($("#merge_writing_cost:checked").length || $("#merge_proofreading_cost:checked").length)
			othercost_add = 0; 
		
		if($("#merge_writing_cost:checked").length)
		{
			writing_cost =  parseFloat(writing_cost_glob)+parseFloat(other_cost_glob);	
		}
		else
			writing_cost =  parseFloat(writing_cost_glob);
		
		if($("#merge_proofreading_cost:checked").length)
		{
			correction_cost =  parseFloat(correction_cost_glob)+parseFloat(other_cost_glob);
		}
		else
			correction_cost = parseFloat(correction_cost_glob);
		$("#writing").val(writing_cost.toFixed(2));
		$("#proofreading").val(correction_cost.toFixed(2));
		//alert(othercost_add);
		var value = writing_cost+correction_cost+othercost_add;
		$("#cost_max").val(value.toFixed(2));
	});
	
	function insertPrice()
	{
		var othercost  = $("#othercost").val();
		$("#price").val(nbarticles*parseFloat(othercost.replace(",",".")));
		//$("#before_prod").css('display','none');
		$(".addmargin").css('margin-bottom','10px');
	}

	function removePrice()
	{
		$("#price").val('new');
		//$("#before_prod").css('display','block');
	}
	
	function writingmax(field, rules, i, options){
		var length = $("#merge_writing_cost:checked").length;
		if(length)
		{
			var max_val = parseFloat(writing_cost_glob)+parseFloat(other_cost_glob);
			if((parseFloat(field.val())) > max_val)
			return ' La valeur maximale possible est de '+max_val.toFixed(2)+' ';
		}
		else
		{
			if(parseFloat(field.val()) > parseFloat(writing_cost_glob))
			return ' La valeur maximale possible est de '+writing_cost_glob.toFixed(2)+' ';
		}
	}
	
	function proofreadingmax(field, rules, i, options){
		var length = $("#merge_proofreading_cost:checked").length;
		if(length)
		{
			var max_val = parseFloat(correction_cost_glob)+parseFloat(other_cost_glob);
			if((parseFloat(field.val())) > max_val)
			return ' La valeur maximale possible est de '+max_val.toFixed(2)+' ';
		}
		else
		{
			if(parseFloat(field.val()) > parseFloat(correction_cost_glob))
			return ' La valeur maximale possible est de '+correction_cost_glob.toFixed(2)+' ';
		}
	}
	
</script>
{/literal}

<h2 class="heading"><a href="/quote/create-client?uaction=view&client_id={$client_info.identifier}&submenuId=ML13-SL1" target="_blank">{if $client_info.company_name}{$client_info.company_name}{else}{$client_info.first_name}&nbsp;{$client_info.last_name}{/if}</a> > <a href="/contractmission/contract-edit?submenuId=ML13-SL3&contract_id={$contract_id}&action=view" target="_blank">{$contract_details.contractname} </a> > <a href="/contractmission/missions-list?submenuId=ML13-SL4&contract_id={$contract_id}" target="_blank">All missions</a> > Mission assignment</h2>

<div class="row-fluid">
<div class="span3">

<div class="alert">
  <img class="rd_30" width="50" src="{$fo_path}profiles/bo/{$loginuserId}/logo.jpg" style="margin-bottom: 15px">
	<h4>Welcome !<br> {$count_text}</h4><br>
</div>
</div>


<!--div id="" class="breadCrumb module">

		<div>
		<ul>
			<li class="first"><i class="icon-home"></i></li>
			<li style=""><a href="/contractmission/contract-list?submenuId=ML13-SL3" title="Contract List">Contract List</a></li>
			<li style="">{$contract_details.contractname}</li>
			<li style=""><a href="/contractmission/missions-list?submenuId=ML13-SL4&contract_id={$contract_details.quotecontractid}" title="Missions List">Missions List</a></li>
			
		</ul>
		</div>

</div-->

				
<div class="row-fluid">
	<div class="span8 offset1">
	<form class="form-horizontal"  action="/contractmission/assign-user" method="POST" id="assignmission" enctype="multipart/form-data">
	<input type="hidden" name="missiontype" id="missiontype" value="{$type}">
	<input type="hidden" name="quoteid" value="{$quote_details.identifier}" />
	<input type="hidden" name="seotechprodid" value="{$seotechprodid}">
	<input type="hidden" name="contractid" value="{$contract_id}">
	<input type="hidden" name="currentindex" value="{$current_index}">
	<input type="hidden" name="maxindex" value="{$max_count}">
	{if $type=='tech'}
		{if $contractDetails}
			<input type="hidden" name="contractmissionid" value="{$contractMissionDetails.contractmissionid}" />
			<input type="hidden" name="assigned_user" value="{$contractMissionDetails.assigned_to}" />
		{else}
		<div class="alert {if $techmissiondetails.before_prod neq 'yes'} alert-info {/if}">
			<a class="close" data-dismiss="alert">&times;</a>
			A <strong>Tech Mission {if $techmissiondetails.before_prod eq 'yes'} Blocker {/if}</strong>
			is expected now, please assign it to someone in your team
		</div>
		{/if}
		
		<div class="w-box" style="margin-bottom:15px">
			<div class="w-box-header">
			{if $current_index != 0}
					{*	<a href="/contractmission/assign-mission?contract_id={$contract_id}&type=tech&index={$current_index-1}&submenuId=ML13-SL4" title="Next Quote Mission"><span class="pull-left btn btn1 btn-mini btn-success btnmargin" style="margin-right:25px;">Previous</span></a> *}
			{/if}
			Liste des missions
			{if $current_index lt ($total_tech_mission_count-1)}
					{*	<a href="/contractmission/assign-mission?contract_id={$contract_id}&type=tech&index={$current_index+1}&submenuId=ML13-SL4" title="Next Quote Mission"><span class="pull-right btn btn1 btn-mini btn-warning btnmargin">Next</span></a> *}
			{/if}
			</div>
			<div class="w-box-content  cnt_a">
			{if $mission_details|@count gt 0}
			{foreach from=$mission_details item=mission name="misson"}
				{assign var=gn_index value=$smarty.foreach.misson.index}
				{assign var=ms_index value=$smarty.foreach.misson.index+1}	
				<div class="row-fluid">	
					<div class="mission-details">
						{if $mission.previousMissionDetails|@count eq 0 && $quote.version gt 1 }
							<div class="new-mission-product">Mission {$ms_index} : {$mission.product_type_converted} <label class="label label-warning">Mission ajout&eacute;e</label></div>
						{else}
							<div class="prod-mission-product"> Mission {$ms_index} : {$mission.product_type_converted}</div>
						{/if}
						<table class="table mission-table">
							<tr>
								<th style="width:30%">LANGUE</th>
								<th style="width:30%">PRODUIT</th>
								<th style="width:20%">VOLUME</th>
								<th style="width:20%">NB MOTS</th>
							</tr>
							<tr class="misson-details-text">
								<td>
								{if $mission.product eq 'translation'}															
										{$mission.language_source_name} > 	{$mission.language_dest_name} 
									{else}
										{$mission.language_source_name}
									{/if}
								{if $mission.language_difference eq 'yes'}
									</span>
								{/if}	
								</td>
							<td>
								{if $mission.product_type_name} 
										{$mission.product_type_name}
									{else}
										{$mission.product_name}
								{/if}
							</td>
							<td>
								{$mission.volume}
							</td>										
							<td>
								{$mission.nb_words}
							</td>
							</tr>	
						</table>
						<!--Tempo details-->
						{include file="gebo/quote/tempo-details.phtml"}
						{if $mission.comments}
						<div class="media mission-comment">
							<a class="pull-left imgframe">
								<img width="60px" src="{$fo_path}/profiles/bo/{$mission.created_by}/logo.jpg" class="media-object">
							</a>
							<div class="media-body">
								<h4 class="media-heading">								
									<a>{$mission.quote_user_name}</a> {$mission.comment_time}
								</h4>								
								<span>{$mission.comments|stripslashes|strip_tags|nl2br}</span>
							</div>
						</div>
						{/if}
					</div>
				</div>	
			{/foreach}
			{/if}
			
			
			</div>						
		</div>
		
		<div class="mission-details">
			<div class="mission-tech-product">
					
					{if $techmissiondetails.title=="" && $techmissiondetails.from_contract==1}
					New Tech Mission
					<input type="hidden" name="update_tech" value="1" />
					{else}
					<input type="hidden" name="update_tech" value="0" />
					{/if}
					{$techmissiondetails.title}
					
			</div>
			<table class="table mission-table" width="100%" style="margin-bottom:0">
			<tbody>
			<tr>
				<th width="40%">Mission</th>
				<th width="30%">Delivery</th>
				<th width="30%">Cost (&{$techmissiondetails.currency};)</th>
			</tr>
			<tr class="misson-details-text">
				<td>
				{assign var="cost_tech" value=false}{$cost_tech}
					{* If mission added in prodassignment asking to enter title, cost and other details *}
				{if $techmissiondetails.title=="" && $techmissiondetails.from_contract==1}
				{assign var="cost_tech" value=true}
				<input id="" class="span10 validate[required]" type="text" placeholder="enter a mission" value="" name="tech_title">
				{else}{$techmissiondetails.title}{/if}</td>
				<td>
				{if $techmissiondetails.delivery_time=="" && $techmissiondetails.from_contract==1}
					<div class="span2"></div>
					<div class="span4">
						<input type="text" id="spinner" name="delivery_time" class="span12 validate[required]" value=""/>
					</div>
					<div class="span4">
						<select name="delivery_option" class="span12" id="">					
							<option value="days">Jours</option>
							<option value="hours">Hours</option>									
						</select>
					</div>	
				{else}
				{$techmissiondetails.delivery_time}{$techmissiondetails.delivery_option}
				{/if}
				</td>
				<td>
				{if $techmissiondetails.from_contract==1 && $cost_tech}
				<input id="" class="span4 validate[required]" type="text" onkeyup="" value="{$techmissiondetails.cost|zero_cut:2}" name="tech_cost">
				{else}
				{$techmissiondetails.cost|zero_cut_t:2}
				{/if}
				</td>
			</tr>
			</tbody>
			</table>
			{if $techmissiondetails.title=="" && $techmissiondetails.from_contract==1}
			<div class="row-fluid span12">
				<div class="span2">
					<span class="free-mission">Offrir cette mission</span>
				</div>
				<div class="">
					<div class="row-fluid free-mission">
						<input id="" type="radio" value="yes" name="free_mission">
							Oui 
						<input id="" type="radio" checked="checked" value="no" name="free_mission">
						Non
					</div>
				</div>
			</div>
			{/if}
			<div class="row-fluid" style="margin:0 0 10px 15px;">
			<div class="span12">
				{*
				<div class="uni-checker" id="">
				{if $techmissiondetails.before_prod eq 'yes'}
					<span class="uni-checked"><input type="checkbox" checked="checked" id="" name="before_prod" class="uni_style" style="opacity: 0;" disabled></span>
				{else}
					<span class=""><input type="checkbox" id="" name="before_prod" class="uni_style" style="opacity: 0;" disabled></span>
				{/if}
				</div> Doit &ecirc;tre r&eacute;alis&eacute; avant de lancer la mission
				*}
				
				{if $techmissiondetails.before_prod eq 'yes'}
				<div class="uni-checker" id="">
					<span class="uni-checked"><input type="checkbox" checked="checked" id="" name="before_prod" class="uni_style" style="opacity: 0;" disabled></span>
				</div> Doit &ecirc;tre r&eacute;alis&eacute; avant de lancer la mission
				{/if}
			</div>
			</div>
		</div>
		<div class="well well-large wbg">
		<h2> Brief and Comments from Quote</h2>
			<div class="">
				<div class="row-fluid">
					{foreach from =$comments item=commentst name=comments}
						<div class="media mission-comment">
							<a class="pull-left imgframe">
								<img class="media-object rd_30" width="50" src="{$fo_path}profiles/bo/{$commentst.created_by}/logo.jpg">
							</a>
							<div class="media-body">
								{if $commentst.created_name}
									<a>{$commentst.created_name}</a> {$commentst.created_time}<br>
								{/if}
								{$commentst.comment|stripslashes|strip_tags|nl2br}
							</div>
						</div>
					{/foreach}
					{if $contractDetails}
					<div class="media mission-comment">
						<a class="pull-left imgframe">
							<img class="media-object rd_30" width="50" src="{$fo_path}profiles/bo/{$contractMissionDetails.updated_by}/logo.jpg">
						</a>
						<div class="media-body">
							<a>{$contractMissionDetails.created_name}</a> {$contractMissionDetails.created_time}<br>
							<textarea name="comment" class="span12">{$contractMissionDetails.comment|stripslashes|strip_tags|nl2br}</textarea>
						</div>
					</div>
					{else}
					<div class="media mission-comment">
						<a class="pull-left imgframe">
							<img class="media-object rd_30" width="50" src="{$fo_path}profiles/bo/{$loginuserId}/logo.jpg">
						</a>
						<div class="media-body">
							<a>{$flname}</a><br>
							<textarea name="comment" class="span12"></textarea>
						</div>
					</div>
					{/if}
				</div>
				<br>
				<div>
				{if $quotefiles || $files}
					<p><strong>Related Files</strong></p>
					<div class="pull-right" style="margin-bottom:5px">
						<a href="/quote/download-document?type=cm_tech&index=-1&quote_id={$contract_details.quoteid}&mission_id={$seotechprodid}" class="btn btn-small zipdownload">Download Zip</a>
					</div>
					<table class="onsuccessrepquote table">
					{$quotefiles}
					</table>
					<table class="onsuccessrep table">
					{$files}
					</table>
				{/if}
					<br>
					<input type="file" name="seo_documents[]" accept="doc|xls|zip|docx|xlsx" class="multi" id=""/>
				</div>
			</div>
		</div>
		
		<div class="well wbg well-large">
			<h2>Assignment</h2><p>Which folk is going to be the Owner?</p>

				<div class="row-fluid">
					<div class="span8">
					
					{if $contractDetails}
						{foreach from=$users item=row}
						<div class="assignuser pull-left">
							<img class="media-object rd_30" height="50" width="50" src="{$fo_path}profiles/bo/{$row.identifier}/logo.jpg">
							{if $row.first_name || $row.last_name}<p>{$row.first_name}&nbsp;{* $row.last_name *}</p>{else}<br/>{/if}
							<input type="radio" class="validate[required] {if $techmissiondetails.techfreeMission eq '1'}freelance {/if}" name="assignuser" {if $contractMissionDetails.assigned_to == $row.identifier} checked="checked" {/if} value="{$row.identifier}" />
							{* <label>{if $contractMissionDetails.assigned_to == $row.identifier} Assigned {else} Assign {/if}</label> *}
						</div>
					{/foreach}
					{else}
					{foreach from=$users item=row}
					<div class="assignuser pull-left">
						<img class="media-object rd_30" height="50" width="50" src="{$fo_path}profiles/bo/{$row.identifier}/logo.jpg">
						{if $row.first_name || $row.last_name}<p>{$row.first_name}&nbsp;{* $row.last_name *}</p>{else}<br/>{/if}
						 <input type="radio" class="validate[required] {if $techmissiondetails.techfreeMission eq '1'}freelance {/if}" name="assignuser" value="{$row.identifier}" />
						{* <label>Assign</label>  *}
					</div>
					{/foreach}
					{/if}
					</div>
					
					{math equation='(x*y)' assign=mission_totalcost x=$techmissiondetails.cost y=$techmissiondetails.volume}
					<div class="span4">
						<div class="{if $contractMissionDetails.assigned_to}{else} hidden{/if} freelance-section well">
						


						<legend>External Mission</legend>
						<label class="radio inline">
						<input type="radio" name="freelance_mission" value="yes" {if $contractMissionDetails.external_mission eq 'yes'}checked="checked"{/if}> Oui&nbsp;</input>
					</label>
					<label class="radio inline">
						<input type="radio" name="freelance_mission"  value="no" {if $contractMissionDetails.external_mission neq 'yes'}checked="checked" {/if}> Non</input>
						</label>


			<div class="freelance-yes {if $contractMissionDetails.external_mission neq 'yes'}hidden {/if}">
					
				<label><br>Name</label>
				 
				<input type="text" name="freelacename" class="span8" value="{$contractMissionDetails.freelance_name}" />
				
			</div>
						<div class="freelance-yes {if $contractMissionDetails.external_mission neq 'yes'}hidden {/if}">

							
							<label><br>Cost</label>
							
							<div class="input-append" style="white-space:normal!important;">
							<input type="text" name="freelacecost" class="validate[required] {if $mission_totalcost},maxWriters[{$mission_totalcost}]{/if} span10 " value="{if $contractMissionDetails.freelance_cost}{$contractMissionDetails.freelance_cost}{else}{$mission_totalcost}{/if}" /> <span class="add-on">&{$techmissiondetails.currency}; </span>
						</div>
						</div>
						</div>
					</div>




				</div>
</div>

		
	{/if}
	
	{* Start of Staff Mission *}
	{if $type=='staff'}
	{if $contractDetails}
		<input type="hidden" name="contractmissionid" value="{$contractMissionDetails.contractmissionid}" />
		<input type="hidden" name="assigned_user" value="{$contractMissionDetails.assigned_to}" />
	{else}
	<div class="alert {if $staffMissionDetails.before_prod neq 'yes'} alert-info {/if}">
		<a class="close" data-dismiss="alert">&times;</a>
		A <strong>Staff Mission {if $staffMissionDetails.before_prod eq 'yes'} Blocker {/if}</strong>
		is expected now, please assign it to someone in your team
	</div>
	{/if}

	<div class="w-box" style="margin-bottom:15px">
		<div class="w-box-header">
		{if $current_index != 0}
				{*	<a href="/contractmission/assign-mission?contract_id={$contract_id}&type=tech&index={$current_index-1}&submenuId=ML13-SL4" title="Next Quote Mission"><span class="pull-left btn btn1 btn-mini btn-success btnmargin" style="margin-right:25px;">Previous</span></a> *}
		{/if}
		Liste des missions
		{if $current_index lt ($total_tech_mission_count-1)}
				{*	<a href="/contractmission/assign-mission?contract_id={$contract_id}&type=tech&index={$current_index+1}&submenuId=ML13-SL4" title="Next Quote Mission"><span class="pull-right btn btn1 btn-mini btn-warning btnmargin">Next</span></a> *}
		{/if}
		</div>
		<div class="w-box-content  cnt_a">
		{if $mission_details|@count gt 0}
		{foreach from=$mission_details item=mission name="misson"}
			{assign var=gn_index value=$smarty.foreach.misson.index}
			{assign var=ms_index value=$smarty.foreach.misson.index+1}	
			<div class="row-fluid">	
				<div class="mission-details">
					{if $mission.previousMissionDetails|@count eq 0 && $quote.version gt 1 }
						<div class="new-mission-product">Mission {$ms_index} : {$mission.product_type_converted} <label class="label label-warning">Mission ajout&eacute;e</label></div>
					{else}
						<div class="prod-mission-product"> Mission {$ms_index} : {$mission.product_type_converted}</div>
					{/if}
					<table class="table mission-table">
						<tr>
							<th style="width:30%">LANGUE</th>
							<th style="width:30%">PRODUIT</th>
							<th style="width:20%">VOLUME</th>
							<th style="width:20%">NB MOTS</th>
						</tr>
						<tr class="misson-details-text">
							<td>
							{if $mission.product eq 'translation'}															
									{$mission.language_source_name} > 	{$mission.language_dest_name} 
								{else}
									{$mission.language_source_name}
								{/if}
							{if $mission.language_difference eq 'yes'}
								</span>
							{/if}	
							</td>
						<td>
							{if $mission.product_type_name} 
									{$mission.product_type_name}
								{else}
									{$mission.product_name}
							{/if}
						</td>
						<td>
							{$mission.volume}
						</td>										
						<td>
							{$mission.nb_words}
						</td>
						</tr>	
					</table>
					{if $mission.comments}
					<div class="media mission-comment">
						<a class="pull-left imgframe">
							<img width="60px" src="{$fo_path}/profiles/bo/{$mission.created_by}/logo.jpg" class="media-object">
						</a>
						<div class="media-body">
							<h4 class="media-heading">								
								<a>{$mission.quote_user_name}</a> {$mission.comment_time}
							</h4>								
							<span>{$mission.comments|stripslashes|strip_tags|nl2br}</span>
						</div>
					</div>
					{/if}
				</div>
			</div>	
		{/foreach}
		{/if}
		
		
		</div>						
	</div>

	<div class="mission-details">
		<div class="mission-tech-product">
				
				{if $staffMissionDetails.title==""}
				New Staff Mission
				<input type="hidden" name="update_staff" value="1" />
				{else}
				<input type="hidden" name="update_staff" value="0" />
				{/if}
				{$staffMissionDetails.title}
				
		</div>
		<table class="table mission-table" width="100%" style="margin-bottom:0">
		<tbody>
		<tr>
			<th width="40%">Mission</th>
			<th width="30%">Delivery</th>
			<th width="30%">Cost (&{$staffMissionDetails.currency};)</th>
		</tr>
		<tr class="misson-details-text">
			<td>
			{assign var="cost_tech" value=false}{$cost_tech}
			{if $staffMissionDetails.title==""}
			{assign var="cost_tech" value=true}
			<input id="" class="span10 validate[required]" type="text" placeholder="enter a mission" value="" name="staff_title">
			{else}{$staffMissionDetails.title}{/if}</td>
			<td>
			{if $cost_tech}
				<div class="span2"></div>
				<div class="span4">
					<input type="text" id="spinner" name="delivery_time" class="span12 validate[required]" value="{$staffMissionDetails.delivery_time}"/>
				</div>
				<div class="span4">
					<select name="delivery_option" class="span12" id="">					
						<option value="days" {if $staffMissionDetails.delivery_option eq 'days'} selected{/if}>Jours</option>
						<option value="hours" {if $staffMissionDetails.delivery_option eq 'hours'} selected{/if}>Hours</option>									
					</select>
				</div>	
			{else}
			{$staffMissionDetails.delivery_time}{$staffMissionDetails.delivery_option}
			{/if}
			</td>
			<td>
			{if $cost_tech}
			<input id="" class="span4 validate[required]" type="text" onkeyup="" value="{$staffMissionDetails.cost|zero_cut:2}" name="staff_cost">
			{else}
			{$staffMissionDetails.cost|zero_cut_t:2}
			{/if}
			</td>
		</tr>
		</tbody>
		</table>
		<div class="row-fluid" style="margin:0 0 10px 15px;">
		<div class="span12">
			{*
			<div class="uni-checker" id="">
			{if $techmissiondetails.before_prod eq 'yes'}
				<span class="uni-checked"><input type="checkbox" checked="checked" id="" name="before_prod" class="uni_style" style="opacity: 0;" disabled></span>
			{else}
				<span class=""><input type="checkbox" id="" name="before_prod" class="uni_style" style="opacity: 0;" disabled></span>
			{/if}
			</div> Doit &ecirc;tre r&eacute;alis&eacute; avant de lancer la mission
			*}
			
			{if $staffMissionDetails.before_prod eq 'yes'}
			<div class="uni-checker" id="">
				<span class="uni-checked"><input type="checkbox" checked="checked" id="" name="before_prod" class="uni_style" style="opacity: 0;" disabled></span>
			</div> Doit &ecirc;tre r&eacute;alis&eacute; avant de lancer la mission
			{/if}
			
		</div>
		</div>
	</div>
	<div class="well wbg well-large">
	<h2> Brief and Comments from Quote</h2>
		<div class="">
			<div class="row-fluid">
				{*
				{if $contract_details.comment}
				<div class="media mission-comment">
					<a class="pull-left imgframe">
						<img class="media-object rd_30" width="50" src="{$fo_path}profiles/bo/{$contract_details.sales_creator_id}/logo.jpg">
					</a>
					<div class="media-body">
						{if $contract_details.created_name}
							<a>{$contract_details.created_name}</a> {$contract_details.created_time}<br>
						{/if}
						{$contract_details.comment}
					</div>
				</div>
				{/if}
				{if $staffMissionDetails.comments}
				<div class="media mission-comment">
					<a class="pull-left imgframe">
						<img class="media-object rd_30" width="50" src="{$fo_path}profiles/bo/{$staffMissionDetails.created_by}/logo.jpg">
					</a>
					<div class="media-body">
						{if $staffMissionDetails.created_name}
							<a>{$staffMissionDetails.created_name}</a> {$staffMissionDetails.created_time}<br>
						{/if}
						{$staffMissionDetails.comments|stripslashes|strip_tags|nl2br}
					</div>
				</div>
				{/if}
				{if $quote_details.sales_comment}
				<div class="media mission-comment">
					<a class="pull-left imgframe">
						<img class="media-object rd_30" width="50" src="{$fo_path}profiles/bo/{$quote_details.created_by}/logo.jpg">
					</a>
					<div class="media-body">
						{if $quote_details.created_name}
							<a>{$quote_details.created_name}</a> {$quote_details.created_time}<br>
						{/if}
						{$quote_details.sales_comment}
					</div>
				</div>
				{/if}
				*}
				{foreach from =$comments item=commentst name=comments}
					<div class="media mission-comment">
						<a class="pull-left imgframe">
							<img class="media-object rd_30" width="50" src="{$fo_path}profiles/bo/{$commentst.created_by}/logo.jpg">
						</a>
						<div class="media-body">
							{if $commentst.created_name}
								<a>{$commentst.created_name}</a> {$commentst.created_time}<br>
							{/if}
							{$commentst.comment|stripslashes|strip_tags|nl2br}
						</div>
					</div>
				{/foreach}
				{if $contractDetails}
				<div class="media mission-comment">
					<a class="pull-left imgframe">
						<img class="media-object rd_30" width="50" src="{$fo_path}profiles/bo/{$contractMissionDetails.updated_by}/logo.jpg">
					</a>
					<div class="media-body">
						<a>{$contractMissionDetails.created_name}</a> {$contractMissionDetails.created_time}<br>
						<textarea name="comment" class="span12">{$contractMissionDetails.comment|stripslashes|strip_tags|nl2br}</textarea>
					</div>
				</div>
				{else}
				<div class="media mission-comment">
					<a class="pull-left imgframe">
						<img class="media-object rd_30" width="50" src="{$fo_path}profiles/bo/{$loginuserId}/logo.jpg">
					</a>
					<div class="media-body">
						<a>{$flname}</a><br>
						<textarea name="comment" class="span12"></textarea>
					</div>
				</div>
				{/if}
			</div>
			<br>
			<div>
			{if $quotefiles || $files}
				<p><strong>Related Files</strong></p>
				<div class="pull-right" style="margin-bottom:5px">
					<a href="/quote/download-document?type=cm_staff&index=-1&quote_id={$contract_details.quoteid}&mission_id={$seotechprodid}" class="btn btn-small zipdownload">Download Zip</a>
				</div>
				<table class="onsuccessrepquote table">
				{$quotefiles}
				</table>
				<table class="onsuccessrep table">
				{$files}
				</table>
			{/if}
				<br>
				<input type="file" name="seo_documents[]" accept="doc|xls|zip|docx|xlsx" class="multi" id=""/>
			</div>
		</div>
	</div>

	<div class="well wbg well-large">
		<h3>Assignment</h3><p>Which folk is going to be the Owner?</p>

			<div class="row-fluid">
				
				{if $contractDetails}
					{foreach from=$users item=row}
					<div class="assignuser pull-left">
						<img class="media-object rd_30" height="50" width="50" src="{$fo_path}profiles/bo/{$row.identifier}/logo.jpg">
						{if $row.first_name || $row.last_name}<p>{$row.first_name}&nbsp;{* $row.last_name *}</p>{else}<br/>{/if}
						<input type="radio" class="validate[required]" name="assignuser" {if $contractMissionDetails.assigned_to == $row.identifier} checked="checked" {/if} value="{$row.identifier}" />
						{* <label>{if $contractMissionDetails.assigned_to == $row.identifier} Assigned {else} Assign {/if}</label> *}
					</div>
				{/foreach}
				{else}
				{foreach from=$users item=row}
				<div class="assignuser pull-left">
					<img class="media-object rd_30" height="50px" width="50" src="{$fo_path}profiles/bo/{$row.identifier}/logo.jpg">
					{if $row.first_name || $row.last_name}<p>{$row.first_name}&nbsp;{* $row.last_name *}</p>{else}<br/>{/if}
					 <input type="radio" class="validate[required]" name="assignuser" value="{$row.identifier}" />
					{* <label>Assign</label>  *}
				</div>
				{/foreach}
				{/if}
			</div>
	</div>

			
	{/if}
	{* End of Staff Mission *}
	
	{* Start of SEO Mission *}
	{if $type=='seo'}
		{if $contractDetails}
			<input type="hidden" name="contractmissionid" value="{$contractMissionDetails.contractmissionid}" />
			<input type="hidden" name="assigned_user" value="{$contractMissionDetails.assigned_to}" />
		{else}
		<div class="alert {if $seoMissionDetails.before_prod neq 'yes'} alert-info {/if}">
			<a class="close" data-dismiss="alert">&times;</a>
			A <strong>SEO Mission {if $seoMissionDetails.before_prod eq 'yes'} Blocker {/if}</strong>
			is expected now, please assign it to someone in the team
		</div>
		{/if}
		
		<div class="w-box" style="margin-bottom:15px">
			<div class="w-box-header">
			{if $current_index != 0}
				{* <a href="/contractmission/assign-mission?contract_id={$contract_id}&type=seo&index={$current_index-1}&submenuId=ML13-SL4" title="Previous SEO Mission"><span class="pull-left btn btn1 btn-mini btn-success btnmargin" style="margin-right:25px">Previous</span></a> *}
			{/if}
			Liste des missions
			{if $current_index lt ($total_seo_mission_count-1)}
				{* <a href="/contractmission/assign-mission?contract_id={$contract_id}&type=seo&index={$current_index+1}&submenuId=ML13-SL4" title="Next SEO Mission"><span class="pull-right btn btn1 btn-mini btn-warning btnmargin">Next</span></a> *}
			{/if}
			</div>
			<div class="w-box-content  cnt_a">
			{if $mission_details|@count gt 0}
			{foreach from=$mission_details item=mission name="misson"}
				{assign var=gn_index value=$smarty.foreach.misson.index}
				{assign var=ms_index value=$smarty.foreach.misson.index+1}	
				<div class="row-fluid">	
					<div class="mission-details">
						{if $mission.previousMissionDetails|@count eq 0 && $quote.version gt 1 }
							<div class="new-mission-product">Mission {$ms_index} : {$mission.product_type_converted} <label class="label label-warning">Mission ajout&eacute;e</label></div>
						{else}
							<div class="prod-mission-product"> Mission {$ms_index} : {$mission.product_type_converted}</div>
						{/if}
						<table class="table mission-table">
							<tr>
								<th style="width:30%">LANGUE</th>
								<th style="width:30%">PRODUIT</th>
								<th style="width:20%">VOLUME</th>
								<th style="width:20%">NB MOTS</th>
							</tr>
							<tr class="misson-details-text">
								<td>
								{if $mission.product eq 'translation'}															
										{$mission.language_source_name} > 	{$mission.language_dest_name} 
									{else}
										{$mission.language_source_name}
									{/if}
								{if $mission.language_difference eq 'yes'}
									</span>
								{/if}	
								</td>
							<td>
								{if $mission.product_type_name} 
										{$mission.product_type_name}
									{else}
										{$mission.product_name}
								{/if}
							</td>
							<td>
								{$mission.volume}
							</td>										
							<td>
								{$mission.nb_words}
							</td>
							</tr>	
						</table>
						<!--Tempo details-->
						{include file="gebo/quote/tempo-details.phtml"}
						{if $mission.comments}
						<div class="media mission-comment">
							<a class="pull-left imgframe">
								<img width="50" src="{$fo_path}/profiles/bo/{$mission.created_by}/logo.jpg" class="media-object rd_30">
							</a>
							<div class="media-body">
								<h4 class="media-heading">								
									<a>{$mission.quote_user_name}</a> {$mission.comment_time}
								</h4>								
								<span>{$mission.comments|stripslashes|strip_tags|nl2br}</span>
							</div>
						</div>
						{/if}
					</div>
				</div>	
			{/foreach}
			{/if}
			
			
			</div>						
		</div>
		
		
		<div class="mission-details">
			<div class="mission-seo-product">
					SEO proposal{$current_index+1}
			</div>
			<table class="table mission-table" width="100%" style="margin-bottom:0">
			<tbody>
			<tr>
				<th style="width:25%">Type</th>
				<th style="width:25%">Langue</th>
				<th {if $seoMissionDetails.product eq 'seo_audit' || $seoMissionDetails.product eq 'smo_audit' || $seoMissionDetails.product eq 'content_strategy' } style="width:30%" {else} style="display:none;width:30%"{/if}>Delivery timing</th>														
				<th {if $seoMissionDetails.product eq 'seo_audit' || $seoMissionDetails.product eq 'smo_audit' || $seoMissionDetails.product eq 'content_strategy' } style="width:20%" {else} style="display:none;width:20%"{/if}>Co&ucirc;t (&{$quote_details.sales_suggested_currency };)</th>
				<th {if $seoMissionDetails.product eq 'seo_audit' || $seoMissionDetails.product eq 'smo_audit' || $seoMissionDetails.product eq 'content_strategy' } style="display:none;width:35%"{else} style="width:35%" {/if}>Product type</th>
				<th {if $seoMissionDetails.product eq 'seo_audit' || $seoMissionDetails.product eq 'smo_audit'  || $seoMissionDetails.product eq 'content_strategy'} style="display:none;width:15%"{else} style="width:15%" {/if}>Nb of words</th>
			</tr>
			<tr class="misson-details-text">
				<td>{$seoMissionDetails.productc}</td>
				<td>{if $seoMissionDetails.product eq 'translation'}{$seoMissionDetails.language_source_converted}&nbsp;>&nbsp;{$seoMissionDetails.language_dest_converted}{else}{$seoMissionDetails.language_source_converted}{/if}</td>
				<td>{if $seoMissionDetails.product eq 'seo_audit' || $seoMissionDetails.product eq 'smo_audit' || $seoMissionDetails.product eq 'content_strategy' }{$seoMissionDetails.mission_length}{$seoMissionDetails.mission_length_option}{else}{$seoMissionDetails.typec}{/if}</td>
				<td>{if $seoMissionDetails.product eq 'seo_audit' || $seoMissionDetails.product eq 'smo_audit' || $seoMissionDetails.product eq 'content_strategy' }{$seoMissionDetails.cost|zero_cut_t:2}{else}{$seoMissionDetails.nb_words}{/if}</td>
			</tr>
			</tbody>
			</table>
			<div class="row-fluid" style="margin:0 0 10px 15px;">
			<div class="span12">
			{if $seoMissionDetails.before_prod eq 'yes'}
				<div class="uni-checker" id="">
				<span class="uni-checked"><input type="checkbox" checked="checked" id="" name="before_prod" class="uni_style" style="opacity: 0;" disabled></span>
				</div> Doit &ecirc;tre r&eacute;alis&eacute; avant de lancer la mission
			{/if}
					
			</div>
			</div>
		</div>
		
		<div class="well wbg well-large">
		<h2> Brief and Comments from Quote</h2>
			<div class="">
				<div class="row-fluid">
					
					{foreach from =$comments item=commentst name=comments}
						<div class="media mission-comment">
							<a class="pull-left imgframe">
								<img class="media-object rd_30" width="50"  src="{$fo_path}profiles/bo/{$commentst.created_by}/logo.jpg">
							</a>
							<div class="media-body">
								{if $commentst.created_name}
									<a>{$commentst.created_name}</a> {$commentst.created_time}<br>
								{/if}
								{$commentst.comment|stripslashes|strip_tags|nl2br}
							</div>
						</div>
					{/foreach}
					{if $contractDetails}
					<div class="media mission-comment">
						<a class="pull-left imgframe">
							<img class="media-object rd_30" width="50"  src="{$fo_path}profiles/bo/{$contractMissionDetails.updated_by}/logo.jpg">
						</a>
						<div class="media-body">
							<a>{$contractMissionDetails.created_name}</a> {$contractMissionDetails.created_time}<br>
							<textarea name="comment" class="span12">{$contractMissionDetails.comment|stripslashes|strip_tags|nl2br}</textarea>
						</div>
					</div>
					{else}
					<div class="media mission-comment">
						<a class="pull-left imgframe">
							<img class="media-object rd_30" width="50"  src="{$fo_path}profiles/bo/{$loginuserId}/logo.jpg">
						</a>
						<div class="media-body">
							<a>{$flname}</a><br>
							<textarea name="comment" class="span12"></textarea>
						</div>
					</div>
					{/if}
				</div>
				<br>
				
				<div>
				{if $quotefiles || $files}
					<h4>Related Files</h4>
					<div class="pull-right" style="margin-bottom:5px">
						<a href="/quote/download-document?type=cm_seo&index=-1&quote_id={$contract_details.quoteid}&mission_id={$seotechprodid}" class="btn btn-small zipdownload">Download Zip</a>
					</div>
					<table class="onsuccessrepquote table">
					{$quotefiles}
					</table>
					<table width="100%" class="onsuccessrep table">
					{$files}
					</table>
				{/if}
					<br>
					<input type="file" name="seo_documents[]" accept="doc|xls|zip|docx|xlsx" class="multi" id=""/>
				</div>
				
			</div>
		</div>
		<div class="w-box">
			<div class="well wbg well-large">
			<h2>Assignment</h2><p>Which folk is going to be the Owner?</p>

				<div class="row-fluid">
					<div class="span8">

					{if $contractDetails}
						{foreach from=$users item=row}
						<div class="assignuser pull-left">
							<img class="media-object rd_30" height="50" width="50" src="{$fo_path}profiles/bo/{$row.identifier}/logo.jpg">
							{if $row.first_name || $row.last_name}<p>{$row.first_name}&nbsp;{* $row.last_name *}</p>{else}<br/>{/if}
							<input type="radio" class="validate[required] freelance" name="assignuser" {if $contractMissionDetails.assigned_to == $row.identifier} checked="checked" {/if} value="{$row.identifier}" />
							{* <label>{if $contractMissionDetails.assigned_to == $row.identifier} Assigned {else} Assign {/if}</label> *}
						</div>
					{/foreach}
					{else}
					{foreach from=$users item=row}
					<div class="assignuser pull-left">
						<img class="media-object rd_30" height="50" width="50" src="{$fo_path}profiles/bo/{$row.identifier}/logo.jpg">
						{if $row.first_name || $row.last_name}<p>{$row.first_name}&nbsp;{* $row.last_name *}</p>{else}<br/>{/if}
						<input type="radio" class="freelance validate[required]" name="assignuser" value="{$row.identifier}" />
						{* <label>Assign</label> *}
					</div>
					{/foreach}
					{/if}
					</div>
					<div class="span4">
						<div class="{if $contractMissionDetails.assigned_to}{else} hidden{/if} freelance-section well">
						<legend>External Mission</legend>
						<label class="radio inline">
							<input type="radio" name="freelance_mission" value="yes" {if $contractMissionDetails.external_mission eq 'yes'}checked="checked"{/if}> Oui&nbsp;</input>
						</label>
						<label class="radio inline">
							<input type="radio" name="freelance_mission"  value="no" {if $contractMissionDetails.external_mission neq 'yes'}checked="checked" {/if}> Non</input>
						</label>

							<div class="freelance-yes {if $contractMissionDetails.external_mission neq 'yes'}hidden {/if}">
								
								<label><br>Name</label>
							 
								<input type="text" name="freelacename" class="span8" value="{$contractMissionDetails.freelance_name}" />
							
							</div>
							<div class="freelance-yes {if $contractMissionDetails.external_mission neq 'yes'}hidden {/if}">

							
							<label><br>Cost</label>
							
							<div class="input-append" style="white-space:normal!important;">
							<input type="text" name="freelacecost" class="validate[required] {if $seoMissionDetails.internal_cost},maxWriters[{$seoMissionDetails.internal_cost}]{/if} span10 " value="{if $contractMissionDetails.freelance_cost && $contractMissionDetails.freelance_cost neq '0.00'}{$contractMissionDetails.freelance_cost}{else}{$seoMissionDetails.internal_cost}{/if}" /> <span class="add-on">&{$seoMissionDetails.sales_suggested_currency};</span>
							</div>
						</div>

					</div>
				</div>	
						
				</div>
			</div>
		</div>
	{/if}
	{* End of SEO mission *}
	
	{* Start of Prod mission *}
	{if $type=='prod'}
		{if $contractDetails}
		
			<input type="hidden" name="contractmissionid" value="{$contractMissionDetails.contractmissionid}" />
			<input type="hidden" name="assigned_user" value="{$contractMissionDetails.assigned_to}" />
		{else}
		<div class="alert alert-info">
			<a class="close" data-dismiss="alert">&times;</a>
			A <strong>Prod Mission</strong> is expected now, please assign it to someone in your team
		</div>
		{/if}	
		
		<div class="mission-details">
				
				<div class="prod-mission-product">
				{if $current_index != 0}
				{*	<a href="/contractmission/assign-mission?contract_id={$contract_id}&type=prod&index={$current_index-1}&submenuId=ML13-SL4" title="Previous Prod Mission"><span class="pull-left btn btn1 btn-mini btn-success" style="margin-right:25px">Previous</span></a> *}
				{/if}
				{$prod_mission_details.mission_title}
				{if $current_index lt ($total_prod_mission_count-1)}
				{*	<a href="/contractmission/assign-mission?contract_id={$contract_id}&type=prod&index={$current_index+1}&submenuId=ML13-SL4" title="Next Prod Mission"><span class="pull-right btn btn1 btn-mini btn-warning">Next</span></a> *}
				{/if}
				</div>
				<table class="table mission-table">
					<tr>
						<th style="width:30%">LANGUE</th>
						<th style="width:30%">PRODUIT</th>
						<th style="width:20%">VOLUME</th>
						<th style="width:20%">NB MOTS</th>
					</tr>
					<tr class="misson-details-text">
						<td>{$prod_mission_details.language_source_name} {if $prod_mission_details.product eq 'translation'}>{$prod_mission_details.language_dest_name}{/if}</td>
						<td>{$prod_mission_details.product_type_name}</td>
						<td>{$prod_mission_details.volume}</td>
						<td>{$prod_mission_details.nb_words}</td>
					</tr>	
				</table>
				<div class="row-fluid" id="prod_missions_{$prod_mission_details.identifier}">
					{* Tempo details start *}
						{if $prod_mission_details.oneshot eq 'yes' || $prod_mission_details.oneshot eq 'no'}
					<div class="row-fluid" >
					{assign var="_tempo_value" value=$prod_mission_details.tempo}
					{assign var="_delivery_volume_option" value=$prod_mission_details.delivery_volume_option}
					{assign var="_tempo_length_option" value=$prod_mission_details.tempo_length_option}
					<div class="mission-details" style="margin:5px">
						<div class="mission-prod-product">
							<span>Tempo Details</span>
						</div>
						<div class="row-fluid">								
							<label class="span3 moveright">Staffing set up</label>
							<div class="span3">
								<div class="span4">
									<h4>
									{if $prod_mission_details.staff_time}
										{$prod_mission_details.staff_time}
										{if $prod_mission_details.staff_time_option eq 'days'} Jours {else} Heures {/if}
									{else}
										/
									{/if} 
									</h4>
								</div>
							</div>	
						</div>	
						{if $prod_mission_details.oneshot}
							<div class="row-fluid">								
								<label class="span3 moveright">One shot</label>
								<div class="span3">
									<h4>
									{if $prod_mission_details.oneshot eq 'yes'}
										OUI
									{else if $prod_mission_details.oneshot eq 'no'}
										NON
									{/if}
									</h4>
								</div>
							</div>
						{/if}
						<div class="row-fluid">								
							<label class="span3 moveright">Dur&eacute;e la mission</label>
							{if $prod_mission_details.duration_dont_know eq 'yes' && $prod_mission_details.mission_length eq '0'} 															
								<div class="span8">
									<h4>* Duration not specified by sales</h4>												
								</div>
							{else}
								<div class="span3">
									<div class="span6">
										<h4>{$prod_mission_details.mission_length} {if $prod_mission_details.mission_length_option eq 'days'} Jours {else} Heures {/if}</h4>
									</div>													
								</div>
								{if $prod_mission_details.duration_dont_know eq 'yes'} 															
									<div class="span4" style="margin-left: 0px">
										* Duration not specified by sales																
									</div>
								{/if}
							{/if}
						</div>
						{if $prod_mission_details.oneshot eq 'no'}
							<div class="row-fluid">								
								<label class="span3 moveright">Volume</label>														
								<div class="span9" id="tempo_details_{$prod_mission_details.identifier}" {if $prod_mission_details.oneshot eq 'yes'} style="display:none" {/if}>
									<div class="span4">		
										<h4>
											{$prod_mission_details.volume_max} {$tempo_array.$_tempo_value} {$volume_option_array.$_delivery_volume_option} {$prod_mission_details.tempo_length} {$tempo_duration_array.$_tempo_length_option}
										</h4>	
									</div>														
								</div>
							</div>
						{/if}	
					</div>
					</div>
					{/if}
					{* Tempo details end *}
				
					{if $prod_mission_details.prod_missions|@count gt 0}
						{foreach from=$prod_mission_details.prod_missions item=prod_misson name="prod_mission"}
							{assign var=pr_index value=$smarty.foreach.prod_mission.index+1}
							<div class="row-fluid" id="prod_missions_{$prod_misson.identifier}_{$pr_index}">
								<div class="mission-details" style="margin:5px">
									<div class="mission-prod-product"><span id="box_title_{$pr_index}">
									{if $prod_misson.product eq 'redaction'}
										R&eacute;daction
									{elseif $prod_misson.product eq 'translation'}
										Traduction 
									{elseif $prod_misson.product eq 'proofreading'}
										Correction 	
									{elseif $prod_misson.product eq 'autre'}
										Autre 		
									{/if}												
									</span>										
									</div>
									<table class="table mission-table">
										<tr>
											<th style="width:15%;">Nb r&eacute;dacteurs</th>											
											<th>Co&ucirc;t/produit</th>
										</tr>				
										<tr class="misson-details-text">
											<td>{$prod_misson.staff}</td>											
											<td>{$prod_misson.cost|zero_cut_t:2} &{$prod_misson.currency};</td>											
											
										</tr>										
									</table>
									{if $prod_misson.comments}
									<div class="media mission-comment">
										<a class="pull-left imgframe">
											<img height="50px" width="50" src="{$fo_path}/profiles/bo/{$prod_misson.created_by}/logo.jpg" class="media-object rd_30">
										</a>
										<div class="media-body">
											<h4 class="media-heading">								
												<a>{$prod_misson.prod_user_name}</a> {$prod_misson.comment_time}
											</h4>
											<span>{$prod_misson.comments|stripslashes|strip_tags|nl2br}</span>
										</div>												
									</div>
									{/if}
								</div>	
							</div>	
						{/foreach}							
					{/if}	
				</div>		
		</div>
		
		<div class="well wbg well-large">
		<h3> Brief and Comments from Quote</h3>
			
				<div class="row-fluid">
					
					{foreach from =$comments item=commentst name=comments}
						<div class="media mission-comment">
							<a class="pull-left imgframe">
								<img class="media-object rd_30" width="50" src="{$fo_path}profiles/bo/{$commentst.created_by}/logo.jpg">
							</a>
							<div class="media-body">
								{if $commentst.created_name}
									<a>{$commentst.created_name}</a> {$commentst.created_time}<br>
								{/if}
								{$commentst.comment|stripslashes|strip_tags|nl2br}
							</div>
						</div>
					{/foreach}
				
					{if $contractDetails}
					<div class="media mission-comment">
						<a class="pull-left imgframe">
							<img class="media-object rd_30" width="50" src="{$fo_path}profiles/bo/{$contractMissionDetails.updated_by}/logo.jpg">
						</a>
						<div class="media-body">
							<a>{$contractMissionDetails.created_name}</a> {$contractMissionDetails.created_time}<br>
							<textarea name="comment" class="span12">{$contractMissionDetails.comment|stripslashes|strip_tags|nl2br}</textarea>
						</div>
					</div>
					{else}
					<div class="media mission-comment">
						<a class="pull-left imgframe">
							<img class="media-object rd_30" width="50" src="{$fo_path}profiles/bo/{$loginuserId}/logo.jpg">
						</a>
						<div class="media-body">
							<a>{$flname}</a><br>
							<textarea name="comment" class="span12"></textarea>
						</div>
					</div>
					{/if}
				</div>
				{if $quotefiles}
				<div class="row-fluid">
					<h4>Related Files</h4>
					<div class="pull-right" style="margin-bottom:5px">
						<a href="/quote/download-document?type=cm_prod&index=-1&quote_id={$contract_details.quoteid}&mission_id={$contractMissionDetails.contractmissionid}" class="btn btn-small zipdownload">Download Zip</a>
					</div>
					<table class="onsuccessrepquote table">
					{$quotefiles}
					</table>
					<br>
					<input type="file" name="seo_documents[]" accept="doc|xls|zip|docx|xlsx" class="multi" id=""/>
				</div>
				{/if}
		</div>
		<br>
		<div class="well wbg well-large">
		<h3>Bidding Rules</h3><hr>

				<div class="row-fluid">
				<div class="span12">
					
					<div class="control-group">
						<label class="control-label">Writing Cost (&{$quote_details.sales_suggested_currency};)</label>
						<div class="controls">
							<div class="span4">
								<input type="text" class="span12 validate[required,custom[number],funcCall[writingmax]] keyup" id="writing" value="{$writing}" name="writing">
							</div>
						</div>
					</div>
					
					<div class="control-group">
						<label class="control-label">Correction Cost (&{$quote_details.sales_suggested_currency};)</label>
						<div class="controls">
							<div class="span4">
								<input type="text" class="span12 validate[required,custom[number],funcCall[proofreadingmax]] keyup" id="proofreading" value="{$proofreading}" name="proofreading">
							</div>
						</div>
					</div>
					
					<div class="control-group">
						<label class="control-label">Other Cost (&{$quote_details.sales_suggested_currency};)</label>
						<div class="controls">
							<div class="span4">
								<input type="text" class="span12 validate[required,custom[number],max[{$autre}]] keyup" id="othercost" value="{$autre}" name="autre">
							</div>
							<div class="span5">
							<label class="radio">
								<input type="radio" name="merge" id="merge_writing_cost" {if $merge=='writing_cost'} checked="checked" 
								{/if} value="writing_cost" class="merge" /> 
								Merge with Writing Cost
							</label>
							<label class="radio">
								<input type="radio" name="merge" id="merge_proofreading_cost" {if $merge=='proofreading_cost'} checked="checked" 
								{/if} value="proofreading_cost"  class="merge" /> 
								Merge with Proofreading Cost
							</label>
							</div>
						</div>
					</div>
					{* {if not $onlysales}
					<div class="control-group">
						<label class="control-label"></label>
						<div class="controls">
							<div class="span8">
								<a name="save" id="newrequest" onclick="return insertPrice()" class="">Voulez-vous lancer une mission tech li&eacute; &agrave; ce co&ucirc;t?</a>
							</div>
						</div>
					</div>
					{/if} *}
					<div class="control-group">
						<label class="control-label"></label>
						<div class="controls">
							<div class="span8">
								<a name="save" id="newrequest" onclick="return insertPrice()" class=""><i class="icon-hand-right"></i> Cr&eacute;er une mission tech li&eacute; &agrave; ce co&ucirc;t?</a>
							</div>
							<div class="span8" style="margin-left:0">
								<a href="" data-toggle="modal" role="button" data-target="#new_staffing" id="" class=""><i class="icon-hand-right"></i>Cr&eacute;er une mission de staffing</a>
							</div>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label">Cost Max (&{$quote_details.sales_suggested_currency};)</label>
						<div class="controls">
						<!--	<div style="margin-right:10px" class="span4">
									Min (&{$quote_details.sales_suggested_currency};) <br>
								<input type="text" class="span12 validate[required]" value="{$min_cost}" name="min_cost">
							</div> -->
							<div class="span4">
								<input type="text" class="span12 validate[required,custom[number],max[{$writing+$proofreading+$autre}]]" id="cost_max" value="{$max_cost}" name="max_cost">
							</div>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label">Correction</label>
						<div class="controls">
							<div class="span6">
								{html_options options=$correction name="correction" selected=$pcorrection class="validate[required]" id="correction" } 
							</div>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label">#Files / Pack</label>
						<div class="controls">
							<input type="text" name="files_pack" value="{$files_pack}" class="span3 inline validate[required]" /> 
						</div>
					</div>
					
					{if $ebookerid == $client_info.identifier}
					<div class="control-group">
						<label class="control-label" style="padding:0">Stencils</label>
						<div class="controls">
								<input type="radio" name="stencils" class="alertemail" {if $stencils eq 'yes'} checked {/if} value="yes">Oui&nbsp;
								<input type="radio" name="stencils" class="alertemail" {if $stencils eq 'no'} checked {/if} value="no">Non
						</div>
					</div>
                    {else}
                    <div class="control-group">
                        <label class="control-label" style="padding:0">BNP Mission</label>
                        <div class="controls">
                            <input type="radio" name="bnp_mission" class="alertemail"  value="yes">Oui&nbsp;
                            <input type="radio" name="bnp_mission" class="alertemail"  value="no" checked >Non
                        </div>
                    </div>
					{/if}
					
					<input type="hidden" value="{$prod_mission_details.oneshot}" name="tempooption" id="tempooption" />
					{if $prod_mission_details.oneshot eq 'yes' || $prod_mission_details.oneshot eq 'no'}
					<div class="control-group">
					
						<label class="control-label"><h4>Tempo</h4></label>
					</div>
					{/if}
					{if $prod_mission_details.oneshot eq 'yes'}
					<div class="control-group">
						<label class="control-label">One shot mission</label>
						<div class="controls" style="margin-top:7px">
						<strong>{$prod_mission_details.mission_length} {$prod_mission_details.mission_length_option_convert}</strong>
						</div>
					</div>
					<div class="control-group">
						<label class="control-label"></label>
						<div class="controls">
						<div class="span12">
							<div id="addshot">
							{if $oneshots}
								{foreach from=$oneshots item=row name="oneshots"}
								<div class="showshot">
								Deliver 
								<input type="text" style="width:10%" id="" name="articles[]" class="validate[required,custom[integer]]" value="{$row.articles}" /> 
								articles after
								<input type="text" id="" name="oneshot_length[]" style="width:10%" class="validate[required,custom[integer]] check" value="{$row.oneshot_length}" /> 
								<select name="oneshot_option[]" id="" class="span2">
									{html_options  options=$tempo_duration_array selected=$row.oneshot_option}
								</select>
								{if !$smarty.foreach.oneshots.first}
								<a class="btn btn-mini closeshot">
									<i class="icon-remove"></i>
								</a>
								{/if}
								</div>
								{/foreach}
							{else}
								<div class="showshot">
									Deliver 
									<input type="text" style="width:10%" id="" name="articles[]" class="validate[required,custom[integer]]" value="" /> 
									articles after
									<input type="text" id="" name="oneshot_length[]" style="width:10%" class="validate[required,custom[integer]] check" value="" /> 
									<select name="oneshot_option[]" id="" class="span2">
										{html_options  options=$tempo_duration_array}
									</select>
								</div>
							{/if}
							</div>
							<div class="span7">
								<a class="btn btn-small topset2 cloneshot pull-right"><i class="icon-plus"></i> Ajouter</a>
							</div>
						</div>
						</div>
					</div>
					{elseif  $prod_mission_details.oneshot eq 'no'}
					<div class="control-group">
						<label class="control-label">Recurring</label>
						<div class="controls" style="margin-top:7px">
						<strong>
							{$prod_mission_details.volume_max} ({$tempo_array.$_tempo_value|capitalize}) {$prod_mission_details.product_type_name} {$volume_option_array.$_delivery_volume_option} {$prod_mission_details.tempo_length} {$tempo_duration_array.$_tempo_length_option}
						</strong>
						</div>
					</div>
					{/if}
						
					{if $prod_mission_details.oneshot eq 'yes' || $prod_mission_details.oneshot eq 'no'}
					<div class="control-group">
						<label class="control-label">Receive an alert by email<br>If tempo not respected</label>
						<div class="controls">
							<div class="span4">
								<input type="radio" name="alert_email" class="alertemail" {if $alertemail eq 'yes' || $alertemail eq ''} checked {/if} value="yes">Oui&nbsp;
								<input type="radio" name="alert_email" class="alertemail" {if $alertemail eq 'no'} checked {/if} value="no">Non
							</div>	
						</div>
					</div>
					{/if}
					<div class="control-group">
						<label class="control-label"></label>
						<div class="controls">
							<label class="radio">
								<input type="radio" name="launch" {if $launch_survey=='yes'} checked="checked" {/if} value="survey" class="launch" /> 
								Launch a Survey
							</label>
							<label class="radio">
								<input type="radio" name="launch" {if $launch_recuritement=='yes'} checked="checked" {/if} value="recruitment"  class="launch" /> 
								Launch a Recruitment
							</label>
							<label class="radio" style="margin-left:15px">
								<span class="help-block">All Missions in the Queue will be performed after the recruitment</span>
							</label>
							<label class="radio">
								<input type="radio" name="launch" {if $launch_recuritement=='no' && $launch_survey=='no'} checked="checked" {/if} value="none"  class="launch" /> 
								None
							</label>
							<label class="checkbox">
								<input type="checkbox" name="privatedelivery" value="yes" {if $privatedelivery=='yes' || $launch_recuritement=='yes'} checked="checked" {/if} class="privatedelivery" /> 
								Private Mission
							</label>
						</div>
					</div>
				</div>
				</div>
			
		</div>	
		
		<br><br>
		<h3>Tech & SEO Missions</h3><br>
			
				<div class="row-fluid">
					<table class="table headercolor table-bordered">
						<tr>
							<th>Expected Mission</th>
							<th>Mission Title</th>
							<th>Delivery Time</th>
							<th>Assigned</th>
							<th>Prior to Prod</th>
							<th>Status</th>
							<th></th>
						</tr>
					{if $expected_techmissions|@count gt 0}
						{foreach from=$expected_techmissions item=row name="tech_mission"}
						<tr>
							<td>Tech Mission</td>
							<td>{$row.title}</td>
							<td>{$row.delivery_time}&nbsp;{$row.delivery_option}</td>
							
							<td>{$row.assigned}</td>
							<td class="capitalise">{$row.before_prod}</td>
							<td class="capitalise">{$row.cmstatus}</td>
							<td>
							{if $row.assigned=="Yes"}
							<a href="/followup/tech?cmid={$row.cmid}&submenuId=ML13-SL4" id="" target="_blank" class="btn btn-mini btn-default">See</a>
							{else}
							<a href="/contractmission/mission-seo-tech?type=tech&id={$row.identifier}" data-toggle="modal" role="button" data-target="#mission_modal" id="" class="btn btn-mini btn-default">See</a>
							{/if}
							</td>
						</tr>
						{/foreach}
					{/if}
					{if $seoMissionDetails|@count gt 0}
						{foreach from=$seoMissionDetails item=row name="tech_mission"}
						<tr>
							<td>SEO Mission</td>
							<td>{$row.title}</td>
							<td>{$row.mission_length}&nbsp;{$row.mission_length_option}</td>
							
							<td>{$row.assigned}</td>
							<td class="capitalise">{$row.before_prod}</td>
							<td class="capitalise">{$row.cmstatus}</td>
							<td>
							{if $row.assigned=="Yes"}
							<a href="/followup/seo?cmid={$row.cmid}&submenuId=ML13-SL4" target="_blank" id="" class="btn btn-mini btn-default">See</a>
							{else}
							<a href="/contractmission/mission-seo-tech?type=seo&id={$row.identifier}" data-toggle="modal" role="button" data-target="#seo_modal" id="" class="btn btn-mini btn-default">See</a>
							{/if}
							</td>
						</tr>
						{/foreach}
						
					{/if}
					{if $expected_techmissions|@count ==0 &&  $seoMissionDetails|@count ==0}
					<tr>
						<td colspan="6">Expected Missions not Found.</td>
					</tr>
					{/if}
					</table>
					<br/>
					<table class="table headercolor table-bordered">
						<tr>
							<th>Extra Mission</th>
							<th>Mission Title</th>
							<th>Delivery Time</th>
							<th>Assigned</th>
							<th>Prior to Prod</th>
							<th>Status</th>
							<th></th>
						</tr>
					{if $extra_techmissions|@count gt 0 || $extra_staff|@count gt 0}
						{foreach from=$extra_techmissions item=row name="tech_mission"}
						<tr>
							<td>Tech Mission {if $row.title==""}<span class="label label-info">Pending</span>{/if}</td>
							<td>{if $row.title}{$row.title}{else}-{/if}</td>
							<td>{if $row.delivery_time}{$row.delivery_time}&nbsp;{$row.delivery_option}{else}-{/if}</td>
							<td>{$row.assigned}</td>
							<td class="capitalise">{$row.before_prod}</td>
							<td class="capitalise">{$row.cmstatus}</td>
							<td>{if $row.title}
							{if $row.assigned=='Yes'}
							<a href="/followup/tech?cmid={$row.cmid}&submenuId=ML13-SL4" id="" target="_blank" class="btn btn-mini btn-default">See</a>
							{else}
							<a href="/contractmission/mission-seo-tech?type=tech&id={$row.identifier}" data-toggle="modal" role="button" data-target="#mission_modal" id="" class="btn btn-mini btn-default">See</a>
							{/if}
							{/if}
							</td>
						</tr>
						{/foreach}
						{foreach from=$extra_staff item=row name="staff_mission"}
						<tr>
							<td>Staff Mission {if $row.title==""}<span class="label label-info">Pending</span>{/if}</td>
							<td>{if $row.title}{$row.title}{else}-{/if}</td>
							<td>{if $row.delivery_time}{$row.delivery_time}&nbsp;{$row.delivery_option}{else}-{/if}</td>
							<td>{$row.assigned}</td>
							<td class="capitalise">{$row.before_prod}</td>
							<td class="capitalise">{$row.cmstatus}</td>
							<td>{if $row.title}
							{if $row.assigned=='Yes'}
							<a href="/followup/staff?cmid={$row.cmid}&submenuId=ML13-SL4" id="" target="_blank" class="btn btn-mini btn-default">See</a>
							{else}
							<a href="/contractmission/mission-seo-tech?type=staff&id={$row.identifier}" data-toggle="modal" role="button" data-target="#mission_modal" id="" class="btn btn-mini btn-default">See</a>
							{/if}
							{/if}
							</td>
						</tr>
						{/foreach}
					{else}
						<tr>
							<td colspan="6">Extra Missions not Found.</td>
						</tr>
					{/if}
					</table>
				</div>
				{* {if not $onlysales} 
				<div class="row-fluid">
					<a name="save" id="newrequest" onclick="return removePrice()" class="btn btn-default">Request a new Tech Mission</a>
				</div>
				 {/if} *}
				<div class="row-fluid">
					<a name="save" id="newrequest" onclick="return removePrice()" class="btn btn-default">Request a new Tech Mission</a>
				</div>
			
			
		
		<br><br>
		<div class="well well-large clearfix">
			<h3>Assignment</h3>
			
					<p>Which folk is going to be the Owner?</p><br>
					{if $contractDetails}
						{foreach from=$users item=row}
						<div class="assignuser pull-left">
							<img class="media-object rd_30" height="50" width="50" src="{$fo_path}profiles/bo/{$row.identifier}/logo.jpg">
							{if $row.first_name || $row.last_name}<p>{$row.first_name}&nbsp;{* $row.last_name *}</p>{else}<br/><br/>{/if}
							<input type="radio" class="validate[required]" name="assignuser" {if $contractMissionDetails.assigned_to == $row.identifier} checked="checked" {/if} value="{$row.identifier}" />
							{* <label>{if $contractMissionDetails.assigned_to == $row.identifier} Assigned {else} Assign {/if}</label> *}
						</div>
					{/foreach}
					{else}
					{foreach from=$users item=row}
					<div class="assignuser pull-left">
						<img class="media-object rd_30" height="50" width="50" src="{$fo_path}profiles/bo/{$row.identifier}/logo.jpg">
						{if $row.first_name || $row.last_name}<p>{$row.first_name}&nbsp;{* $row.last_name *}</p>{else}<br/><br>{/if}
						<input type="radio" class="validate[required]" name="assignuser" value="{$row.identifier}" />
						{* <label>Assign</label> *}
					</div>
					{/foreach}
					{/if}
		
	</div>
		
	{/if}	
	
	<div class="row-fluid topset2" style="text-align:center">
	{* Restricting submit if there are any blocker tech or seo missions untill they are assigned *}
	{if $submit}
		<button type="submit" name="save" onclick="removeDisabled()" class="btn btn-primary">Submit</button>
	{else}
		<div class="alert alert-warning"><h4>SEO or Tech Missions Prior to Prod are required. You can't assign someone for the moment.</h4></div> 
	{/if}
	</div>
	{* End of Prod mission *}
	</form>
	</div>
	
</div>
<!--popup to show tech mission details-->
<div class="modal container hide fade" id="mission_modal">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Tech Mission</h3>
    </div>
    <div class="modal-body">
		
	</div>
    <div class="modal-footer">
    </div>
</div>	
<!--popup to show Seo mission details-->
<div class="modal container hide fade" id="seo_modal">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>SEO Mission</h3>
    </div>
    <div class="modal-body">
		
	</div>
    <div class="modal-footer">
    </div>
</div>	
<!--popup to show new tech mission details-->
<div class="modal hide fade" id="close_quote" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
		<h3>Tech Mission Request</h3>
    </div>
    <div class="modal-body">
		<form action="/contractmission/add-new-techmission" method="post" id="closequote" enctype="multipart/form-data">
			<input type="hidden" name="contractid" value="{$smarty.get.contract_id}" />
			<input type="hidden" name="quoteid" value="{$quote_details.identifier}" />
			<input type="hidden" name="index" value="{$current_index}" />
			<input type="hidden" name="price" id="price" value="new" />
			<section>
				<div class="row-fluid topset2">
					<div class="media mission-comment addmargin">
							<a class="pull-left imgframe">
								<img width="60px" src="{$fo_path}/profiles/bo/{$loginuserId}/logo.jpg" class="media-object">
							</a>
							<div class="media-body">
								<textarea name="comment" id="newcomment" class="validate[required] span12" placeholder="Explain what do you need here"></textarea>
							</div>
							<input type="file" name="seo_documents[]" accept="doc|xls|zip|docx|xlsx" class="multi" id=""/>
					</div>
					{if $contractDetails==false}
					<div class="control-group"  id="before_prod" >
						<label class="control-label"></label>
						<div class="controls">
							<label class="checkbox span3">
								<input type="checkbox" name="before_prod" value="yes" class="" /> 
								Set as Blocker
							</label>
						</div>
					</div>
					{else}
						<br/>
					{/if}
					<div class="control-group span12">
						<div class="span4"></div>
						<div class="span8">
							<button  class="btn" data-dismiss="modal" type="reset">Cancel</button>
							<button class="btn btn-primary" name="submit" value="no" type="submit">Request</button>
						</div>
					</div>
				</div>
			</section>
		</form>
    </div>
    <div class="modal-footer">
    </div>
</div>

<!--popup to show new tech mission details-->
<div class="modal hide fade" id="new_staffing" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
		<h3>Staff Mission</h3>
    </div>
    <div class="modal-body">
		<form action="/contractmission/add-new-staffmission" method="post" id="newstaff" enctype="multipart/form-data">
			<input type="hidden" name="contractid" value="{$smarty.get.contract_id}" />
			<input type="hidden" name="quoteid" value="{$quote_details.identifier}" />
			<input type="hidden" name="missionid" value="{$seotechprodid}" />
			<input type="hidden" name="index" value="{$current_index}" />
			<input type="hidden" name="price" id="price" value="new" />
			<input type="hidden" name="staff_time" id="staff_time" value="{$prod_mission_details.staff_time}" />
			<input type="hidden" name="staff_time_option" id="staff_time_option" value="{$prod_mission_details.staff_time_option}" />
			<section>
				<p>Vous vous appr&ecirc;tez &agrave; cr&eacute;er une mission de staffing, merci de confirmer votre choix ci-dessous</p>
			
			{* <div class="row-fluid topset2">
					<div class="media mission-comment addmargin">
							<a class="pull-left imgframe">
								<img width="60px" src="{$fo_path}/profiles/bo/{$loginuserId}/logo.jpg" class="media-object">
							</a>
							<div class="media-body">
								<textarea name="comment" id="staffcomment" class="validate[required] span12" placeholder="Explain what do you need here"></textarea>
							</div>
							<input type="file" name="staff_documents[]" accept="doc|xls|zip|docx|xlsx" class="multi" id=""/>
					</div>
					{if $contractDetails==false}
					<div class="control-group"  id="before_prod" >
						<label class="control-label"></label>
						<div class="controls">
							<label class="checkbox span3">
								<input type="checkbox" name="before_prod" value="yes" class="" /> 
								Set as Blocker
							</label>
						</div>
					</div>
					{else}
						<br/>
					{/if}
				*}
					<div class="control-group span12">
						<div class="span4"></div>
						<div class="span8">
							<button  class="btn" data-dismiss="modal" type="reset">Annuler</button>
							<button class="btn btn-primary" name="submit" value="no" type="submit">Validate</button>
						</div>
					</div>
				</div>
			
			</section>
		</form>
    </div>
    <div class="modal-footer">
    </div>
</div>

{* to clone in tempo one shot *}
<div id="cloneshots" class="showshot" style="display:none">
	Deliver 
	<input type="text" style="width:10%" id="" name="articles[]" class="validate[required,custom[integer]]]" value="{$mission.tempo_length}" /> 
	articles after
	<input type="text" id="" name="oneshot_length[]" style="width:10%" class="validate[required,custom[integer]] check" value="{$mission.tempo_length}" /> 
	<select name="oneshot_option[]" id="" class="span2">
		{html_options  options=$tempo_duration_array selected=$mission.tempo_length_option}
	</select>
	<a class="btn btn-mini closeshot">
		<i class="icon-remove"></i>
	</a>
</div>
{literal}
	<script>
		$(document).ready(function(){
			 $('input[type=radio]').on('ifChecked', function(event){
			  //$(this).closest("div").find(".change").text('Assigned');
			});
		
			 $('input[type=radio]').on('ifUnchecked', function(event){
			  $(this).closest("div").find(".change").text('Assign');
			});
			
			$(document).on("click","#newrequest",function(){
				
						$("#close_quote").modal('show');
						$("#close_quote").removeClass( "hide" ).addClass("in");
					
			})
			
			$("#spinner").spinner({min:1});
			
			$('.alertemail').iCheck({
				checkboxClass: 'icheckbox_square-blue',
				radioClass: 'iradio_square-blue'		
			});
			
			$(".cloneshot").click(function(){
				$("#cloneshots").clone().appendTo("#addshot");
				$("#addshot").find("#cloneshots").removeAttr("id");
			})
			
			$(document).on("click",".closeshot",function(){
				$(this).closest("div").remove();
			});
		})
		/* To check one shot articles option in Ascending order */
		function checkMax(){
			var current_value = prev_value = "";
			$("#addshot [name=articles\\[\\]]").each(function(index,value){
				current_value = parseInt($(this).val());
				if(prev_value !="" && current_value < prev_value)
				{
					$(this).addClass("errortempo");
					//$(this).css("border","1px solid #d90501");
					prodsubmit = false;
					$('html, body').animate({ scrollTop: $('#addshot').offset().top }, 'slow');
					return false;
				}
				else
				{
					//$(this).css("border","none");
					$(this).removeClass("errortempo");
					prodsubmit = true;
				}
					
				prev_value = current_value;
			})
			if(prodsubmit == false)
				return false;
			current_value = prev_value = "";
			$("#addshot [name=oneshot_length\\[\\]]").each(function(index,value){
				current_value = parseInt($(this).val());
				if(prev_value !="" && current_value < prev_value)
				{
					$(this).addClass("errortempo");
					//$(this).css("border","1px solid #d90501");
					prodsubmit = false;
					$('html, body').animate({ scrollTop: $('#addshot').offset().top }, 'slow');
					return false;
				}
				else
				{
					//$(this).css("border","none");
					$(this).removeClass("errortempo");
					prodsubmit = true;
				}
					
				prev_value = current_value;
			})
			
			return prodsubmit;
		}
		
	</script>
{/literal}