{literal}
<script type="text/javascript">	
$(document).ready(function() {
	$('.contractlist').dataTable({
            "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            "sPaginationType": "bootstrap",
            "aaSorting": [[ 0, "asc" ]],
			"iDisplayLength":50,
            "aoColumns": [
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "numeric" },
                { "sType": "string" },
                { "sType": "date" },
                { "sType": "date" },
                { "sType": "date" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" }
            ]
        });
		
	 /* $('.tooltips').tooltipster(
	 {
		contentAsHTML: true,
		theme: 'tooltipster-noir',
		position: 'bottom',
		interactive: true,
	 }); */
	 
});	


</script>

<link rel="stylesheet" type="text/css" href="/BO/theme/gebo/lib/tooltipster/css/tooltipster.css" />
<link rel="stylesheet" type="text/css" href="/BO/theme/gebo/lib/tooltipster/css/themes/tooltipster-noir.css" />
<script src="/BO/theme/gebo/lib/tooltipster/js/jquery.tooltipster.min.js" type="text/javascript"></script>
<link rel="stylesheet" type="text/css" href="/BO/theme/gebo/lib/jsgantt/jsgantt.css"/>
<script language="javascript" src="/BO/theme/gebo/lib/jsgantt/jsgantt-cm.js"></script>
{/literal}

<div class="row-fluid">
	<div class="span12">
    	<h3 class="heading">Contract Follow Up</h3>
		
		<ul class="nav nav-tabs">
			<li class="{if $smarty.get.active eq ''} active {/if}"><a href="#opened" data-toggle="tab">Opened</a></li>
			<li class="{if $smarty.get.active eq 'validate'} active {/if}"><a href="#validate" data-toggle="tab">To Validate</a></li>
			<li class="{if $smarty.get.active eq 'finished'} active {/if}"><a href="#finished" data-toggle="tab">Finished</a></li>
		</ul>	
		
		<div class="tab-content">
			<div class="tab-pane {if $smarty.get.active eq ''} active {/if}" id="opened">
		
				 <table class="table table-bordered table-striped table_vam contractlist" id="" >
					<thead>
						<tr>
						   <th style="display:none"></th>
						   <th>Contract Name</th>
						   <th>Turnover</th>
						   <th>Sales Name</th>
						   <th>Signature</th>
						   <th>Launch</th>                   
						   <th>Delivery</th>                   
						   <th>Team</th>                   
						   <th>Action</th>                   
						   <th>View Missions</th>                   
						</tr>
					</thead>
					<tbody>
					{assign var="sales" value="true"}
						{foreach from=$contracts_opened item="contract" name="contracts" }
						{assign var="sales" value="true"}
							<tr>
								<td style="display:none"></td>
								<td><span class="tooltips" title="&lt;a href=&quot;  &quot; &gt; View Contract &lt;/a&gt;
								&lt;br&gt;
								&lt;a href=&quot;  &quot; &gt; View Missions &lt;/a&gt;">{$contract.contractname}</span></td>
								<td>{$contract.turnover|zero_cut:2}&nbsp;&{$contract.sales_suggested_currency};</td>
								<td>{$contract.first_name}&nbsp;{$contract.last_name}</td>
								<td>{$contract.signaturedate|date_format:"%d/%m/%Y"}</td>
								<td>{$contract.expected_launch_date|date_format:"%d/%m/%Y"}</td>
								<td>{$contract.expected_end_date|date_format:"%d/%m/%Y"}</td>
								<td>
									{if $contract.tech_team}
										{assign var="sales" value="false"}
										{if ($user_type == 'superadmin' || $user_type =='techuser') && $contract.status == 'finance' }	
										<a href="/contractmission/assign-mission?contract_id={$contract.quotecontractid}&type=tech">Tech</a>&nbsp;
										{else}
										Tech&nbsp;	
										{/if}
									{/if}
									{if $contract.seo_team}
										{assign var="sales" value="false"}
										{if ($user_type == 'superadmin' || $user_type =='seouser') && $contract.status == 'finance'}	
										<a href="/contractmission/assign-mission?contract_id={$contract.quotecontractid}&type=seo">Seo</a>&nbsp;
										{else}
										Seo&nbsp;	
										{/if}
									{/if}
									{if $contract.prod_team}
									{assign var="sales" value="false"}
										{if ($user_type == 'superadmin' || $user_type =='produser') && $contract.status == 'finance' }	
										<a href="/contractmission/assign-mission?contract_id={$contract.quotecontractid}&type=prod">Prod</a>&nbsp;
										{else}
										Prod&nbsp;	
										{/if}
									{/if}
									{if $sales=="true"}
										Only Sales
									{/if}
								</td>
								<td>
								{if $contract.status eq 'sales'}
									{if $user_type == 'superadmin'}	
									<a href="/contractmission/contract-sales-edit?contract_id={$contract.quotecontractid}">Edit</a>&nbsp;|
									{/if}
									{if $user_type =='salesuser'}
										<a href="/contractmission/contract-sales-edit?contract_id={$contract.quotecontractid}">Edit</a>
									{/if}
									{if $user_type == 'superadmin' || $user_type =='financeuser' }
									<a href="/contractmission/contract-finance-edit?contract_id={$contract.quotecontractid}">Validate</a>
									{/if}
								{else}
									{if $user_type == 'superadmin' || $user_type =='financeuser' }
									<a href="/contractmission/contract-finance-edit?contract_id={$contract.quotecontractid}">Validated</a>
									{else}
									 Validated
									{/if}
								{/if}
								</td>
								<td>
									<a href="/contractmission/mission-details?quote_id={$contract.identifier}" data-toggle="modal" role="button" data-target="#mission_modal" id="" class="btn btn-mini btn-primary">View Missions</a>
								</td>
							</tr>
						{/foreach}
					</tbody>
				</table>
			</div>
			
			<div class="tab-pane {if $smarty.get.active eq 'validate'} active {/if}" id="validate">
				<table class="table table-bordered table-striped table_vam contractlist" id="" >
					<thead>
						<tr>
						   <th style="display:none"></th>
						   <th>Contract Name</th>
						   <th>Turnover</th>
						   <th>Sales Name</th>
						   <th>Signature</th>
						   <th>Launch</th>                   
						   <th>Delivery</th>                   
						   <th>Team</th>                   
						   <th>Action</th>                   
						   <th>View Missions</th>                   
						</tr>
					</thead>
					<tbody>
					{assign var="sales" value="true"}
						{foreach from=$contracts_to_validate item="contract" name="contracts" }
						{assign var="sales" value="true"}
							<tr>
								<td style="display:none"></td>
								<td>{$contract.contractname}</td>
								<td>{$contract.turnover|zero_cut:2}&nbsp;&{$contract.sales_suggested_currency};</td>
								<td>{$contract.first_name}&nbsp;{$contract.last_name}</td>
								<td>{$contract.signaturedate|date_format:"%d/%m/%Y"}</td>
								<td>{$contract.expected_launch_date|date_format:"%d/%m/%Y"}</td>
								<td>{$contract.expected_end_date|date_format:"%d/%m/%Y"}</td>
								<td>
									{if $contract.tech_team}
										{assign var="sales" value="false"}
										{if ($user_type == 'superadmin' || $user_type =='techuser') && $contract.status == 'finance' }	
										<a href="/contractmission/assign-mission?contract_id={$contract.quotecontractid}&type=tech">Tech</a>&nbsp;
										{else}
										Tech&nbsp;	
										{/if}
									{/if}
									{if $contract.seo_team}
										{assign var="sales" value="false"}
										{if ($user_type == 'superadmin' || $user_type =='seouser') && $contract.status == 'finance'}	
										<a href="/contractmission/assign-mission?contract_id={$contract.quotecontractid}&type=seo">Seo</a>&nbsp;
										{else}
										Seo&nbsp;	
										{/if}
									{/if}
									{if $contract.prod_team}
									{assign var="sales" value="false"}
										{if ($user_type == 'superadmin' || $user_type =='produser') && $contract.status == 'finance' }	
										<a href="/contractmission/assign-mission?contract_id={$contract.quotecontractid}&type=prod">Prod</a>&nbsp;
										{else}
										Prod&nbsp;	
										{/if}
									{/if}
									{if $sales=="true"}
										Only Sales
									{/if}
								</td>
								<td>
								{if $contract.status eq 'sales'}
									{if $user_type == 'superadmin'}	
									<a href="/contractmission/contract-sales-edit?contract_id={$contract.quotecontractid}">Edit</a>&nbsp;|
									{/if}
									{if $user_type =='salesuser'}
										<a href="/contractmission/contract-sales-edit?contract_id={$contract.quotecontractid}">Edit</a>
									{/if}
									{if $user_type == 'superadmin' || $user_type =='financeuser' }
									<a href="/contractmission/contract-finance-edit?contract_id={$contract.quotecontractid}">Validate</a>
									{/if}
								{else}
									{if $user_type == 'superadmin' || $user_type =='financeuser' }
									<a href="/contractmission/contract-finance-edit?contract_id={$contract.quotecontractid}">Validated</a>
									{else}
									 Validated
									{/if}
								{/if}
								</td>
								<td>
									<a href="/contractmission/mission-details?quote_id={$contract.identifier}" data-toggle="modal" role="button" data-target="#mission_modal" id="" class="btn btn-mini btn-primary">View Missions</a>
								</td>
							</tr>
						{/foreach}
					</tbody>
				</table>
			</div>
			
			<div class="tab-pane {if $smarty.get.active eq 'finished'} active {/if}" id="finished">
				<table class="table table-bordered table-striped table_vam contractlist" id="" >
					<thead>
						<tr>
						   <th style="display:none"></th>
						   <th>Contract Name</th>
						   <th>Turnover</th>
						   <th>Sales Name</th>
						   <th>Signature</th>
						   <th>Launch</th>                   
						   <th>Delivery</th>                   
						   <th>Team</th>                   
						   <th>Action</th>                   
						   <th>View Missions</th>                   
						</tr>
					</thead>
					<tbody>
					</tbody>
				</table>
			</div>
			
		</div>
	</div>
</div>

<div class="row-fluid">
	<div id='contract-calender'></div>
</div>

<!--popup to show mission details-->
<div class="modal container hide fade" id="mission_modal">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Missions</h3>
    </div>
    <div class="modal-body">
		
	</div>
    <div class="modal-footer">
    </div>
</div>	

{literal}
<!-- JS Gantt -->

<script>

  var g = new JSGantt.GanttChart('g',document.getElementById('contract-calender'), 'day');

	g.setShowRes(0); // Show/Hide Responsible (0/1)
	g.setShowDur(0); // Show/Hide Duration (0/1)
	g.setShowComp(0); // Show/Hide % Complete(0/1)
    g.setCaptionType('Resource');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)

	  if(g) {
		/* g.AddTaskItem(new JSGantt.TaskItem(35,'Duration','12/12/2008','2/04/2009','f600f6','',0,'Brain',0,0,0,0,'','Caption 1'));
		g.AddTaskItem(new JSGantt.TaskItem(31,'Define Variables','7/07/2008','8/07/2008','ff00ff','http://help.com',0,'{"name":"John Johnson","street":"Oslo West 16","phone":"555 1234567"}',0,0,0,0,'','Caption 1','{"name":"John Johnson","street":"Oslo West 16","phone":"555 1234567"}'));
		g.AddTaskItem(new JSGantt.TaskItem(32,'Define Variables','7/02/2008','8/08/2008','ff00ff','http://help.com',0,'{"name":"John Johnson","street":"Oslo West 16","phone":"555 1234567"}',0,0,0,0,'','Caption 1')); */
{/literal}
{foreach from=$contracts_opened item="contract" name="contracts" }
{literal} id = {/literal}{$contract.quotecontractid}{literal};{/literal}
{literal} cname = {/literal}"{$contract.contractname}"{literal};{/literal}
{literal} edate = {/literal}"{$contract.expected_end_date}"{literal};{/literal}
{literal} ldate = {/literal}"{$contract.expected_launch_date}"{literal};{/literal}
{literal} turnover = {/literal}"{$contract.turnover|zero_cut:2}"{literal};{/literal}
{literal} sname = {/literal}"{$contract.first_name} {$contract.last_name}"{literal};{/literal}
{literal} sdate = {/literal}"{$contract.signaturedate|date_format:'%d/%m/%Y'}"{literal};{/literal}
{literal}
json = '{"turnover":"'+turnover+'","sname":"'+sname+'","sdate":"'+sdate+'"}';
	g.AddTaskItem(new JSGantt.TaskItem(id,cname,ldate,edate,'ff00ff','',0,cname,0,0,0,0,'','Caption 1',json));
{/literal}
{/foreach}
{literal}
		g.Draw();	
		g.DrawDependencies();
	  }
	  else
	  {
		alert("not defined");
	  }

</script>

{/literal}