{literal}
<script type="text/javascript">	
$(document).ready(function() {
	$('.contractlist').dataTable({
            "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            "sPaginationType": "bootstrap",
            "aaSorting": [[ 0, "asc" ]],
			"iDisplayLength":50,
            "aoColumns": [
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "numeric" },
                { "sType": "string" },
                { "sType": "date" },
                { "sType": "date" },
                { "sType": "date" },
                { "sType": "string" },
                { "sType": "string" },
                { "sType": "string" }
            ]
        });
		
	 
	  $("#salesuseropen, #contractsopen").chosen({allow_single_deselect:false,search_contains: true});
	  $("#salesusertovalid, #salesuser_contracts, #salesuserclosed, #contractsclosed").chosen({allow_single_deselect:false,search_contains: true});
	  
	  $('#salesuseropen, #contractsopen').on('change', function(evt, params) {
		$(".openreplace").html('<center><b>Please wait Loading...</b></center>');
		$.post('/contractmission/loadcontracts/',{'sid':$("#salesuseropen").val(),'opened':1,'client_id':$("#contractsopen").val()},function(data){$(".openreplace").html(data)})
	  });

	  $('#salesuserclosed, #contractsclosed').on('change', function(evt, params) {
		$(".closedreplace").html('<center><b>Please wait Loading...</b></center>');
		$.post('/contractmission/loadcontracts/',{'sid':$("#salesuserclosed").val(),'opened':2,'client_id':$("#contractsclosed").val()},function(data){$(".closedreplace").html(data)})
	  });
	  
	   $('#salesusertovalid, #salesuser_contracts').on('change', function(evt, params) {
		$(".tovalidreplace").html('<center><b>Please wait Loading...</b></center>');
		$.post('/contractmission/loadcontracts/',{'sid':$("#salesusertovalid").val(),'opened':0,'client_id':$("#salesuser_contracts").val()},function(data){$(".tovalidreplace").html(data)})
	  });
	
	  $(document).on("click",".uni_style",function(){
		 $(".uni_style").uniform();
			 $(".tooltips").popover({ trigger: "manual" ,placement: 'top', html: true, animation:false})
			.on("mouseenter", function () {
				var _this = this;
				$(this).popover("show");
				$(".popover").on("mouseleave", function () {
					$(_this).popover('hide');
				});
			}).on("mouseleave", function () {
				var _this = this;
				setTimeout(function () {
					if (!$(".popover:hover").length) {
						$(_this).popover("hide");
					}
				}, 300);
			});
	  })
	  
	  $(document).on("click",".uni_style2",function(){
		 $(".uni_style2").uniform();
	  })
		  
	 
});	

</script>

<link rel="stylesheet" type="text/css" href="/BO/theme/gebo/lib/jsgantt/jsgantt.css"/>
<script language="javascript" src="/BO/theme/gebo/lib/jsgantt/jsgantt-cm.js"></script>
<style>

	#leftside td, #leftside th
	{
		padding:8px;
	}
	
	#rightside th,#rightside td
	{
		padding:8px 0;
	}
	
	.tooltips 
	{
		cursor:pointer;
		
	}
</style>

{/literal}

<div class="row-fluid">
	<div class="span12">
		<h1 class="heading">Contract Follow Up</h1>
		<ul class="nav nav-tabs">
			<li class="{if $smarty.get.active eq ''} active {/if}"><a href="#openedup" data-toggle="tab">Opened</a></li>
			<li class="{if $smarty.get.active eq 'validate'} active {/if}"><a href="#validateup" data-toggle="tab" class="">To Validate&nbsp;<span class="badge badge-warning" id="assigncount"></span></a></li>
			<li class="{if $smarty.get.active eq 'finished'} active {/if}"><a href="#finishedup" data-toggle="tab">Finished</a></li>
		</ul>	
		
		<div class="tab-content" style="overflow:hidden;min-height:400px">
			<div class="tab-pane {if $smarty.get.active eq ''} active {/if}" id="openedup">
				<div class="row-fluid">
					<div class="">
					<select data-placeholder="All Sales" id="salesuseropen" class='cselect'>
						<option value="">All PM</option>
						{foreach from=$salesusers item=user name=users}
						   <option value="{$user.identifier}" >{if $user.first_name || $user.last_name}{$user.first_name}&nbsp;{$user.last_name}{else}{$user.email}{/if}</option>
						{/foreach}
					</select>
					<select data-placeholder="All Sales" id="contractsopen" class='cselect'>
						<option value="">All Clients</option>
						{foreach from=$clients item=user name=users}
						   <option value="{$user.identifier}" >{$user.company_name}</option>
						{/foreach}
					</select>
					</div>
				</div>
				<div class="row-fluid">
					<div class="openreplace">
					{if $contracts_opened|@count eq 0}
						<center><strong>No Contracts Found</strong></center>
					{else}
						<div id='contract-calender'></div>
					{/if}
					</div>
				</div>
			</div>
			<div class="tab-pane {if $smarty.get.active eq 'validate'} active {/if}" id="validateup">
					<div class="row-fluid">
					<select data-placeholder="All Sales" id="salesusertovalid" class='cselect'>
						<option value="">All PM</option>
						{foreach from=$salesusers item=user name=users}
						   <option value="{$user.identifier}" >{if $user.first_name || $user.last_name}{$user.first_name}&nbsp;{$user.last_name}{else}{$user.email}{/if}</option>
						{/foreach}
					</select>
					<select data-placeholder="All Sales" id="salesuser_contracts" class='cselect'>
						<option value="">All Clients</option>
						{foreach from=$clients item=user name=users}
						<option value="{$user.identifier}" >{$user.company_name}</option>
						{/foreach}
					</select>
					</div>
					<div class="row-fluid">
					<div class="tovalidreplace">
					{if $contracts_to_validate|@count eq 0}
						<center><strong>No Contracts Found</strong></center>
					{else}
						<div id='contract-calender2'></div>
					{/if}
					</div>
					</div>
			</div>
			<div class="tab-pane {if $smarty.get.active eq 'finished'} active {/if}" id="finishedup">
				<div class="row-fluid">
					<div class="">
					<select data-placeholder="All Sales" id="salesuserclosed" class='cselect'>
						<option value="">All PM</option>
						{foreach from=$salesusers item=user name=users}
						   <option value="{$user.identifier}" >{if $user.first_name || $user.last_name}{$user.first_name}&nbsp;{$user.last_name}{else}{$user.email}{/if}</option>
						{/foreach}
					</select>
					<select data-placeholder="All Sales" id="contractsclosed" class='cselect'>
						<option value="">All Clients</option>
						{foreach from=$clients item=user name=users}
						   <option value="{$user.identifier}" >{$user.company_name}</option>
						{/foreach}
					</select>
					</div>
				</div>
				<div class="row-fluid">
					<div class="closedreplace">
					{if $contracts_closed|@count eq 0}
						<center><strong>No Contracts Found</strong></center>
					{else}
						<div id='contract-calender3'></div>
					{/if}
				</div>
			</div>
		</div>
	</div>
</div>


<!--popup to show mission details-->
<div class="modal container hide fade" id="mission_modal">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Missions</h3>
    </div>
    <div class="modal-body">
		
	</div>
    <div class="modal-footer">
    </div>
</div>	

{literal}
<!-- JS Gantt -->
<style>
div.uni-radio {    
    margin-left: 10px;
	margin-right:0px;
}	
</style>
<script>
  var utype = {/literal}"{$user_type}"{literal};
  var assigncount = 0;
 /*  if(utype=='salesuser' || utype=='salesmanager' || utype=='ceouser')
  var cedit = 'contract-finance-edit';
  else */
  //var cedit = 'contract-sales-edit';
  var cedit = 'contract-edit';
  var g = new JSGantt.GanttChart('g',document.getElementById('contract-calender'), 'day');

	g.setShowRes(0); // Show/Hide Responsible (0/1)
	g.setShowDur(0); // Show/Hide Duration (0/1)
	g.setShowComp(0); // Show/Hide % Complete(0/1)
    g.setCaptionType('None');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)

	  if(g) {
		{/literal}
		{foreach from=$contracts_opened item="contract" name="contracts" }
		{literal} id = {/literal}{$contract.quotecontractid}{literal};{/literal}
		{literal} cname = {/literal}"{$contract.contractname}"{literal};{/literal}
		{literal} cid = {/literal}"{$contract.client_id}"{literal};{/literal}
		{literal} edate = {/literal}"{$contract.expected_end_date}"{literal};{/literal}
		{literal} ldate = {/literal}"{$contract.expected_launch_date}"{literal};{/literal}
		{literal} turnover = {/literal}"{$contract.turnover|zero_cut_t:2}"{literal};{/literal}
		{literal} currency = {/literal}"{$contract.sales_suggested_currency}"{literal};{/literal}
		{literal} duration = {/literal}"{$contract.duration}"{literal};{/literal}
		{literal} sname = {/literal}"{$contract.first_name} {$contract.last_name}"{literal};{/literal}
		{literal} sdate = {/literal}"{$contract.signaturedate|date_format:'%d/%m/%Y'}"{literal};{/literal}
		{literal} pdone = {/literal}"{$contract.percentage}"{literal};{/literal}
		/*{literal} clientname = {/literal}"{if $contract.clfname || $contract.cllname}{$contract.clfname} {$contract.cllname}{else}{$contract.clemail}{/if}"{literal};{/literal} */
		{literal} clientname = {/literal}"{$contract.clemail}"{literal};{/literal}
		{literal} compname = {/literal}"{$contract.company_name}"{literal};{/literal}
		{literal}
		json = '{"turnover":"'+turnover+'","sname":"'+sname+'","sdate":"'+sdate+'","currency":"'+currency+'","duration":"'+duration+'","pdone":"'+pdone+'","id":"'+id+'","cedit":"'+cedit+'","clientname":"'+clientname+'","cid":"'+cid+'","compname":"'+compname+'"}';
		g.AddTaskItem(new JSGantt.TaskItem(id,cname,ldate,edate,'2B78E4','',0,cname,0,0,0,0,'','Caption 1',json));
		{/literal}
		{/foreach}
		{literal}
		g.Draw();	
		g.DrawDependencies();
	  }
	  else
	  {
		alert("not defined");
	  }
 
 var g1 = new JSGantt1.GanttChart('g1',document.getElementById('contract-calender2'), 'day');
	var assigncount = 0;
	g1.setShowRes(0); // Show/Hide Responsible (0/1)
	g1.setShowDur(0); // Show/Hide Duration (0/1)
	g1.setShowComp(0); // Show/Hide % Complete(0/1)
    g1.setCaptionType('None');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)

	  if(g1) {
		{/literal}
		{foreach from=$contracts_to_validate item="contract" name="contracts" }
		{literal} id = {/literal}{$contract.quotecontractid}{literal};{/literal}
		{literal} cname = {/literal}"{$contract.contractname|utf8_encode}"{literal};{/literal}
		{literal} cid = {/literal}"{$contract.client_id}"{literal};{/literal}
		{literal} edate = {/literal}"{$contract.expected_end_date}"{literal};{/literal}
		{literal} edispdate = {/literal}"{$contract.expected_end_date|date_format:'%d/%m/%Y'}"{literal};{/literal}
		{literal} ldate = {/literal}"{$contract.expected_launch_date}"{literal};{/literal}
		{literal} ldispdate = {/literal}"{$contract.expected_launch_date|date_format:'%d/%m/%Y'}"{literal};{/literal}
		{literal} turnover = {/literal}"{$contract.turnover|zero_cut_t:2}"{literal};{/literal}
		{literal} currency = {/literal}"{$contract.sales_suggested_currency}"{literal};{/literal}
		{literal} duration = {/literal}"{$contract.duration}"{literal};{/literal}
		{literal} sname = {/literal}"{$contract.first_name|utf8_encode} {$contract.last_name|utf8_encode}"{literal};{/literal}
		{literal} sdate = {/literal}"{$contract.signaturedate|date_format:'%d/%m/%Y'}"{literal};{/literal}
		/* {literal} clientname = {/literal}"{if $contract.clfname || $contract.cllname}{$contract.clfname|utf8_encode} {$contract.cllname|utf8_encode}{else}{$contract.clemail|utf8_encode}{/if}"{literal};{/literal} */
		/*{literal} clientname = {/literal}"{if $contract.clfname || $contract.cllname}{$contract.clfname} {$contract.cllname}{else}{$contract.clemail}{/if}"{literal};{/literal} */
		{literal} clientname = {/literal}"{$contract.clemail}"{literal};{/literal}
		{literal} compname = {/literal}"{$contract.company_name}"{literal};{/literal}
		{literal}
		json = '{"turnover":"'+turnover+'","sname":"'+sname+'","sdate":"'+sdate+'","currency":"'+currency+'","edispdate":"'+edispdate+'","duration":"'+duration+'","id":"'+id+'","cedit":"'+cedit+'","ldispdate":"'+ldispdate+'","clientname":"'+clientname+'","cid":"'+cid+'","compname":"'+compname+'"}';
			g1.AddTaskItem(new JSGantt1.TaskItem(id,cname,ldate,edate,'2B78E4','',0,cname,0,0,0,0,'','Caption 1',json));
		{/literal}
		assigncount++;
		{/foreach}
		{literal}
		g1.Draw();	
		g1.DrawDependencies();
	  }
	  else
	  {
		alert("not defined");
	  } 

	
	var g2 = new JSGantt3.GanttChart('g2',document.getElementById('contract-calender3'), 'day');

	g2.setShowRes(0); // Show/Hide Responsible (0/1)
	g2.setShowDur(0); // Show/Hide Duration (0/1)
	g2.setShowComp(0); // Show/Hide % Complete(0/1)
    g2.setCaptionType('None');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)

	  if(g2) {
		{/literal}
		{foreach from=$contracts_closed item="contract" name="contracts" }
		{literal} id = {/literal}{$contract.quotecontractid}{literal};{/literal}
		{literal} cname = {/literal}"{$contract.contractname}"{literal};{/literal}
		{literal} cid = {/literal}"{$contract.client_id}"{literal};{/literal}
		{literal} edate = {/literal}"{$contract.expected_end_date}"{literal};{/literal}
		{literal} ldate = {/literal}"{$contract.expected_launch_date}"{literal};{/literal}
		{literal} turnover = {/literal}"{$contract.turnover|zero_cut_t:2}"{literal};{/literal}
		{literal} currency = {/literal}"{$contract.sales_suggested_currency}"{literal};{/literal}
		{literal} duration = {/literal}"{$contract.duration}"{literal};{/literal}
		{literal} sname = {/literal}"{$contract.first_name} {$contract.last_name}"{literal};{/literal}
		{literal} sdate = {/literal}"{$contract.signaturedate|date_format:'%d/%m/%Y'}"{literal};{/literal}
		{literal} pdone = {/literal}"{$contract.percentage}"{literal};{/literal}
		/*{literal} clientname = {/literal}"{if $contract.clfname || $contract.cllname}{$contract.clfname} {$contract.cllname}{else}{$contract.clemail}{/if}"{literal};{/literal} */
		{literal} clientname = {/literal}"{$contract.clemail}"{literal};{/literal}
		{literal} compname = {/literal}"{$contract.company_name}"{literal};{/literal}
		{literal}
		json = '{"turnover":"'+turnover+'","sname":"'+sname+'","sdate":"'+sdate+'","currency":"'+currency+'","duration":"'+duration+'","pdone":"'+pdone+'","id":"'+id+'","cedit":"'+cedit+'","clientname":"'+clientname+'","cid":"'+cid+'","compname":"'+compname+'"}';
		g2.AddTaskItem(new JSGantt.TaskItem(id,cname,ldate,edate,'2B78E4','',0,cname,0,0,0,0,'','Caption 1',json));
		{/literal}
		{/foreach}
		{literal}
		g2.Draw();	
		g2.DrawDependencies();
	  }
	  else
	  {
		alert("not defined");
	  }
	
$(document).ready(function() {
 $(".uni_style2").uniform();
		 $(".uni_style").uniform();
		
	/* $('.tooltips').popover({trigger:'hover'}).mouseenter(function(e) {
                $(this).popover('show');
            });  */
		
		$(".tooltips").popover({ trigger: "manual" ,placement: 'top', html: true, animation:false})
		.on("mouseenter", function () {
			var _this = this;
			$(this).popover("show");
			$(".popover").on("mouseleave", function () {
				$(_this).popover('hide');
			});
		}).on("mouseleave", function () {
			var _this = this;
			setTimeout(function () {
				if (!$(".popover:hover").length) {
					$(_this).popover("hide");
				}
			}, 300);
		});
		
	if(assigncount>0)
	{
		$("#assigncount").text(assigncount);
		$("#assigncount").removeClass('hide');
	}
	else
	$("#assigncount").addClass('hide');
});
</script>
{/literal}