{literal}
<script src="/BO/theme/gebo/lib/tinymce_4.2.5/js/tinymce/tinymce.min.js"></script>
	<style>
	/*	#missionTable tr:nth-child(even)
		{
			background-color:#F5F5F5;
			border-bottom:1px solid #ddd;
			text-align:center;
			font-weight:bold;
		}
		.padd td
		{
			padding:15px 5px;
		}
		
		#missionTable tr:nth-child(odd)
		{
			text-align:center;
		}
	*/	
		#missionTable td
		{
			font-size: 13px;
		} 
		
		.xdsoft_today_button
		{
			display:none !important;
		}
				
				
		input[readonly]
		{
			background-color:#fff !important;
			border: 1px solid #ccc !important;
			box-shadow: 0 1px 1px rgba(0, 0, 0, 0.075) inset !important;
			cursor:initial !important;
		}
		
		.txterror
		{
			color: #b94a48;
			margin-top: 4px;
		}
	</style>
	<link href="/BO/theme/gebo/css/jquery.datetimepicker.css" rel="stylesheet">
	<script src="/BO/theme/gebo/js/jquery.datetimepicker.js" type="text/javascript" charset="utf-8"></script>
	<link rel="stylesheet" href="/BO/theme/gebo/js/validation-engine/validationEngine.jquery.css" type="text/css"/>
	<link rel="stylesheet" href="/BO/theme/gebo/lib/iCheck/skins/square/blue.css" type="text/css"/>
	<script src="/BO/theme/gebo/lib/iCheck/icheck.min.js" type="text/javascript" charset="utf-8"></script> 
	<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine-fr.js" type="text/javascript" charset="utf-8"></script>
	<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>
	<script src="/BO/theme/gebo/js/jquery.MultiFileQuote.js" type="text/javascript" charset="utf-8"></script>
	<script>
		var final_end_date ="";
		function changefield()
		{
			$(".splitvaltxt").toggleClass('hide');
			$(".splitfield").toggleClass('hide');
			if($(".splitfield").css('display')=="none")
			$(".splitfield").attr('disabled',true);
			else
			{
				$(".splitfield").each(function(){
					$(this).val(function() {
					return this.defaultValue;
				});
				});
				$(".splitfield").attr('disabled',false);
			}
			return false;
		}
		
		var salesdtime = {/literal}{$quotedetails.final_mission_length}{literal};
		var salesdtimeo = {/literal}"{$quotedetails.final_mission_length_option}"{literal};
		var scurrency = {/literal}"{$quotedetails.sales_suggested_currency}"{literal};
		var prod_extra_launch_days = {/literal}"{$quotedetails.prod_extra_launch_days}"{literal};
		var peinfo = {/literal}"{$quotedetails.prod_extra_info}"{literal};
		var turnover = {/literal}{$quotedetails.turnover}{literal};
		var exp_end_date = {/literal}"{$quotedetails.exp_end_date}"{literal};
		var signed_at = {/literal}'{$quotedetails.signed_at|date_format:"%d/%m/%Y"}'{literal};
		var quote_id = {/literal}"{$quotedetails.identifier}"{literal};
		var setexpdate = peinfo;
		var enddate = "";
		var setdate = "";
		var mindate = {/literal}'{$quotedetails.signed_at|date_format:"%d/%m/%Y"}'{literal};
		function removeDisabled(){	setTimeout(function(){$(".MultiFile-applied").removeAttr("disabled");}, 1000);	}
		$(document).ready(function(){
			$('.icheck').iCheck({
				radioClass: 'iradio_square-blue'
			}); 
		  $("#contractsource").chosen({  allow_single_deselect:false,disable_search: true });
		  $(".select").chosen({  allow_single_deselect:false,disable_search: true });
		  $(".paymenttype").chosen({  allow_single_deselect:false,disable_search: true });
		  $(".uni_style").uniform();
		  $("#qlinked").css('height',$("#cprofile").height());
		  
		  jQuery('#sigdate').datetimepicker({
		  format:'d/m/Y',
		  formatDate:'d/m/Y',
		  //minDate:mindate,
		  minDate:'01/01/2014',
		  timepicker:false,
		  closeOnDateSelect:true,
		  onSelectDate:function(ct,$i){
		  if(setexpdate=='yes')
		  {
			var newdate =$i.val();
			splitval = newdate.split('/');
			reqdate = splitval[1]+"/"+splitval[0]+"/"+splitval[2];
			var startdate = new Date(Date.parse(reqdate));
			var expDate = startdate;
			expDate.setDate(startdate.getDate() + parseInt(prod_extra_launch_days));
			var month = expDate.getMonth()+1;
			if(month<10)
			month = '0'+month;
			var setdate = expDate.getDate()+"/"+month+"/"+expDate.getFullYear();
			loadsplitvalues(setdate);
			$("#launchdate").datetimepicker({ format:'d/m/Y',
			formatDate:'d/m/Y',
			//minDate:setdate,
			minDate:'01/01/2014',
		   timepicker:false
		  });
		   $("#launchdate").val(setdate);
		  }
		  }
		});
		  
		if(setexpdate=='yes')
		{
			var expmindate = {/literal}"{$quotedetails.exp_end_stddate|date_format:'%d/%m/%Y'}"{literal};
		}
		else
		{
			var expmindate = mindate;
		}
		
		$("#launchdate").datetimepicker({ 
			format:'d/m/Y',
			formatDate:'d/m/Y',
			//minDate:expmindate,
			minDate:'01/01/2014',
		    timepicker:false,
		    closeOnDateSelect:true,
			onSelectDate:function(ct,$i){
			 loadsplitvalues($i.val());
			 }
		  });
		
		$("#enddate").datetimepicker({ 
			format:'d/m/Y',
			formatDate:'d/m/Y',
			minDate:expmindate,
		    timepicker:false,
		    closeOnDateSelect:true,
			onSelectDate:function(ct,$i){
			// loadsplitvalues($i.val());
			 var split_final_date = final_end_date.split("/");
			  var date1 = split_final_date[2]+"-"+split_final_date[1]+"-"+split_final_date[0];
			  var current_date = $i.val().split("/");
			  var date2 = current_date[2]+"-"+current_date[1]+"-"+current_date[0];
			  if(date2<date1)
				$("#enderror").show();
			  else
				$("#enderror").hide();
			 }
		  });
			
		  $("#enddate").blur(function(){
			  var split_final_date = final_end_date.split("/");
			  var date1 = split_final_date[2]+"-"+split_final_date[1]+"-"+split_final_date[0];
			  var current_date = $(this).val().split("/");
			  var date2 = current_date[2]+"-"+current_date[1]+"-"+current_date[0];
			  if(date2<date1)
				$("#enderror").show();
			  else
				$("#enderror").hide();
		  })
		  
		})
	</script>
	
{/literal}
<form class="form-horizontal" action="/contractmission/save-contract" name="createContract" id="createcontract" method="POST" enctype='multipart/form-data'>
<div class="row-fluid">
	<div class="span12">
		<h3 class="heading">
			New Purchase Order
		</h3>
		<!-- <h4>{$quote_res.title}</h4> -->
	</div>	
</div>
<div class="row-fluid">
	<div class="span4">
		<div class="w-box">
			<div class="w-box-header">
				Client Profile
			</div>
			 <div class="w-box-content cnt_a" id="cprofile">
				<div class="row-fluid">
				{if $client_info !="no"}
					<div class="pull-left">
						<img title="{$client_info.company_name}" src="{$fo_path}/profiles/clients/logos/{$client_info.user_id}/{$client_info.user_id}_global.png?12345" alt="{$client_info.company_name}" >
					</div>
					<div class="span8">
						<div><a href="/quote/create-client?uaction=view&client_id={$client_info.identifier}&submenuId=ML13-SL1" target="_blank">{$client_info.company_name}</a></div>
						<div>{$client_info.initial} {$client_info.first_name} {$client_info.last_name}</div>
						{if $client_info.client_code}
						<div>Client code: {$client_info.client_code}</div>
						{/if}
						{if $client_info.ca_number}
						<div>CA info: {$client_info.ca_number|zero_cut_t:2}</div>
						{/if}
						<div>Category: {$quotedetails.category_name}</div> 
					</div>	
				{else}
					{$client_info}
				{/if}
				</div>
			 </div>
		</div>
	</div>
	<div class="span4">
		<div class="w-box">
			<div class="w-box-header">
				From Signed Quote
			</div>
			 <div class="w-box-content cnt_a" id="qlinked">
				<div class="row-fluid">
                    <div class="span12">                        				
						{if $quotedetails.is_new_quote eq '1'}
							<a href="/quote-new/sales-final-validation?qaction=briefing&quote_id={$smarty.get.quote_id}" target="_blank"><b>{$quotedetails.title}</b></a>
						{else}
							<a href="/quote/quote-followup?quote_id={$smarty.get.quote_id}}&submenuId=ML13-SL2" target="_blank"><b>{$quotedetails.title}</b></a>
						{/if}
                    </div>
				</div>
			 </div>
		</div>
	</div>
	<div class="span4">
		<div class="w-box">
			<div class="w-box-header">
				Contacts (<a href="/quote/create-client?uaction=view&client_id={$client_info.identifier}&submenuId=ML13-SL1" target="_blank">Update</a>)
			</div>
			 <div class="w-box-content cnt_a" id="qlinked">

                 <div style="overflow: auto; max-height: 80px; overflow-x: hidden;">
                     {if $clientContacts|@count gt 0}
						 {foreach  from=$clientContacts item="clientContact" name="clientContacts" }
							 <div class="media">
								<div class="span2">	
									<input type="radio" style="margin-top:50%;position:relative" class="icheck validate[required]" {if $clientContact.main_contact eq 'yes'} checked{/if} name="contact_client"  value="{$clientContact.identifier}">
								</div>
								 <div class="media-body">						
									 <p><strong>{$clientContact.first_name}</strong><br />
										{$clientContact.job_title}<br />
										{if $clientContact.office_phone}{$clientContact.office_phone}<br />{/if}
										{if $clientContact.email}<a href="mailto:{$clientContact.email}">{$clientContact.email}</a>{/if}
									 </p>
								 </div>
							 </div>
							 <hr>
						 {/foreach}
                     {else}
						<strong>No Contacts Available</strong>
                     {/if}
                 </div>
			 </div>
		</div>
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="w-box">
			<div class="w-box-header">
                PO & Mission Launch Information
				{* <a href="#" data-toggle="modal" class="pull-right" role="button" data-target="#view_info"><img src="/BO/theme/gebo/img/gCons/cassette.png" alt="" /></a> *}
			</div>
			 <div class="w-box-content cnt_a">
				<div class="control-group">
					<label class="control-label">PO Name</label>
					<div class="controls">
						<input type="text" name="contract_name" class="span4 validate[required]" />
					</div>
				</div>
				<div class="control-group">
					<label class="control-label">PO Status</label>
					<div class="controls">
						<label class="radio inline">
							<input type="radio" checked value="New" class="status uni_style" id="optionsRadios1" name="status"  />
							New
						</label>
						<label class="radio inline">
							<input type="radio" value="Renew" id="optionsRadios2" class="status uni_style" name="status" />
							Renew
						</label>
					</div>
				</div>
				<div class="control-group">
                     <label class="control-label">Signed PO</label>
                     <div class="controls">
                         <input type="checkbox" id="signed_PO" name="signed_PO" {if $contractDetials.signed_PO  eq 'yes'}checked="checked"{/if}/>
                     </div>
                 </div>
				<div class="control-group">
					<label class="control-label">PO Source</label>
					<div class="controls">
						<div class="span6">
							{html_options options=$csarray name="contractsource" class="validate[required]" id="contractsource"} 
						</div>
					</div>
				</div>
				<div class="control-group">
					<div class="controls">
						<div class="span10">
							<div id="showepfiles" style="display:none">
								<a href="/BO/dowload-source-contract.php?filename=CGV-Edit-Place-2016-JAN-16.pdf">CGV EditPlace 2016</a>
								<br/>
								<a href="/quote/download-quote-xls?quote_id={$quotedetails.identifier}">Quote XLS</a>
							</div>
							<input type="file" name="mulitupload[]" class="multi validate[required]" />
						</div>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label">Signature Date</label>
					<div class="controls">
						<input class="validate[required]" id="sigdate" value="{$quotedetails.signed_at|date_format:'%d/%m/%Y'}" name="signature_date" type="text" readonly="readonly" />
					</div>
				</div>
				<div class="control-group">
					<label class="control-label">Expected Launch Date</label>
					<div class="controls">
					{if $quotedetails.exp_end_date}
						<input class="validate[required]" id="launchdate" value='{$quotedetails.exp_end_stddate|date_format:"%d/%m/%Y"}' name="expected_launch_date" type="text" readonly="readonly" />
					{else}
							<input class="validate[required]" name="expected_launch_date" id="launchdate" value="{$quotedetails.signed_at|date_format:'%d/%m/%Y'}" type="text" readonly="readonly" />
					{/if}
					</div>
				</div>
				<div class="control-group">
					<label class="control-label">Expected End Date</label>
					<div class="controls">
						<input class="validate[required]" name="expected_end_date" id="enddate" type="text" />
						<div id="enderror" class="hide txterror">Lesser than calculated date</div>
					</div>
				</div>
				<div class="control-group">
					<label class="control-label">Contract overview</label>
					<div class="controls">
						<textarea name="comment" id="txtarea_sp" class="span6" rows="8" placeholder="D&eacute;crire le contexte de la mission + les modalit&eacute;s de facturation si sp&eacute;cificit&eacute; (upfront, BAT)
						"></textarea>		
						<span class="help-block">
							D&eacute;crire le contexte de la mission + les modalit&eacute;s de facturation si sp&eacute;cificit&eacute; (upfront, BAT)
						</span>
					</div>
				</div>                 
			</div>	
		</div>	
	</div>
</div>
<div class="row-fluid">
	<div class="span12">
		<div class="w-box">
			<div class="w-box-header">
				Turnover & Payment
			</div>
			 <div class="w-box-content cnt_a">
				<div class="row-fluid">
					<div class="span8">	
						<div class="control-group">
							<label class="control-label">Total turnover</label>
							<div class="controls">
							<div class="span4">
								<input type="text" name="turnover" readonly class="span12" value="{$quotedetails.turnover} &{$quotedetails.sales_suggested_currency};" />
							</div>
							<div class="span4">
								<label class="checkbox inline">
									<input type="checkbox" name="indicative_turnover" id="indicative_turnover" value="yes">Indicative Turnover
								</label>
							</div>
							</div>
						</div>
						<div class="control-group">
							<label class="control-label">Minimum turnover</label>
							<div class="controls">
							<div class="span4">
								<div id="normal-toggle-button">
                                    <input type="checkbox" value="1" name="mini_turn">
                                </div>
							</div>
							<div class="span4 hide" id="minimum_turnover">
								<input type="text" name="minimum_turnover" id="" class="span11 validate[required,custom[number],max[{$quotedetails.turnover}]]" value="" />&nbsp;&{$quotedetails.sales_suggested_currency};
							</div>
							</div>
						</div>
						<div class="control-group">
						<label class="control-label">Type of Payment</label>
						<div class="controls">
							<div class="span6">
								{html_options options=$typeofpayment selected=$client_info.payment_type name="paymenttype" class="paymenttype" } 
							</div>
						</div>
						</div>
					</div>
					<!-- <div class="pull-right">
						<div class="well span12 pull-center" style="padding-top:10px">
							<i class="icon-time"></i>
							<div>Expected End Date</div>
							<div style="font-weight:bold;text-align:center" id="repldate"></div>
						</div>
					</div> -->
					<div class="clearfix"></div>
					<div class="w-box">
						<div class="w-box-header displaysplit" style="display:none">
							Split per month
							{*	<a onclick="return changefield()"><i id="editcname" class="splashy-pencil" style="margin:0 5px 10px;cursor:pointer"></i> Modify</a> *}
						</div>
						<div class="replace">
						
						</div>
					</div>
				</div>
			 </div>
		</div>
	</div>
</div>
{if $missiondetails|@count > 0}
<div class="row-fluid">
	<div class="span12">
		<div class="w-box">
			<div class="w-box-header">
				Type of invoice
			</div>
			<div class="w-box-content cnt_a">
				<div class="row-fluid">
					<div class="span12">
						<table width="" class="table table-striped table-bordered" id="missionTable">
							<tr>
								<th>Mission</th>
								<th>Type</th>
								<th>Language</th>
								<th>Words</th>
								<th>Price/art</th>
								<th>Volume</th>
								<th>Tempo</th>
								<th>Invoice per</th>
								<th>Turnover</th>
								<th>History Quote BO</th>
								<th>History Quote FO</th>
							</tr>
						{foreach from=$missiondetails item="mission" name="missionDetails"}		
							<tr class="">
								<td>{$mission.product_type_converted}</td>
								<td>{$mission.product_type_name}</td>
								<td>
									{if $mission.product eq 'translation'}{$mission.language_source_converted}&nbsp;>&nbsp;{$mission.language_dest_converted}{else}{$mission.language_source_converted}
									{/if}
								</td>
								<td>{$mission.nb_words}</td>
								<td>{$mission.unit_price|zero_cut_t:2}&nbsp;&{$quotedetails.sales_suggested_currency};</td>
								<td>{$mission.volume}</td>
								<td>
								{if $mission.oneshot eq 'yes'} 
									One shot 
								{elseif  $mission.oneshot eq 'no'} 
								{assign var="_tempo_value" value=$mission.tempo}
								{assign var="_delivery_volume_option" value=$mission.delivery_volume_option}
								{assign var="_tempo_length_option" value=$mission.tempo_length_option}
									<span class="version-change pop_over" data-placement="top" data-original-title="Recurring" data-content="{$mission.volume_max} ( {$tempo_array.$_tempo_value}) articles {$volume_option_array.$_delivery_volume_option}  {$mission.tempo_length}  {$tempo_duration_array.$_tempo_length_option}" data-html="true">Recurring</span> 
								{else}
									-
								{/if}
								</td>
								<td>
									<select name="invoice_per[{$mission.identifier}]" class="select span10" style="width:90px">
										<option value='month' {if $mission.invoice_per == 'month'} selected="selected"{/if}>Month</option>
										<option value='mission' {if $mission.invoice_per == 'mission'} selected='selected' {/if}>Mission</option>
										<option value='delivery' {if $mission.invoice_per == 'delivery'} selected='selected'{/if}>Delivery</option>
									</select>
								</td>
								<td>
                                    {if $mission.free_mission eq 'yes'}Gratuit{else}{$mission.turnover|zero_cut_t:2}&nbsp;&{$quotedetails.sales_suggested_currency};{/if}
                                    <br />
                                    <label class="checkbox inline">
                                        <input type='checkbox' class="indicative" name="inductive[{$mission.identifier}]" {if $mission.indicative_turnover}checked='checked'{/if} value='1'/>
                                        Indicative
                                    </label>
                                    <input type='hidden' name="missiontable[{$mission.identifier}]" value='qm'/>

                                </td>
								<td>
									<input type='checkbox' class="indicative" name="history_bo[{$mission.identifier}]" {if $mission.history_bo eq 'yes'}checked='checked'{/if} value='yes'/>								
								</td>
								<td>
									<input type='checkbox' class="indicative" name="history_fo[{$mission.identifier}]" {if $mission.history_fo eq 'yes'}checked='checked'{/if} value='yes'/>								
								</td>
							</tr>
						{/foreach}
						</table>
					</div>
				</div>
				
			</div>
		</div>
	</div>
</div>
{/if}
<input type="hidden" name="quote_id" value="{$smarty.get.quote_id}" />
<input type="hidden" name="activetab" value="validate" />
<div class="row-fluid topset2">
	<div class="span12 pull-center">
		<div> You're about to request a legal and financial Validation </div>
		<button class="btn btn-primary topset2" onclick="return removeDisabled()" type="submit">Submit</button>
	</div>
</div>
</div>
</form>

<!-- View Info -->
<div class="modal container hide fade" style="top:0%" id="view_info">
    <div class="modal-header">        
		<button class="close" data-dismiss="modal">&times;</button>
        <h3>Info</h3>		
    </div>
    <div class="modal-body" style="min-height:480px">
		<button type="button" name="" class="btn btn-primary pull-right" data-toggle="modal" role="button" data-target="#edit_info">Edit(If superadmin)</button>
		<h2>Heading of Info</h2>
		<br/>
		<p style="font-size:15px">Brief Description of the info</p>
	</div>
	 <div class="modal-footer"></div>
</div>

<!-- Edit Info -->
<div class="modal container hide fade" style="top:0%" id="edit_info">
    <div class="modal-header">        
		<button class="close" data-dismiss="modal">&times;</button>
        <h3>Edit Info</h3>		
    </div>
    <div class="modal-body" style="min-height:480px">
		<form class="form-horizontal" action="" id="" method="POST">
			<div class="media mission-comment">
				<div class="control-group">
					<label class="control-label">Info Heading<span class="f_req">*</span></label>
					<div class="controls">
						<input type="text" name="title" class="span9 validate[required]" value="" />
					</div>
				</div>
			</div>
			<div class="media mission-comment">
				<div class="control-group">
					<label class="control-label">Description<span class="f_req">*</span></label>
					<div class="controls">
						<div class="media-body">
							<textarea name="comment" class="span9 validate[required]"></textarea>
						</div>
					</div>
				</div>
			</div>
			<div class="control-group">
					<div class="controls topset2 pull-center" style="margin-left:0">
						<button  class="btn" data-dismiss="modal" type="reset">Cancel</button>
						<button class="btn btn-primary" type="submit">Done</button>
					</div>
			</div>
		</form>
	</div>
	 <div class="modal-footer"></div>
</div>

{literal}
  <script src="/BO/theme/gebo/lib/toggle_buttons/jquery.toggle.buttons.js"></script>
	<script>
		peinfo = "no";
		$("#contractsource").change(function(){
			if($(this).val()=="Edit Place")
				$("#showepfiles").css("display","block");
			else
				$("#showepfiles").css("display","none");
		});
			
		
		function loadsplitvalues(date)
		{
				$.ajax({
				url:'/contractmission/get-split-month',
				type:'POST',
				data:{'quote_id':quote_id,'expected_launch_date':date,'turnover':turnover,'salesdtime':salesdtime,'salesdtimeo':salesdtimeo,"scurrency":scurrency,'pdays':prod_extra_launch_days,'peinfo':peinfo},
				beforeSend:function()
				{
					$(".displaysplit").css("display","block");
					$(".replace").html("<b style='text-align:center'>Please Wait Loading...</b>");
				},
				success:function(html){
					$(".replace").html(html);
					//$("#repldate").text($("#explaunchdate").val());
					final_end_date = $("#explaunchdate").val();
					if($("#enddate").val()=="")
					$("#enddate").val(final_end_date);
					/* $("#enddate").datetimepicker({ 
						format:'d/m/Y',
						formatDate:'d/m/Y',
						minDate:setdate
					});
					$("#enddate").val(setdate); */
				}
			});
		}

		if(setexpdate=='yes')
		{
			/*$("#expdate").datepicker({startDate:{/literal}"{$quotedetails.exp_end_stddate|date_format:'%d/%m/%Y'}"{literal}}).on("changeDate",function(e){
				var date = $(this).data('date');
				loadsplitvalues(date);
				
			/*});*/
		
		}
		else
		{
			/* $("#expdate").datepicker({format: 'dd/mm/yyyy',startDate:{/literal}"{$quotedetails.signed_at|date_format:'%d/%m/%Y'}"{literal}}).on("changeDate",function(e){
				var date = $(this).data('date');
				loadsplitvalues(date);
			}); */
		}
		
		/* $(".expenddate").datepicker({format: 'dd/mm/yyyy'}).on("changeDate",function(e){
				/* var date = $(this).data('date');
				loadsplitvalues(date); 
		}); */
			
		/* $("#sigdate").datepicker({format: 'dd/mm/yyyy',startDate:{/literal}"{$quotedetails.signed_at|date_format:'%d/%m/%Y'}"{literal}}).on("changeDate",function(e){
			
			if(setexpdate=='yes')
			{
				var newdate = $(this).data('date');
				splitval = newdate.split('/');
				reqdate = splitval[1]+"/"+splitval[0]+"/"+splitval[2];
				var startdate = new Date(Date.parse(reqdate));
				var expDate = startdate;
				expDate.setDate(startdate.getDate() + parseInt(prod_extra_launch_days));
				var month = expDate.getMonth()+1;
				if(month<10)
				month = '0'+month;
				var setdate = expDate.getDate()+"/"+month+"/"+expDate.getFullYear();
				$('#expdate').datepicker('setStartDate',setdate);
				loadsplitvalues(setdate);
				//$('#expdate').datepicker("setValue", new Date(2015,9,03));
				$("#launchdate").val(setdate);
			}
			else
			$('#expdate').datepicker('setStartDate',$(this).data('date'));
		});
		*/
		
		$(document).ready(function(){
			$("#createcontract").validationEngine({prettySelect : true,useSuffix: "_chzn"});
			if(exp_end_date)
			{
			loadsplitvalues(exp_end_date);
			//alert($('#expdate').val())
			//$('#expdate').datepicker('setStartDate',$('#expdate').data('date'));
			//$('#expdate').datepicker('setDate',new Date(2015,02,14));
			}
			else
				loadsplitvalues(signed_at);
			$('#normal-toggle-button').toggleButtons(
			{
			label:{enabled: "Yes",disabled: "No"},
			onChange: function () {
				if($("input[name='mini_turn']:checked").val()=="1")
					$("#minimum_turnover").show();
				else
					$("#minimum_turnover").hide();		
			}
			});
			
			$("#indicative_turnover").click(function(){
				if($("#indicative_turnover:checked").length)
				$(".indicative").addClass('validate[minCheckbox[1]]');
				else
				$(".indicative").removeClass('validate[minCheckbox[1]]');
			});
			
			/*tinymce initialization*/
			tinymce.init({
				selector: "#txtarea_sp",
				setup : function(ed)
				{
					ed.on('init', function() 
					{
						this.getDoc().body.style.fontSize = '14px';
						this.getDoc().body.style.fontFamily = 'arial';
					});
				},
				theme: "modern",
				statusbar:false,
				menubar: false,
				plugins: [
					 "advlist autolink link image lists charmap print preview hr anchor pagebreak spellchecker",
					 "searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking",
					 "save table contextmenu directionality emoticons template paste textcolor"
			   ],
			   content_css: "css/content.css",
			   toolbar: "bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link emoticons", 
			   style_formats: [
					{title: 'Bold text', inline: 'b'},
					{title: 'Red text', inline: 'span', styles: {color: '#ff0000'}},
					{title: 'Red header', block: 'h1', styles: {color: '#ff0000'}},
					{title: 'Example 1', inline: 'span', classes: 'example1'},
					{title: 'Example 2', inline: 'span', classes: 'example2'},
					{title: 'Table styles'},
					{title: 'Table row 1', selector: 'tr', classes: 'tablerow1'}
				]
			});
		})
			
	</script>
{/literal}