{if $opened eq '1'}

{if $contractmissionsopened|@count eq 0}


<center><strong>No Missions Found</strong></center>

{else}
<div id='missions-opened'></div>
{literal}
<script>

  var g = new JSGantt.GanttChart('g',document.getElementById('missions-opened'), 'day');
	var user_type = {/literal}"{$user_type}"{literal};
	g.setShowRes(0); // Show/Hide Responsible (0/1)
	g.setShowDur(0); // Show/Hide Duration (0/1)
	g.setShowComp(0); // Show/Hide % Complete(0/1)
    g.setCaptionType('None');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)

	 if(g) {
		{/literal}
		{foreach from=$contractmissionsopened item="missions" name="contractids" }
		{foreach from=$missions item="mission" name="contracts" }
		{literal} id = {/literal}{$smarty.foreach.contractids.iteration}{$smarty.foreach.contracts.iteration}{literal};{/literal}
		{literal} mname = {/literal}"{$mission.title|utf8_encode}"{literal};{/literal}
		{literal} lang = {/literal}"{$mission.lang|utf8_encode}"{literal};{/literal}
		{literal} edate = {/literal}"{$mission.edate}"{literal};{/literal}
		{literal} ldate = {/literal}"{$mission.ldate}"{literal};{/literal}
		{literal} pdone = {/literal}"{$mission.percentage}"{literal};{/literal}
		{literal} pm = {/literal}"{$mission.pmnew|utf8_encode}"{literal};{/literal}
		{literal} cmid = {/literal}"{$mission.cmid}"{literal};{/literal}
		{literal} cid = {/literal}"{$mission.cid}"{literal};{/literal}
		{literal} type = {/literal}"{$mission.type}"{literal};{/literal}
		{literal} index = {/literal}"{$mission.index}"{literal};{/literal}
		{literal}
		json = '{"lang":"'+lang+'","pdone":"'+pdone+'","pm":"'+pm+'","cmid":"'+cmid+'","type":"'+type+'","user_type":"'+user_type+'","cid":"'+cid+'","index":"'+index+'"}';
			g.AddTaskItem(new JSGantt.TaskItem(cmid,mname,ldate,edate,'2B78E4','',0,mname,0,0,0,0,'','Caption 1',json));
		{/literal}
		{/foreach}
		{/foreach}
		{literal}
		g.Draw();	
		g.DrawDependencies();
	  }
	  else
	  {
		alert("not defined");
	  }
	  
	  $(".uni_style").uniform();
	  $(document).ready(function() {
	  $(".tooltips").popover({ trigger: "manual" ,placement: 'top', html: true, animation:false})
	.on("mouseenter", function () {
		var _this = this;
		$(this).popover("show");
		$(".popover").on("mouseleave", function () {
			$(_this).popover('hide');
		});
	}).on("mouseleave", function () {
		var _this = this;
		setTimeout(function () {
			if (!$(".popover:hover").length) {
				$(_this).popover("hide");
			}
		}, 300);
	});
	});
	  
 </script>
 {/literal}
 {/if}
 {elseif $opened eq '2'}
 
 {if $contractmissionsfinished|@count gt 0}
	<div id='missions-finished'></div>
	{else}
	<center><strong>No Missions Found</strong></center>
	{/if}
 
 {literal}
 <script>
	var g2 = new JSGantt2.GanttChart('g2',document.getElementById('missions-finished'), 'day');

	g2.setShowRes(0); // Show/Hide Responsible (0/1)
	g2.setShowDur(0); // Show/Hide Duration (0/1)
	g2.setShowComp(0); // Show/Hide % Complete(0/1)
    g2.setCaptionType('None');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)

	  if(g2) {
		{/literal}
		{foreach from=$contractmissionsfinished item="missions" name="contractids" }
		{foreach from=$missions item="mission" name="contracts" }
		{literal} id = {/literal}{$smarty.foreach.contractids.iteration}{$smarty.foreach.contracts.iteration}{literal};{/literal}
		{literal} mname = {/literal}"{$mission.title|utf8_encode}"{literal};{/literal}
		{literal} lang = {/literal}"{$mission.lang}"{literal};{/literal}
		{literal} edate = {/literal}"{$mission.edate}"{literal};{/literal}
		{literal} ldate = {/literal}"{$mission.ldate}"{literal};{/literal}
		{literal} pdone = {/literal}"{$mission.percentage}"{literal};{/literal}
		{literal} pm = {/literal}"{$mission.pmnew|utf8_encode}"{literal};{/literal}
		{literal} cmid = {/literal}"{$mission.cmid}"{literal};{/literal}
		{literal} type = {/literal}"{$mission.type}"{literal};{/literal}
		{literal}
		json = '{"lang":"'+lang+'","pdone":"'+pdone+'","pm":"'+pm+'","cmid":"'+cmid+'","type":"'+type+'"}';
			g2.AddTaskItem(new JSGantt.TaskItem(cmid,mname,ldate,edate,'2B78E4','',0,mname,0,0,0,0,'','Caption 1',json));
		{/literal}
		{/foreach}
		{/foreach}
		{literal}
		g2.Draw();	
		g2.DrawDependencies();
	  }
	  else
	  {
		alert("not defined");
	  }
 </script>
 {/literal}
 
{elseif $opened eq '0'}
<div id='missions-toassign'></div>
{if $contractmissionstoassign|@count eq 0}
<center><strong>No Missions Found</strong></center>
{/if}
{literal}
<script>
var g1 = new JSGantt1.GanttChart('g1',document.getElementById('missions-toassign'), 'day');
	assigncount = 0;
	g1.setShowRes(0); // Show/Hide Responsible (0/1)
	g1.setShowDur(0); // Show/Hide Duration (0/1)
	g1.setShowComp(0); // Show/Hide % Complete(0/1)
    g1.setCaptionType('None');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)

	  if(g1) {
		{/literal}
		{foreach from=$contractmissionstoassign item="missions" name="contractids" }
		{foreach from=$missions item="mission" name="contracts" }
		{literal} id = {/literal}{$smarty.foreach.contractids.iteration}{$smarty.foreach.contracts.iteration}{literal};{/literal}
		{literal} mname = {/literal}"{$mission.title|utf8_encode}"{literal};{/literal}
		{literal} lang = {/literal}"{$mission.lang|utf8_encode}"{literal};{/literal}
		{literal} edate = {/literal}"{$mission.edate}"{literal};{/literal}
		{literal} edispdate = {/literal}"{$mission.edispdate}"{literal};{/literal}
		{literal} ldate = {/literal}"{$mission.ldate}"{literal};{/literal}
		{literal} pdone = {/literal}"0%"{literal};{/literal}
		{literal} pm = {/literal}"{$mission.pm|utf8_encode}"{literal};{/literal}
		{literal} turnover = {/literal}"{$mission.turnover|zero_cut_t:2}"{literal};{/literal}
		{literal} currency = {/literal}"{$mission.currency}"{literal};{/literal}
		{literal} type = {/literal}"{$mission.type}"{literal};{/literal}
		{literal} cid = {/literal}"{$mission.cid}"{literal};{/literal}
		{literal} cmid = {/literal}"{$mission.cmid}"{literal};{/literal}
		{literal} index = {/literal}"{$mission.index}"{literal};{/literal}
		{literal}
			json = '{"lang":"'+lang+'","turnover":"'+turnover+'","currency":"'+currency+'","edispdate":"'+edispdate+'","type":"'+type+'","index":"'+index+'","cid":"'+cid+'","cmid":"'+cmid+'"}';
			g1.AddTaskItem(new JSGantt1.TaskItem(id,mname,ldate,edate,'2B78E4','',0,mname,0,0,0,0,'','Caption 1',json));
			assigncount++;
		{/literal}
		{/foreach}
		{/foreach}
		{literal}
		g1.Draw();	
		g1.DrawDependencies();
	  }
	  else
	  {
		alert("not defined");
	  }
	if(assigncount>0)
	{
		$("#assigncount").text(assigncount);
		$("#assigncount").removeClass('hide');
	}
	else
	$("#assigncount").addClass('hide');
	  $(".uni_style2").uniform();
  </script>
 {/literal}
{else}
	{* Load All Tabs *}
	
	<div class="tab-pane {if $smarty.get.active eq ''} active {/if}" id="opened">
			{if $user_type=='superadmin' || $user_type=='techmanager' || $user_type=='seomanager' || $user_type=='prodmanager'}
				<div class="row-fluid">
				<select data-placeholder="All Sales" id="pm" class="cselect">
					<option value="">All PM</option>
					{foreach from=$pms item=user name=users}
					   <option value="{$user.identifier}" >{$user.first_name} {$user.last_name}</option>
					{/foreach}
				</select>
				
				<select data-placeholder="All Language" id="langauges" class="cselect">
					<option value="">All Language</option>
					{foreach from=$languages key=k item=v}
					   <option value="{$k}" >{$v}</option>
					{/foreach}
				</select>
				
				</div>
			{/if}
				<div class="row-fluid">
				<div class="missionsopenreplace" style="min-height:400px">
				{if $contractmissionsopened|@count eq 0}
					<center><strong>No Missions Found</strong></center>
				{else}
					<div id='missions-opened'></div>
				{/if}
				</div>
				</div>
	</div>
	{if $user_type=='superadmin' || $user_type=='techmanager' || $user_type=='seomanager' || $user_type=='prodmanager'}
	<div class="tab-pane {if $smarty.get.active eq 'validate'} active {/if}" id="validate">
				<div class="row-fluid">
					<select data-placeholder="All Language" id="assign_lang" class="cselect">
						<option value="">All Language</option>
						{foreach from=$languages key=k item=v}
						   <option value="{$k}" >{$v}</option>
						{/foreach}
					</select>
				</div>
				<div class="row-fluid">
				<div class="missionsassignreplace"  style="min-height:400px">
				{if $contractmissionstoassign|@count gt 0}
					<div id='missions-toassign'></div>
				{else}
					<center><strong>No Missions Found</strong></center>
				{/if}
				</div>
				</div>
	</div>
	{/if}
	<div class="tab-pane {if $smarty.get.active eq 'finished'} active {/if}" id="finished">
		{if $user_type=='superadmin' || $user_type=='techmanager' || $user_type=='seomanager' || $user_type=='prodmanager'}
			<div class="row-fluid">
				<select data-placeholder="All Sales" id="pm1" class="cselect">
					<option value="">All PM</option>
					{foreach from=$pms item=user name=users}
					   <option value="{$user.identifier}" >{$user.first_name} {$user.last_name}</option>
					{/foreach}
				</select>
				
				<select data-placeholder="All Language" id="langauges1" class="cselect">
					<option value="">All Language</option>
					{foreach from=$languages key=k item=v}
					   <option value="{$k}" >{$v}</option>
					{/foreach}
				</select>

			</div>
		{/if}
		
				<div class="row-fluid">
				<div class="missionsfinished"  style="min-height:400px">
				{if $contractmissionsfinished|@count gt 0}
				<div id='missions-finished'></div>
				{else}
				<center><strong>No Missions Found</strong></center>
				{/if}
				</div>
				</div>
				
	</div>
	{literal}
		<script type="text/javascript">
			var assigncount = 0;
			 var g = new JSGantt.GanttChart('g',document.getElementById('missions-opened'), 'day');
				var user_type = {/literal}"{$user_type}"{literal};
				g.setShowRes(0); // Show/Hide Responsible (0/1)
				g.setShowDur(0); // Show/Hide Duration (0/1)
				g.setShowComp(0); // Show/Hide % Complete(0/1)
				g.setCaptionType('None');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)

				 if(g) {
		{/literal}
		{foreach from=$contractmissionsopened item="missions" name="contractids" }
		{foreach from=$missions item="mission" name="contracts" }
		{literal} id = {/literal}{$smarty.foreach.contractids.iteration}{$smarty.foreach.contracts.iteration}{literal};{/literal}
		{literal} mname = {/literal}"{$mission.title|utf8_encode}"{literal};{/literal}
		{literal} lang = {/literal}"{$mission.lang|utf8_encode}"{literal};{/literal}
		{literal} edate = {/literal}"{$mission.edate}"{literal};{/literal}
		{literal} ldate = {/literal}"{$mission.ldate}"{literal};{/literal}
		{literal} pdone = {/literal}"{$mission.percentage}"{literal};{/literal}
		{literal} pm = {/literal}"{$mission.pmnew|utf8_encode}"{literal};{/literal}
		{literal} cmid = {/literal}"{$mission.cmid}"{literal};{/literal}
		{literal} cid = {/literal}"{$mission.cid}"{literal};{/literal}
		{literal} type = {/literal}"{$mission.type}"{literal};{/literal}
		{literal} index = {/literal}"{$mission.index}"{literal};{/literal}
		{literal}
		json = '{"lang":"'+lang+'","pdone":"'+pdone+'","pm":"'+pm+'","cmid":"'+cmid+'","type":"'+type+'","user_type":"'+user_type+'","cid":"'+cid+'","index":"'+index+'"}';
			g.AddTaskItem(new JSGantt.TaskItem(cmid,mname,ldate,edate,'2B78E4','',0,mname,0,0,0,0,'','Caption 1',json));
		{/literal}
		{/foreach}
		{/foreach}
		{literal}
		g.Draw();	
		g.DrawDependencies();
	  }
	  else
	  {
		alert("not defined");
	  }
	  
			 {/literal}
			 {if $user_type=='superadmin' || $user_type=='techmanager' || $user_type=='seomanager' || $user_type=='prodmanager'}
					{literal}
				var g1 = new JSGantt1.GanttChart('g1',document.getElementById('missions-toassign'), 'day');

				g1.setShowRes(0); // Show/Hide Responsible (0/1)
				g1.setShowDur(0); // Show/Hide Duration (0/1)
				g1.setShowComp(0); // Show/Hide % Complete(0/1)
				g1.setCaptionType('None');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)

				  if(g1) {
					{/literal}
					{foreach from=$contractmissionstoassign item="missions" name="contractids" }
					{foreach from=$missions item="mission" name="contracts" }
					{literal} id = {/literal}{$smarty.foreach.contractids.iteration}{$smarty.foreach.contracts.iteration}{literal};{/literal}
					{literal} mname = {/literal}"{$mission.title|utf8_encode}"{literal};{/literal}
					{literal} lang = {/literal}"{$mission.lang|utf8_encode}"{literal};{/literal}
					{literal} edate = {/literal}"{$mission.edate}"{literal};{/literal}
					{literal} edispdate = {/literal}"{$mission.edispdate}"{literal};{/literal}
					{literal} ldate = {/literal}"{$mission.ldate}"{literal};{/literal}
					{literal} pdone = {/literal}"0%"{literal};{/literal}
					{literal} pm = {/literal}"{$mission.pm|utf8_encode}"{literal};{/literal}
					{literal} turnover = {/literal}"{$mission.turnover|zero_cut_t:2}"{literal};{/literal}
					{literal} currency = {/literal}"{$mission.currency}"{literal};{/literal}
					{literal} type = {/literal}"{$mission.type}"{literal};{/literal}
					{literal} cid = {/literal}"{$mission.cid}"{literal};{/literal}
					{literal} cmid = {/literal}"{$mission.cmid}"{literal};{/literal}
					{literal} index = {/literal}"{$mission.index}"{literal};{/literal}
					{literal}
					json = '{"lang":"'+lang+'","turnover":"'+turnover+'","currency":"'+currency+'","edispdate":"'+edispdate+'","type":"'+type+'","index":"'+index+'","cid":"'+cid+'","cmid":"'+cmid+'"}';
						g1.AddTaskItem(new JSGantt1.TaskItem(id,mname,ldate,edate,'2B78E4','',0,mname,0,0,0,0,'','Caption 1',json));
						assigncount++;
					{/literal}
					{/foreach}
					{/foreach}
					{literal}
					g1.Draw();	
					g1.DrawDependencies();
				  }
				  else
				  {
					alert("not defined");
				  }
				   {/literal}
			 {/if}
				{literal}
				
				var g2 = new JSGantt2.GanttChart('g2',document.getElementById('missions-finished'), 'day');

				g2.setShowRes(0); // Show/Hide Responsible (0/1)
				g2.setShowDur(0); // Show/Hide Duration (0/1)
				g2.setShowComp(0); // Show/Hide % Complete(0/1)
				g2.setCaptionType('None');  // Set to Show Caption (None,Caption,Resource,Duration,Complete)

				  if(g2) {
					{/literal}
					{foreach from=$contractmissionsfinished item="missions" name="contractids" }
					{foreach from=$missions item="mission" name="contracts" }
					{literal} id = {/literal}{$smarty.foreach.contractids.iteration}{$smarty.foreach.contracts.iteration}{literal};{/literal}
					{literal} mname = {/literal}"{$mission.title|utf8_encode}"{literal};{/literal}
					{literal} lang = {/literal}"{$mission.lang|utf8_encode}"{literal};{/literal}
					{literal} edate = {/literal}"{$mission.edate}"{literal};{/literal}
					{literal} ldate = {/literal}"{$mission.ldate}"{literal};{/literal}
					{literal} pdone = {/literal}"{$mission.percentage}"{literal};{/literal}
					{literal} pm = {/literal}"{$mission.pmnew|utf8_encode}"{literal};{/literal}
					{literal} cmid = {/literal}"{$mission.cmid}"{literal};{/literal}
					{literal} type = {/literal}"{$mission.type}"{literal};{/literal}
					{literal}
					json = '{"lang":"'+lang+'","pdone":"'+pdone+'","pm":"'+pm+'","cmid":"'+cmid+'","type":"'+type+'"}';
						g2.AddTaskItem(new JSGantt.TaskItem(cmid,mname,ldate,edate,'2B78E4','',0,mname,0,0,0,0,'','Caption 1',json));
					{/literal}
					{/foreach}
					{/foreach}
					{literal}
					g2.Draw();	
					g2.DrawDependencies();
				  }
				  else
				  {
					alert("not defined");
				  }
				  
				 $(document).ready(function() {
	$(".uni_style").uniform();
	$(".uni_style2").uniform();
	/* $('.tooltips').tooltipster(
	 {
		contentAsHTML: true,
		theme: 'tooltipster-noir',
		position: 'bottom',
		positionTracker:true,
		interactive: true,
	 });  */
		$(".tooltips").popover({ trigger: "manual" ,placement: 'top', html: true, animation:false})
	.on("mouseenter", function () {
		var _this = this;
		$(this).popover("show");
		$(".popover").on("mouseleave", function () {
			$(_this).popover('hide');
		});
	}).on("mouseleave", function () {
		var _this = this;
		setTimeout(function () {
			if (!$(".popover:hover").length) {
				$(_this).popover("hide");
			}
		}, 300);
	});
	$(".cselect").chosen({allow_single_deselect:false,disable_search: true});
	if(assigncount>0)
	{
		$("#assigncount").text(assigncount);
		$("#assigncount").removeClass('hide');
	}
	else
	$("#assigncount").addClass('hide');
	
	$(".nav-tabs li").removeClass('active');
	$(".assignopened").addClass('active');
	
	 $('#pm').on('change', function(evt, params) {
		$(".missionsopenreplace").html('<center><b>Please wait Loading...</b></center>');
		$.post('/contractmission/loadmissions/',{'pmid':$("#pm").val(),'opened':1,'lang':$("#langauges").val(),'cid':$("#allcontract").val()},function(data){$(".missionsopenreplace").html(data)})
	  });

	  $('#pm1').on('change', function(evt, params) {
		$(".missionsfinished").html('<center><b>Please wait Loading...</b></center>');
		$.post('/contractmission/loadmissions/',{'pmid':$("#pm1").val(),'opened':2,'lang':$("#langauges1").val(),'cid':$("#allcontract").val()},function(data){$(".missionsfinished").html(data)})
	  });
	  
	  $('#langauges').on('change', function(evt, params) {
	  $(".missionsopenreplace").html('<center><b>Please wait Loading...</b></center>');
		$.post('/contractmission/loadmissions/',{'pmid':$("#pm").val(),'opened':1,'lang':$("#langauges").val(),'cid':$("#allcontract").val()},function(data){$(".missionsopenreplace").html(data)})
	  });
	  
	   $('#langauges1').on('change', function(evt, params) {
	  $(".missionsfinished").html('<center><b>Please wait Loading...</b></center>');
		$.post('/contractmission/loadmissions/',{'pmid':$("#pm1").val(),'opened':2,'lang':$("#langauges1").val(),'cid':$("#allcontract").val()},function(data){$(".missionsfinished").html(data)})
	  });
	  
	  $('#assign_lang').on('change', function(evt, params) {
	  $(".missionsassignreplace").html('<center><b>Please wait Loading...</b></center>');
		$.post('/contractmission/loadmissions/',{'pmid':'','opened':0,'lang':$("#assign_lang").val(),'cid':$("#allcontract").val()},function(data){$(".missionsassignreplace").html(data)})
	  });
	
	
});
		</script>
	{/literal}
{/if}