{literal}
<link href="/BO/theme/gebo/css/jquery.datetimepicker.css" rel="stylesheet">
<script src="/BO/theme/gebo/js/jquery.datetimepicker.js" type="text/javascript" charset="utf-8"></script>
<script type="text/javascript">	
$(document).ready(function() {
		$('#clientList').dataTable({
            "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            "sPaginationType": "bootstrap",
            "aaSorting": [[ 3, "desc" ]],
			"iDisplayLength":50,
            "aoColumns": [
		{ "sType": "string" },
                { "sType": "html" },
                { "sType": "string" },
                { "sType": "eu_date" },
                { "sType": "string" },
		//{ "sType": "string" },
		//{ "sType": "string" },
                { "sType": "string" }
            ]
        });
		
		$("#ong_search").click(function () {
				$("#search_block").toggle();
		});
		
		/*search form elements*/
		
		$("#created_user").chosen({ allow_single_deselect: true,search_contains: true});
		$("#premium").chosen({ allow_single_deselect: true,search_contains: true,disable_search: true});
		$("#online").chosen({ allow_single_deselect: true,search_contains: true,disable_search: true});		
		$("#ctype").chosen({ allow_single_deselect: true,search_contains: true,disable_search: true});		
		
		$('#startdate').datetimepicker({
			format:'Y-m-d',
			lang:'fr',
			timepicker:false
			/* onShow:function( ct ){
				this.setOptions({
					maxDate:get_date($('#enddate').val())?get_date($('#enddate').val()):false,formatDate:'Y-m-d',minDate:0
				})
			} */
		});

		$('#enddate').datetimepicker({
			format:'Y-m-d',
			lang:'fr',
			timepicker:false,
			onShow:function( ct ){
				this.setOptions({
					minDate:get_date($('#startdate').val())?get_date($('#startdate').val()):false,formatDate:'Y-m-d'
				})
			}
		});

});

function get_date(input) {
	if(input == '') {
		return false;
	}
	else {
		// Split the date, divider is '/'
		var parts = input.match(/(\d+)/g);
		return parts[0]+'-'+parts[1]+'-'+parts[2];
	}
}
</script>
<style>
	#clientList .image {
    margin: 0;
}
#clientList .image {
    float: left;
    height: 50px;
    margin: 0;
    text-align: center;
    width: 50px;
}
.imgtxtpos
{
	float:left;
	margin:15px 10px;
}
</style>
{/literal}
<div class="row-fluid">
	<div class="span12">
    	<h1 class="heading pull-left">Premium Client List <a class="btn btn-gebo1" id="ong_search">Filtrer</a></h1>
		<div class="pull-right">
		<a class="btn btn-primary" href="/quote/create-client?submenuId=ML13-SL1">Create Client</a>
		</div>
	</div>
</div>	
<div class="row-fluid">	
	<div class="{if !$smarty.get.search}hide{/if} well clearfix" id="search_block">
		<div class="row-fluid">
			<form action={$smarty.server.REQUEST_URI} method="get" id="searchform" name="searchform" >				
				 <input type="hidden" id="submenuId" name="submenuId"  value="{$submenuId}"/>
				<div class="row-fluid">
					<span class="span2">
						<select name="created_user"  class="span12" id="created_user" data-placeholder="Creator ">
							<option value=""></option>
							{html_options  options=$client_creators  selected=$smarty.get.created_user}	
						</select>	
					</span>
					<span class="span2">
						<div class="input-append date">
							<input class="span10 validate[required]" value="{$smarty.get.startdate}" type="text" name="startdate" id="startdate" placeholder="From"/><span class="add-on"><i class="splashy-calendar_day_up"></i></span>
						</div>
					</span>
					<span class="span2">
						<div class="input-append date">
							<input class="span10 validate[required]" value="{$smarty.get.enddate}" type="text" name="enddate" id="enddate" placeholder="To"/><span class="add-on"><i class="splashy-calendar_day_up"></i></span>
						</div>	
					</span>
					<!--<span class="span2">
						<select id="premium" class="span12" name="premium" data-placeholder="Premium ">
							<option value=""></option>
							<option value="yes" {if $smarty.get.premium eq 'yes' }selected{/if}>OUI </option>
                            <option value="no" {if $smarty.get.premium eq 'no'}selected{/if}>NON</option>
						</select>	
					</span>
					<span class="span1">
						<select id="online" class="span12" name="online" data-placeholder="Online">
							<option value=""></option>
							<option value="yes" {if $smarty.get.online eq 'yes' }selected{/if}>OUI </option>
                            <option value="no" {if $smarty.get.online eq 'no'}selected{/if}>NON</option>						
						</select>	
					</span>-->
					<span class="span2">
						<select id="ctype" class="span12" name="ctype" data-placeholder="Type de client">
							<option value=""></option>
							<option value="p" {if $smarty.get.ctype eq 'p' }selected{/if}>Prospect</option>
                            <option value="c" {if $smarty.get.ctype eq 'c'}selected{/if}>Client</option>						
						</select>	
					</span>
					<span class="span1">
						<button class="btn btn-danger pull-center" id="search" name="search" type="submit" value="search" >Search</button>
					</span>
				</div>
			</form>		  
		</div>
	</div>
	<div class="clearfix"></div>
	<div class="row-fluid">
		<table class="table table-bordered table-hover table_vam" id="clientList" >
			<thead>
				<tr>
				   <th>Code client</th>
				   <th>Company name</th>
				   <th>Created by</th>
				   <th>Created at</th>
				   <th>First contact</th>
				   <!--<th>ONLINE</th>
				   <th>PREMIUM</th> -->
				   <th>Action</th>
				</tr>
			</thead>
			<tbody>
			{foreach from=$clients item=client}
				<tr>
					<td>
					{$client.client_code}
					</td>
					<td>
					{if $client.created_by!='FO' && $client.contactname}
						<a href="/quote/create-client?uaction=view&client_id={$client.identifier}&submenuId=ML13-SL1">
					{else}
						<a href="/user/client-edit?submenuId=ML10-SL2&tab=viewclient&userId={$client.identifier}">		
					{/if}		
					
					{if $client.company_name}
						<img src="{$fo_path}profiles/clients/logos/{$client.identifier}/{$client.identifier}_global.png?12345" class="image rd_30" alt="{$client.company_name}">
						<span class="imgtxtpos">{$client.company_name}</span>	
					{elseif $client.first_name}	
						<img src="{$fo_path}profiles/clients/logos/{$client.identifier}/logo.jpg?123" class="image rd_30" alt="{$client.first_name}">
						<span class="imgtxtpos">{$client.first_name}</span>
					{else}			
						<img src="{$fo_path}profiles/clients/logos/{$client.identifier}/logo.jpg?123" class="image rd_30" alt="{$client.email}">
						<span class="imgtxtpos">{$client.email}</span>		
					{/if}		
						</a>			
					</td>
					<td>
						<a class="hint--right" data-hint="{$client.created_by}">
							<img src="{$fo_path}/profiles/bo/{$client.created_user}/logo.jpg?123" class="image rd_30" alt="{$client.created_by}">
						</a>
						{* <span class="imgtxtpos">{$client.created_by}</span> *}
					</td>
					<td>{$client.created_at|date_format:"%d/%m/%Y"}</td>
					<td>
						{if $client.contactname}
							{$client.contactname}
						{else}		
							-			
						{/if}		
					</td>		
					<!--<td>		
						{if $client.online_count gt 0}	
							OUI			
						{else}			
							NON			
						{/if}		
					</td>	
					<td>	
						{if $client.premium_count gt 0}		
							OUI				
						{else}		
							NON		
						{/if}		
					</td>-->
					<td>
					{if $client.created_by!='FO' && $client.contactname}						
						<a href="/quote/create-client?uaction=view&client_id={$client.identifier}&submenuId=ML13-SL1" class="btn">View</a>
						<a href="/quote/create-client?uaction=edit&client_id={$client.identifier}&submenuId=ML13-SL1" class="btn btn-primary">Edit</a>	
					{else}						
						<a href="/user/client-edit?submenuId=ML10-SL2&tab=viewclient&userId={$client.identifier}" class="btn">View</a>						
						<a href="/user/client-edit?submenuId=ML10-SL2&tab=editclient&userId={$client.identifier}" class="btn btn-primary">Edit</a>					
					{/if}	
					</td>
				</tr>
			{/foreach}
			</tbody>
		</table>
	</div>
</div>
