<div class="row-fluid">
	<div class="span12">		
		<form class="form-horizontal form_validation_ttip" id="estimate_sign_form" action="/quote/save-estimate-sign-details" method="POST">
			<input type="hidden" id="quote_id" name="quote_id" value="{$smarty.get.quote_id}">
			<fieldset>
				<div class="control-group formSep">
					<label class="control-label">% estim&eacute; de signature :</label>
					<div class="controls">
						<select name="estimate_sign_percentage" id="estimate_sign_percentage" class="span5" style="margin-top: -10px;">					
							<option value="20" {if $quote.estimate_sign_percentage eq '20'} selected {/if}>20</option>
							<option value="40" {if $quote.estimate_sign_percentage eq '40'} selected {/if}>40</option>
							<option value="60" {if $quote.estimate_sign_percentage eq '60'} selected {/if}>60</option>
							<option value="80" {if $quote.estimate_sign_percentage eq '80'} selected {/if}>80</option>
							
						</select>						
					</div>
				</div>
				<div class="control-group formSep">
					<label class="control-label">Estimation de la date de signature :</label>
					<div class="controls">
						<div class="input-append date">
							<input class="span12 validate[required]" value="{$quote.estimate_sign_date}" type="text" name="estimate_sign_date" id="estimate_sign_date"/><span class="add-on"><i class="splashy-calendar_day_up"></i></span>
						</div>							
					</div>
				</div>				
				<div class="control-group formSep">
					<label class="control-label">Commentaire(s) :</label>
					<div class="controls">
						<textarea name="estimate_sign_comments" id="estimate_sign_comments" class="span12">{$quote.estimate_sign_comments|utf8_encode}</textarea>	
					</div>
				</div>					
				<div class="control-group">
					<div class="controls">
						<button class="btn btn-gebo" name="estimate_sign" type="submit">Valider</button>
						<button class="btn" data-dismiss="modal" id="cancel">Annuler</button>
					</div>
				</div>
			</fieldset>
		</form>
	</div>
</div>
{literal}
<link href="/BO/theme/gebo/css/jquery.datetimepicker.css" rel="stylesheet">
<script src="/BO/theme/gebo/js/jquery.datetimepicker.js" type="text/javascript" charset="utf-8"></script>
<script language="javascript">
	$(document).ready(function(){
			$("#estimate_sign_form").validationEngine();
			//estimate sign date 
		$('#estimate_sign_date').datetimepicker({
			format:'Y-m-d',
			lang:'fr',
			timepicker:false
		});
	});		
</script>
{/literal}