{if $quoteDetails|@count gt 0}
	{foreach from=$quoteDetails item=quote name="quote"}
		<table>
			<tr>
				<td align="left" colspan="9"><img src="/BO/theme/gebo/img/edit-place.png"></td>
			</tr>
		</table>	
		<table>
			<tr><td colspan="9"></td></tr>
		</table>	
		<table border="1" width="100%">
			<tr>
				<td colspan="2">{$quote.client_code}</td>
				<td align="center" style="font-size:22px;" colspan="5"><b>BON DE COMMANDE ou DEVIS</b></td>
				<td colspan="2"></td>
			</tr>
			<tr>
				<td style="font-size:16px;" colspan="2"><b>EDIT-PLACE SAS Groupe WEBEDIA</b></td>				
				<td colspan="5" align="center"></td>				
				<td style="font-size:16px;" colspan="2"><b>{$quote.company_name}<b></td>
			</tr>
			
			<tr><td colspan="9"></td></tr>
			
			<tr>
				<td colspan="2">2 rue Paul Vaillant Couturier</td>
				<td colspan="5"></td>
				<td colspan="2">{$quote.address|strip_tags}</td>
			</tr>
			<tr>
				<td colspan="2">92300</td>
				<td colspan="5"></td>
				<td>{$quote.zipcode}</td>  <td>{$quote.city|lower|ucfirst}</td>
			</tr>
			<tr>
				<td colspan="2">LEVALLOIS PERRET</td>
				<td colspan="5"></td>
				<td colspan="2">{$quote.country_name|lower|ucfirst}</td>
			</tr>
			<tr>
				<td colspan="2">France</td>
				<td colspan="5"></td>
				<td colspan="2">{$quote.client_phone}</td>
			</tr>
			<tr><td colspan="9"></td></tr>
			
			<tr>
				<td colspan="2"><u>Contact commercial</u></td>
				<td colspan="5"></td>
				<td colspan="2"><u>Contact commercial</u></td>
			</tr>
			<tr>
				<td colspan="2">{$quote.quote_user_name}</td>
				<td colspan="5"></td>
				<td colspan="2">{$quote.client_contact_name}</td>
			</tr>
			<tr>
				<td colspan="2"><a href="mailto:{$quote.email}">{$quote.email}</a></td>
				<td colspan="5"></td>
				<td colspan="2"><a href="mailto:{$quote.client_contact_email}">{$quote.client_contact_email}</a></td>
			</tr>	
			<tr>
				<td colspan="2">&nbsp;{$quote.phone_number}</td>
				<td colspan="5"></td>
				<td colspan="2">&nbsp;{$quote.client_contact_phone}</td>
			</tr>
			<tr><td colspan="9"></td></tr>
			<tr>
				<td colspan="2"><u>Contact Finance</u></td>
				<td colspan="5"></td>
				<td>Date de d&eacute;but</td>
				<td></td>
			</tr>
			<tr>
				<td colspan="2"><a href="mailto:comptabilite@edit-place.com">comptabilite@edit-place.com</a></td>
				<td colspan="5"></td>
				<td>Date de fin</td>
				<td></td>
			</tr>
			<tr>
				<td colspan="2">00 33 1 85 08 40 14</td>
				<td colspan="5"></td>
				<td>Dur&eacute;e</td>
				<td>{$quote.total_duration}{if $quote.final_mission_length_option eq 'days'} Jours {elseif $quote.final_mission_length_option eq 'hours'} Hours{/if}</td>
			</tr>		
		</table>
		<table>
			<tr><td colspan="9"></td></tr>
			<tr><td colspan="9"></td></tr>
		</table>
		<table border="1" width="100%">
			<tr>
				<td bgcolor="#F2F2F2"><b>Ref</b></td>
				<td bgcolor="#F2F2F2" colspan="3"><b>Prestation</b></td>
				<td bgcolor="#F2F2F2"><b>PRODUIT</b></td>
				<td bgcolor="#F2F2F2"><b>Taille (mots)</b></td>
				<td bgcolor="#F2F2F2"><b>Quantit&eacute;</b></td>
				<td bgcolor="#F2F2F2"><b>Prix U HT&{$quote.sales_suggested_currency};</b></td>
				<td bgcolor="#F2F2F2"><b>TOTAL</b></td>
			</tr>	
			{if $quote.mission_details|@count gt 0}
				{assign var=ref_number value=0}
				{foreach from=$quote.mission_details item=mission name="misson"}							
					{assign var=ms_index value=$smarty.foreach.misson.index+1}	
					{if $mission.before_prod eq 'yes'}{assign var="before_prod" value="yes}{/if}					
					{if $mission.package neq 'user'}						
						{assign var=ref_number value=$ref_number+1}
						<tr>	
							<td align="left">{$ref_number}</td>							
								{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy'}
									<td colspan="3">{$mission.product_name} en {$mission.language_source_name|utf8_decode} {if $mission.before_prod eq 'yes'}*{/if}</td>
								{else}
									<td colspan="3">{$mission.product_name} en {$mission.language_source_name|utf8_decode} {if $mission.product eq 'translation'} - {$mission.language_dest_name|utf8_decode}{/if} {if $mission.before_prod eq 'yes'}*{/if}</td>
								{/if}							
							
								{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy'}
									<td>{$mission.product_name}</td>
								{else}
									<td>{$mission.product_type_name}</td>
								{/if}
							
							<td align="right">{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy'}-{else}{$mission.nb_words}{/if}</td>
							<td align="right">{$mission.volume}</td>
							<td align="right">{if $currency=='usd'}{if $mission.free_mission eq 'yes'}OFFERT in &{$quote.sales_suggested_currency}; {$mission.unit_price|num_format:2} {else} &{$quote.sales_suggested_currency}; {$mission.unit_price|num_format:2} {/if}{else}{if $mission.free_mission eq 'yes'}OFFERT in {$mission.unit_price|num_format:2} &{$quote.sales_suggested_currency};{else}{$mission.unit_price|num_format:2} &{$quote.sales_suggested_currency};{/if}{/if}</td>
							<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$mission.turnover|num_format:2}{else}{$mission.turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
						</tr>
						{if $mission.package eq 'team'}
							{assign var=ref_number value=$ref_number+1}
							<tr>
								<td align="left">{$ref_number}</td>								
									{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy' }
										{assign var="missionType" value=$mission.product_name}
										<td colspan="3">{$mission.product_name} en {$mission.language_source_name|utf8_decode} - Staffing - Pack de {$mission.team_packs} CVs</td>
									{else}
										{assign var="missionType" value=$mission.product_type_name}
										<td colspan="3">{$mission.product_name} en {$mission.language_source_name|utf8_decode} {if $mission.product eq 'translation'}- {$mission.language_dest_name|utf8_decode}{/if} - Staffing - Pack de {$mission.team_packs} CVs</td>
									{/if}								
								<td>{$missionType}</td>
								<td align="right">{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy'}-{else}{$mission.nb_words}{/if}</td>
								<td align="right">{$mission.team_packs}</td>
								<td align="right">{if $currency=='usd'}{if $mission.free_mission eq 'yes'}OFFERT in &{$quote.sales_suggested_currency}; {$mission.team_fee|num_format:2} {else} &{$quote.sales_suggested_currency}; {$mission.team_fee|num_format:2}{/if}{else}{if $mission.free_mission eq 'yes'}OFFERT in {$mission.team_fee|num_format:2} &{$quote.sales_suggested_currency};{else}{$mission.team_fee|num_format:2} &{$quote.sales_suggested_currency};{/if}{/if}</td>
								<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$mission.team_package_turnover|num_format:2}{else}{$mission.team_package_turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
							</tr>
						{/if}
					{elseif $mission.package eq 'user'}
						{assign var=ref_number value=$ref_number+1}
						<tr>
							<td align="left">{$ref_number}</td>
							
								{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy' }
									{assign var="missionType" value=$mission.product_name}
									<td colspan="3">{$mission.product_name} en {$mission.language_source_name|utf8_decode} - Nombre de profils {$mission.required_writes}</td>
								{else}
									{assign var="missionType" value=$mission.product_type_name}
									<td colspan="3">{$mission.product_name} en {$mission.language_source_name|utf8_decode} {if $mission.product eq 'translation'}- {$mission.language_dest_name|utf8_decode}{/if} - Nombre de profils {$mission.required_writes}</td>
									
								{/if}							
							<td>{$missionType}</td>
							<td align="right">{if $mission.product eq 'smo_audit' || $mission.product eq 'seo_audit' || $mission.product eq 'content_strategy'}-{else}{$mission.nb_words}{/if}</td>
							<td align="right">{$mission.required_writes}</td>
							<td align="right">{if $currency=='usd'}{if $mission.free_mission eq 'yes'}OFFERT in  &{$quote.sales_suggested_currency};  {$mission.user_fee|num_format:2}{else} &{$quote.sales_suggested_currency}; {$mission.user_fee|num_format:2} {/if}{else}{if $mission.free_mission eq 'yes'}OFFERT in {$mission.user_fee|num_format:2} &{$quote.sales_suggested_currency};{else}{$mission.user_fee|num_format:2} &{$quote.sales_suggested_currency};{/if}{/if}</td>
							<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$mission.user_package_turnover|num_format:2}{else}{$mission.user_package_turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
						</tr>
					{/if}
				{/foreach}
			{/if}
			{if $quote.tech_mission_details|@count gt 0}
				{foreach from=$quote.tech_mission_details item=tmission name="tmission"}					
				{if $tmission.before_prod eq 'yes'}{assign var="before_prod" value="yes}{/if}					
					{if $tmission.package neq 'user'}						
						{assign var=ref_number value=$ref_number+1}
						<tr>	
							<td align="left">{$ref_number}</td>
							<td colspan="3">{$tmission.title}{if $tmission.before_prod eq 'yes'}*{/if}</td>
							<td>Mission technique</td>
							<td align="right">-</td>
							<td align="right">{$tmission.volume}</td>
							<td align="right">{if $currency=='usd'}{if $tmission.free_mission eq 'yes'}OFFERT in &{$quote.sales_suggested_currency};  {$tmission.unit_price|num_format:2} {else}&{$quote.sales_suggested_currency}; {$tmission.unit_price|num_format:2}{/if}{else}{if $tmission.free_mission eq 'yes'}OFFERT in {$tmission.unit_price|num_format:2} &{$quote.sales_suggested_currency};{else}{$tmission.unit_price|num_format:2} &{$quote.sales_suggested_currency};{/if}{/if}</td>
							<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$tmission.turnover|num_format:2} {else}{$tmission.turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
						</tr>						
						{if $tmission.package eq 'team'}
							{assign var=ref_number value=$ref_number+1}							
							<tr>
								<td align="left">{$ref_number}</td>
								<td colspan="3">{$tmission.title} - Pack de {$tmission.team_packs} CVs</td>
								<td>Mission technique</td>
								<td align="right">-</td>
								<td align="right">{$tmission.team_packs}</td>
								<td align="right">{if $currency=='usd'}{if $tmission.free_mission eq 'yes'}OFFERT in &{$quote.sales_suggested_currency}; {$tmission.team_fee|num_format:2} {else}&{$quote.sales_suggested_currency}; {$tmission.team_fee|num_format:2} {/if}{else}{if $tmission.free_mission eq 'yes'}OFFERT in {$tmission.team_fee|num_format:2} &{$quote.sales_suggested_currency};{else}{$tmission.team_fee|num_format:2} &{$quote.sales_suggested_currency};{/if}{/if}</td>
								<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$tmission.team_package_turnover|num_format:2}{else}{$tmission.team_package_turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>									
							</tr>
						{/if}
					{elseif $tmission.package eq 'user'}
						{assign var=ref_number value=$ref_number+1}	
						<tr>
							<td align="left">{$ref_number}</td>
							<td colspan="3">{$tmission.title} - Nombre de profils {$tmission.required_writes}</td>
							<td>Mission technique</td>
							<td align="right">-</td>
							<td align="right">{$tmission.required_writes}</td>
							<td align="right">{if $currency=='usd'}{if $tmission.free_mission eq 'yes'}OFFERT in &{$quote.sales_suggested_currency}; {$tmission.user_fee|num_format:2} {else} &{$quote.sales_suggested_currency}; {$tmission.user_fee|num_format:2}{/if}{else}{if $tmission.free_mission eq 'yes'}OFFERT in {$tmission.user_fee|num_format:2} &{$quote.sales_suggested_currency};{else}{$tmission.user_fee|num_format:2} &{$quote.sales_suggested_currency};{/if}{/if}</td>
							<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$tmission.user_package_turnover|num_format:2}{else}	{$tmission.user_package_turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
						</tr>
					{/if}
				{/foreach}
			{/if}
			<tr><td colspan="9"></td></tr>
			
			<tr>
				<td colspan="2">Acompte 30%</td>
				<td colspan="2">non</td>
				<td>D&eacute;lai de mise en place</td>
				<td>{$quote.total_staff_setup_time} {if $quote.final_mission_length_option eq 'days'} Jours {elseif $quote.final_mission_length_option eq 'hours'} Hours{/if} ouvr&eacute;s</td>
				<td></td>
				<td><b>TOTAL HT</td></td>
				<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$quote.final_turnover|num_format:2}{else}{$quote.final_turnover|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
			</tr>
			<tr>
				<td colspan="2">D&eacute;lai de r&egrave;glement</td>
				<td colspan="2">30 jours date de facture</td>
				<td>D&eacute;lai de livraison</td>
				<td>{$quote.total_delivery_time}{if $quote.final_mission_length_option eq 'days'} Jours {elseif $quote.final_mission_length_option eq 'hours'} Hours{/if}</td>
				<td></td>
				<td><b>TVA</td></td>
				<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$quote.tva|num_format:2}{else}{$quote.tva|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
			</tr>
			<tr>
				<td colspan="7"></td>
				<td><b>TOTAL TTC</td></td>
				<td align="right">{if $currency=='usd'}&{$quote.sales_suggested_currency}; {$quote.total_htc|num_format:2}{else}{$quote.total_htc|num_format:2} &{$quote.sales_suggested_currency};{/if}</td>
			</tr>
		</table>			
		{if $before_prod eq 'yes'}
			<table>
				<tr>
					<td colspan="9">*Cette mission doit &ecirc;tre termin&eacute;e  pour pouvoir  lancer la production</td>
				</tr>
			</table>
		{/if}
		<table>
			<tr>
				<td align="center" bgcolor="#F2F2F2" colspan="9">Commentaires</td>
			</tr>
			<tr><td colspan="9"></td></tr>
			<tr><td colspan="9" align="center" rowspan="3" height="50px">INSERER VOS COMMENTAIRES ICI: </td></tr>
			<tr><td colspan="9"></td></tr>
			<tr><td colspan="9"></td></tr>
			<tr><td colspan="9"></td></tr>
		</table>
		<table><tr><td colspan="9"></td></tr></table>
		<table><tr><td colspan="9"></td></tr></table>
		<table><tr><td colspan="9"></td></tr></table>
		<table>
			<tr>
				<td align="center" colspan="9">Ce devis est valide pendant 21 jours &agrave; compter du {$quote.updated_at|date_format:"%d/%m/%Y"}</td>
			</tr>
			<tr>
				<td align="center" colspan="9">Avant de pouvoir d&eacute;marrer toute mission les CGS ainsi que le BDC doivent imp&eacute;rativement etre sign&eacute;s, tamponn&eacute;s et dat&eacute;s.</td>
			</tr>
		</table>
		<table><tr><td colspan="9"></td></tr></table>
		<table><tr><td colspan="9"></td></tr></table>
		<table>
			<tr>
				<td colspan="2"><b>Signature Edit-Place (Tampon)</b></td>
				<td colspan="5"></td>
				<td colspan="2"><b>Signature Client (Tampon)</b></td>
			</tr>
			<tr>
				<td colspan="2">Lu et approuv&eacute;</td>
				<td colspan="5"></td>
				<td colspan="2">Lu et approuv&eacute;</td>
			</tr>
			<tr>
				<td colspan="2"><b>{$smarty.now|date_format:"%d/%m/%Y"}</b></td>
				<td colspan="5"></td>
				<td colspan="2"></td>
			</tr>				
		</table>
		<table><tr><td colspan="9"></td></tr></table>
		<table><tr><td colspan="9"></td></tr></table>
		<table><tr><td colspan="9"></td></tr></table>
		<table><tr><td colspan="9"></td></tr></table>
		<table>
				
				<tr><td colspan="9" align="center" style="font-size:10px;">EDIT-PLACE.COM SAS &ndash; Groupe WEBEDIA &ndash; 2 rue Paul Vaillant Couturier &ndash;  CS 60102 &ndash; 92532 Levallois-Perret Cedex &ndash; T&eacute;l. +33 1 85 08 40 13</td></tr>
				<tr><td colspan="9" align="center" style="font-size:10px;">S.A.S AU CAPITAL DE 36 531,20&euro; &ndash; RCS NANTERRE  521 287 193 &ndash; N&deg;INTRACOMMUNAUTAIRE : FR 43521287193</td></tr>						
		</table>
	{/foreach}
{/if}
