{literal}
<link rel="stylesheet" href="/BO/theme/gebo/js/validation-engine/validationEngine.jquery.css" type="text/css"/>
<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine-fr.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/gebo/js/jquery.MultiFileQuote.js" type="text/javascript" charset="utf-8"></script>
<script src="/BO/theme/gebo/js/validation-engine/jquery.validationEngine.js" type="text/javascript" charset="utf-8"></script>
<script language="JavaScript" type="text/javascript" src="/BO/theme/gebo/js/countdown.js"></script>
<script src="/BO/theme/gebo/lib/datepicker/bootstrap-timepicker.min.js"></script>
<script language="javascript">
$(document).ready(function() {

	
	$(".uni_style").uniform();
	$('#tech_missions textarea').css('height','60px');
	$('#tech_missions textarea').autosize();
	
	//more info popup
	$("#quote_more_info").click(function(){
		$("#quote_more_info_pop").modal('show');
		$("#quote_more_info_pop").removeClass( "hide" ).addClass("in");
	});
	
	
	$("#quote_save,#quote_validate").click(function(){
		if($("#challenge_quote").validationEngine('validate'))
		{
			$("#quote_updated_pop").modal('show');
			$("#quote_updated_pop").removeClass( "hide" ).addClass("in");
		}	
	});
	
	$("#skip_btn").click(function(){
		$("#quote_skip_pop").modal('show');
		$("#quote_skip_pop").removeClass( "hide" ).addClass("in");
	});
	
	
	$("#challenge_btn").click(function(){
		$("#tech_challenge").modal('show');
		$("#tech_challenge").removeClass( "hide" ).addClass("in");
	});	
	
	
	//validation
	$("#challenge_quote").validationEngine();	
	$('#quote_updated_comments').attr('data-prompt-position','topLeft');
	$('#quote_updated_comments').data('promptPosition','topLeft');
	
	$("[id^=delivery_time_]").spinner({min:1});
	$("[id^=delivery_option_]").chosen({ allow_single_deselect: false,search_contains: true});	
	
	//calculate changed in quote price percentage
	fnCalculateQuote();
	
	//scroll to tech misson
	$( '.searchbyid' ).on('click', function(event) {
		event.preventDefault();
		var target = "#" + $(this).data('target');
		$('html, body').animate({
			scrollTop: $(target).offset().top
		}, 2000);
	});
	
	//close mission
	$("[id^=mission_close_]").live('click', function() {
			var DivId = $(this).attr('id');			
			var parentDiv=$(this).parents("div:eq(3)").attr('id');
			
			var mission_identifier=$(this).attr('rel');		
			var	quote_id=$("#quote_id").val();		
			if(!mission_identifier)
			{
				//alert($("[id^=tech_mission_]").size());
				if($("[id^=tech_mission_]").size()>1)
				{
					$("#"+parentDiv).remove();
					if($("[id^=tech_mission_]").size()==1)
					{	
						$("#addmore_mission_link").click();
					}
				}					
					fnCalculateQuote();
			}	
			else
			{	
				smoke.confirm("Souhaitez-vous vraiment supprimer cette mission tech du devis?",function(e){
					if (e)
					{
						if($("[id^=tech_mission_]").size()>2)
						{
							$("#"+parentDiv).html('<center><img alt="" src="/BO/theme/gebo/img/ajax_loader.gif"> Suppression de cette mission tech... </center>');
							ajaxTechMissionUpdate(quote_id,mission_identifier,parentDiv,'');
							fnCalculateQuote();
						}	
						else
						{
							$("#"+parentDiv).html('<center><img alt="" src="/BO/theme/gebo/img/ajax_loader.gif"> Suppression de cette mission tech... </center>');
							ajaxTechMissionUpdate(quote_id,mission_identifier,parentDiv,'final');	
							
						}
					}
					else
					{
						return false;
					}
				});				
			}	
			techIncDec();	
		});	

	function techIncDec()
	{
		var mid =1;
		$("[id^=box_title_]").each(function(){
			$(this).text('Tech Mission '+mid++);
		})
	}
		
	//Adding tech missions
	var mission_cnt=1;
	$("[id^=tech_mission_]" ).each(function(z) {
			mission_cnt=z++;
	});
	//Add more mission
	$("#addmore_mission_link").click(function() {
		
		var cloned =$("#tech_missions");	
		var duplicate_id;		
		
		$("[id^=tech_mission_]" ).each(function(m) {
			var div_id = $(this).attr('id');
			var div_numbers=div_id.split("_");
			duplicate_id=div_numbers[2];
			duplicate_id=0;
			if(duplicate_id)
			return false;
			//break;
		});		
		//alert(mission_cnt+duplicate_id);
		$('#delivery_time_'+duplicate_id).spinner( "destroy" );
		
		$("#tech_mission_"+duplicate_id).clone().attr('id', 'tech_mission_'+(++mission_cnt) ).appendTo( cloned );	
		$('#tech_mission_'+mission_cnt).show();
		$('#tech_mission_'+mission_cnt+' #box_title_'+duplicate_id).attr('id','box_title_'+mission_cnt); //changing mission tilte id
		$('#box_title_'+mission_cnt).text('Tech Mission '+mission_cnt); //changing mission tilte		
		$('#tech_mission_'+mission_cnt+' #mission_close_'+duplicate_id).attr('id','mission_close_'+mission_cnt); //chaning id of close button
		$('#mission_close_'+mission_cnt).show();
		$('#mission_close_'+mission_cnt).attr('rel','');
				
			
		//Product select box
		$('#tech_mission_'+mission_cnt+' #delivery_option_'+duplicate_id).attr('id','delivery_option_'+mission_cnt); //changing product id		
		
		//before prod checkbox
		$('#tech_mission_'+mission_cnt+' #before_prod_'+duplicate_id).attr('id','before_prod_'+mission_cnt); 
		$('#tech_mission_'+mission_cnt+' input[name="before_prod_'+duplicate_id+'"]').attr('name','before_prod_'+mission_cnt);
		$(".uni_style").uniform();
		
		$("#delivery_option_"+mission_cnt).removeClass("chzn-done" ).addClass("");	
		$("#tech_mission_"+mission_cnt+ " .chzn-container").remove(); 		
		
		$("#delivery_option_"+mission_cnt).chosen({ allow_single_deselect: false,search_contains: true});	//updating selected value
		$("#delivery_option_"+mission_cnt).val('');
		$("#delivery_option_"+mission_cnt).trigger("liszt:updated");		
		
		
		$('#tech_mission_'+mission_cnt+' input[name="mission_title[]"]').attr('id','mission_title_'+mission_cnt);
		$('#tech_mission_'+mission_cnt+' input[name="mission_cost[]"]').attr('id','mission_cost_'+mission_cnt);
		$('#tech_mission_'+mission_cnt+' input[name="delivery_time[]"]').attr('id','delivery_time_'+mission_cnt);		
		$('#tech_mission_'+mission_cnt+' #comments_'+duplicate_id).attr('id','comments_'+mission_cnt);		
		$('#tech_mission_'+mission_cnt+' input[name="tech_documents_'+duplicate_id+'"]').attr('id','tech_documents_'+mission_cnt);
		$('#tech_mission_'+mission_cnt+' input[name="tech_documents_'+duplicate_id+'"]').attr('name','tech_documents_'+mission_cnt+'[]');						
		clearChildren(document.getElementById('tech_mission_'+mission_cnt));
		
		$('#delivery_time_'+mission_cnt).val(3);
		$("[id^=delivery_time_]").spinner({min:1});
		$("#tech_documents_"+mission_cnt).MultiFile();
				
		$('#tech_mission_'+mission_cnt+' textarea').css('height','60px');
		$('#tech_mission_'+mission_cnt+' textarea').autosize();
		
		techIncDec();
	});		
	
	////////////to show the timer of tech time line///////
      var cur_date={/literal}{$smarty.now}{literal};
      var js_date=(new Date().getTime())/ 1000;
      var diff_date=Math.floor(js_date-cur_date);
     //////////show timer//////////
	$("[id^=time_]").each(function(i) {
		var article=$(this).attr('id').split("_");
		var ts=article[2];
		$("#time_"+article[1]+"_"+article[2]).countdown({
			timestamp   : ts,
            diff_date  : diff_date,
			callback    : function(days, hours, minutes, seconds){
				var message = "";
				if(days >0 )message += days + " jours"  +", ";
				if(hours >0 )message += hours + " h" +",";
				if(minutes >0 )message += minutes + " mns"+ ", ";
				message += seconds + " s";
				$("#text_"+article[1]+"_"+article[2]).html(message);
				if(days==0 && hours==0 && minutes==0 && seconds==0)
				{
					//window.location.reload();
				}
			}
		});
	});	
	
});
/** ajax function to delete super client contact data**/
function ajaxTechMissionUpdate(quote_id,mission_identifier,divid,last)
{
        var target_page = "/quote/update-quote-techmission?quote_id="+quote_id+"&mission_identifier="+mission_identifier;
//alert(target_page)		;
		$.post(target_page, function(data){					
				//alert(data);
				sleep(4000);
				$("#"+divid).remove();
				if(last=='final')
					location.reload();
			});
}

//calculate Quote price changes
function fnCalculateQuote()
{
	var quotePrice=parseFloat($("#sales_suggested_price").val());
	var added_price=0;
	$("[id^=mission_cost_]" ).each(function(z) {
		var missionPrice=parseFloat($(this).val());
		if(isNaN(missionPrice))
			missionPrice=0;
		added_price=added_price+missionPrice;
	});
	
	var changedPercentage=parseFloat((added_price/quotePrice)*100);
	changedPercentage = new Number(changedPercentage);
	changedPercentage=changedPercentage.toPrecision(2);
	var change_text= '+'+changedPercentage+'%';
	if(changedPercentage>0 && quotePrice>0)
	{
		$("#percentage_change").text(change_text);	
		$("#percentage_change").show();
	}
	else	
		$("#percentage_change").hide();
	
}

function changeNames()
{
	var i = 1;
	$("#tech_missions").find('.MultiFile-wrap').each(function(){
		$(this).find(":file").each(function(){
			$(this).attr("name","tech_documents_"+i+"[]");
		})
		
		$(this).find(":text").each(function(){
			$(this).attr("name","document_name"+i+"[]");
		})
		i++;
	})
}

$(document).on("click",".deletetech",function(){
	var id_identifier = $(this).attr("rel");
		if(confirm("Are you sure? Want to delete this File"))
		{
			//$(this).closest(".topset2").remove();
			var thisvar =$(this).closest('.onsuccessrep');
			thisvar.html("Please Wait Deleting File.");
			$.post("/quote-test/delete-document-tech",{"identifier":id_identifier},function(result){
					thisvar.html(result);
			}); 
		}	
	});


function removeDisabled(){	setTimeout(function(){$(".MultiFile-applied").removeAttr("disabled");}, 1000);	}


</script>
<style type="text/css">
.splashy-documents
{
top:3px;
}
.deletetech
{
	color:#000;
	margin: 0 5px;
	cursor: pointer;
}
</style>
{/literal}
<div class="row-fluid">    
	<div class="span12">
		<div class="row-fluid">
			<ul id="validate_wizard-titles" class="stepy-titles clearfix">
				<li id="validate_wizard-title-0"><div>Creation</div><span class="stepNb">1</span></li>
				<li id="validate_wizard-title-1" class="current-step"><div>TECH review</div><span class="stepNb">2</span></li>
				<li id="validate_wizard-title-2"><div>SEO review</div><span class="stepNb">3</span></li>
				<li id="validate_wizard-title-3"><div>Prod review</div><span class="stepNb">4</span></li>
				<li id="validate_wizard-title-4"><div>Validation</div><span class="stepNb">5</span></li>
			</ul>
		</div>
		{if $quoteDetails|@count gt 0}
		{foreach from=$quoteDetails item=quote name="quote"}
			<h1 class="heading topset2">{$quote.title}
			
			{if $quote.tec_review eq 'challenged' || $quote.tec_review eq 'validated'}
				{if $quote.tech_timeline_stamp < $smarty.now}<label class="pull-right label label-warning"> Retard</label>{/if}
				<span id="time_{$quote.identifier}_{$quote.tech_timeline_stamp}" class="alert alert-danger pull-right quote-timer">
					<i class="icon-time"></i> <span id="text_{$quote.identifier}_{$quote.tech_timeline_stamp}"></span>
				</span>
			{/if}	
				
			</h1>			
				{if $quote.tec_review eq 'challenged' || $quote.tec_review eq 'validated'}
					<div class="alert alert-success">
						<a data-dismiss="alert" class="close">&times;</a>
						<b>Votre challenge tech &agrave; bien &eacute;t&eacute; pris en compte! Merci de compl&eacute;ter votre devis tech dans la dur&eacute;e impartie</b>
					</div>	
				{else}
					<div class="alert alert-info">
						<a data-dismiss="alert" class="close">&times;</a>
						<b>{$quote.quote_user_name} vous &agrave; envoy&eacute; un devis. Merci de le challenger ou de passer votre tour en <a class="searchbyid"data-target="challenge_quote">cliquant</a> ci-dessous</b>
					</div>	
				{/if}	
			
			<div class="row-fluid">			
				<div class="span9">
					<div class="w-box">
						<div class="w-box-header">Commentaire g&eacute;n&eacute;ral</div>
						<div class="w-box-content  cnt_a">
							<div class="media">
								<a class="pull-left imgframe">
									<img width="60px" src="{$fo_path}/profiles/bo/{$quote.quote_by}/logo.jpg" class="media-object">
								</a>
								<div class="media-body">
									<h4 class="media-heading">								
										<a>{$quote.quote_user_name}</a> {$quote.comment_time}
									</h4>								
									<span>{$quote.sales_comment}</span>
								</div>
							</div>
						</div>	
					</div>	
					<div class="w-box">
						<div class="w-box-header">Liste des missions</div>
						<div class="w-box-content  cnt_a">
						{if $quote.mission_details|@count gt 0}
						{foreach from=$quote.mission_details item=mission name="misson"}
							{assign var=gn_index value=$smarty.foreach.misson.index}
							{assign var=ms_index value=$smarty.foreach.misson.index+1}	
							<div class="row-fluid">	
								<div class="mission-details">
									{if $mission.previousMissionDetails|@count eq 0 && $quote.version gt 1 }
										<div class="new-mission-product">Mission {$ms_index} : {$mission.product_name} <label class="label label-warning">Mission ajout&eacute;e</label></div>
									{else}
										<div class="prod-mission-product"> Mission {$ms_index} : {$mission.product_name}</div>
									{/if}
									<table class="table mission-table">
										<tr>
											<th style="width:30%">LANGUE</th>
											<th style="width:30%">PRODUIT</th>
											<th style="width:20%">VOLUME</th>
											<th style="width:20%">NB MOTS</th>
										</tr>
										<tr class="misson-details-text">
											<td>
											{if $mission.language_difference eq 'yes'}
												<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$mission.language_versions|escape|stripslashes}" data-html="true"> <i class="splashy-documents"></i> 
											{/if}	
												{if $mission.product eq 'translation'}															
													{$mission.language_source_name} > 	{$mission.language_dest_name} 
												{else}
													{$mission.language_source_name}
												{/if}
											{if $mission.language_difference eq 'yes'}
												</span>
											{/if}	
											</td>
										<td>
											{if $mission.product_type_difference eq 'yes'}
												<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$mission.product_type_versions|escape|stripslashes}" data-html="true"> <i class="splashy-documents"></i> 
											{/if}														
												{if $mission.product_type_name} 
													{$mission.product_type_name} {if $mission.product_type eq 'autre'}<br/>({$mission.product_type_other}){/if}
												{else}
													{$mission.product_name}
												{/if}
											{if $mission.product_type_difference eq 'yes'}
												</span>
											{/if}	
										</td>
										<td>
											{if $mission.volume_difference eq 'yes'}
												<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$mission.volume_versions|escape|stripslashes}" data-html="true"> <i class="splashy-documents"></i>
											{/if}
												{$mission.volume}
											{if $mission.volume_difference eq 'yes'}
												</span>
											{/if}	
												
										</td>										
										<td>
											{if $mission.nb_words_difference eq 'yes'}
												<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$mission.nb_words_versions|escape|stripslashes}" data-html="true"> <i class="splashy-documents"></i> 
											{/if}
												{$mission.nb_words}
											{if $mission.nb_words_difference eq 'yes'}
												</span>
											{/if}
										</td>
										</tr>	
									</table>									
									<!--Tempo details-->
									{include file="gebo/quote/tempo-details.phtml"}
									
									{if $mission.comments}
									<div class="media mission-comment">
										<a class="pull-left imgframe">
											<img width="60px" src="{$fo_path}/profiles/bo/{$quote.quote_by}/logo.jpg" class="media-object">
										</a>
										<div class="media-body">
											<h4 class="media-heading">								
												<a>{$quote.quote_user_name}</a> {$mission.comment_time}
											</h4>								
											<span>{$mission.comments|stripslashes|htmlentities|nl2br}</span>
										</div>
									</div>
									{/if}
								</div>
							</div>	
						{/foreach}
						{/if}
						<!--Deleted Quote missions-->
						{if $quote.deletedMissionVersions|@count gt 0}
						{foreach from=$quote.deletedMissionVersions item=dmission name="dmisson"}
							{assign var=gn_index value=$smarty.foreach.dmission.index}
							{assign var=ms_index value=$smarty.foreach.dmission.index+1}	
							<div class="row-fluid">	
								<div class="mission-details">
									<div class="delete-mission-product">{$dmission.product_name} <label class="label">Mission supprim&eacute;e</label></div>
									
									<table class="table mission-table">
										<tr>
											<th style="width:30%">LANGUE</th>
											<th style="width:30%">PRODUIT</th>
											<th style="width:20%">VOLUME</th>
											<th style="width:20%">NB MOTS</th>
										</tr>
										<tr class="misson-details-text">
											<td>
												{if $dmission.product eq 'translation'}
													{$dmission.language_source_name} > 	{$dmission.language_dest_name} 
												{else}
													{$dmission.language_source_name}
												{/if}											
											</td>
										<td>
											{if $dmission.product_type_name} 
												{$dmission.product_type_name}
											{else}
												{$dmission.product_name}
											{/if}												
										</td>
										<td>{$dmission.volume}</td>										
										<td>{$dmission.nb_words}</td>
										</tr>	
									</table>
									{if $dmission.comments}
									<div class="media mission-comment">
										<a class="pull-left imgframe">
											<img width="60px" src="{$fo_path}/profiles/bo/{$quote.quote_by}/logo.jpg" class="media-object">
										</a>
										<div class="media-body">
											<h4 class="media-heading">								
												<a>{$quote.quote_user_name}</a> {$dmission.comment_time}
											</h4>								
											<span>{$dmission.comments|stripslashes|htmlentities|nl2br}</span>
										</div>
									</div>
									{/if}
								</div>
							</div>	
						{/foreach}
						{/if}
						<h2 class="heading">&Eacute;changes de mails avec le client</h2>
							<textarea rows="10" disabled class="span12">{$quote.client_email_text}</textarea>
							<div class="row-fluid">
								<div class="span3">Documents &agrave; t&eacute;l&eacute;charger :</div>
							</div>	
							<div class="row-fluid">
								{$quote.related_files}
							</div>
						</div>						
					</div>	
					<form action="/quote/save-tech-review" method="POST" id="challenge_quote" enctype="multipart/form-data">
						<input type="hidden" name="quote_id" id="quote_id" value="{$quote.identifier}">
						<input type="hidden" name="currency" value="{$quote.sales_suggested_currency}">
						<div class="formSep topset2">
						{if $quote.tec_review eq 'challenged' || $quote.tec_review eq 'validated'}
							<div class="w-box">
								<div class="w-box-header">Tech Mission</div>
								<div class="w-box-content  cnt_a">
									<div class="row-fluid" id="tech_missions">
										{if $techMissionDetails|@count gt 0}
										{foreach from=$techMissionDetails item=mission name="tmisson"}
										{assign var=gn_index value=$smarty.foreach.tmisson.index}
										{assign var=ms_index value=$smarty.foreach.tmisson.index+1}		
										<div class="row-fluid" id="tech_mission_{$ms_index}">	
										<input type="hidden" name="tech_mission_id[]" value="{$mission.identifier}">
											<div class="mission-details">												
												<div class="mission-tech-product">
													<span id="box_title_{$ms_index}">{$mission.title} {if $mission.previousMissionDetails|@count eq 0 && $quote.version gt 1 }<label class="label label-warning">New</label> {/if}</span>
													
													<div class="pull-right">												
													<a class="btn close-tech" rel="{$mission.identifier}" id="mission_close_{$ms_index}">&times;</a>
														 												
													</div>											
												</div>		
												<table class="table mission-table">
													<tr>
														<th style="width:33%">Mission</th>
														<th style="width:33%">D&eacute;lai de livraison</th>
														<th style="width:33">Co&ucirc;t (&{$quote.sales_suggested_currency };)</th>
													</tr>
													<tr class="misson-details-text">
														<td>
															{if $mission.title_difference eq 'yes'}
																<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$mission.title_versions|escape|stripslashes}" data-html="true"> <i class="splashy-documents"></i></span>
															{/if}
															<input type="text" name="mission_title[]" id="mission_title_{$ms_index}" value="{$mission.title}" class="span10 validate[required]" placeholder="enter a mission">
														</td>
														<td>
															<div class="span2">																
																{if $mission.mission_length_difference eq 'yes'}
																	<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$mission.mission_length_versions|escape|stripslashes}" data-html="true"> <i class="splashy-documents"></i> </span>
																{/if}
															</div>
															<div class="span4">
																<input type="text" id="delivery_time_{$ms_index}" name="delivery_time[]" class="span12 validate[required]" value="{$mission.delivery_time}"/>
															</div>
															<div class="span4">
																<select name="delivery_option[]" id="delivery_option_{$ms_index}">					
																	<option value="days" {if $mission.delivery_option eq 'days'} selected{/if} >Jours</option>
																	<option value="hours" {if $mission.delivery_option eq 'hours'} selected{/if}>Hours</option>									
																</select>
															</div>	
														</td>
														<td>
															{if $mission.cost_difference eq 'yes'}
																<span class="version-change pop_over" data-placement="top" data-original-title="Historique devis" data-content="{$mission.price_versions|escape|stripslashes}" data-html="true"> <i class="splashy-documents"></i></span>
															{/if}
															<input type="text" id="mission_cost_{$ms_index}" name="mission_cost[]" class="span4 validate[required,custom[number]]" value="{$mission.cost|zero_cut:2}" onkeyup="fnCalculateQuote();"/>
														</td>														
													</tr>														
												</table>
												<div class="row-fluid" style="margin-left: 15px;">
													<div class="span12">
														<input type="checkbox" class="uni_style" name="before_prod_{$ms_index}" id="before_prod_{$ms_index}" {if $mission.before_prod eq 'yes'} checked {/if}
														> Doit &ecirc;tre r&eacute;alis&eacute; avant de lancer la mission
													</div>	
												</div>
												<div class="media mission-comment">
													<a class="pull-left imgframe">
														<img width="60px" src="{$fo_path}/profiles/bo/{$mission.created_by}/logo.jpg" class="media-object">
													</a>
													<div class="media-body">														
														<textarea name="comments[]" rows="2" placeholder="ins&eacute;rer un commentaire" id="comments_{$ms_index}" class="span12">{$mission.comments}</textarea>
													</div>
												</div>	
												<div class="row-fluid topset2">	
													<div class="span12" style="padding:0 10px;">
														<input type="file" name="tech_documents_{$ms_index}[]" accept="doc|xls|zip|docx|xlsx" class="multi" id="tech_documents_{$ms_index}"/>
													<div class="onsuccessrep">
														{$mission.files}
													</div>
													</div>
												</div>
											</div>
										</div>									
										{/foreach}	
										{else}	
										<div class="row-fluid" id="tech_mission_1">
											<div class="mission-details">
												<div class="mission-tech-product"><span id="box_title_1">Tech mission 1</span>
													<div class="pull-right">												
														<a class="btn close-tech" rel="" id="mission_close_1">&times;</a>
													</div>											
												</div>
												<table class="table mission-table">
													<tr>
														<th style="width:33%">Mission</th>
														<th style="width:33%">D&eacute;lai de livraison</th>
														<th style="width:33">Co&ucirc;t (&{$quote.sales_suggested_currency };)</th>
													</tr>
													<tr class="misson-details-text">
														<td>
															<input type="text" name="mission_title[]" id="mission_title_1" class="span11 validate[required]" placeholder="enter a mission">
														</td>
														<td>
															<div class="span2"></div>
															<div class="span4">
																<input type="text" id="delivery_time_1" name="delivery_time[]" class="span12 validate[required]" value="3"/>
															</div>
															<div class="span4">
																<select name="delivery_option[]" id="delivery_option_1">					
																	<option value="days">Jours</option>
																	<option value="hours">Hours</option>									
																</select>
															</div>	
														</td>
														<td>
															<input type="text" id="mission_cost_1" name="mission_cost[]" class="span4 validate[required,custom[number]]" onkeyup="fnCalculateQuote();"/>
														</td>														
													</tr>														
												</table>
												<div class="row-fluid" style="margin-left: 15px;">
													<div class="span12">
														<input type="checkbox" class="uni_style" name="before_prod_1" id="before_prod_1"> Doit &ecirc;tre r&eacute;alis&eacute; avant de lancer la mission
													</div>	
												</div>
												<div class="media mission-comment">
													<a class="pull-left imgframe">
														<img width="60px" src="{$fo_path}/profiles/bo/{$userId}/logo.jpg" class="media-object">
													</a>
													<div class="media-body">														
														<textarea name="comments[]" rows="2" placeholder="ins&eacute;rer un commentaire" id="comments_1" class=" span12"></textarea>
													</div>												
												</div>
												<div class="row-fluid topset2">	
													<div class="span12" style="padding:0 10px;">
														<input type="file" name="tech_documents_1[]" accept="doc|xls|zip|docx|xlsx" class="multi" id="tech_documents_1"/>
													</div>
												</div>
											</div>	
										</div>	
										{/if}	
									</div>								
								</div>	
								<div class="row-fluid formSep ">	
									<div id="addmore_mission_link"><a class="btn topset2"><i class="icon-plus"></i>Ajouter nouvelle mission</a></div> 
								</div>
							</div>
							{/if}
							<div class="row-fluid">
								<div class="span4"></div>
								<div class="span6">
									{if $quote.tec_review eq 'not_done'}
										{if $quote.quote_type eq 'normal'}
											<button type="button" id="skip_btn" name="review_skip" class="btn">Skip</button>
										{/if}
										<button type="button" id="challenge_btn" name="challenge" class="btn btn-primary">Challenge</button>
									{elseif $quote.tec_review eq 'challenged' || $quote.tec_review eq 'validated'}
										{if $quote.tech_challenge eq 'yes'}<button type="button" id="challenge_btn" name="challenge" class="btn btn-primary">Challenge</button>{/if}
										{if $quote.tec_review eq 'challenged'}
											<button type="submit" name="review_save" onclick="changeNames(); removeDisabled()" class="btn btn-success">Sauvegarder</button>
											{if $show_validate eq 'yes'}
												<button type="submit" name="review_validate" onclick="changeNames(); removeDisabled()" class="btn btn-primary">Valider</button>
											{/if}	
										{elseif $quote.tec_review eq 'validated'}
											<button type="button" id="quote_save" name="review_save" class="btn btn-success">Sauvegarder</button>
											{if $show_validate eq 'yes'}
												<button type="button" id="quote_validate" name="review_validate" class="btn btn-primary">Valider</button>
											{/if}	
										{/if}	
									{/if}
								<!--	<button type="button" id="quote_more_info" name="quote_more_info" class="btn btn-info">Besoin de pr&eacute;cisions </button> -->
									
								</div>
							</div>
						</div>
						<!--popup to show quote updated in edit mode-->
						{if $quote.tec_review eq 'validated'}
						<div class="modal hide fade" id="quote_updated_pop" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
							<div class="modal-header">
								<button class="close" data-dismiss="modal" >&times;</button>
								<h3>Mise &agrave; jour</h3>
							</div>
							<div class="modal-body">
								<section>
									<div class="row-fluid">
										<div class="media">
											<br>											
											<br>
											<a class="pull-left imgframe">
												<img width="60px" src="{$fo_path}/profiles/bo/{$userId}/logo.jpg" class="media-object">
											</a>
											<div class="media-body">														
												<textarea name="quote_updated_comments" placeholder="Tell team what you have changed and SEND" id="quote_updated_comments" class="span12 validate[required]"></textarea>
											</div>												
										</div>
									</div>	
									<div class="row-fluid">
										<div class="span12">
											<button type="button" class="btn" data-dismiss="modal" aria-hidden="true">Annuler</button>
											<button type="submit" name="review_validate" onclick="changeNames(); removeDisabled()" class="btn btn-primary">Valider</button>
										</div>
									</div>										
								</section>
							</div>
							<div class="modal-footer">
							</div>
						</div>
						{/if}
					</form>	
				</div>
				<div class="span3">
					<aside>
						<div class="aside-bg">							
							<div class="aside-block" id="selected-client">
								<div class="editor-container">
									<h2 class="heading">Info client</h2>
									<img title="{$quote.company_name}" src="{$fo_path}/profiles/clients/logos/{$quote.client_id}/{$quote.client_id}_global.png?12345">
									<p class="editor-name"><a href="/quote/create-client?uaction=view&client_id={$quote.client_id}&submenuId=ML13-SL1" target="_blank">{$quote.company_name}</a></p>
									<p class="editor-info">
									CA info : {$quote.ca_number|zero_cut_t:2} euros<br>
									Cat&eacute;gorie : {$quote.category_name}<br><br>
									<label class="label label-info">Sites internet</label><br>
									{foreach from=$quote.websites item=site}
										<a href="{$site}">{$site|domain_url}</a> <br/>
									{/foreach}
									</p>
								</div>
							</div>
							<div class="aside-block" id="selected-bouser">
								<div class="editor-container">
									<h2 class="heading">Devis r&eacute;alis&eacute; par</h2>
									<img title="{$quote.quote_user_name}" src="{$fo_path}/profiles/bo/{$quote.quote_by}/{$quote.quote_by}_p.jpg">
									<p class="editor-name">{$quote.quote_user_name}</p>
									<p class="editor-info">
									T&eacute;l : {$quote.phone_number}<br>
									Email : <a href="mailto:{$quote.email}">{$quote.email}</a><br><br>
									</p>									
								</div>
							</div>
							<div class="aside-block" id="selected-bouser">
							<input type="hidden" id="sales_suggested_price" name="sales_suggested_price" value="{$quote.sales_suggested_price|zero_cut:2}">
								<div class="editor-container">
									<h2 class="heading">Total devis &agrave; date</h2>
									<p class="editor-name">{$quote.sales_suggested_price_format} &{$quote.sales_suggested_currency };</p>
									<label id="percentage_change" style="display:none" class="label label-success"></label>
								</div>
							</div>	
						</div>	
					</aside>
				</div>
			</div>	
		{/foreach}
		{/if}
	</div>
</div>
<div class="row-fluid" id="tech_mission_0" style="display:none">	
	<div class="mission-details">
		<div class="mission-tech-product"><span id="box_title_0">Tech mission 0</span>
			<div class="pull-right">												
				<a class="btn close-tech" rel="" id="mission_close_0">&times;</a>
			</div>											
		</div>
		<table class="table mission-table">
			<tr>
				<th style="width:33%">Mission</th>
				<th style="width:33%">D&eacute;lai de livraison</th>
				<th style="width:33">Co&ucirc;t (&{$quote.sales_suggested_currency };)</th>
			</tr>
			<tr class="misson-details-text">
				<td>
					<input type="text" name="mission_title[]" id="mission_title_0" class="span11 validate[required]" placeholder="enter a mission">
				</td>
				<td>
					<div class="span2"></div>
					<div class="span4">
						<input type="text" id="delivery_time_0" name="delivery_time[]" class="span12 validate[required]" value="3"/>
					</div>
					<div class="span4">
						<select name="delivery_option[]" id="delivery_option_0">					
							<option value="days">Jours</option>
							<option value="hours">Hours</option>									
						</select>
					</div>	
				</td>
				<td>
					<input type="text" id="mission_cost_0" name="mission_cost[]" class="span4 validate[required,custom[number]]" onkeyup="fnCalculateQuote();"/>
				</td>														
			</tr>	
		</table>
		<div class="row-fluid" style="margin-left: 15px;" id="div_before_prod_0">
			<div class="span12">
				<input type="checkbox" class="uni_style" name="before_prod_0" id="before_prod_0"> Doit &ecirc;tre r&eacute;alis&eacute; avant de lancer la mission
			</div>	
		</div>
		<div class="media mission-comment">
			<a class="pull-left imgframe">
				<img width="60px" src="{$fo_path}/profiles/bo/{$userId}/logo.jpg" class="media-object">
			</a>
			<div class="media-body">														
				<textarea name="comments[]" rows="2" placeholder="ins&eacute;rer un commentaire" id="comments_0" class="span12"></textarea>
			</div>												
		</div>
		<div class="row-fluid topset2">	
			<div class="span12"  style="padding:0 10px;">
				<input type="file" name="tech_documents_0" accept="doc|xls|zip|docx|xlsx" class="" id="tech_documents_0"/>
			</div>
			
		</div>
	</div>	
</div>
<!--popup to show after quote created-->
<div class="modal hide fade" id="tech_challenge" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>TECH - CHALLENGE</h3>
    </div>
    <div class="modal-body">
		<section>
			<div class="row-fluid">
				<div class="span9">
					{literal}
					<script language="javascript">
					$(document).ready(function() {		
						$('#tp_2').timepicker({
							defaultTime: 'value',
							minuteStep: 1,
							disableFocus: true,
							showMeridian: false,
							template: 'dropdown'
						});
						//validation
						$("#tech_challenge_form").validationEngine();
					});		
					</script>	
					{/literal}
					<form id="tech_challenge_form"  method="POST" action="/quote/save-tech-review" enctype="mulitpart/form-data">					
						<input type="hidden" name="quote_id" value="{$smarty.get.quote_id}">
						<!--<div class="formSep control-group">
							<label for="tech_timeline" class="control-label"><b>Due date:</b></label>
							<div class="row-fluid controls">
								<div class="span5">
									<div class="input-append date" id="dp2" data-date-format="dd/mm/yyyy">
										<input class="span10 validate[required]"  name="tech_timeline" id="tech_timeline" type="text" readonly="readonly" {if $quote.tech_timeline_date} value="{$quote.tech_timeline_date}" {/if} /><span class="add-on"><i class="splashy-calendar_day"></i></span>
									</div>
								</div>	
								<div class="span3">
									<input type="text" name="tech_time" id="tp_2" class="span8" {if $quote.tech_timeline_time} value="{$quote.tech_timeline_time}" {else} value='{$smarty.now|date_format:"%H:%M"}'{/if}>
								</div>	
							</div>
						</div> -->
						<div class="formSep control-group">
							<label for="tech_challenge_comments" class="control-label"><b>Commentaire:</b></label>
							<div class="row-fluid controls">
								<div class="span2">
									<img width="60px" src="{$fo_path}/profiles/bo/{$userId}/logo.jpg" class="media-object">
								</div>	
								<div class="span10">
									<textarea name="tech_challenge_comments" placeholder="ins&eacute;rer un commentaire" id="tech_challenge_comments" class="validate[required] span12">{$quote.tech_challenge_comments}</textarea>
								</div>	
							</div>
						</div>
						<div class="formSep control-group">
							<div class="row-fluid controls">
								<div class="span4"></div>
								<div class="span6">
									<button type="button" class="btn" data-dismiss="modal" aria-hidden="true">Annuler</button>
									<button type="submit" name="review_challenge" class="btn btn-primary">Challenge</button>
								</div>	
							</div>
						</div>	
					</form>
				</div>
			</div>
		</section>
    </div>
    <div class="modal-footer">
    </div>
</div>

<!-- SKip Quote popup-->
<div class="modal hide fade" id="quote_skip_pop" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button class="close" data-dismiss="modal" >&times;</button>
		<h3>Skip devis</h3>
	</div>
	<div class="modal-body">
		{literal}
		<script language="javascript">
		$(document).ready(function() {
			//validation
			$("#skip_comment_form").validationEngine();
		});		
		</script>	
		{/literal}
		<form  method="POST" id="skip_comment_form" action="/quote/save-tech-review" enctype="mulitpart/form-data">
		<input type="hidden" name="quote_id" value="{$smarty.get.quote_id}">
			<section>
				<div class="row-fluid">
					<div class="span9">
						<div class="row-fluid">
							<div class="media">
								<br>											
								<br>
								<a class="pull-left imgframe">
									<img width="60px" src="{$fo_path}/profiles/bo/{$userId}/logo.jpg" class="media-object">
								</a>
								<div class="media-body">														
									<textarea name="skip_comments" placeholder="skip commentaires" class="span12 validate[required]"></textarea>
								</div>												
							</div>
						</div>	
						<div class="row-fluid">
							<div class="span12">
								<button type="button" class="btn" data-dismiss="modal" aria-hidden="true">Annuler</button>
								<button type="submit" name="review_skip" class="btn btn-primary">Skip</button>
							</div>
						</div>	
					</div>
				</div>	
			</section>
		</form>	
	</div>
	<div class="modal-footer">
	</div>
</div>



<!-- Need more info comments-->
<div class="modal hide fade" id="quote_more_info_pop" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-header">
		<button class="close" data-dismiss="modal" >&times;</button>
		<h3>Besoin de précisions </h3>
	</div>
	<div class="modal-body">		
		<form  method="POST" id="more_info_comment_form" action="/quote/need-more-info" enctype="mulitpart/form-data">
		<input type="hidden" name="quote_id" value="{$smarty.get.quote_id}">
		<input type="hidden" name="team_review" value="tech">
			<section>
				<div class="row-fluid">
					<div class="span12">
						<div class="row-fluid">
							<div class="media">
								<br>								
								<div class="media-body">														
									<textarea name="more_info_comments" id="more_info_comments" rows="10" placeholder="commentaires" class="span9 validate[required]"></textarea>
								</div>	
								<label id="error_comment" class="error" style="display:none">Ce champs est requis</label>
							</div>
						</div>	
						<div class="row-fluid">
							<div class="span12">
								<button type="button" class="btn" data-dismiss="modal" aria-hidden="true">Annuler</button>
								<button id="more_info_btn"class="btn btn-primary" type="button">Ok</button>								
							</div>
						</div>	
					</div>
				</div>	
			</section>
		</form>	
		{literal}
		<script language="javascript">
		$(document).ready(function() {			
			$('#more_info_btn').click(function(){
				var more_info_comments=$("#more_info_comments").val();
				var comments = more_info_comments.replace(/\n/g, "");
				if (comments)
				{
					$("#error_comment").parent().removeClass('f_error');
					$("#error_comment").hide();
					$('#more_info_comment_form').submit();
				}
				else
				{
					$("#error_comment").parent().addClass('f_error');
					$("#error_comment").show();
				}			
			});	
		});		
		</script>	
		{/literal}
	</div>
	<div class="modal-footer">
	</div>
</div>
