{literal}
<script type="text/javascript">	
$(document).ready(function() {
		$('#techmList').dataTable({
            "sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
            "sPaginationType": "bootstrap",
            "aaSorting": [[ 0, "asc" ]],
			"iDisplayLength":50,
            "aoColumns": [
		        { "sType": "formatted-num" },
                { "sType": "string" },
                { "sType": "eu_date" },
                { "sType": "string" },
                { "sType": "string" },
		        { "sType": "string" }
            ]
        });
});

function deleteTechmission(tid)
{
	smoke.confirm("Do you really want to delete this type? ",function(e){
			if (e)
			{
			   var target_page = "/quote/deletetechmissiontype?tid="+tid;
				$.post(target_page, function(data){ 
					//smoke.alert("Deleted successfully !!"); 
					window.location.reload();
				});
			}
			else
			{
				return false;
			}
		});		
}
</script>
{/literal}
<div class="row-fluid">
	<div class="span12">
    	<h1 class="heading pull-left">Tech Mission Types</h1>
		<div class="pull-right">
		<a class="btn btn-primary" data-toggle="modal" data-target="#addtechmissiontype" href="/quote/add-techmissiontype">Add Tech mission type</a>
		</div>
	</div>
</div>	

<div class="row-fluid">
	<table class="table table-bordered table-hover table_vam" id="techmList" >
		<thead>
			<tr>
			   <th>S No</th>
			   <th>Title</th> 
			   <th>Type</th>
			   <th>Created at</th>
			   <th>Cost</th>
			   <th>Delivery time</th>
			   <th>Action</th>
			</tr>
		</thead>
		<tbody>
		{foreach from=$techmissions item=tech name="techmissionloop"}
			<tr>
				<td>{$smarty.foreach.techmissionloop.index+1}</td>
				<td>{$tech.tech_title}</td>
				<td>{if $tech.tech_type_assign eq 'superadmin'}Tech(superadmin){else}{$tech.tech_type_assign|ucfirst}{/if}</td>
				<td>{$tech.created_at|date_format:"%d/%m/%Y"}</td>
				<td>{$tech.cost}</td>
				<td>{$tech.delivery_time}&nbsp;{if $tech.delivery_option=='days'}Jour(s){else}Heure(s){/if}</td>
				<td>
					<a data-toggle="modal" data-target="#addtechmissiontype" href="/quote/add-techmissiontype?tid={$tech.tid}"><img class="splashy-application_windows_edit"></a>
					<a href="javascript:void(0);" onClick="deleteTechmission('{$tech.tid}');"><img src="/BO/theme/gebo/img/red_trash.png"></a>	
				</td>
			</tr>
		{/foreach}
		</tbody>
	</table>
</div>

<div class="modal hide fade" id="addtechmissiontype">
    <div class="modal-header">
        <button class="close" data-dismiss="modal">&times;</button>
        <h3>Add Tech mission type</h3>
    </div>
    <div class="modal-body" id="techmissionform">
	</div>
    <div class="modal-footer">
    </div>
</div>