<div class="row-fluid">
	{assign var="_tempo_value" value=$mission.tempo}
	{assign var="_delivery_volume_option" value=$mission.delivery_volume_option}
	{assign var="_tempo_length_option" value=$mission.tempo_length_option}
	<div class="mission-details">
		<div class="mission-prod-product">
			<span>Tempo Details</span>
		</div>
		<div class="row-fluid">								
			<label class="span3 moveright">Staffing set up</label>
			<div class="span3">
				<div class="span4">
				<h4>
					{if $mission.staff_time}
						{$mission.staff_time} {if $mission.staff_time_option eq 'days'} Jours {else} Heures {/if}
					{else}
						/
					{/if}
				</h4>
				</div>
			</div>	
		</div>	
		{if $mission.oneshot}
			<div class="row-fluid">								
				<label class="span3 moveright">One shot</label>
				<div class="span3">
					<h4>
					{if $mission.oneshot eq 'yes'}
						OUI
					{else if $mission.oneshot eq 'no'}
						NON
					{/if}
					</h4>
				</div>
			</div>
		{/if}
		<div class="row-fluid">								
			<label class="span3 moveright">Dur&eacute;e la mission</label>
			<div class="span6">
				{if $mission.duration_dont_know eq 'yes' && $mission.mission_length eq '0'} 															
				<div class="span8">
					<h4>* Duration not specified by sales</h4>																
				</div>
				{else}
					<div class="span3">
						<h4>{$mission.mission_length} {if $mission.mission_length_option eq 'days'} Jours {else} Heures {/if}</h4>
					</div>		
					{if $mission.duration_dont_know eq 'yes'} 															
					<div class="span8" style="margin-left: 0px">
						* Duration not specified by sales																
					</div>
					{/if}
				{/if}
			</div>
		</div>
		{if $mission.oneshot eq 'no'}
			<div class="row-fluid">								
				<label class="span3 moveright">Volume</label>														
				<div class="span9" id="tempo_details_{$mission.identifier}" {if $mission.oneshot eq 'yes'} style="display:none" {/if}>
					<div class="span4">		
						<h4>
							{$mission.volume_max} {$tempo_array.$_tempo_value} {$volume_option_array.$_delivery_volume_option} {$mission.tempo_length} {$tempo_duration_array.$_tempo_length_option}
						</h4>	
					</div>														
				</div>
			</div>
		{/if}	
	</div>
</div>