{literal}
<style type="text/css">

    .editor-container {
        font-size: 11px;
        padding: 15px 5px;
        text-align: center;
        transition: background 0.3s ease 0s;
    }
</style>
{/literal}
<table class="table table-striped table-bordered table-condensed">
    <thead>
    <tr>
        <th><span>Profile</span></th>
        <th><span>Name</span></th>
        <th><span>Email ID</span></th>
        <th><span>Participated Date</span></th>
        <th><span>Price Proposed</span></th>
        <th><span>Margin</span></th>
        <th><span>Price with margin</span></th>
        <th><span>Availability</span></th>
    </tr>
    </thead>
    {foreach from=$userdetials key=userdetials_key item=userdetials_item name=userdetials_loop}
    <tr>
        <td>
            <div class="span1">
                <a class="imgframe-large" target="_blank" href="/user/contributor-edit?submenuId=ML10-SL6&tab=viewcontrib&userId={$userdetials_item.identifier}">
                    <img title="click to view details" src="http://ep-test.edit-place.com/FO/profiles/contrib/pictures/{$userdetials_item.identifier}/{$userdetials_item.identifier}_p.jpg">
                </a>
            </div>
        </td>
        <td><span >
                <a class="imgframe-large" target="_blank" href="/user/contributor-edit?submenuId=ML10-SL6&tab=viewcontrib&userId={$userdetials_item.identifier}">
                    {$userdetials_item.first_name} {$userdetials_item.last_name}
                </a>
            </span>
        </td>
        <td><span >{$userdetials_item.email}</span></td>
        <td><span >{$userdetials_item.created_at|date_format:'%d/%m/%Y %H:%M'}</span></td>
        <td><span >{$userdetials_item.price_user}</span></td>
        <td><span >{$userdetials_item.margin}</span></td>
        <td><span >{$userdetials_item.pricewithmargin}*</span></td>
        <td><span >{$userdetials_item.valid_date|date_format:'%d/%m/%Y'}</span></td>
    </tr>
    {/foreach}
</table>

