<div class="scroll1">
{if $histories|@count > 0 || $logs|@count > 0}
	{foreach from=$histories item=history}
	<div class="media act-comment">
		<a class="pull-left imgframe">
		{if $history.type=='superclient'}
			<img class="media-object" width="60px" src="{$fo_path}profiles/superclients/logos/{$history.user_id}/{$history.user_id}.png">
		{elseif $history.type=='contributor'}
			<img class="media-object" width="60px" src="{$fo_path}profiles/contrib/pictures/{$history.user_id}/{$history.user_id}_h.jpg">
		{elseif $history.type=='client'}
			<img class="media-object" width="60px" src="{$fo_path}profiles/clients/logos/{$history.user_id}/{$history.user_id}.png">
		{else}
			<img class="media-object" width="60px" src="{$fo_path}profiles/bo/{$history.user_id}/logo.jpg">
		{/if}
		</a>
		<div class="media-body">
			{if $history.first_name}
				<a>{$history.first_name|utf8_encode} {$history.last_name|utf8_encode}</a> {$history.action_at|time_ago}{$history.time}<br>
			{/if}
			{$history.action_sentence|utf8_encode}
			<div>{$history.comments|stripslashes|htmlentities|nl2br|utf8_encode}</div>
		</div>
	</div>
	{/foreach}
	{* {foreach from=$logs item=log}
		<div class="media act-comment">
			<a class="pull-left imgframe">
			<img class="media-object" width="60px" src="{$fo_path}profiles/bo/{$log.user_id}/logo.jpg">
			</a>
			<div class="media-body">
				{if $log.first_name}
					<a>{$log.first_name} {$log.last_name}</a> {$log.action_at|time_ago}<span class="pull-right rightcontent">{$log.time}</span><br>
				{/if}
				{$log.action_sentence}
				<div>{$log.comments|stripslashes|htmlentities|nl2br}</div>
			</div>
		</div>
	{/foreach} *}
{else}
	<div class="media act-comment">
		<strong>No history found</strong>
	</div>
{/if}
</div>
{literal}
	<script type="text/javascript">
	$(document).ready(function(){
	$(".scroll1").mCustomScrollbar({
				scrollButtons:{enable:true,scrollType:"stepless"},
				keyboard:{scrollType:"stepless"},
				mouseWheel:{ scrollAmount:100 },
				theme:"rounded-dark",
				autoHideScrollbar:true
				});
			});
	</script>
{/literal}

