{literal}
<!-- custom scrollbar plugin -->
<link rel="stylesheet" href="/BO/theme/gebo/lib/scrollbar/jquery.mCustomScrollbar.css">
<script src="/BO/theme/gebo/lib/scrollbar/jquery.mCustomScrollbar.concat.min.js"></script>
<link href="/BO/theme/gebo/css/mission-followup.css" rel="stylesheet" />
<script src="/BO/theme/gebo/lib/tiny_mce/jquery.tinymce.js"></script>
<script language="JavaScript" type="text/javascript" src="/BO/theme/gebo/js/countdown.js"></script>
<style>
	.clear
	{
		clear:both;
	}
	
	.viewart label
	{
		margin: 5px 5px 0;
	}
	
	.viewarttable td
	{
		font-size: 13px;
		text-align:left;
	}
	
	.activity
	{
		box-shadow: none !important;
		border-top: none !important;
		border-left: none !important;
		border-right: none !important;
		border-bottom: 1px solid #e4e4e4 !imortant;
		border-radius: 0 !important;
		padding: 3px !important;
	}
	
	.progress-bar
	{
		display:list-item;
	}
	
	.icon-time
	{
		top:0;
	}
	
	#bodymsg label, .pointer  label, #bodymsg .label, .pointer .label
	{
		text-transform: uppercase;
	}
</style>
<!--<script language="JavaScript" type="text/javascript" src="/BO/theme/gebo/lib/ckeditor/ckeditor.js"></script>-->
<script type="text/javascript" >
    $(document).ready(function() {	
		$('body').on('hidden', '#republish ,#bulkrepublish ,#edit_article_modal ,#edit_ao_modal ,#view_article_modal', function (){        
			$(this).removeData('modal');				
			$('.modal-body',this).html('');		
			$("body").css("overflow", "auto");    
		});
		
		var article_id='{/literal}{$smarty.get.article_id}{literal}';	

		if(article_id)
		{
			/* $.get('/deliveryongoing/view-article?article_id='+article_id+'&currency=euro', function(data) {
				$("#view_article_modal .modal-body").html(data);
				$("#view_article_modal").modal('show');
			}); */
			$.get('/deliveryongoing/edit-article?article_id='+article_id, function(data) {
				$("#edit_article_modal .modal-body").html(data);
				$("#edit_article_modal").modal('show');
				$("#edit_article_modal").css('display','block');
			});
		}	
		
		//Tiny Editor
		$('#textarea').tinymce({
        // Location of TinyMCE script
        script_url 							: '/BO/theme/gebo/lib/tiny_mce/tiny_mce.js?' + new Date().getTime(),
        // General options
        theme 								: "advanced",
        plugins 							: "autoresize,style,table,advhr,advimage,advlink,emotions,inlinepopups,preview,media,contextmenu,paste,fullscreen,noneditable,xhtmlxtras,template,advlist",
        // Theme options
        theme_advanced_buttons1 			: "undo,redo,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
        theme_advanced_buttons2 			: "forecolor,backcolor,|,cut,copy,paste,pastetext,|,bullist,numlist,link,image,media,|,code,preview,fullscreen",
        theme_advanced_buttons3 			: "",
        theme_advanced_toolbar_location 	: "top",
        theme_advanced_toolbar_align 		: "left",
        theme_advanced_statusbar_location 	: "bottom",
        theme_advanced_resizing 			: false,
        content_css                         : "/BO/theme/gebo/css/tinymce_styles.css?" + new Date().getTime(),
        theme_advanced_font_sizes           : "8px,10px,12px,13px,14px,16px,18px,20px",
        font_size_style_values              : "8px,10px,12px,13px,14px,16px,18px,20px",
        init_instance_callback				: function(){

            function resizeWidth() {
                document.getElementById(tinyMCE.activeEditor.id+'_tbl').style.width='100%';
            }
            resizeWidth();
            $(window).resize(function() {
                resizeWidth();
            })
        }
    });
		
////////////to show the timer in selection profile page///////
      var cur_date={/literal}{$smarty.now}{literal};
      var js_date=(new Date().getTime())/ 1000;
      var diff_date=Math.floor(js_date-cur_date);
     //////////show timer//////////
	$("[id^=time_]").each(function(i) {
		var article=$(this).attr('id').split("_");
		var ts=article[2];
		$("#time_"+article[1]+"_"+article[2]).countdown({
			timestamp   : ts,
            diff_date  : diff_date,
			callback    : function(days, hours, minutes, seconds){
				var message = "";
				if(days >0 )message += days + " jours"  +", ";
				if(hours >0 )message += hours + " h" +",";
				if(minutes >0 )message += minutes + " mns"+ ", ";
				message += seconds + " s";
				$("#text_"+article[1]+"_"+article[2]).html(message);
				if(days==0 && hours==0 && minutes==0 && seconds==0)
				{
					//window.location.reload();
				}
			}
		});
	});	
		
//onload getting deliveries linked to client
			var client_id=$("#clients").val();
			
       if($('#ao_details').length) {
               $('#ao_details').dataTable({
					"sDom": "<'row'<'span6'<'dt_actions'>l><'span6'f>r>t<'row'<'span6'i><'span6'p>>",
					"sPaginationType": "bootstrap",
					"aaSorting": [[ 0, "asc" ]],
					"iDisplayLength":10,
					"aoColumns": [
						{ "sType": "html" },
						{ "sType": "string" },
						{ "sType": "string" },
						{ "sType": "numeric" },
						{ "sType": "string" },
						{ "sType": "string" },
						{ "sType": "string" },
						{ "sType": "string" },
						{ "sType": "string" },
						{ "sType": "string" }
					]
					});	
            }		
			
    });
function loadEditors(id)
{
    $('#'+id).tinymce({
        // Location of TinyMCE script
        script_url 							: '/BO/theme/gebo/lib/tiny_mce/tiny_mce.js?' + new Date().getTime(),
        // General options
        theme 								: "advanced",
        plugins 							: "autoresize,style,table,advhr,advimage,advlink,emotions,inlinepopups,preview,media,contextmenu,paste,fullscreen,noneditable,xhtmlxtras,template,advlist",
        // Theme options
        theme_advanced_buttons1 			: "undo,redo,|,bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,fontselect,fontsizeselect",
        theme_advanced_buttons2 			: "forecolor,backcolor,|,cut,copy,paste,pastetext,|,bullist,numlist,link,image,media,|,code,preview,fullscreen",
        theme_advanced_buttons3 			: "",
        theme_advanced_toolbar_location 	: "top",
        theme_advanced_toolbar_align 		: "left",
        theme_advanced_statusbar_location 	: "bottom",
        theme_advanced_resizing 			: false,
        content_css                         : "/BO/theme/gebo/css/tinymce_styles.css?" + new Date().getTime(),
        theme_advanced_font_sizes           : "8px,10px,12px,13px,14px,16px,18px,20px",
        font_size_style_values              : "8px,10px,12px,13px,14px,16px,18px,20px",
        init_instance_callback				: function(){

            function resizeWidth() {
                document.getElementById(tinyMCE.activeEditor.id+'_tbl').style.width='100%';
            }
            resizeWidth();
            $(window).resize(function() {
                resizeWidth();
            })
        }
    });
    // Creates a new editor instance
    var ed = new tinymce.Editor(id, {
        some_setting : 1
    });

}	
	//////////get comment for refusal when the close button is pressed///
/* function getCloseComment(artid, partscount)
  {
		if (tinymce.getInstanceById('closemailcontent'))
		{
			tinymce.execCommand('mceRemoveControl', true, 'closemailcontent');
			loadEditors('closemailcontent');
		}
		else if (!tinymce.getInstanceById('closemailcontent'))
			loadEditors('closemailcontent');
		
		var target_page = "/republish/getclosemailpopup?artid="+artid+"&usercount="+partscount;
		
		$.post(target_page, function(data){   //alert(data);
			 data1 = data.split("*");
			$("#closemailcontent").html(data1[0]);
			$('#bodymsg').html(data1[1]);
		});
	  
	  //valid button
	  var button='<button type="button" id="closeart"  name="closeart" class="btn btn-danger" onclick="closeArtprofile(\''+artid+'\', \'yes\');">Valider</button>';
	  $("#valid_button").html(button);
	  
	  
	  
      $('#closemail').modal('show');
  } */
function getCloseComment(artid, partscount)
{
    $('#artid').val(artid);
    if (CKEDITOR.instances['closemailcontent'])
    {
        CKEDITOR.instances['closemailcontent'].destroy();
    }
    var editor = CKEDITOR.replace( 'closemailcontent',
            {
                language: 'de', uiColor: '#D9DDDC', enterMode : CKEDITOR.ENTER_BR, removePlugins : 'resize',
                toolbar : [ ['Undo','Redo'], ['Find','Replace'],['Link', 'Unlink', 'Image'], ['FontSize', 'Bold', 'Italic','Underline'],
                    ['TextColor', '-', 'Smiley','SpecialChar', '-', 'Maximize'] ]
            }
    );
    var target_page = "/article-republish/getclosemailpopup?artid="+artid+"&usercount="+partscount;
    $.post(target_page, function(data){   //alert(data);
         data1 = data.split("*");
        CKEDITOR.instances['closemailcontent'].setData(data1[0]);
        $('#bodymsg').html(data1[1]);
    });
    $('#closemail').modal('show');
}
  ///////////when click on TO BE CLOSED in list of profiles/////////////
  /* function closeArtprofile(artid, participants)
  {
        var comment = CKEDITOR.instances['closemailcontent'].getData();
        var target_page = "/republish/closeartprofile?comment="+escape(comment)+"&art_id="+artid+"&participants="+participants;
        $.post(target_page, function(data){  //alert(data);
            window.location.reload();
        });
  } */
  function closeArtprofile(artid, participants)
{
    var participants = participants;
    if(participants == 'no')
    {
        smoke.confirm("Voulez-vous r\351ellement fermer cet article? Aucun contributeur n'a particip\351, aucun email ne sera donc envoy\351",function(e){
            if (e)
            {
                $.ajax({
                    url: "/article-republish/closeartprofile?art_id="+artid+"&participants="+participants,
                    global: false,
                    type: "GET",
                    dataType: "html",
                    async:false,
                    success: function(msg){ //alert(msg);
                        location.reload();
                        // $('#closeart'+artid).html("<a onclick=\"return closeArtprofile('"+artid+"', 'disclose');\" class='btn btn-info'>Closed</a>");
                    }
                });
            }
            else
            {
                return false;
            }
        });
    }
    else
    {
        var artid = $('#artid').val();
        var comment = CKEDITOR.instances['closemailcontent'].getData();
        var target_page = "/article-republish/closeartprofile?comment="+escape(comment)+"&art_id="+artid+"&participants="+participants;
        $.post(target_page, function(data){  //alert(data);
            window.location.reload();
        });
    }
}
  //get all contributor based on the type, lang, cat//////
function updatedContribList(artId)
{
	var contribtype = $("input[name='contribtype[]']:checked").map(function () {return this.value;}).get().join("','");
	var cat=$("#contrib_cat").val();
	var lang=$("select#contrib_lang").val();
	//alert(artId)
	lang= $.trim(lang);
	$.ajax({
		type: 'GET',
		//url: '/ao/updatecontriblist',
		url: '/article-republish/loaduserslist',
		// data: 'type=' + contribtype+'&category='+cat+'&language='+lang+'&parameter='+param,
		data: 'type=' + contribtype+'&category='+cat+'&language='+lang+"&artId="+artId,
		success: function(data)
		{ // alert(data);
			$('#contribs').html(data);
			$("#favcontribcheck").chosen();
		}
	});
} 

//get all contributor based on the type, lang, cat//////
function updatedBulkContribList2(aoId)
{
	var contribtype = $("input[name='contribtype[]']:checked").map(function () {return this.value;}).get().join("','");
    var cat=$("#contrib_cat").val();
    var lang=$("select#contrib_lang").val();    
    var artlist = $("#artlist").val();
    lang= $.trim(lang);
    $.ajax({
        type: 'GET',
        //url: '/ao/updatecontriblist',
        url: '/article-republish/loadbulkuserslist',
        // data: 'type=' + contribtype+'&category='+cat+'&language='+lang+'&parameter='+param,
        data: 'type=' + contribtype+'&category='+cat+'&language='+lang+"&artlist="+artlist+"&aoId="+aoId,
        success: function(data)
        {                      // alert(data);
            $('#contribs').html(data);
            $("#favcontribcheck").chosen();
            fngetbulkmailcontent();
        }

    });
}

//stop participation 
function stopparticipation(art,type)
{
	   smoke.confirm("Do you really want to stop this participation ? ",function(e){
            if (e)
            {
               $.ajax({
					type: 'GET',
					url: '/deliveryongoing/stop-participation',
					data: 'type=' + type+'&article='+art,
					success: function(data)
					{   
						window.location.reload();
					}

				});
            }
            else
            {
                return false;
            }
        });
}
</script>
<style type="text/css">
.alert,.label-warning
{
	padding:3px;
	margin:3px;
}
#ao_details_wrapper a label
{
cursor:pointer;
}
</style>
{/literal}

<div class="row-fluid">
	<div class="span12">
	{if $aoDetails |@count gt 0}
	{assign var="end_date" value=''}
		{foreach item=delivery from=$aoDetails name="aoDetails"} 
		{assign var="end_date" value=$delivery.delivery_end}
		{assign var="missiontest" value=$delivery.missiontest}
		{assign var="aocurrency" value=$delivery.sales_suggested_currency}
		<div class="followup-header">
			<h3>{$delivery.mission_title} > {$delivery.title} <span class="headerdim">{$delivery.publishdate} - {$delivery.delivery_end}</span>
			<a href="/followup/prod?cmid={$delivery.contract_mission_id}&index={$smarty.get.index}&active=delivery&submenuId=ML13-SL4#deliveries">
			<span class="pull-right">
				<button class="btn btn-success" name="back">Retour</button>
			</span>
			</a>
			</h3>
			<div class="row-fluid">    
				<div class="header-info">
				
					<div class="span3" style="padding-top:20px">
						<div class="span10" style="padding:0">
						<div class="sepH_b progress progress-success">
							<div class="bar" style="width: {$delivery.progresspercentage}%;background-image:linear-gradient({$delivery.colorcode}, {$delivery.colorcode})"></div> 
						</div>
						{* <div class="sepH_b progress progress-success" style="{if $progresspercentage!=0}background:{$delivery.colorcode};{/if}">
							<div class="bar" style="width: {$delivery.progresspercentage}%"></div> 
						</div> *}
						</div>
						<div><strong>&nbsp;{$delivery.progresspercentage}%</strong></div>
					</div>
					<div class="span2" style="padding-left:0">
						<span class="upper">Delivered</span>
						<span class="bottom">{$delivery.published_articles} / {$delivery.totalArticle}</span>
					</div>
					<div class="span2">
						<span class="upper">Bidding Failure</span>
						<span class="bottom" id="bfailure">-</span>
					</div>
					<div class="span3">
						<span class="upper">Writer Cost</span>
						<span class="bottom">
						{if $delivery.totalAmount}
							{$delivery.totalAmount|replace:',':''|zero_cut_t:2} &{$delivery.sales_suggested_currency};
						{else}
							-
						{/if}
						</span>
					</div>
					<div class="span2">
						<span class="upper">Proofreader Cost</span>
						<span class="bottom">
						{if $delivery.totalCorrectorAmount}
								{$delivery.totalCorrectorAmount|replace:',':''|zero_cut_t:2} &{$delivery.sales_suggested_currency};
						{else}
								-
						{/if}
						</span>
					</div>
				</div>
			</div>
		</div>
		<div class="pull-left loadactions">
			
		</div>
		<div class="pull-right bottomset">
		
			{if $ebookerid == $smarty.get.client_id}
			<a href="/followup/convert-stencils?ao_id={$delivery.id}&client_id=120207144632412&submenuId=ML13-SL4" target="_blank" class="">
				<button class="btn btn-primary" name="">View Stencils</button>
			</a>														
			{/if}
		
			{if $repeat_delivery eq 'yes'}
				<a class="btn btn-primary" href="/followup/edit-repeat-delivery?delivery_id={$delivery.id}" data-target="#repeat_delivery" role="button" data-toggle="modal"><i class="splashy-refresh"></i> Repeat scheduler</a>
			{/if}	
			
			<a href="/deliveryongoing/ao-contribmail?ao_id={$delivery.id}" role="button" data-toggle="modal" data-target="#ao_contribmail" class="">
				<button class="btn btn-primary" name=""><i class="splashy-mail_light_stuffed"></i> Contact</button>
			</a>
			<a class="" href="/BO/download-brief.php?ao_id={$delivery.id}">
				<button class="btn btn-primary" name=""><i class="splashy-arrow_large_down"></i> Brief</button>
			</a>
			
		</div>
		<div style="clear:both"></div>
		{/foreach}
		{/if}
	
		<div class="row-fluid">		
		   
			<table class="table table-striped table-bordered dTableR" id="ao_details">
				<thead>
					<tr>
						<th></th>
						<th>S.No.</th>
						<th>Titre de l'article</th>
						<th>Price</th>
						<th>End of Production</th>
						<th>R&eacute;dacteur</th>
						<th>Correcteur</th>
						<th>Progress</th>						
						<th>Writing Status</th>
						<th>Correction Statut</th>
						<th>Delivered</th>
						{* <th>Action</th>
						<th>Note</th> *}
					</tr>
				</thead>
				<tbody>
			{if $articleDetails |@count gt 0}
				{assign var="bfailure" value=0}
				{foreach item=article from=$articleDetails name="articleDetails"} 
					<tr>
						<td><input type="checkbox" name="articleid[]" class="artload" value="{$article.id}" /></td>
						<td>{$smarty.foreach.articleDetails.index+1}</td>
						<td><a class="editable editable-click" href="/deliveryongoing/view-article?article_id={$article.id}&currency={$aocurrency}" data-toggle="modal" role="button" data-target="#view_article_modal" id="view_article">{$article.title|stripslashes}</a></td>
						<td>
							{if $article.writer_facturation_details |@count gt 0 OR $article.corrector_facturation_details |@count gt 0 }
							<span {if $article.writer_facturation_details[0].price_user && $article.corrector_facturation_details[0].price_corrector}data-hint="R&eacute;daction + Correction" {elseif $article.writer_facturation_details[0].price_user} data-hint="R&eacute;daction" {elseif $article.corrector_facturation_details[0].price_corrector}data-hint="Correction"{/if}  class="label label-inverse hint--left  hint">	{$article.writer_facturation_details[0].price_user+$article.corrector_facturation_details[0].price_corrector}&euro;
							</span>
							{else}
							-
							{/if}
						</td>
						<td>
						{$end_date|date_format:"%d/%m/%Y"}
						</td>
						<td>
							{if $article.bo_closed_status eq 'closed' && !$article.writerParticipation}
								<label class="label label-warning">article ferm&eacute;</label>								
							{elseif $article.totalParticipations eq '0'}
								{if $article.republish_count > 0 ||  $article.participation_expires < $smarty.now}
									{assign var='bfailure' value=$bfailure+1}
								{/if}
								<span class="label label-important">AUCUNE PARTICIPATION</span>
							{elseif $article.writerParticipation}
						
								{if $article.writer_comment_count}
									<a href="/deliveryongoing/article-comments?ao_id={$article.delivery_id}&article_id={$article.id}" data-toggle="modal" data-target="#comments_article"><sup class="pull-right"><img alt="" src="/BO/theme/gebo/img/gCons/comment.png"></sup></a>
								{/if}
								<a target="_writer" href="/user/contributor-edit?submenuId=ML2-SL7&tab=viewcontrib&userId={$article.writer_bid_details[0].user_id}">{$article.writerName}</a>
								
							{if $article.writer_bid_details |@count gt 0}
							
                            {if $article.writer_bid_details[0].writer_status eq 'bid' OR $article.writer_bid_details[0].writer_status eq 'disapproved' OR $article.writer_bid_details[0].writer_status eq 'time_out'}
							
								{if ($article.writer_bid_details[0].writer_status eq 'bid' && $article.writer_bid_details[0].article_submit_expires lt $smarty.now) OR ($article.writer_bid_details[0].writer_status eq 'time_out')}
								
                                {else}
								<br/>
									<span id="time_{$article.id}_{$article.writer_bid_details[0].article_submit_expires}" class="alert alert-danger">
										<i class="icon-time"></i> <span id="text_{$article.id}_{$article.writer_bid_details[0].article_submit_expires}"></span>
									</span>
								{/if}
                            {/if}
                            {/if}	
							{elseif $article.totalParticipations ||  $article.totalcycleParticipations}
							<a href="/processao/article-profiles?submenuId=ML2-SL2&aoId={$article.delivery_id}"><span class="label label-warning">{$article.totalParticipations}</span><span class="label label-inverse">of {$article.totalcycleParticipations}</span></a>
							{else}
								-
							{/if}
						</td> 
						<td>		
						{if $article.correction eq 'yes'}  
							{if $article.totalCorrectionParticipations eq '0'}
									<span class="label label-important">AUCUNE PARTICIPATION</span> 
							{elseif $article.correctorParticipation}
								{if $article.corrector_comment_count}
									<a href="/deliveryongoing/article-comments?ao_id={$article.delivery_id}&article_id={$article.id}" data-toggle="modal" data-target="#comments_article"><sup class="pull-right"><img alt="" src="/BO/theme/gebo/img/gCons/comment.png"></sup></a>
								{/if}
									<a target="_writer" href="/user/contributor-edit?submenuId=ML2-SL7&tab=viewcontrib&userId={$article.corrector_bid_details[0].corrector_id}">{$article.correctorName}</a>
								 {if $article.corrector_bid_details |@count gt 0}
									{if ($article.corrector_bid_details[0].corrector_status eq 'bid' || $article.corrector_bid_details[0].corrector_status eq 'disapproved') && ($article.writer_bid_details[0].writer_status eq 'under_study')}

										{if ($article.corrector_bid_details[0].corrector_status eq 'bid' &&  	$article.corrector_bid_details[0].corrector_submit_expires lt $smarty.now) OR ($article.corrector_bid_details[0].corrector_status eq 'time_out')}
										
										{else}
										<br>
										<span id="time_{$article.id}-correction_{$article.corrector_bid_details[0].corrector_submit_expires}" class="alert alert-danger">
											<i class="icon-time"></i> <span id="text_{$article.id}-correction_{$article.corrector_bid_details[0].corrector_submit_expires}"></span>
										</span>
										{/if}
									
									{/if}
								{/if}	
							{else}
							<a href="/correction/corrector-article-profiles?submenuId=ML2-SL18&aoId={$article.delivery_id}"><span  style="cursor:pointer" class="label label-warning">En attente de s&eacute;lection</span></a>
							{/if}
						{else}
							Internal
						{/if}
						</td>					  
						<td>
							  {$article.progressbar_percent}%
						</td>
						<td>
							{if $article.status eq 'refused'} <label class="label label-important">closed</label>
							{elseif $article.participation_expires lt $smarty.now && $article.totalParticipations eq 0 }
								<label class="label label-important">AUCUNE PARTICIPATION</label> 
							{elseif $article.writer_bid_details |@count gt 0}
								{* {if $article.writer_bid_details |@count gt 0} *}
									{if $article.writer_bid_details[0].writer_status eq 'bid' OR $article.writer_bid_details[0].writer_status eq 'disapproved' OR $article.writer_bid_details[0].writer_status eq 'time_out'}

										{if ($article.writer_bid_details[0].writer_status eq 'bid' && $article.writer_bid_details[0].article_submit_expires lt $smarty.now) OR ($article.writer_bid_details[0].writer_status eq 'time_out')}
											<label class="label label-important">Non envoy&eacute; par le r&eacute;dacteur</label>
										{else}
											<a href="/processao/article-profiles?submenuId=ML2-SL2&aoId={$article.delivery_id}"><label class="label label-info">
													{if $article.writer_bid_details[0].writer_status eq 'bid' OR $article.writer_bid_details[0].writer_status eq 'time_out' }
													EN COURS DE REDACTION {if $article.writer_bid_details[0].latest_cycle gt 1}({$article.writer_bid_details[0].latest_cycle}) {/if}
													{else}
													non1 envoy&eacute;
													{/if}
												</label></a>
										{/if}
									{elseif $article.writer_bid_details[0].writer_status eq 'plag_exec' OR $article.writer_bid_details[0].current_stage eq 'stage0' }
									<a href="/proofread/stage-articles?submenuId=ML3-SL11&aoId={$article.delivery_id}"><label class="label label-info">EN PHASE PLAGIAT</label></a>
									{elseif $article.writer_bid_details[0].writer_status eq 'under_study' && $article.writer_bid_details[0].current_stage eq 'stage1'}
									<a href="/proofread/stage-articles?submenuId=ML3-SL2&aoId={$article.delivery_id}"><label class="label label-info">EN RELECTURE PHASE 1</label></a>
									<br>
									<!--{$article.writer_bid_details[0].updated_at|date_format:"%d/%m/%Y %R"}-->
									{elseif $article.writer_bid_details[0].writer_status eq 'under_study' && $article.writer_bid_details[0].current_stage eq 'client'}
									<label class="label label-info">EN RELECTURE Client</label>
									<br>
									{$article.writer_bid_details[0].updated_at|date_format:"%d/%m/%Y %R"}
									{elseif $article.writer_bid_details[0].writer_status eq 'under_study' && $article.writer_bid_details[0].current_stage eq 'stage2'}
									<a href="/proofread/stage-articles?submenuId=ML3-SL3&aoId={$article.delivery_id}"><label class="label label-info">EN RELECTURE PHASE 2</label></a>
									<br>
									<!--{$article.writer_bid_details[0].updated_at|date_format:"%d/%m/%Y %R"}-->

									{elseif $article.writer_bid_details[0].writer_status eq 'published' && $article.corrector_bid_details[0].corrector_status neq 'published'}
									<label class="label label-warning">VALID&Eacute;</label>
									{elseif ($article.writer_bid_details[0].writer_status eq 'under_study' || $article.writer_bid_details[0].writer_status eq 'disapproved_temp' || $article.writer_bid_details[0].writer_status eq 'closed_temp') && $article.writer_bid_details[0].current_stage eq 'corrector'}	
										{if ($article.corrector_bid_details[0].corrector_status eq 'bid' || $article.corrector_bid_details[0].corrector_status eq 'disapproved') && ($article.writer_bid_details[0].writer_status neq 'disapproved_temp' && $article.writer_bid_details[0].writer_status neq 'closed_temp' )}
											{if ($article.corrector_bid_details[0].corrector_status eq 'bid' &&  	$article.corrector_bid_details[0].corrector_submit_expires lt $smarty.now) OR ($article.corrector_bid_details[0].corrector_status eq 'time_out')}
											<label class="label label-important">Non envoy&eacute; par le correcteur</label>
											{else}
											<a href="/correction/corrector-article-profiles?submenuId=ML2-SL18&aoId={$article.delivery_id}"><label class="label label-info">
													{if $article.corrector_bid_details[0].corrector_status eq 'bid' || $article.corrector_bid_details[0].corrector_status eq 'disapproved' } 
													EN COURS DE CORRECTION {if $article.corrector_bid_details[0].latest_cycle gt 1}({$article.corrector_bid_details[0].latest_cycle}) {/if}
													{else}
													Non envoy&eacute; par le correcteur
													{/if}
												</label></a><br>
																
											{/if}
										{elseif ($article.corrector_bid_details[0].corrector_status eq 'bid' || $article.corrector_bid_details[0].corrector_status eq 'disapproved') && ($article.writer_bid_details[0].writer_status eq 'disapproved_temp' || $article.writer_bid_details[0].writer_status eq 'closed_temp' )}
										<a href="/correction/moderation?submenuId=ML3-SL10"><label class="label label-info">EN COURS DE MODERATION</label></a>
										<br>
									   {elseif ($article.corrector_bid_details[0].corrector_status eq 'under_study' && $article.corrector_bid_details[0].current_stage eq 'mission_test') && ($article.writer_bid_details[0].writer_status eq 'under_study' || $article.writer_bid_details[0].current_stage eq 'mission_test' )}
										<a href="/ao/markstat?submenuId=ML2-SL3"><label class="label label-info">Statistiques de missions test</label></a>
										<br>
									   
										
										{elseif $article.writer_bid_details[0].writer_status eq 'closed' OR $article.bo_closed_status eq 'closed' }
										<label class="label label-warning">article ferm&eacute;</label>
										{elseif $article.corrector_bid_details|@count eq 0 }
											<label class="label label-warning">En attente de s&eacute;lection du correcteur	</label>
									{/if}
									{elseif ($article.corrector_bid_details[0].corrector_status eq 'under_study' && $article.corrector_bid_details[0].current_stage eq 'stage2') && ($article.writer_bid_details[0].writer_status eq 'under_study' || $article.writer_bid_details[0].current_stage eq 'stage2' )}
											<a href="/proofread/stage-deliveries?submenuId=ML3-SL3"><label class="label label-info">EN RELECTURE PHASE 2</label></a>
												<br>
									{elseif $article.corrector_bid_details[0].corrector_status eq 'published' &&  $article.writer_bid_details[0].writer_status eq 'published'}
												<label class="label label-warning">VALID&Eacute;</label>
									{else}
										-
									{/if}
									{* {/if} *}
							{/if}

							{if $article.bo_closed_status eq 'closed' && !$article.writerParticipation}
							<label class="label label-warning">article ferm&eacute;</label>
							{elseif $article.participation_expires gt $smarty.now OR $article.correction_participationexpires gt $smarty.now}
								{if $article.participation_expires gt $smarty.now && !$article.writerParticipation && $article.publishtime gt $smarty.now }
								<a href="/processao/article-profiles?submenuId=ML2-SL2&aoId={$article.delivery_id}"><label class="label label-info hint--left  hint" data-hint="R&eacute;dacteur">PROGRAMM&Eacute;</label></a><br>
										<span id="time_{$article.id}_{$article.publishtime}" class="alert alert-danger">
											<i class="icon-time"></i> <span id="text_{$article.id}_{$article.publishtime}"></span>
										</span>
								{elseif $article.participation_expires gt $smarty.now && !$article.writerParticipation}
								<a href="/processao/article-profiles?submenuId=ML2-SL2&aoId={$article.delivery_id}"><label class="label label-info hint--left  hint" data-hint="R&eacute;dacteur">PARTICIPATIONS EN COURS</label></a><br>
										<span id="time_{$article.id}_{$article.participation_expires}" class="alert alert-danger">
											<i class="icon-time"></i> <span id="text_{$article.id}_{$article.participation_expires}"></span>
										</span>
								{* {elseif $article.correction_participationexpires gt $smarty.now &&  $article.writer_bid_details[0].writer_status eq 'under_study' && !$article.corrector_bid_details[0].corrector_status && !$article.correctorParticipation}
								<a href="/correction/corrector-article-profiles?submenuId=ML2-SL18&aoId={$article.delivery_id}"><label class="label label-info hint--left  hint" data-hint="Correcteur">PARTICIPATIONS EN COURS</label></a><br>
										<span id="time_{$article.id}_{$article.correction_participationexpires}" class="alert alert-danger">
											<i class="icon-time"></i> <span id="text_{$article.id}_{$article.correction_participationexpires}"></span>
										</span> *}
								{/if}
							{elseif $article.participation_expires lt $smarty.now && $article.totalParticipations gt 0 && !$article.writerParticipation}
								{if $article.totalParticipations==$article.totalRefusedParticipations}
									<a href="/processao/article-profiles?submenuId=ML2-SL2&aoId={$article.delivery_id}"><span  style="cursor:pointer" class="label label-warning hint--left  hint" data-hint="R&eacute;dacteur">PARTICIPATION(S) REFUS&Eacute;E(S)</span></a>
								{else}
									<a href="/processao/article-profiles?submenuId=ML2-SL2&aoId={$article.delivery_id}"><span  style="cursor:pointer" class="label label-warning hint--left  hint" data-hint="R&eacute;dacteur">EN S&Eacute;LECTION DE PROFIL</span></a>
								{/if}
							{elseif $article.participation_expires lt $smarty.now && $article.totalParticipations gt 0 && !$article.writerParticipation}
							<a href="/processao/article-profiles?submenuId=ML2-SL2&aoId={$article.delivery_id}"><span  style="cursor:pointer" class="label label-warning hint--left  hint" data-hint="R&eacute;dacteur">EN S&Eacute;LECTION DE PROFIL</span></a>                            
							{/if}
						</td>
						<!--correction details-->
						<td>
							{if $article.correction eq 'yes'}  
								{if $article.status eq 'refused'} <label class="label label-important">closed</label>
								{elseif $article.bo_closed_status eq 'closed'}
									<label class="label label-warning">article ferm&eacute;</label>
								{elseif $article.correction_participationexpires gt $smarty.now}
									{if $article.correction_participationexpires gt $smarty.now && !$article.corrector_bid_details[0].corrector_status && !$article.correctorParticipation}
									<a href="/correction/corrector-article-profiles?submenuId=ML2-SL18&aoId={$article.delivery_id}"><label class="label label-info hint--left  hint" data-hint="Correcteur">PARTICIPATIONS EN COURS</label></a><br>
											<span id="time_{$article.id}-correction_{$article.correction_participationexpires}" class="alert alert-danger">
												<i class="icon-time"></i> <span id="text_{$article.id}-correction_{$article.correction_participationexpires}"></span>
											</span>
									{/if}
								{elseif $article.correction_participationexpires lt $smarty.now && $article.totalCorrectionParticipations gt 0 && !$article.correctorParticipation}
									{if $article.totalCorrectionParticipations==$article.totalRefusedCorrectionParticipations}
									<a href="/correction/corrector-article-profiles?submenuId=ML2-SL18&aoId={$article.delivery_id}"><span  style="cursor:pointer" class="label label-warning hint--left  hint" data-hint="Correcteur">PARTICIPATION(S) REFUS&Eacute;E(S)</span></a>
									{else}
										<a href="/correction/corrector-article-profiles?submenuId=ML2-SL18&aoId={$article.delivery_id}"><span  style="cursor:pointer" class="label label-warning hint--left  hint" data-hint="Correcteur">EN S&Eacute;LECTION DE PROFIL</span></a>
									{/if}	
								{elseif $article.correction_participationexpires lt $smarty.now && $article.totalCorrectionParticipations eq 0 }
									<label class="label label-important">AUCUNE PARTICIPATION</label> 
								{elseif $article.writer_bid_details[0].writer_status eq 'bid' OR $article.writer_bid_details[0].writer_status eq 'disapproved' OR $article.writer_bid_details[0].writer_status eq 'time_out'}

										{if (($article.writer_bid_details[0].writer_status eq 'bid' || $article.writer_bid_details[0].writer_status eq 'disapproved') && $article.writer_bid_details[0].article_submit_expires lt $smarty.now) OR ($article.writer_bid_details[0].writer_status eq 'time_out')}
											<label class="label label-important">Non envoy&eacute; par le r&eacute;dacteur</label>
										{else}
											<a href="/processao/article-profiles?submenuId=ML2-SL2&aoId={$article.delivery_id}"><label class="label label-info">
												   
													{if $article.writer_bid_details[0].writer_status eq 'bid' OR $article.writer_bid_details[0].writer_status eq 'disapproved'}    
														EN COURS DE REDACTION {if $article.writer_bid_details[0].latest_cycle gt 1}({$article.writer_bid_details[0].latest_cycle}) {/if}
													{else}
														Non envoy&eacute; par le r&eacute;dacteur
													{/if}
												</label></a><br>		
										{/if}
								{elseif $article.writer_bid_details[0].writer_status eq 'plag_exec' OR $article.writer_bid_details[0].current_stage eq 'stage0' }
									<a href="/proofread/stage-articles?submenuId=ML3-SL11&aoId={$article.delivery_id}"><label class="label label-info">EN PHASE PLAGIAT</label></a>
								{elseif $article.corrector_bid_details |@count gt 0 }
								
										{if ($article.corrector_bid_details[0].corrector_status eq 'bid' || $article.corrector_bid_details[0].corrector_status eq 'disapproved') && ($article.writer_bid_details[0].writer_status eq 'under_study' && $article.writer_bid_details[0].current_stage eq 'corrector')}

											{if ($article.corrector_bid_details[0].corrector_status eq 'bid' &&  	$article.corrector_bid_details[0].corrector_submit_expires lt $smarty.now) OR ($article.corrector_bid_details[0].corrector_status eq 'time_out')}
											<label class="label label-important">Non envoy&eacute; par le correcteur</label>
											{else}
											<a href="/correction/corrector-article-profiles?submenuId=ML2-SL18&aoId={$article.delivery_id}"><label class="label label-info">
													{if $article.corrector_bid_details[0].corrector_status eq 'bid'  || $article.corrector_bid_details[0].corrector_status eq 'disapproved' } 
													EN COURS DE CORRECTION {if $article.corrector_bid_details[0].latest_cycle gt 1}({$article.corrector_bid_details[0].latest_cycle}) {/if}
													{else}
													Non envoy&eacute; par le correcteur
													{/if}
												</label></a>																
											{/if}
										{elseif ($article.corrector_bid_details[0].corrector_status eq 'bid' || $article.corrector_bid_details[0].corrector_status eq 'disapproved') && ($article.writer_bid_details[0].writer_status eq 'disapproved_temp' || $article.writer_bid_details[0].writer_status eq 'closed_temp' )}
										<a href="/correction/moderation?submenuId=ML3-SL10"><label class="label label-info">EN COURS DE MODERATION</label></a>
										<br>
									   
										{elseif ($article.corrector_bid_details[0].corrector_status eq 'under_study' && $article.corrector_bid_details[0].current_stage eq 'stage2') && ($article.writer_bid_details[0].writer_status eq 'under_study' || $article.writer_bid_details[0].current_stage eq 'stage2' )}
										<a href="/proofread/stage-articles?submenuId=ML3-SL3&aoId={$article.delivery_id}"><label class="label label-info">EN RELECTURE PHASE 2</label></a>
										<br>
									   
										{elseif ($article.corrector_bid_details[0].corrector_status eq 'under_study' && $article.corrector_bid_details[0].current_stage eq 'mission_test') && ($article.writer_bid_details[0].writer_status eq 'under_study' || $article.writer_bid_details[0].current_stage eq 'mission_test' )}
										<a href="/ao/markstat?submenuId=ML2-SL3"><label class="label label-info">Statistiques de missions test</label></a>
										<br>
									   
										{elseif $article.corrector_bid_details[0].corrector_status eq 'published' &&  $article.writer_bid_details[0].writer_status eq 'published'}
										<label class="label label-warning">VALID&Eacute;</label>
										{elseif $article.writer_bid_details[0].writer_status eq 'closed' OR $article.bo_closed_status eq 'closed' }
										<label class="label label-warning">article ferm&eacute;</label>
										{elseif $article.writer_bid_details|@count eq 0 }
											<label class="label label-warning">En attente de s&eacute;lection du r&eacute;dacteur</label>
										{/if}
								{/if}
							{else}
								<span class="label">Correction BO</span>
							{/if}
						</td>
                        <td>
                            {if $article.delivered eq 'yes'}Yes{else}No{/if}
                        </td>
						{* <td>
							{if $article.totalParticipations eq '0' &&  $article.participation_expires lt $smarty.now && $article.writer_bid_details[0].writer_stage neq 'stage0' && $article.writer_bid_details[0].writer_stage neq 'stage1' && $article.writer_bid_details[0].writer_stage neq 'stage2' && $article.writer_bid_details[0].writer_stage neq 'corrector' && $article.missiontest neq 'yes' &&  $article.status neq 'refused'}
								<button class="btn btn-danger btn hint--left  hint" name="closerepublish" href="/article-republish/republishpopup?artId={$article.id}" data-target="#republish" data-toggle="modal" type="button"  data-hint="Re publier R&eacute;dacteur"><i class="icon-repeat"></i></button>
							{elseif $article.totalParticipations gt 0 && $article.writer_bid_details[0].writer_status neq 'published' && $article.writer_bid_details[0].writer_stage neq 'stage0' && $article.writer_bid_details[0].writer_stage neq 'stage1' && $article.writer_bid_details[0].writer_stage neq 'stage2' && $article.writer_bid_details[0].writer_stage neq 'corrector' &&  $article.participation_expires lt $smarty.now && $article.missiontest neq 'yes' &&  $article.status neq 'refused'}
								<button class="btn btn-danger btn hint--left  hint" name="closerepublish" href="/article-republish/republishpopup?artId={$article.id}" data-target="#republish" data-toggle="modal" type="button"  data-hint="Re publier R&eacute;dacteur"><i class="icon-repeat"></i></button>
							{/if}
							{if $article.totalCorrectionParticipations eq '0' && $article.correction eq 'yes' && $article.correction_participationexpires lt $smarty.now && $article.correction_participationexpires neq 0 && $article.writerParticipation && $article.missiontest neq 'yes' &&  $article.status neq 'refused'}
								<button class="btn btn-danger btn hint--left  hint" name="closerepublish" id="closerepublish0" href="/correction/republishcorrectorpopup?nopart=no&amp;close=no&amp;artId={$article.id}" data-target="#republish" data-toggle="modal" type="button" data-hint="Re publier Correcteur"><i class="icon-repeat"></i></button>
							{elseif $article.totalCorrectionParticipations gt 0 && $article.correction eq 'yes' && $article.corrector_bid_details[0].corrector_status neq 'published' && $article.correction_participationexpires lt $smarty.now && $article.correction_participationexpires neq 0 && $article.missiontest neq 'yes' &&  $article.status neq 'refused'}
								<button class="btn btn-danger btn hint--left  hint" name="closerepublish" id="closerepublish0" href="/correction/republishcorrectorpopup?close=yes&amp;artId={$article.id}" data-target="#republish" data-toggle="modal" type="button" data-hint="Re publier Correcteur"><i class="icon-repeat"></i></button>
							{/if}
							
							{if $article.writerParticipation}
								{if $article.expiredWriterParticipation }
									<a href="/deliveryongoing/extend-time?utype=writer&participation_id={$article.expiredWriterParticipation}" role="button" data-toggle="modal" data-target="#extend_time" class="btn hint--left  hint" data-hint="Ajouter temps R&eacute;dacteur"><i class="icon-time"></i><sup>+</sup></a>								
								{/if}
								{if $article.writer_bid_details[0].writer_status neq 'published' && $article.writer_bid_details[0].writer_status neq 'closed' && $article.writer_bid_details[0].current_stage neq 'stage2' }
									<a data-toggle="modal" class="btn btn-inverse" onclick="return getCloseComment('{$article.id}',0)">Clore</a>
								{/if}
							{/if}
							{if $article.correctorParticipation}
								{if $article.expiredcorrectorParticipation }
									<a href="/deliveryongoing/extend-time?utype=corrector&participation_id={$article.expiredcorrectorParticipation}" role="button" data-toggle="modal" data-target="#extend_time" class="btn hint--left  hint" data-hint="Ajouter temps Correcteur"><i class="icon-time"></i><sup>+</sup></a>								
								{/if}								
							{/if}
							<br/>
							<a href="/deliveryongoing/ao-history?ao_id={$article.delivery_id}&article_id={$article.id}" role="button" data-toggle="modal" data-target="#ao_history" class="label label-warning">Voir l'historique</a>							
						</td>
						<td>
								{if $article.writer_bid_details[0].marks}
									<span class="label"><span class="label label-important">{$article.writer_bid_details[0].marks}</span> / <span class="label label-inverse">10</span></span>
								{else}
									-NA-
								{/if}
						</td>
						<td>
							{if $article.comment_count gt 0}
								<a href="/deliveryongoing/article-comments?ao_id={$article.delivery_id}&article_id={$article.id}" data-toggle="modal" data-target="#comments_article" data-hint="Commentaires" class="btn btn-info hint--left hint--info"><i class="splashy-comments_reply"></i></a>
							{else}
								<a href="/deliveryongoing/article-comments?ao_id={$article.delivery_id}&article_id={$article.id}" data-toggle="modal" data-target="#comments_article" data-hint="Commentaires" class="btn hint--left hint--info"><i class="splashy-comments_reply"></i></a>
							{/if}	
						</td> *}
					</tr> 
				{/foreach}
			{/if}	
							
				</tbody>
			</table>                        
	  </div>
	</div>
</div>
    <input type="hidden" id="hide_total" name="hide_total"  />

<!--///for the article view popup///-->
<div class="modal fullscreen hide fade" id="view_article_modal">
    <div class="modal-header">        
		<button class="close" data-dismiss="modal">&times;</button>
        <h3>View Article</h3>		
    </div>
    <div class="modal-body"></div>
    <div class="modal-footer"></div>
</div>

<!--///for the article edit popup///-->
<div class="modal fullscreen hide fade" id="edit_article_modal">
    <div class="modal-header">        
		<button class="close" data-dismiss="modal">&times;</button>
        <h3>&Eacute;dition de l&rsquo;article</h3>		
    </div>
    <div class="modal-body"></div>
    <div class="modal-footer"></div>
</div>
<!--///when republish the popup comes for edit details and mail for republish article///-->
<div class="modal fullscreen hide fade" id="republish">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Re-publication de l'article</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>


<!--Extend time of writer/corrector ///-->
<div class="modal container hide fade" id="extend_time">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Donner plus de temps</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>

<!--History of AO-->
<div class="modal container hide fade" id="ao_history">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Historique des actions men&eacute;es sur l'AO</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>
<!--Comments of AO-->
<div class="modal container hide fade" id="comments_article">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Commentaires</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>
<!--///for mail content show up for close the profile for close popup///-->
<div class="modal hide fade" id="closemail">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>FERMETURE DE L'ARTICLE</h3>
    </div>
    <div class="modal-body">
		<h3 id="bodymsg"></h3>
        <textarea name="closemailcontent" class="textarea" id="closemailcontent"></textarea>
    </div>
    <div class="modal-footer">
        <input type="hidden" id="userid" name="userid" />
        <input type="hidden" id="partid" name="partid" />
        <input type="hidden" id="artid" name="artid" />

        <span id="valid_button">
			<button type="button" id="closeart"  name="closeart" class="btn btn-danger" onclick="closeArtprofile('', 'yes');" >Valider</button>
		</span>	
		
    </div>
</div>
<div class="modal hide fade" id="refusal_reasons">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Les raisons du refus</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>

<!--COntributor emails-->
<div class="modal container hide fade" id="ao_contribmail">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Envoyer un email &agrave; tous les contributeurs de l'AO</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>
{* Bulk Republish *}
<div class="modal fullscreen hide fade" id="bulkrepublish">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
        <h3>Bulk Re-publication de l'article</h3>
    </div>
    <div class="modal-body">
    </div>
    <div class="modal-footer">
    </div>
</div>

{*Repeat Delivery modal*}
<div class="modal hide fade" id="repeat_delivery" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-header">
        <button class="close" data-dismiss="modal" >&times;</button>
		<h3>Repeat</h3>
    </div>
    <div class="modal-body">
	
	</div>    
</div>	
<!--///for the ao edit popup///-->
<div class="modal fullscreen hide fade" id="edit_ao_modal">
    <div class="modal-header">        
		<button class="close" data-dismiss="modal">&times;</button>
        <h3>&Eacute;diter L'AO</h3>		
    </div>
    <div class="modal-body"></div>
    <div class="modal-footer"></div>
</div>
{literal}
<script>
	$(".artload").click(function(){
		var ids = $(".artload:checked").map(function()
            {
                return $(this).val();
            }).get();
		if($.trim(ids))
		{
			$(".loadactions").html('<strong>Please Wait Loading</strong>');
			$.post('/deliveryongoing/load-art-actions',{'ids':ids,'missiontest':{/literal}"{$missiontest}"{literal},'ao_id':{/literal}"{$smarty.get.ao_id}"{literal},'client_id':{/literal}"{$smarty.get.client_id}"{literal}},function(data){$(".loadactions").html(data)});
		}
		else
			$(".loadactions").html('');
	})
	
	var bfailure = {/literal}"{$bfailure}"{literal}
	if(bfailure!=0)
	$("#bfailure").text(bfailure);
</script>
{/literal}
<link rel="stylesheet" href="/BO/theme/gebo/lib/bootstrap-multiselect/bootstrap-multiselect.css" type="text/css"/>
<script src="/BO/theme/gebo/lib/bootstrap-multiselect/bootstrap-multiselect.js" type="text/javascript" charset="utf-8"></script>